import '../../models/models.dart';

class AbsExercises {
  static final List<Exercise> exercises = [
    // 1. Ab Wheel Rollout
    Exercise(
      exerciseId: 'ab_wheel_rollout',
      name: 'Ab Wheel Rollout',
      aliases: ['Ab Roller Rollout', 'Wheel Rollout'],
      muscleGroup: 'Core',
      targetRegions: ['Upper Abs', 'Lower Abs', 'Transverse Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['Strength Training', 'Calisthenics', 'Functional Fitness'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Ab Roller'],
      difficulty: 'Advanced',
      movementPattern: 'Anti Extension',
      goalTags: ['Core Strength', 'Endurance', 'Core Stability'],
      isCompound: true,
      primaryMuscles: ['Core', 'Transverse Abdominis'],
      secondaryMuscles: ['Shoulders', 'Lats', 'Lower Back'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['plank', 'hollow_body_hold'],
      progressions: ['standing_ab_wheel_rollout'],
      regressions: ['knee_plank', 'swiss_ball_rollout'],
      thumbnail: 'https://images.unsplash.com/photo-1599058917765-a780eda07a3e?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/ab_wheel_rollout.gif',
      videoUrl: '',
      steps: [
        'Kneel on the floor with your knees on a mat and hold the ab wheel handles.',
        'Place the wheel on the floor directly beneath your shoulders.',
        'Brace your core and slowly roll the wheel forward, extending your body into a straight line.',
        'Roll forward as far as you can without letting your hips sag or your lower back arch.',
        'Pull yourself back to the starting kneeling position using your abdominal muscles.'
      ],
      commonMistakes: ['Sagging hips', 'Arching the lower back', 'Pulling back with hips/arms instead of abs'],
      safetyTips: ['Do not over-extend beyond your core strength capability', 'Keep the lower back neutral'],
      breathing: 'Inhale rolling forward, exhale rolling backward.',
      estimatedCaloriesPerMinute: 6.5,
      tags: ['Upper Abs', 'Lower Abs', 'Transverse Abdominis', 'Ab Roller', 'Advanced', 'Compound', 'Core'],
    ),
    // 2. Bicycle Crunch
    Exercise(
      exerciseId: 'bicycle_crunch',
      name: 'Bicycle Crunch',
      aliases: ['Air Bicycle', 'Alternating Bicycle Crunch'],
      muscleGroup: 'Core',
      targetRegions: ['Upper Abs', 'Lower Abs', 'Obliques', 'Rectus Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'General Fitness', 'Calisthenics', 'Fat Loss', 'Athletic Performance'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Rotation',
      goalTags: ['Core Strength', 'Oblique Development', 'Fat Loss', 'Muscular Endurance'],
      isCompound: false,
      primaryMuscles: ['Rectus Abdominis', 'Obliques'],
      secondaryMuscles: ['Lower Abs', 'Hip Flexors'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Beginner Friendly'],
      alternatives: ['russian_twist', 'crunch', 'reverse_crunch'],
      progressions: ['weighted_bicycle_crunch', 'decline_bicycle_crunch', 'hanging_bicycle_raise'],
      regressions: ['heel_touch', 'crunch'],
      thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/bicycle_crunch.gif',
      videoUrl: '',
      steps: [
        'Lie on your back with your hands lightly supporting your head.',
        'Lift your shoulders off the floor and raise both legs.',
        'Bring your right elbow toward your left knee while extending your right leg.',
        'Rotate your torso instead of simply moving your elbows.',
        'Alternate sides in a smooth pedaling motion.',
        'Continue with slow, controlled repetitions while keeping your core engaged.'
      ],
      commonMistakes: [
        'Pulling the neck with the hands',
        'Moving too quickly',
        'Using momentum instead of abdominal muscles',
        'Keeping the elbows too close together',
        'Not fully extending the opposite leg'
      ],
      safetyTips: [
        'Keep your lower back pressed into the floor.',
        'Rotate through your torso rather than just your arms.',
        'Move slowly for maximum abdominal activation.',
        'Keep your neck neutral throughout the movement.'
      ],
      breathing: 'Exhale as your elbow and knee come together. Inhale while switching sides.',
      estimatedCaloriesPerMinute: 6.2,
      tags: ['Core', 'Upper Abs', 'Lower Abs', 'Obliques', 'Rectus Abdominis', 'Bodyweight', 'Isolation', 'Beginner', 'Fat Loss', 'General Fitness', 'Calisthenics', 'Rotation'],
    ),

    // 3. Bird Dog
    Exercise(
      exerciseId: 'bird_dog',
      name: 'Bird Dog',
      aliases: ['Quadruped Opposition', 'Alternate Arm Leg Extension'],
      muscleGroup: 'Core',
      targetRegions: ['Lower Back', 'Glutes', 'Erector Spinae', 'Deep Core'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Calisthenics', 'Athletic Performance', 'Rehabilitation'],
      categories: ['Static Hold', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Extension',
      goalTags: ['Core Stability', 'Lower Back Health', 'Balance', 'Posture Improvement'],
      isCompound: true,
      primaryMuscles: ['Erector Spinae', 'Gluteus Maximus'],
      secondaryMuscles: ['Rectus Abdominis', 'Hamstrings', 'Deltoids'],
      mechanics: 'Compound',
      forceType: 'Static',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Lower Back Friendly', 'Beginner Friendly'],
      alternatives: ['plank', 'dead_bug', 'superman'],
      progressions: ['weighted_bird_dog', 'elevated_bird_dog', 'bird_dog_on_stability_ball'],
      regressions: ['supported_bird_dog', 'arm_only_bird_dog', 'leg_only_bird_dog'],
      thumbnail: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/bird_dog.gif',
      videoUrl: '',
      steps: [
        'Start on your hands and knees in a tabletop position with a neutral spine.',
        'Align your hands directly under your shoulders and knees under your hips.',
        'Slowly extend your right arm straight forward and left leg straight back.',
        'Keep your hips level and square to the floor without arching your back.',
        'Hold the extended position for 2 to 3 seconds while squeezing your glutes.',
        'Return to the starting position and repeat on the opposite side.'
      ],
      commonMistakes: [
        'Arching the lower back excessively',
        'Lifting the extended leg or arm too high',
        'Tilting or rotating the hips to one side',
        'Hyperextending or straining the neck upward',
        'Rushing the movement and losing balance'
      ],
      safetyTips: [
        'Keep your abdominal muscles braced throughout the entire movement.',
        'Look down at the floor to maintain a neutral cervical spine.',
        'Do not lift your arm or leg past horizontal alignment with your torso.',
        'Move slowly and with total control to protect your lower back.'
      ],
      breathing: 'Inhale to prepare. Exhale as you extend your arm and leg. Inhale as you return to the start.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Core', 'Lower Back', 'Glutes', 'Erector Spinae', 'Bodyweight', 'Compound', 'Beginner', 'Stability', 'General Fitness', 'Calisthenics', 'Extension'],
    ),


    // 4. Cable Crunch
    Exercise(
      exerciseId: 'cable_crunch',
      name: 'Cable Crunch',
      aliases: ['Kneeling Cable Crunch', 'Cable Pulldown Crunch'],
      muscleGroup: 'Core',
      targetRegions: ['Upper Abs', 'Lower Abs', 'Rectus Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Strength Training'],
      categories: ['Isolation', 'Machine'],
      equipment: ['Cable'],
      difficulty: 'Intermediate',
      movementPattern: 'Spinal Flexion',
      goalTags: ['Muscle Gain', 'Core Strength'],
      isCompound: false,
      primaryMuscles: ['Rectus Abdominis'],
      secondaryMuscles: ['Obliques'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['crunch', 'machine_crunch'],
      progressions: ['weighted_cable_crunch'],
      regressions: ['standard_crunch'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/cable_crunch.gif',
      videoUrl: '',
      steps: [
        'Kneel in front of a cable station with a rope attachment.',
        'Hold the rope ends next to your temples, leaning forward slightly.',
        'Engage your abs and flex your spine to bring your elbows toward your thighs.',
        'Squeeze your abdominal muscles at the bottom, keeping your hips stationary.',
        'Return slowly to the starting position.'
      ],
      commonMistakes: ['Pulling with the arms', 'Sitting back on the heels', 'Flexing at the hips instead of the spine'],
      safetyTips: ['Keep your hips locked in place', 'Maintain slow, controlled reps'],
      breathing: 'Exhale on flexion, inhale returning to starting position.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Upper Abs', 'Lower Abs', 'Cable', 'Intermediate', 'Isolation', 'Core'],
    ),
    // 5. Copenhagen Plank
    Exercise(
      exerciseId: 'copenhagen_plank',
      name: 'Copenhagen Plank',
      aliases: ['Copenhagen Adductor Plank', 'Copenhagen Side Plank'],
      muscleGroup: 'Core',
      targetRegions: ['Obliques', 'Adductors'],
      exerciseType: 'Strength',
      trainingStyles: ['Functional Fitness', 'Athletic Performance', 'Injury Prevention'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Bench'],
      difficulty: 'Advanced',
      movementPattern: 'Anti Lateral Flexion',
      goalTags: ['Core Stability', 'Hip Strength', 'Adductor Strength'],
      isCompound: true,
      primaryMuscles: ['Obliques', 'Adductors'],
      secondaryMuscles: ['Glutes', 'Core'],
      mechanics: 'Static',
      forceType: 'Isometric',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['side_plank', 'adductor_raises'],
      progressions: ['weighted_copenhagen_plank'],
      regressions: ['short_lever_copenhagen_plank', 'standard_side_plank'],
      thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Lie on your side with one elbow on the floor under your shoulder.',
        'Place your top leg on a stable bench and keep your bottom leg suspended under the bench.',
        'Raise your hips off the floor, forming a straight line from your head to your ankles.',
        'Hold the position, keeping your core and inner thighs braced.'
      ],
      commonMistakes: ['Hips sagging', 'Twisting the body', 'Overloading the knee joint'],
      safetyTips: ['Start with short lever (placing knee on bench instead of foot) to build tolerance', 'Stop if you feel knee pain'],
      breathing: 'Maintain steady, controlled breathing.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Obliques', 'Adductors', 'Bench', 'Advanced', 'Compound', 'Core'],
    ),
    // 6. Crunch
    Exercise(
      exerciseId: 'crunch',
      name: 'Crunch',
      aliases: ['Abdominal Crunch', 'Floor Crunch'],
      muscleGroup: 'Core',
      targetRegions: ['Upper Abs', 'Rectus Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'General Fitness', 'Fat Loss', 'Calisthenics'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Spinal Flexion',
      goalTags: ['Muscle Building', 'Core Strength', 'Fat Loss'],
      isCompound: false,
      primaryMuscles: ['Upper Abs', 'Rectus Abdominis'],
      secondaryMuscles: ['Obliques', 'Hip Flexors'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['sit_up', 'cable_crunch', 'machine_crunch'],
      progressions: ['decline_crunch', 'weighted_crunch', 'cable_crunch'],
      regressions: ['partial_crunch', 'dead_bug'],
      thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/crunch.gif',
      videoUrl: '',
      steps: [
        'Lie on your back with knees bent and feet flat on the floor.',
        'Place fingertips lightly behind your head without pulling the neck.',
        'Brace your core.',
        'Lift your shoulders off the floor by contracting your abdominal muscles.',
        'Pause briefly at the top.',
        'Slowly lower back to the starting position.'
      ],
      commonMistakes: [
        'Pulling on the neck',
        'Using momentum',
        'Lifting the lower back off the floor',
        'Moving too fast'
      ],
      safetyTips: [
        'Keep the lower back pressed into the floor.',
        'Lift using your abs instead of your neck.',
        'Perform slow and controlled repetitions.'
      ],
      breathing: 'Exhale while curling upward. Inhale while lowering to the starting position.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Upper Abs', 'Rectus Abdominis', 'Bodyweight', 'Beginner', 'Isolation', 'Core', 'Fat Loss', 'Muscle Building', 'General Fitness'],
    ),
    // 7. Dead Bug
    Exercise(
      exerciseId: 'dead_bug',
      name: 'Dead Bug',
      aliases: ['Lying Dead Bug'],
      muscleGroup: 'Core',
      targetRegions: ['Transverse Abdominis', 'Lower Abs'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Functional Fitness', 'Rehabilitation'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Anti Extension',
      goalTags: ['Core Stability', 'Posture', 'Injury Prevention'],
      isCompound: false,
      primaryMuscles: ['Core', 'Transverse Abdominis'],
      secondaryMuscles: ['Hip Flexors', 'Lower Back'],
      mechanics: 'Isolation',
      forceType: 'Isometric',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Lower Back Friendly', 'Beginner Friendly'],
      alternatives: ['plank', 'bird_dog'],
      progressions: ['weighted_dead_bug', 'elevated_dead_bug'],
      regressions: ['single_leg_lower', 'dead_bug_static'],
      thumbnail: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/dead_bug.gif',
      videoUrl: '',
      steps: [
        'Lie on your back on a mat, arms pointing straight up, knees bent at 90 degrees directly above your hips.',
        'Flatten your lower back against the floor, ensuring no space exists between your spine and the mat.',
        'Slowly lower your right arm backward while extending your left leg forward and down.',
        'Stop just before your hand and heel touch the floor.',
        'Return to the starting position and repeat on the opposite side.'
      ],
      commonMistakes: ['Arching the lower back off the floor', 'Moving opposite limbs out of sync', 'Speeding through the movement'],
      safetyTips: ['The lower back must remain flat against the floor at all times', 'Move slowly and with full control'],
      breathing: 'Exhale as you extend your limbs, inhale as you return to center.',
      estimatedCaloriesPerMinute: 4.0,
      tags: ['Transverse Abdominis', 'Lower Abs', 'Bodyweight', 'Beginner', 'Isolation', 'General Fitness', 'Core'],
    ),
    // 8. Decline Crunch
    Exercise(
      exerciseId: 'decline_crunch',
      name: 'Decline Crunch',
      aliases: ['Decline Bench Crunch', 'Decline Sit-Up'],
      muscleGroup: 'Core',
      targetRegions: ['Upper Abs', 'Lower Abs'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Strength Training'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Spinal Flexion',
      goalTags: ['Muscle Gain', 'Core Strength'],
      isCompound: false,
      primaryMuscles: ['Rectus Abdominis'],
      secondaryMuscles: ['Obliques', 'Hip Flexors'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['crunch', 'weighted_crunch'],
      progressions: ['weighted_decline_crunch'],
      regressions: ['standard_crunch'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Secure your feet at the end of a decline bench and lie back.',
        'Place fingertips behind your head or cross arms over chest.',
        'Engage your abs and flex your spine to lift your shoulders off the bench.',
        'Slowly return to the starting position.'
      ],
      commonMistakes: ['Using momentum', 'Pulling the neck', 'Going past 45 degrees (shifts load to hip flexors)'],
      safetyTips: ['Do not use hip flexors to yank body up', 'Keep lower back safe'],
      breathing: 'Exhale climbing, inhale returning.',
      estimatedCaloriesPerMinute: 5.4,
      tags: ['Upper Abs', 'Lower Abs', 'Bench', 'Intermediate', 'Isolation', 'Core'],
    ),
    // 9. Dragon Flag
    Exercise(
      exerciseId: 'dragon_flag',
      name: 'Dragon Flag',
      aliases: ['Dragonflag', 'Bruce Lee Dragon Flag'],
      muscleGroup: 'Core',
      targetRegions: ['Transverse Abdominis', 'Lower Abs', 'Upper Abs'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Advanced Strength'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Bench'],
      difficulty: 'Advanced',
      movementPattern: 'Anti Extension',
      goalTags: ['Core Strength', 'Core Stability'],
      isCompound: true,
      primaryMuscles: ['Core', 'Transverse Abdominis'],
      secondaryMuscles: ['Glutes', 'Lower Back', 'Lats'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['plank', 'hanging_leg_raise'],
      progressions: ['dragon_flag_flutter_kicks'],
      regressions: ['tucked_dragon_flag', 'lying_leg_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1599058917765-a780eda07a3e?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/dragon_flag.gif',
      videoUrl: '',
      steps: [
        'Lie on your back on a bench, gripping the top of the bench firmly behind your head.',
        'Lift your hips and legs upward toward the ceiling, supporting your weight on your shoulders.',
        'Lower your body in a straight line under strict control until you are just above the bench.',
        'Pull your body back up to vertical using your core, keeping your torso straight.'
      ],
      commonMistakes: ['Arching the lower back', 'Bending at the waist', 'Allowing shoulders to slide'],
      safetyTips: ['Ensure bench is heavy and stable', 'Support weight on shoulders/upper back, NEVER on your neck'],
      breathing: 'Exhale raising, inhale lowering.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Transverse Abdominis', 'Lower Abs', 'Upper Abs', 'Bench', 'Advanced', 'Compound', 'Core'],
    ),
    // 10. Farmer's Carry
    Exercise(
      exerciseId: 'farmers_carry',
      name: "Farmer's Carry",
      aliases: ["Farmer's Walk", 'Heavy Carry'],
      muscleGroup: 'Core',
      targetRegions: ['Transverse Abdominis', 'Obliques'],
      exerciseType: 'Strength',
      trainingStyles: ['Strength Training', 'Functional Fitness', 'Strongman'],
      categories: ['Compound', 'Dumbbell'],
      equipment: ['Dumbbell', 'Kettlebell'],
      difficulty: 'Intermediate',
      movementPattern: 'Anti Lateral Flexion',
      goalTags: ['Grip Strength', 'Core Stability', 'Full Body Strength'],
      isCompound: true,
      primaryMuscles: ['Forearms', 'Core', 'Transverse Abdominis'],
      secondaryMuscles: ['Shoulders', 'Upper Back', 'Traps', 'Glutes'],
      mechanics: 'Compound',
      forceType: 'Isometric',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['suitcase_carry', 'plank'],
      progressions: ['heavy_farmers_carry'],
      regressions: ['lighter_farmers_carry'],
      thumbnail: 'https://images.unsplash.com/photo-1627483297886-49710ae1fc22?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand between two heavy dumbbells or kettlebells.',
        'Hinge at hips, bend knees, and grip the weights firmly.',
        'Stand up with neutral posture, pulling your shoulders back and engaging your core.',
        'Walk forward in a straight line with slow, measured steps, keeping your torso upright.'
      ],
      commonMistakes: ['Shrugging shoulders', 'Leaning forward or to the side', 'Looking down'],
      safetyTips: ['Keep spine neutral during lift and carry', 'Do not rush the walk'],
      breathing: 'Breathe steadily in rhythm with your steps.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Transverse Abdominis', 'Obliques', 'Dumbbell', 'Intermediate', 'Compound', 'Core'],
    ),
    // 11. Flutter Kick
    Exercise(
      exerciseId: 'flutter_kick',
      name: 'Flutter Kick',
      aliases: ['Flutter Kicks', 'Alternating Leg Raise', 'Scissor Flutter Kick'],
      muscleGroup: 'Core',
      targetRegions: ['Lower Abs', 'Rectus Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'General Fitness', 'Calisthenics', 'Fat Loss', 'Athletic Performance'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Hip Flexion',
      goalTags: ['Lower Ab Development', 'Core Strength', 'Muscular Endurance', 'Fat Loss'],
      isCompound: false,
      primaryMuscles: ['Lower Abs', 'Rectus Abdominis'],
      secondaryMuscles: ['Hip Flexors', 'Quadriceps', 'Obliques'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Beginner Friendly'],
      alternatives: ['lying_leg_raise', 'reverse_crunch', 'scissor_kick'],
      progressions: ['weighted_flutter_kick', 'hollow_body_flutter_kick', 'hanging_flutter_kick'],
      regressions: ['bent_knee_flutter_kick', 'dead_bug'],
      thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/flutter_kick.gif',
      videoUrl: '',
      steps: [
        'Lie flat on your back with your legs extended.',
        'Place your hands underneath your glutes for additional lower back support.',
        'Lift both legs a few inches off the floor.',
        'Brace your core and keep your lower back pressed into the ground.',
        'Alternately raise one leg while lowering the other in a controlled fluttering motion.',
        'Maintain small, quick kicks without allowing your heels to touch the floor.'
      ],
      commonMistakes: [
        'Arching the lower back',
        'Kicking with large uncontrolled movements',
        'Holding the breath',
        'Letting the feet touch the floor',
        'Using momentum instead of core control'
      ],
      safetyTips: [
        'Keep your lower back firmly pressed against the floor.',
        'Maintain small, controlled kicks.',
        'Keep your neck and shoulders relaxed.',
        'Stop immediately if you experience lower back discomfort.'
      ],
      breathing: 'Breathe steadily throughout the movement. Avoid holding your breath during the exercise.',
      estimatedCaloriesPerMinute: 6.4,
      tags: ['Core', 'Lower Abs', 'Rectus Abdominis', 'Hip Flexors', 'Quadriceps', 'Bodyweight', 'Isolation', 'Beginner', 'General Fitness', 'Fat Loss', 'Calisthenics', 'Athletic Performance', 'Muscular Endurance'],
    ),
    // 12. Hanging Knee Raise
    Exercise(
      exerciseId: 'hanging_knee_raise',
      name: 'Hanging Knee Raise',
      aliases: ['Hanging Knee Lift', 'Knee Raise from Bar'],
      muscleGroup: 'Core',
      targetRegions: ['Lower Abs', 'Rectus Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Bodybuilding', 'General Fitness'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Pull-up Bar'],
      difficulty: 'Intermediate',
      movementPattern: 'Spinal Flexion',
      goalTags: ['Core Strength', 'Lower Ab Development'],
      isCompound: true,
      primaryMuscles: ['Lower Abs', 'Rectus Abdominis'],
      secondaryMuscles: ['Forearms', 'Hip Flexors'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['lying_leg_raise', 'reverse_crunch'],
      progressions: ['hanging_leg_raise', 'toes_to_bar'],
      regressions: ['assisted_hanging_knee_raise', 'lying_knee_tucks'],
      thumbnail: 'https://images.unsplash.com/photo-1544033527-b192daee1f5b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/hanging_knee_raise.gif',
      videoUrl: '',
      steps: [
        'Hang from a pullup bar with a shoulder-width, overhand grip.',
        'Keep your legs together and brace your core.',
        'Raise your knees toward your chest, curling your pelvis upward.',
        'Pause at the top, then slowly lower your legs back to starting hang.'
      ],
      commonMistakes: ['Swinging for momentum', 'Keeping shoulders loose/unpacked', 'Dropping legs too fast'],
      safetyTips: ['Keep shoulders packed down away from ears', 'Perform the raise under strict core control'],
      breathing: 'Exhale raising knees, inhale lowering.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Lower Abs', 'Rectus Abdominis', 'Pull-up Bar', 'Intermediate', 'Compound', 'Core'],
    ),
    // 13. Hanging Leg Raise
    Exercise(
      exerciseId: 'hanging_leg_raise',
      name: 'Hanging Leg Raise',
      aliases: ['Leg Raises', 'Hanging Leg Lift'],
      muscleGroup: 'Core',
      targetRegions: ['Lower Abs'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Strength Training'],
      categories: ['Calisthenics', 'Strength Training', 'Compound'],
      equipment: ['Pull-up Bar'],
      difficulty: 'Advanced',
      movementPattern: 'Flexion',
      goalTags: ['Core Strength', 'Grip Strength'],
      isCompound: true,
      primaryMuscles: ['Core'],
      secondaryMuscles: ['Forearms', 'Hip Flexors'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['lying_leg_raise', 'plank'],
      progressions: ['toes_to_bar'],
      regressions: ['hanging_knee_raises', 'hanging_knee_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1544033527-b192daee1f5b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/hanging_leg_raise.gif',
      videoUrl: '',
      steps: [
        'Hang from a pullup bar with a shoulder-width grip and fully extended arms.',
        'Keep your legs straight and engage your core.',
        'Slowly raise your legs until they are parallel to the floor.',
        'Control the descent back to the starting hang.'
      ],
      commonMistakes: ['Using momentum/swinging', 'Shrugging shoulders', 'Dropping legs too fast'],
      safetyTips: ['Keep shoulders packed', 'Control the entire range of motion'],
      breathing: 'Exhale raising, inhale lowering.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Lower Abs', 'Bodyweight', 'Advanced', 'Compound', 'Calisthenics', 'Flexion', 'Core'],
    ),
    // 14. Hanging Windshield Wiper
    Exercise(
      exerciseId: 'hanging_windshield_wiper',
      name: 'Hanging Windshield Wiper',
      aliases: ['Hanging Wipers'],
      muscleGroup: 'Core',
      targetRegions: ['Obliques', 'Lower Abs', 'Transverse Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Athletic Performance'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Pull-up Bar'],
      difficulty: 'Advanced',
      movementPattern: 'Rotation',
      goalTags: ['Core Strength', 'Oblique Development', 'Grip Strength'],
      isCompound: true,
      primaryMuscles: ['Obliques', 'Lower Abs'],
      secondaryMuscles: ['Lats', 'Forearms', 'Hip Flexors'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['windshield_wiper', 'russian_twist'],
      progressions: ['hanging_windshield_wiper_slow'],
      regressions: ['windshield_wiper', 'hanging_leg_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1544033527-b192daee1f5b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/hanging_windshield_wiper.gif',
      videoUrl: '',
      steps: [
        'Hang from a pullup bar and raise your straight legs into an inverted vertical position (feet toward bar).',
        'Rotate your hips and legs to the right as far as possible.',
        'Bring them back to center, then rotate them to the left side.',
        'Maintain a tight grip and stabilize your shoulders.'
      ],
      commonMistakes: ['Kicking legs back and forth', 'Using momentum', 'Sinking at shoulders'],
      safetyTips: ['Keep shoulders highly active and stable', 'Perform under control to protect back'],
      breathing: 'Breathe out as you rotate, inhale at center.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Obliques', 'Lower Abs', 'Transverse Abdominis', 'Pull-up Bar', 'Advanced', 'Compound', 'Core'],
    ),
    // 15. Heel Touch
    Exercise(
      exerciseId: 'heel_touch',
      name: 'Heel Touch',
      aliases: ['Heel Tap', 'Alternating Heel Touch', 'Heel Reach'],
      muscleGroup: 'Core',
      targetRegions: ['Obliques', 'Upper Abs'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'General Fitness', 'Calisthenics', 'Fat Loss', 'Functional Fitness'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Lateral Flexion',
      goalTags: ['Oblique Development', 'Core Strength', 'Fat Loss', 'Muscular Endurance'],
      isCompound: false,
      primaryMuscles: ['Obliques'],
      secondaryMuscles: ['Rectus Abdominis', 'Upper Abs'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Beginner Friendly', 'Lower Back Friendly'],
      alternatives: ['bicycle_crunch', 'russian_twist', 'side_plank'],
      progressions: ['weighted_heel_touch', 'decline_heel_touch'],
      regressions: ['crunch'],
      thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/heel_touch.gif',
      videoUrl: '',
      steps: [
        'Lie on your back with your knees bent and feet flat on the floor.',
        'Keep your arms extended by your sides.',
        'Lift your shoulders slightly off the floor by engaging your core.',
        'Reach your right hand toward your right heel.',
        'Return to the center under control.',
        'Repeat on the left side.',
        'Continue alternating sides while keeping constant tension on your abs.'
      ],
      commonMistakes: [
        'Using momentum instead of controlled movement',
        'Lifting the lower back off the floor',
        'Dropping the shoulders between repetitions',
        'Moving too quickly',
        'Holding your breath'
      ],
      safetyTips: [
        'Keep your chin slightly tucked.',
        'Maintain tension in your abdominal muscles throughout the exercise.',
        'Move only through your torso rather than swinging your arms.',
        'Perform slow and controlled repetitions.'
      ],
      breathing: 'Exhale while reaching toward each heel. Inhale while returning to the center.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Core', 'Obliques', 'Upper Abs', 'Bodyweight', 'Isolation', 'Beginner', 'General Fitness', 'Fat Loss', 'Lateral Flexion', 'Functional Fitness'],
    ),
    // 16. Hollow Body Hold
    Exercise(
      exerciseId: 'hollow_body_hold',
      name: 'Hollow Body Hold',
      aliases: ['Gymnastic Hollow Hold'],
      muscleGroup: 'Core',
      targetRegions: ['Transverse Abdominis', 'Upper Abs', 'Lower Abs'],
      exerciseType: 'Warm-up',
      trainingStyles: ['Calisthenics', 'Functional Fitness', 'Gymnastics'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Anti Extension',
      goalTags: ['Core Stability', 'Endurance', 'Posture'],
      isCompound: false,
      primaryMuscles: ['Core', 'Transverse Abdominis'],
      secondaryMuscles: ['Hip Flexors', 'Quadriceps'],
      mechanics: 'Static',
      forceType: 'Isometric',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['plank', 'dead_bug'],
      progressions: ['hollow_body_rocks'],
      regressions: ['dead_bug_static', 'tucked_hollow_hold'],
      thumbnail: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Lie flat on your back, legs extended and arms overhead.',
        'Press your lower back firmly into the floor.',
        'Slowly lift your legs and shoulders slightly off the ground.',
        'Keep your legs together and arms extended, holding your body in a shallow banana shape.'
      ],
      commonMistakes: ['Lower back arching off the floor', 'Craning the neck', 'Holding the breath'],
      safetyTips: ['If lower back lifts, raise legs higher to maintain contact', 'Keep abs deeply braced'],
      breathing: 'Breathe steadily in shallow breaths.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Transverse Abdominis', 'Upper Abs', 'Lower Abs', 'Bodyweight', 'Intermediate', 'Isolation', 'Core'],
    ),
    // 17. Jackknife Sit-Up
    Exercise(
      exerciseId: 'jackknife_sit_up',
      name: 'Jackknife Sit-Up',
      aliases: ['Jackknife Crunch', 'V-Up Jackknife'],
      muscleGroup: 'Core',
      targetRegions: ['Upper Abs', 'Lower Abs', 'Rectus Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Fat Loss', 'General Fitness'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Spinal Flexion',
      goalTags: ['Core Strength', 'Fat Loss'],
      isCompound: false,
      primaryMuscles: ['Rectus Abdominis'],
      secondaryMuscles: ['Hip Flexors', 'Obliques'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['v_up', 'crunches'],
      progressions: ['weighted_jackknife_sit_up'],
      regressions: ['crunches', 'lying_leg_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/jackknife_sit_up.gif',
      videoUrl: '',
      steps: [
        'Lie flat on your back with arms extended overhead and legs straight.',
        'Simultaneously lift your torso and legs to meet in the middle.',
        'Reach your hands toward your feet, bending at the waist.',
        'Slowly lower back to starting position.'
      ],
      commonMistakes: ['Moving arms and legs out of sync', 'Using neck to pull torso up'],
      safetyTips: ['Control the descent to protect the back', 'Do not crash down'],
      breathing: 'Exhale folding, inhale returning.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Upper Abs', 'Lower Abs', 'Rectus Abdominis', 'Bodyweight', 'Intermediate', 'Isolation', 'Core'],
    ),
    // 18. L-Sit
    Exercise(
      exerciseId: 'l_sit',
      name: 'L-Sit',
      aliases: ['L Sit', 'Gymnastic L-Sit'],
      muscleGroup: 'Core',
      targetRegions: ['Lower Abs', 'Transverse Abdominis', 'Rectus Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Advanced Strength'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Parallettes', 'Dip Station'],
      difficulty: 'Advanced',
      movementPattern: 'Anti Rotation',
      goalTags: ['Core Strength', 'Grip Strength', 'Shoulder Stability'],
      isCompound: true,
      primaryMuscles: ['Core', 'Lower Abs'],
      secondaryMuscles: ['Shoulders', 'Triceps', 'Hip Flexors', 'Quadriceps'],
      mechanics: 'Static',
      forceType: 'Isometric',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['plank', 'hanging_leg_raise'],
      progressions: ['v_sit', 'l_sit_lifts'],
      regressions: ['tucked_l_sit', 'single_leg_l_sit'],
      thumbnail: 'https://images.unsplash.com/photo-1599058917765-a780eda07a3e?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/l_sit.gif',
      videoUrl: '',
      steps: [
        'Support your weight on parallettes or parallel bars with elbows locked.',
        'Brace your core and lift your straight legs in front of you until they are parallel to the floor.',
        'Hold your body in a clear L-shape, keeping your chest broad and shoulders depressed.'
      ],
      commonMistakes: ['Shrugging shoulders', 'Bending knees', 'Allowing hips to sink backward'],
      safetyTips: ['Keep elbows strictly locked out', 'Depress shoulders strongly throughout hold'],
      breathing: 'Maintain steady, shallow breathing.',
      estimatedCaloriesPerMinute: 7.5,
      tags: ['Lower Abs', 'Transverse Abdominis', 'Rectus Abdominis', 'Bodyweight', 'Advanced', 'Compound', 'Core'],
    ),
    // 19. Leg Raise
    Exercise(
      exerciseId: 'leg_raise',
      name: 'Leg Raise',
      aliases: ['Straight Leg Raise', 'Leg Lifts'],
      muscleGroup: 'Core',
      targetRegions: ['Lower Abs', 'Rectus Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'General Fitness'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Hip Flexion',
      goalTags: ['Core Strength', 'Lower Ab Development'],
      isCompound: false,
      primaryMuscles: ['Lower Abs'],
      secondaryMuscles: ['Hip Flexors', 'Rectus Abdominis'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['lying_leg_raise', 'reverse_crunch'],
      progressions: ['hanging_leg_raise'],
      regressions: ['lying_knee_tucks'],
      thumbnail: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/leg_raise.gif',
      videoUrl: '',
      steps: [
        'Lie flat on your back on a mat, hands under glutes or beside hips.',
        'Keeping your legs fully straight, raise them together until they are perpendicular to the floor.',
        'Slowly lower your legs back to a few inches off the floor.'
      ],
      commonMistakes: ['Arching lower back off floor', 'Lifting hips too early', 'Dropping legs too fast'],
      safetyTips: ['Focus on pressed spine alignment', 'Lower legs only as far as back remains flat'],
      breathing: 'Exhale raising, inhale lowering.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Lower Abs', 'Rectus Abdominis', 'Bodyweight', 'Beginner', 'Isolation', 'Core'],
    ),
    // 20. Lying Leg Raise
    Exercise(
      exerciseId: 'lying_leg_raise',
      name: 'Lying Leg Raise',
      aliases: ['Lying Leg Lifts'],
      muscleGroup: 'Core',
      targetRegions: ['Lower Abs'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['General Fitness', 'Calisthenics'],
      categories: ['General Fitness', 'Calisthenics', 'Isolation'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Flexion',
      goalTags: ['Core Strength', 'Lower Abs'],
      isCompound: false,
      primaryMuscles: ['Core'],
      secondaryMuscles: ['Hip Flexors'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['plank', 'crunches'],
      progressions: ['hanging_leg_raises', 'hanging_leg_raise'],
      regressions: ['lying_knee_tucks'],
      thumbnail: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/lying_leg_raise.gif',
      videoUrl: '',
      steps: [
        'Lie flat on your back on a mat, hands under your glutes for lower back support.',
        'Keep your legs straight and lift them toward the ceiling until they are perpendicular to the floor.',
        'Slowly lower your legs back down until they are just above the floor.',
        'Repeat without letting your heels touch the floor.'
      ],
      commonMistakes: ['Arching the lower back off the floor', 'Dropping legs too fast'],
      safetyTips: ['Keep lower back pressed flat against the mat', 'Control the leg descent'],
      breathing: 'Exhale raising, inhale lowering.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Lower Abs', 'Bodyweight', 'Beginner', 'Isolation', 'General Fitness', 'Flexion', 'Core'],
    ),
    // 21. Machine Crunch
    Exercise(
      exerciseId: 'machine_crunch',
      name: 'Machine Crunch',
      aliases: ['Ab Machine Crunch', 'Seated Machine Crunch'],
      muscleGroup: 'Core',
      targetRegions: ['Upper Abs', 'Lower Abs', 'Rectus Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding'],
      categories: ['Isolation', 'Machine'],
      equipment: ['Machine'],
      difficulty: 'Beginner',
      movementPattern: 'Spinal Flexion',
      goalTags: ['Muscle Gain', 'Core Strength'],
      isCompound: false,
      primaryMuscles: ['Rectus Abdominis'],
      secondaryMuscles: ['Obliques'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['crunch', 'cable_crunch'],
      progressions: ['weighted_machine_crunch'],
      regressions: ['standard_crunch'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/machine_crunch.gif',
      videoUrl: '',
      steps: [
        'Sit on the crunch machine and select a suitable weight.',
        'Secure your feet under the pads and hold the upper handles.',
        'Contract your abs and curl your torso forward, flexing your spine.',
        'Slowly return to the starting position.'
      ],
      commonMistakes: ['Pushing with the arms', 'Moving too fast', 'Improper seat adjustment'],
      safetyTips: ['Focus the contraction solely on the abs', 'Keep back supported on pad during return'],
      breathing: 'Exhale flexing forward, inhale returning.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Upper Abs', 'Lower Abs', 'Machine', 'Beginner', 'Isolation', 'Core'],
    ),
    // 22. Medicine Ball Slam
    Exercise(
      exerciseId: 'medicine_ball_slam',
      name: 'Medicine Ball Slam',
      aliases: ['Ball Slam', 'Med Ball Slam'],
      muscleGroup: 'Core',
      targetRegions: ['Rectus Abdominis', 'Lower Abs', 'Upper Abs'],
      exerciseType: 'Strength',
      trainingStyles: ['Functional Fitness', 'HIIT', 'Athletic Performance'],
      categories: ['Compound', 'Medicine Ball'],
      equipment: ['Medicine Ball'],
      difficulty: 'Intermediate',
      movementPattern: 'Spinal Flexion',
      goalTags: ['Explosive Power', 'Core Strength', 'Conditioning'],
      isCompound: true,
      primaryMuscles: ['Core', 'Rectus Abdominis'],
      secondaryMuscles: ['Shoulders', 'Lats', 'Quads', 'Glutes'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['kettlebell_swing', 'burpees'],
      progressions: ['heavy_medicine_ball_slam'],
      regressions: ['light_medicine_ball_slam'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/medicine_ball_slam.gif',
      videoUrl: '',
      steps: [
        'Stand with feet shoulder-width apart, holding a medicine ball with both hands.',
        'Reach the ball high overhead, extending your body fully.',
        'Use your core and arms to throw the ball down into the floor as hard as possible.',
        'Catch the ball on the rebound and repeat.'
      ],
      commonMistakes: ['Bending at the waist without using abs', 'Throwing with arms only', 'Improper spinal alignment'],
      safetyTips: ['Do not let the ball bounce back into your face', 'Keep core highly active'],
      breathing: 'Inhale raising, exhale throwing down.',
      estimatedCaloriesPerMinute: 9.0,
      tags: ['Rectus Abdominis', 'Lower Abs', 'Upper Abs', 'Medicine Ball', 'Intermediate', 'Compound', 'Core'],
    ),
    // 23. Mountain Climber
    Exercise(
      exerciseId: 'mountain_climber',
      name: 'Mountain Climber',
      aliases: ['Mountain Climbers', 'Alternating Knee In'],
      muscleGroup: 'Core',
      targetRegions: ['Lower Abs', 'Transverse Abdominis'],
      exerciseType: 'HIIT',
      trainingStyles: ['Functional Fitness', 'HIIT', 'Fat Loss', 'Calisthenics'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Hip Flexion',
      goalTags: ['Core Strength', 'Conditioning', 'Fat Loss'],
      isCompound: true,
      primaryMuscles: ['Core', 'Lower Abs'],
      secondaryMuscles: ['Shoulders', 'Quadriceps', 'Hip Flexors'],
      mechanics: 'Compound',
      forceType: 'Isometric',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['plank', 'burpees'],
      progressions: ['cross_body_mountain_climber', 'sliding_mountain_climbers'],
      regressions: ['incline_mountain_climbers', 'slow_mountain_climber'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/mountain_climber.gif',
      videoUrl: '',
      steps: [
        'Start in a high plank position, hands under shoulders, spine straight.',
        'Brace your core and pull your right knee toward your chest.',
        'Extend the right leg back while simultaneously pulling the left knee forward.',
        'Alternate legs rapidly in a running motion while maintaining a stable plank.'
      ],
      commonMistakes: ['Bouncing the hips up and down', 'Letting hands drift forward of shoulders', 'Rounding the spine'],
      safetyTips: ['Keep your shoulders directly over your wrists', 'Do not arch lower back'],
      breathing: 'Maintain a fast, steady breathing rhythm.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Lower Abs', 'Transverse Abdominis', 'Bodyweight', 'Intermediate', 'Compound', 'Core'],
    ),
    // 24. Pallof Press
    Exercise(
      exerciseId: 'pallof_press',
      name: 'Pallof Press',
      aliases: ['Cable Pallof Press', 'Band Pallof Press'],
      muscleGroup: 'Core',
      targetRegions: ['Obliques', 'Transverse Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['Functional Fitness', 'Rehabilitation', 'Strength Training'],
      categories: ['Isolation', 'Cable'],
      equipment: ['Cable', 'Band'],
      difficulty: 'Intermediate',
      movementPattern: 'Anti Rotation',
      goalTags: ['Core Stability', 'Injury Prevention', 'Oblique Development'],
      isCompound: false,
      primaryMuscles: ['Obliques', 'Transverse Abdominis'],
      secondaryMuscles: ['Shoulders', 'Glutes'],
      mechanics: 'Isolation',
      forceType: 'Isometric',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home'],
      injuryFriendly: ['Lower Back Friendly', 'Shoulder Friendly'],
      alternatives: ['plank', 'russian_twist'],
      progressions: ['kneeling_pallof_press', 'pallof_press_with_rotation'],
      regressions: ['band_pallof_press_light'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/pallof_press.gif',
      videoUrl: '',
      steps: [
        'Stand lateral to a cable or band attachment, holding the handle with both hands at your chest.',
        'Step away to create tension and brace your core, keeping your feet shoulder-width apart.',
        'Press the cable handle straight forward, extending your arms.',
        'Hold the extended position for 2 seconds, resisting the cable pulling your torso side-to-side.',
        'Return hands slowly to chest.'
      ],
      commonMistakes: ['Shrugging shoulders', 'Letting the torso twist', 'Using too much weight'],
      safetyTips: ['Focus on preventing rotation', 'Keep knees soft and glutes squeezed'],
      breathing: 'Exhale pressing forward, inhale returning.',
      estimatedCaloriesPerMinute: 4.2,
      tags: ['Obliques', 'Transverse Abdominis', 'Cable', 'Intermediate', 'Isolation', 'Core'],
    ),
    // 25. Plank
    Exercise(
      exerciseId: 'plank',
      name: 'Plank',
      aliases: ['Forearm Plank', 'Static Plank'],
      muscleGroup: 'Core',
      targetRegions: ['Transverse Abdominis', 'Upper Abs', 'Lower Abs'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Calisthenics', 'Warm-up'],
      categories: ['Calisthenics', 'Isolation'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Anti Extension',
      goalTags: ['Core Stability', 'Endurance'],
      isCompound: false,
      primaryMuscles: ['Core', 'Transverse Abdominis'],
      secondaryMuscles: ['Glutes', 'Shoulders'],
      mechanics: 'Static',
      forceType: 'Isometric',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Beginner Friendly', 'Lower Back Friendly'],
      alternatives: ['hollow_body_hold', 'dead_bug'],
      progressions: ['weighted_plank', 'plank_shoulder_tap'],
      regressions: ['knee_plank'],
      thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/plank.gif',
      videoUrl: '',
      steps: [
        'Get into a forearm plank position, elbows directly under your shoulders, forearms flat on the floor.',
        'Extend your legs straight back, resting on the balls of your feet.',
        'Create a straight line from your head to your heels, bracing your core and squeezing your glutes.',
        'Hold this position without letting your hips sag or your upper back round.'
      ],
      commonMistakes: ['Sagging hips', 'Hyperextending neck', 'Holding breath'],
      safetyTips: ['Keep your spine neutral', 'Brace abdominal wall actively'],
      breathing: 'Breathe steadily and deeply.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Transverse Abdominis', 'Upper Abs', 'Lower Abs', 'Bodyweight', 'Beginner', 'Isolation', 'General Fitness', 'Isometric', 'Core'],
    ),
    // 26. Plank Shoulder Tap
    Exercise(
      exerciseId: 'plank_shoulder_tap',
      name: 'Plank Shoulder Tap',
      aliases: ['High Plank Shoulder Taps', 'Shoulder Taps'],
      muscleGroup: 'Core',
      targetRegions: ['Transverse Abdominis', 'Obliques'],
      exerciseType: 'Warm-up',
      trainingStyles: ['General Fitness', 'Calisthenics', 'Fat Loss'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Anti Rotation',
      goalTags: ['Core Stability', 'Core Strength', 'Balance'],
      isCompound: false,
      primaryMuscles: ['Core', 'Transverse Abdominis'],
      secondaryMuscles: ['Shoulders', 'Triceps'],
      mechanics: 'Static',
      forceType: 'Isometric',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Office', 'Travel'],
      injuryFriendly: ['Knee Friendly'],
      alternatives: ['plank', 'dead_bug'],
      progressions: ['weighted_plank_shoulder_tap'],
      regressions: ['knee_plank_shoulder_tap'],
      thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Start in a high plank position with feet slightly wider than hip-width.',
        'Brace your core, keeping your pelvis entirely stable.',
        'Lift your right hand and tap your left shoulder.',
        'Return to standard plank and repeat with the left hand on the right shoulder.',
        'Avoid shifting your weight or rotating your hips.'
      ],
      commonMistakes: ['Shifting hips side to side', 'Lifting hips too high', 'Dropping the head'],
      safetyTips: ['Keep your spine straight', 'Maintain active shoulder stability on the floor hand'],
      breathing: 'Breathe steadily. Exhale as you lift hand, inhale as it returns.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Transverse Abdominis', 'Obliques', 'Bodyweight', 'Intermediate', 'Isolation', 'Core'],
    ),
    // 27. Reverse Crunch
    Exercise(
      exerciseId: 'reverse_crunch',
      name: 'Reverse Crunch',
      aliases: ['Lying Reverse Crunch', 'Reverse Ab Crunch'],
      muscleGroup: 'Core',
      targetRegions: ['Lower Abs', 'Rectus Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'General Fitness', 'Calisthenics', 'Fat Loss'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Spinal Flexion',
      goalTags: ['Lower Ab Development', 'Core Strength', 'Muscle Building', 'Endurance'],
      isCompound: false,
      primaryMuscles: ['Lower Abs', 'Rectus Abdominis'],
      secondaryMuscles: ['Upper Abs', 'Hip Flexors', 'Obliques'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Lower Back Friendly', 'Beginner Friendly'],
      alternatives: ['lying_leg_raise', 'hanging_knee_raise', 'reverse_crunch_on_bench'],
      progressions: ['decline_reverse_crunch', 'weighted_reverse_crunch', 'dragon_flag'],
      regressions: ['bent_knee_reverse_crunch', 'dead_bug'],
      thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/reverse_crunch.gif',
      videoUrl: '',
      steps: [
        'Lie flat on your back with your arms beside your body.',
        'Lift your legs so your hips and knees are bent at approximately 90 degrees.',
        'Brace your core and press your lower back into the floor.',
        'Curl your pelvis upward, bringing your knees toward your chest.',
        'Pause briefly at the top while squeezing your abdominal muscles.',
        'Slowly lower your hips and legs back to the starting position without using momentum.'
      ],
      commonMistakes: [
        'Swinging the legs instead of using the abs',
        'Using momentum to lift the hips',
        'Arching the lower back',
        'Lowering the legs too quickly',
        'Holding the breath'
      ],
      safetyTips: [
        'Keep movements slow and controlled.',
        'Focus on curling the pelvis rather than swinging the legs.',
        'Maintain contact between the lower back and the floor.',
        'Stop if you experience lower back pain.'
      ],
      breathing: 'Exhale while curling your hips upward. Inhale while slowly returning to the starting position.',
      estimatedCaloriesPerMinute: 5.1,
      tags: ['Core', 'Lower Abs', 'Rectus Abdominis', 'Bodyweight', 'Isolation', 'Beginner', 'General Fitness', 'Fat Loss', 'Muscle Building', 'Calisthenics'],
    ),
    // 28. Russian Twist
    Exercise(
      exerciseId: 'russian_twist',
      name: 'Russian Twist',
      aliases: ['Oblique Twists', 'Russian Twists'],
      muscleGroup: 'Core',
      targetRegions: ['Obliques'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['General Fitness', 'Calisthenics'],
      categories: ['General Fitness', 'Calisthenics', 'Isolation'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Rotation',
      goalTags: ['Oblique Strength', 'Core Stability'],
      isCompound: false,
      primaryMuscles: ['Core'],
      secondaryMuscles: ['Obliques'],
      mechanics: 'Isolation',
      forceType: 'Isometric',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['plank', 'side_plank'],
      progressions: ['weighted_russian_twists'],
      regressions: ['feet_supported_russian_twists'],
      thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/russian_twist.gif',
      videoUrl: '',
      steps: [
        'Sit on the floor, lean your torso back slightly, and lift your feet off the ground.',
        'Hold your hands together in front of your chest.',
        'Rotate your torso to the right, touching the floor with your hands.',
        'Rotate back to the center and then to the left.'
      ],
      commonMistakes: ['Only moving the arms instead of rotating the torso', 'Rounding the spine'],
      safetyTips: ['Keep your spine straight', 'Control the twisting movement'],
      breathing: 'Breathing continuously throughout the movement.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Obliques', 'Bodyweight', 'Intermediate', 'Isolation', 'General Fitness', 'Rotation', 'Core'],
    ),
    // 29. Scissor Kick
    Exercise(
      exerciseId: 'scissor_kick',
      name: 'Scissor Kick',
      aliases: ['Scissor Kicks', 'Horizontal Scissor Kicks'],
      muscleGroup: 'Core',
      targetRegions: ['Lower Abs', 'Rectus Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Fat Loss', 'General Fitness'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Hip Flexion',
      goalTags: ['Lower Ab Development', 'Core Strength'],
      isCompound: false,
      primaryMuscles: ['Lower Abs'],
      secondaryMuscles: ['Hip Flexors', 'Rectus Abdominis'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Beginner Friendly'],
      alternatives: ['flutter_kick', 'lying_leg_raise'],
      progressions: ['hollow_body_scissor_kicks'],
      regressions: ['bent_knee_scissor_kicks'],
      thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/scissor_kick.gif',
      videoUrl: '',
      steps: [
        'Lie flat on your back, hands under your glutes for back support.',
        'Lift both legs slightly off the floor.',
        'Spread your legs wide, then cross them over one another in a horizontal crossing motion.',
        'Keep your legs fully straight and control the action.'
      ],
      commonMistakes: ['Arching the lower back', 'Bending the knees too much'],
      safetyTips: ['Press the spine flat against the ground', 'If back arches, raise legs higher'],
      breathing: 'Breathe steadily throughout the movement.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Lower Abs', 'Rectus Abdominis', 'Bodyweight', 'Beginner', 'Isolation', 'Core'],
    ),
    // 30. Side Plank
    Exercise(
      exerciseId: 'side_plank',
      name: 'Side Plank',
      aliases: ['Lateral Plank', 'Side Hold'],
      muscleGroup: 'Core',
      targetRegions: ['Obliques', 'Transverse Abdominis'],
      exerciseType: 'Warm-up',
      trainingStyles: ['General Fitness', 'Calisthenics', 'Fat Loss', 'Rehabilitation'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Anti Lateral Flexion',
      goalTags: ['Core Stability', 'Posture', 'Injury Prevention'],
      isCompound: false,
      primaryMuscles: ['Core', 'Obliques'],
      secondaryMuscles: ['Shoulders', 'Glutes'],
      mechanics: 'Static',
      forceType: 'Isometric',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Lower Back Friendly', 'Knee Friendly'],
      alternatives: ['plank', 'copenhagen_plank'],
      progressions: ['weighted_side_plank', 'side_plank_raises'],
      regressions: ['knee_side_plank'],
      thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/side_plank.gif',
      videoUrl: '',
      steps: [
        'Lie on your side with your elbow directly below your shoulder.',
        'Stack your feet together.',
        'Lift your hips off the floor, forming a straight line from head to ankles.',
        'Hold the position without letting your hips sag.'
      ],
      commonMistakes: ['Hips sagging', 'Elbow not aligned under shoulder', 'Twisting the shoulders forward'],
      safetyTips: ['Squeeze glutes to maintain hip extension', 'Keep head in neutral extension'],
      breathing: 'Maintain slow, steady breathing.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Obliques', 'Transverse Abdominis', 'Bodyweight', 'Beginner', 'Isolation', 'Core'],
    ),
    // 31. Sit-Up
    Exercise(
      exerciseId: 'sit_up',
      name: 'Sit-Up',
      aliases: ['Ab Sit-Up', 'Bodyweight Sit-Up'],
      muscleGroup: 'Core',
      targetRegions: ['Upper Abs', 'Lower Abs', 'Rectus Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'General Fitness', 'Calisthenics', 'Fat Loss', 'Athletic Performance'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Spinal Flexion',
      goalTags: ['Core Strength', 'Muscle Building', 'Endurance'],
      isCompound: false,
      primaryMuscles: ['Rectus Abdominis', 'Upper Abs'],
      secondaryMuscles: ['Lower Abs', 'Hip Flexors', 'Obliques'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Beginner Friendly'],
      alternatives: ['crunch', 'machine_crunch', 'cable_crunch'],
      progressions: ['weighted_sit_up', 'decline_sit_up', 'medicine_ball_sit_up'],
      regressions: ['partial_sit_up', 'crunch'],
      thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/sit_up.gif',
      videoUrl: '',
      steps: [
        'Lie on your back with knees bent and feet flat on the floor.',
        'Cross your arms over your chest or place fingertips lightly beside your head.',
        'Brace your core before initiating the movement.',
        'Lift your torso until your chest approaches your thighs.',
        'Pause briefly at the top.',
        'Slowly lower your torso back to the starting position with control.'
      ],
      commonMistakes: [
        'Using momentum instead of abdominal muscles',
        'Pulling the neck forward',
        'Lifting the feet off the ground',
        'Dropping quickly during the lowering phase'
      ],
      safetyTips: [
        'Move in a slow and controlled manner.',
        'Keep your neck neutral throughout the movement.',
        'Engage your core before every repetition.',
        'Stop if you feel pain in your lower back.'
      ],
      breathing: 'Exhale while sitting up. Inhale while lowering back to the floor.',
      estimatedCaloriesPerMinute: 5.2,
      tags: ['Core', 'Upper Abs', 'Lower Abs', 'Rectus Abdominis', 'Bodyweight', 'Isolation', 'Beginner', 'General Fitness', 'Fat Loss', 'Muscle Building'],
    ),
    // 32. Stability Ball Crunch
    Exercise(
      exerciseId: 'stability_ball_crunch',
      name: 'Stability Ball Crunch',
      aliases: ['Swiss Ball Crunch', 'Physioball Crunch'],
      muscleGroup: 'Core',
      targetRegions: ['Upper Abs', 'Lower Abs', 'Rectus Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Rehabilitation'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Stability Ball'],
      difficulty: 'Beginner',
      movementPattern: 'Spinal Flexion',
      goalTags: ['Core Stability', 'Core Strength'],
      isCompound: false,
      primaryMuscles: ['Rectus Abdominis'],
      secondaryMuscles: ['Obliques'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['crunch', 'decline_crunch'],
      progressions: ['weighted_stability_ball_crunch'],
      regressions: ['standard_crunch'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/stability_ball_crunch.gif',
      videoUrl: '',
      steps: [
        'Lie face-up on a stability ball, with your lower back supported by the curve of the ball.',
        'Keep your feet flat on the floor, knees bent at 90 degrees.',
        'Place fingertips behind your head and contract your abs to curl your torso up.',
        'Slowly lower back, achieving a slight abdominal stretch over the ball.'
      ],
      commonMistakes: ['Pulling neck', 'Ball rolling during crunch', 'Pushing off with feet'],
      safetyTips: ['Ensure the ball is properly inflated', 'Keep feet firmly planted to stabilize the ball'],
      breathing: 'Exhale curling up, inhale stretching back.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Upper Abs', 'Lower Abs', 'Stability Ball', 'Beginner', 'Isolation', 'Core'],
    ),
    // 33. Suitcase Carry
    Exercise(
      exerciseId: 'suitcase_carry',
      name: 'Suitcase Carry',
      aliases: ['One-Arm Carry', 'Single Dumbbell Walk'],
      muscleGroup: 'Core',
      targetRegions: ['Obliques', 'Transverse Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['Strength Training', 'Functional Fitness'],
      categories: ['Compound', 'Dumbbell'],
      equipment: ['Dumbbell', 'Kettlebell'],
      difficulty: 'Intermediate',
      movementPattern: 'Anti Lateral Flexion',
      goalTags: ['Core Stability', 'Grip Strength', 'Postural Strength'],
      isCompound: true,
      primaryMuscles: ['Obliques', 'Transverse Abdominis'],
      secondaryMuscles: ['Forearms', 'Upper Back', 'Glutes'],
      mechanics: 'Compound',
      forceType: 'Isometric',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['farmers_carry', 'side_plank'],
      progressions: ['heavy_suitcase_carry'],
      regressions: ['lighter_suitcase_carry'],
      thumbnail: 'https://images.unsplash.com/photo-1627483297886-49710ae1fc22?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Hold a single heavy dumbbell in one hand beside your thigh.',
        'Brace your core, squeeze your shoulder blades, and stand completely straight (avoid leaning toward weight).',
        'Walk forward in a straight line with controlled steps, keeping your posture vertical.'
      ],
      commonMistakes: ['Leaning to one side', 'Holding the dumbbell away from the body', 'Shrugging shoulders'],
      safetyTips: ['Keep spine entirely straight and upright', 'Maintain a firm core brace'],
      breathing: 'Breathe steadily throughout the walk.',
      estimatedCaloriesPerMinute: 7.2,
      tags: ['Obliques', 'Transverse Abdominis', 'Dumbbell', 'Intermediate', 'Compound', 'Core'],
    ),
    // 34. Swiss Ball Pike
    Exercise(
      exerciseId: 'swiss_ball_pike',
      name: 'Swiss Ball Pike',
      aliases: ['Stability Ball Pike', 'Gymnastic Ball Pike'],
      muscleGroup: 'Core',
      targetRegions: ['Lower Abs', 'Transverse Abdominis', 'Upper Abs'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Functional Fitness', 'Gymnastics'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Stability Ball'],
      difficulty: 'Advanced',
      movementPattern: 'Hip Flexion',
      goalTags: ['Core Strength', 'Shoulder Stability', 'Balance'],
      isCompound: true,
      primaryMuscles: ['Core', 'Lower Abs'],
      secondaryMuscles: ['Shoulders', 'Triceps', 'Hip Flexors'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['trx_pike', 'plank'],
      progressions: ['swiss_ball_pike_one_leg'],
      regressions: ['swiss_ball_knee_tucks'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/swiss_ball_pike.gif',
      videoUrl: '',
      steps: [
        'Start in a pushup position with your shins resting on top of a stability ball.',
        'Brace your core and keep your arms straight.',
        'Using your abs, roll the ball forward while lifting your hips toward the ceiling.',
        'Keep your legs straight, arriving in an inverted V-shape over the ball.',
        'Slowly lower back to standard pushup plank.'
      ],
      commonMistakes: ['Arching the lower back', 'Bending the knees', 'Sinking in the shoulders'],
      safetyTips: ['Focus on active shoulder push', 'Maintain control over the ball stability'],
      breathing: 'Exhale raising hips, inhale lowering to start.',
      estimatedCaloriesPerMinute: 7.0,
      tags: ['Lower Abs', 'Transverse Abdominis', 'Upper Abs', 'Stability Ball', 'Advanced', 'Compound', 'Core'],
    ),
    // 35. Toe Touch
    Exercise(
      exerciseId: 'toe_touch',
      name: 'Toe Touch',
      aliases: ['Lying Toe Touches', 'Toe Touch Crunch'],
      muscleGroup: 'Core',
      targetRegions: ['Upper Abs', 'Rectus Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Calisthenics'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Spinal Flexion',
      goalTags: ['Core Strength', 'Lower Ab Development'],
      isCompound: false,
      primaryMuscles: ['Rectus Abdominis'],
      secondaryMuscles: ['Lower Abs'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Knee Friendly'],
      alternatives: ['crunch', 'v_up'],
      progressions: ['weighted_toe_touch'],
      regressions: ['crunch'],
      thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/toe_touch.gif',
      videoUrl: '',
      steps: [
        'Lie on your back, raising your straight legs until they point straight toward the ceiling.',
        'Extend your arms overhead.',
        'Engage your abs and flex your spine to lift your head and shoulders, reaching hands to toes.',
        'Slowly lower back to floor.'
      ],
      commonMistakes: ['Pulling head forward', 'Bending knees', 'Using momentum'],
      safetyTips: ['Keep lower back pressed against mat', 'Do not bounce shoulders off floor'],
      breathing: 'Exhale raising, inhale lowering.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Upper Abs', 'Rectus Abdominis', 'Bodyweight', 'Beginner', 'Isolation', 'Core'],
    ),
    // 36. TRX Pike
    Exercise(
      exerciseId: 'trx_pike',
      name: 'TRX Pike',
      aliases: ['Suspension Trainer Pike', 'TRX Ab Pike'],
      muscleGroup: 'Core',
      targetRegions: ['Lower Abs', 'Transverse Abdominis', 'Upper Abs'],
      exerciseType: 'Strength',
      trainingStyles: ['Functional Fitness', 'Calisthenics'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Suspension Trainer (TRX)'],
      difficulty: 'Advanced',
      movementPattern: 'Hip Flexion',
      goalTags: ['Core Strength', 'Shoulder Stability', 'Balance'],
      isCompound: true,
      primaryMuscles: ['Core', 'Lower Abs'],
      secondaryMuscles: ['Shoulders', 'Triceps', 'Hip Flexors'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['swiss_ball_pike', 'plank'],
      progressions: ['trx_pike_to_pushup'],
      regressions: ['trx_knee_tucks'],
      thumbnail: 'https://images.unsplash.com/photo-1544033527-b192daee1f5b?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Place feet in the TRX foot cradles and start in a high plank position, hands on floor.',
        'Brace your core and keep your legs straight.',
        'Lift your hips toward the ceiling, pulling your feet forward.',
        'Keep your legs fully straight as you enter an inverted V-position.',
        'Slowly lower back to plank.'
      ],
      commonMistakes: ['Bending the knees', 'Arching lower back', 'Sinking at shoulders'],
      safetyTips: ['Maintain active, pushed shoulders', 'Keep hips aligned throughout descent'],
      breathing: 'Exhale lifting, inhale lowering.',
      estimatedCaloriesPerMinute: 7.2,
      tags: ['Lower Abs', 'Transverse Abdominis', 'Upper Abs', 'Suspension Trainer (TRX)', 'Advanced', 'Compound', 'Core'],
    ),
    // 37. V-Up
    Exercise(
      exerciseId: 'v_up',
      name: 'V-Up',
      aliases: ['V Up', 'V-Ups', 'Jackknife Crunch'],
      muscleGroup: 'Core',
      targetRegions: ['Upper Abs', 'Lower Abs', 'Rectus Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Fat Loss', 'Gymnastics'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Spinal Flexion',
      goalTags: ['Core Strength', 'Lower Ab Development'],
      isCompound: false,
      primaryMuscles: ['Rectus Abdominis'],
      secondaryMuscles: ['Hip Flexors', 'Obliques'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['crunches', 'jackknife_sit_up'],
      progressions: ['weighted_v_up'],
      regressions: ['crunches', 'lying_leg_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/v_up.gif',
      videoUrl: '',
      steps: [
        'Lie flat on your back with legs straight and arms extended overhead.',
        'Simultaneously lift your legs and torso off the ground, folding at the waist.',
        'Reach your hands toward your feet, balancing on your glutes to form a V-shape.',
        'Slowly lower back to starting position under control.'
      ],
      commonMistakes: ['Bending the knees', 'Arching lower back on descent', 'Swinging arms instead of abdominal curl'],
      safetyTips: ['Avoid crashing down to the floor', 'Stop if you feel sharp back pain'],
      breathing: 'Exhale folding, inhale lowering.',
      estimatedCaloriesPerMinute: 6.2,
      tags: ['Upper Abs', 'Lower Abs', 'Rectus Abdominis', 'Bodyweight', 'Intermediate', 'Isolation', 'Core'],
    ),
    // 38. Weighted Plank
    Exercise(
      exerciseId: 'weighted_plank',
      name: 'Weighted Plank',
      aliases: ['Plate Loaded Plank'],
      muscleGroup: 'Core',
      targetRegions: ['Transverse Abdominis', 'Upper Abs', 'Lower Abs'],
      exerciseType: 'Strength',
      trainingStyles: ['Strength Training', 'Powerlifting', 'Bodybuilding'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Weight Plate'],
      difficulty: 'Intermediate',
      movementPattern: 'Anti Rotation',
      goalTags: ['Core Strength', 'Core Stability', 'Endurance'],
      isCompound: false,
      primaryMuscles: ['Core', 'Transverse Abdominis'],
      secondaryMuscles: ['Shoulders', 'Glutes', 'Lower Back'],
      mechanics: 'Static',
      forceType: 'Isometric',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['plank', 'ab_wheel_rollout'],
      progressions: ['heavier_weighted_plank'],
      regressions: ['plank'],
      thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/weighted_plank.gif',
      videoUrl: '',
      steps: [
        'Have a partner place a weight plate flat on your upper back while in a forearm plank, or secure it carefully.',
        'Align your body in a straight line from head to heels.',
        'Engage your abs and glutes, resisting the added weight pulling your hips downward.',
        'Hold the plank for the target duration.'
      ],
      commonMistakes: ['Allowing hips to sag', 'Holding breath', 'Pec/shoulder shrugging'],
      safetyTips: ['Ensure the plate is stable and positioned securely on your upper back', 'Brace core deeply to protect back'],
      breathing: 'Breathe continuously in shallow, controlled breaths.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Transverse Abdominis', 'Upper Abs', 'Lower Abs', 'Weight Plate', 'Intermediate', 'Isolation', 'Core'],
    ),
    // 39. Windshield Wiper
    Exercise(
      exerciseId: 'windshield_wiper',
      name: 'Windshield Wiper',
      aliases: ['Floor Windshield Wiper', 'Lying Windshield Wiper'],
      muscleGroup: 'Core',
      targetRegions: ['Obliques', 'Lower Abs'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'General Fitness'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Rotation',
      goalTags: ['Oblique Development', 'Core Strength', 'Rotational Stability'],
      isCompound: false,
      primaryMuscles: ['Obliques'],
      secondaryMuscles: ['Lower Abs', 'Hip Flexors'],
      mechanics: 'Isolation',
      forceType: 'Isometric',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['russian_twist', 'side_plank'],
      progressions: ['hanging_windshield_wiper'],
      regressions: ['bent_knee_windshield_wiper'],
      thumbnail: 'https://images.unsplash.com/photo-1544033527-b192daee1f5b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/windshield_wiper.gif',
      videoUrl: '',
      steps: [
        'Lie flat on your back with arms extended out to the sides for stability.',
        'Raise your straight legs together until they are perpendicular to the floor.',
        'Under strict control, lower your legs to the right side, stopping just before they touch the floor.',
        'Return to center, then lower them to the left side.'
      ],
      commonMistakes: ['Lifting shoulders off floor', 'Allowing legs to drop quickly', 'Bending knees'],
      safetyTips: ['Keep shoulders pinned flat against the mat', 'Control rotation speed'],
      breathing: 'Exhale returning to center, inhale lowering to side.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Obliques', 'Lower Abs', 'Bodyweight', 'Intermediate', 'Isolation', 'Core', 'Rotation'],
    ),
    // 40. Wood Chop
    Exercise(
      exerciseId: 'wood_chop',
      name: 'Wood Chop',
      aliases: ['Cable Wood Chop', 'Band Woodchop'],
      muscleGroup: 'Core',
      targetRegions: ['Obliques', 'Transverse Abdominis'],
      exerciseType: 'Strength',
      trainingStyles: ['Functional Fitness', 'Athletic Performance', 'Strength Training'],
      categories: ['Compound', 'Cable'],
      equipment: ['Cable', 'Band'],
      difficulty: 'Intermediate',
      movementPattern: 'Rotation',
      goalTags: ['Rotational Power', 'Core Strength', 'Oblique Development'],
      isCompound: true,
      primaryMuscles: ['Obliques', 'Transverse Abdominis'],
      secondaryMuscles: ['Shoulders', 'Glutes', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['russian_twist', 'pallof_press'],
      progressions: ['heavy_cable_woodchop'],
      regressions: ['band_woodchop_light'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand lateral to a cable station, feet slightly wider than shoulder-width, holding the high cable attachment.',
        'Rotate your torso and pull the cable down and diagonally across your body to your opposite knee.',
        'Pivot on your back foot as you twist your hips.',
        'Return slowly to starting position under control.'
      ],
      commonMistakes: ['Twisting with back instead of hips', 'Bending elbows (pulling with arms)', 'Moving too fast'],
      safetyTips: ['Keep core tightly braced', 'Pivot the foot to protect knees'],
      breathing: 'Exhale twisting down, inhale returning.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Obliques', 'Transverse Abdominis', 'Cable', 'Intermediate', 'Compound', 'Core', 'Rotation'],
    ),
  ];
}