import '../../models/models.dart';

class BackExercises {
  static final List<Exercise> exercises = [
    // 1. Assisted Pull-Up
    Exercise(
      exerciseId: 'assisted_pull_up',
      name: 'Assisted Pull-Up',
      aliases: ['Machine Assisted Pullup', 'Band Assisted Pull-Up'],
      muscleGroup: 'Back',
      targetRegions: ['Lats', 'Upper Back'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Bodybuilding'],
      categories: ['Compound', 'Machine'],
      equipment: ['Assisted Pull-Up Machine', 'Resistance Band'],
      difficulty: 'Beginner',
      movementPattern: 'Vertical Pull',
      goalTags: ['Strength', 'Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Lats'],
      secondaryMuscles: ['Biceps', 'Rhomboids', 'Rear Delts'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['lat_pulldown', 'negative_pull_up'],
      progressions: ['pull_up'],
      regressions: ['assisted_pull_up_heavy'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-a6f9d1f6b1b8?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Set the weight assistance on the machine (heavier provides more help).',
        'Kneel or stand on the platform/pad and grip the handles slightly wider than shoulder-width.',
        'Hang with arms fully extended, keeping your chest up and shoulders pulled down.',
        'Pull your body upward until your chin clears the bar, squeezing your shoulder blades together.',
        'Slowly lower back down to full extension under control.'
      ],
      commonMistakes: ['Using momentum', 'Not extending arms fully at the bottom', 'Shrugging shoulders at the top'],
      safetyTips: ['Step onto the platform carefully', 'Ensure the pin is fully inserted into the weight stack'],
      breathing: 'Exhale pulling up, inhale lowering down.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Lats', 'Upper Back', 'Machine', 'Beginner', 'Compound', 'Back'],
    ),

    // 2. Back Extension
    Exercise(
      exerciseId: 'back_extension',
      name: 'Back Extension',
      aliases: ['Roman Chair Back Extension', '45 Degree Back Extension'],
      muscleGroup: 'Back',
      targetRegions: ['Lower Back', 'Erector Spinae'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Powerlifting', 'General Fitness', 'Rehabilitation'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Roman Chair', 'Back Extension Bench'],
      difficulty: 'Beginner',
      movementPattern: 'Hinge',
      goalTags: ['Core Strength', 'Posture', 'Injury Prevention'],
      isCompound: false,
      primaryMuscles: ['Lower Back'],
      secondaryMuscles: ['Glutes', 'Hamstrings'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['superman', 'bird_dog'],
      progressions: ['weighted_back_extension'],
      regressions: ['bird_dog', 'superman'],
      thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Position yourself in the Roman chair, adjusting the hip pad so it rests just below your hip crease.',
        'Hook your ankles securely under the roller pads.',
        'Cross your arms over your chest or place fingertips behind your ears.',
        'Bend at the waist to lower your upper body slowly, maintaining a straight spine.',
        'Contract your lower back and glutes to raise your torso back to a straight line with your legs.'
      ],
      commonMistakes: ['Hyperextending the spine at the top', 'Rounding the back during the movement', 'Moving too fast'],
      safetyTips: ['Avoid jerking or swinging at the top', 'Do not arch your back excessively'],
      breathing: 'Inhale lowering, exhale raising.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Lower Back', 'Erector Spinae', 'Bench', 'Beginner', 'Isolation', 'Back'],
    ),

    // 3. Bent Over Barbell Row
    Exercise(
      exerciseId: 'bent_over_barbell_row',
      name: 'Bent Over Barbell Row',
      aliases: ['Barbell Row', 'Bent Over Row'],
      muscleGroup: 'Back',
      targetRegions: ['Mid Back', 'Upper Back', 'Lats'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Powerlifting', 'General Fitness', 'Strength Training'],
      categories: ['Compound', 'Barbell'],
      equipment: ['Barbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Horizontal Row',
      goalTags: ['Muscle Gain', 'Strength', 'Posture'],
      isCompound: true,
      primaryMuscles: ['Upper Back', 'Lats'],
      secondaryMuscles: ['Biceps', 'Rear Delts', 'Lower Back'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['t_bar_row', 'dumbbell_row', 'seated_cable_row'],
      progressions: ['heavy_barbell_row', 'pendlay_row'],
      regressions: ['chest_supported_row', 'machine_row'],
      thumbnail: 'https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand over a barbell with feet hip-width apart, bend knees slightly, and hinge at your hips until your torso is almost parallel to the floor.',
        'Grip the barbell with an overhand grip, slightly wider than shoulder-width, arms fully extended.',
        'Brace your core, squeeze your shoulder blades, and pull the bar to your lower chest/upper abdomen.',
        'Keep elbows tucked close to your body and squeeze your back at the top.',
        'Slowly lower the barbell back to starting hang under full control.'
      ],
      commonMistakes: ['Rounding the lower back', 'Standing up too straight during the row', 'Using momentum (jerking body)'],
      safetyTips: ['Keep your spine completely straight', 'Engage your core to protect the lower back'],
      breathing: 'Exhale pulling up, inhale extending down.',
      estimatedCaloriesPerMinute: 7.5,
      tags: ['Mid Back', 'Upper Back', 'Lats', 'Barbell', 'Intermediate', 'Compound', 'Back'],
    ),

    // 4. Bird Dog
    Exercise(
      exerciseId: 'bird_dog',
      name: 'Bird Dog',
      aliases: ['Quadruped Alternating Arm and Leg Raise'],
      muscleGroup: 'Back',
      targetRegions: ['Lower Back', 'Transverse Abdominis'],
      exerciseType: 'Warm-up',
      trainingStyles: ['General Fitness', 'Functional Fitness', 'Rehabilitation'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Anti Rotation',
      goalTags: ['Core Stability', 'Injury Prevention', 'Posture'],
      isCompound: false,
      primaryMuscles: ['Lower Back', 'Core'],
      secondaryMuscles: ['Glutes', 'Shoulders'],
      mechanics: 'Isolation',
      forceType: 'Isometric',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Lower Back Friendly', 'Wrist Friendly'],
      alternatives: ['plank', 'dead_bug'],
      progressions: ['weighted_bird_dog', 'elevated_bird_dog'],
      regressions: ['single_limb_raises'],
      thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Start on your hands and knees in a tabletop position, hands under shoulders and knees under hips.',
        'Brace your core, keeping your spine neutral.',
        'Slowly reach your right arm straight forward and extend your left leg straight backward.',
        'Keep your hips level and avoid arching your lower back.',
        'Hold for 2 seconds, then return to the starting tabletop position.',
        'Repeat on the opposite side.'
      ],
      commonMistakes: ['Arching the lower back', 'Tilting the hips', 'Looking straight up (craning neck)'],
      safetyTips: ['Focus on extension and stability rather than height', 'Keep your neck in line with your spine'],
      breathing: 'Exhale as you extend, inhale as you return.',
      estimatedCaloriesPerMinute: 3.5,
      tags: ['Lower Back', 'Transverse Abdominis', 'Bodyweight', 'Beginner', 'Isolation', 'General Fitness', 'Core', 'Back'],
    ),

    // 5. Cable Pullover
    Exercise(
      exerciseId: 'cable_pullover',
      name: 'Cable Pullover',
      aliases: ['Standing Cable Lat Pushdown', 'Straight Arm Cable Pulldown'],
      muscleGroup: 'Back',
      targetRegions: ['Lats'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Isolation', 'Cable'],
      equipment: ['Cable', 'Straight Bar'],
      difficulty: 'Intermediate',
      movementPattern: 'Vertical Pull',
      goalTags: ['Muscle Gain', 'Lat Isolation'],
      isCompound: false,
      primaryMuscles: ['Lats'],
      secondaryMuscles: ['Triceps', 'Chest', 'Rear Delts'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['straight_arm_pulldown', 'machine_pullover'],
      progressions: ['heavy_cable_pullover'],
      regressions: ['resistance_band_pullover'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Attach a straight bar or rope to a high pulley cable station.',
        'Grip the attachment and step back to create tension, leaning forward slightly from the hips with a flat back.',
        'Keep a very slight bend in your elbows and lock them in place.',
        'Contract your lats to pull the bar down in an arc to your thighs.',
        'Slowly return the bar to the starting overhead position, feeling a stretch in your lats.'
      ],
      commonMistakes: ['Bending and extending the elbows (turning it into a pressdown)', 'Rounding the upper back', 'Using too much momentum'],
      safetyTips: ['Keep your spine neutral throughout the movement', 'Control the return phase completely'],
      breathing: 'Exhale pulling down, inhale returning.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Lats', 'Cable', 'Intermediate', 'Isolation', 'Back'],
    ),

    // 6. Chest Supported Row
    Exercise(
      exerciseId: 'chest_supported_row',
      name: 'Chest Supported Row',
      aliases: ['Incline Bench Dumbbell Row', 'T-Bar Chest Supported Row'],
      muscleGroup: 'Back',
      targetRegions: ['Mid Back', 'Upper Back', 'Lats'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Strength Training', 'General Fitness'],
      categories: ['Compound', 'Dumbbell'],
      equipment: ['Bench', 'Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Horizontal Row',
      goalTags: ['Muscle Gain', 'Strength', 'Posture'],
      isCompound: true,
      primaryMuscles: ['Upper Back', 'Lats'],
      secondaryMuscles: ['Biceps', 'Rhomboids', 'Rear Delts'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['machine_row', 'seated_cable_row'],
      progressions: ['bent_over_barbell_row', 'heavy_dumbbell_row'],
      regressions: ['trx_row', 'machine_row'],
      thumbnail: 'https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Set an incline bench to roughly 30-45 degrees.',
        'Lie chest-down on the bench, holding dumbbells with fully extended arms.',
        'Pull your elbows upward and backward, squeezing your shoulder blades together.',
        'Keep your chest pressed against the pad throughout the movement.',
        'Slowly lower the dumbbells back to full extension.'
      ],
      commonMistakes: ['Lifting the chest off the pad', 'Shrugging shoulders upward', 'Short range of motion'],
      safetyTips: ['Do not strain your neck; keep it neutral', 'Keep core engaged'],
      breathing: 'Exhale rowing up, inhale lowering.',
      estimatedCaloriesPerMinute: 6.8,
      tags: ['Mid Back', 'Upper Back', 'Lats', 'Dumbbell', 'Beginner', 'Compound', 'Back'],
    ),

    // 7. Chin-Up
    Exercise(
      exerciseId: 'chin_up',
      name: 'Chin-Up',
      aliases: ['Underhand Grip Pullup', 'Chinup'],
      muscleGroup: 'Back',
      targetRegions: ['Lats', 'Lower Traps'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Strength Training', 'Bodybuilding'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Pull-up Bar'],
      difficulty: 'Intermediate',
      movementPattern: 'Vertical Pull',
      goalTags: ['Strength', 'Muscle Gain', 'Bicep Growth'],
      isCompound: true,
      primaryMuscles: ['Lats', 'Biceps'],
      secondaryMuscles: ['Rhomboids', 'Upper Back', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['pull_up', 'reverse_grip_lat_pulldown'],
      progressions: ['weighted_chin_up'],
      regressions: ['assisted_pull_up', 'negative_pull_up'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-a6f9d1f6b1b8?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Grip the pull-up bar with an underhand (supinated) grip, shoulder-width apart.',
        'Hang with fully extended arms, shoulders pulled down and back.',
        'Pull your chest up toward the bar, leading with your elbows.',
        'Continue until your chin clears the bar and squeeze your biceps and back.',
        'Slowly lower yourself back to full extension.'
      ],
      commonMistakes: ['Swinging or using leg drive (kicking)', 'Not completing full range of motion', 'Shrugging shoulders'],
      safetyTips: ['Keep your core tight and body stable', 'Avoid dropping quickly into full extension'],
      breathing: 'Exhale pulling up, inhale lowering down.',
      estimatedCaloriesPerMinute: 7.5,
      tags: ['Lats', 'Biceps', 'Bodyweight', 'Intermediate', 'Compound', 'Back'],
    ),

    // 8. Close Grip Cable Row
    Exercise(
      exerciseId: 'close_grip_cable_row',
      name: 'Close Grip Cable Row',
      aliases: ['Seated Close Grip Cable Row', 'V-Bar Cable Row'],
      muscleGroup: 'Back',
      targetRegions: ['Mid Back', 'Lats'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'General Fitness', 'Strength Training'],
      categories: ['Compound', 'Cable'],
      equipment: ['Cable', 'V-Bar Attachment'],
      difficulty: 'Beginner',
      movementPattern: 'Horizontal Row',
      goalTags: ['Muscle Gain', 'Strength', 'Posture'],
      isCompound: true,
      primaryMuscles: ['Lats', 'Upper Back'],
      secondaryMuscles: ['Biceps', 'Rhomboids', 'Rear Delts'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['t_bar_row', 'chest_supported_row'],
      progressions: ['heavy_seated_cable_row', 'bent_over_barbell_row'],
      regressions: ['machine_row', 'trx_row'],
      thumbnail: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit at a cable row machine with a V-bar attachment.',
        'Place feet on the footplates, bend knees slightly, and grip the attachment.',
        'Sit tall with your spine straight, leaning back very slightly from the hips.',
        'Pull the attachment to your lower chest/upper abdomen, squeezing your shoulder blades together.',
        'Slowly extend your arms back out under control.'
      ],
      commonMistakes: ['Leaning forward and backward excessively (swinging)', 'Rounding the spine', 'Shrugging shoulders'],
      safetyTips: ['Keep your lower back flat and locked', 'Keep your elbows tucked close to your sides'],
      breathing: 'Exhale rowing, inhale returning.',
      estimatedCaloriesPerMinute: 6.5,
      tags: ['Mid Back', 'Lats', 'Cable', 'Beginner', 'Compound', 'Back'],
    ),

    // 9. Close Grip Lat Pulldown
    Exercise(
      exerciseId: 'close_grip_lat_pulldown',
      name: 'Close Grip Lat Pulldown',
      aliases: ['V-Bar Lat Pulldown', 'Close Grip Pulldown'],
      muscleGroup: 'Back',
      targetRegions: ['Lats', 'Lower Traps'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Compound', 'Machine'],
      equipment: ['Lat Pulldown Machine', 'V-Bar Attachment'],
      difficulty: 'Beginner',
      movementPattern: 'Vertical Pull',
      goalTags: ['Muscle Gain', 'Back Width'],
      isCompound: true,
      primaryMuscles: ['Lats'],
      secondaryMuscles: ['Biceps', 'Rhomboids', 'Upper Back'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['lat_pulldown', 'chin_up'],
      progressions: ['heavy_close_grip_pulldown'],
      regressions: ['assisted_pull_up', 'straight_arm_pulldown'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Attach a V-bar handle to the lat pulldown station and adjust the thigh pad.',
        'Grip the handles and sit down, locking your thighs under the pads.',
        'Lean back very slightly and pull the bar straight down to your chest.',
        'Drive your elbows downward, squeezing your lats at the bottom.',
        'Slowly let the attachment return to the top until your arms are fully extended.'
      ],
      commonMistakes: ['Pulling the bar behind the neck', 'Leaning back excessively to pull the weight', 'Using momentum'],
      safetyTips: ['Control the ascent phase', 'Keep shoulders packed down away from ears'],
      breathing: 'Exhale pulling down, inhale returning up.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Lats', 'Lower Traps', 'Machine', 'Beginner', 'Compound', 'Back'],
    ),

    // 10. Close Grip Pull-Up
    Exercise(
      exerciseId: 'close_grip_pull_up',
      name: 'Close Grip Pull-Up',
      aliases: ['Close Grip Pullup', 'Narrow Grip Pullup'],
      muscleGroup: 'Back',
      targetRegions: ['Lats', 'Lower Traps'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Strength Training', 'Bodybuilding'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Pull-up Bar'],
      difficulty: 'Intermediate',
      movementPattern: 'Vertical Pull',
      goalTags: ['Strength', 'Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Lats'],
      secondaryMuscles: ['Biceps', 'Rhomboids', 'Upper Back'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['chin_up', 'neutral_grip_pull_up'],
      progressions: ['weighted_pull_up'],
      regressions: ['assisted_pull_up', 'negative_pull_up'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-a6f9d1f6b1b8?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Grip the pull-up bar with an overhand grip, hands closer than shoulder-width.',
        'Hang with fully extended arms, keeping your chest proud.',
        'Pull your body upward, driving your elbows down toward your ribs.',
        'Continue until your chin clears the bar, squeezing your shoulder blades together.',
        'Slowly lower yourself back to full extension.'
      ],
      commonMistakes: ['Using momentum (swinging)', 'Kicking legs', 'Shrugging shoulders'],
      safetyTips: ['Keep your spine straight and core braced', 'Control the eccentric phase'],
      breathing: 'Exhale pulling up, inhale lowering down.',
      estimatedCaloriesPerMinute: 7.2,
      tags: ['Lats', 'Lower Traps', 'Bodyweight', 'Intermediate', 'Compound', 'Back'],
    ),

    // 11. Deadlift
    Exercise(
      exerciseId: 'deadlift',
      name: 'Deadlift',
      aliases: ['Conventional Deadlift', 'Barbell Deadlift'],
      muscleGroup: 'Back',
      targetRegions: ['Lower Back', 'Glutes', 'Hamstrings', 'Erector Spinae'],
      exerciseType: 'Strength',
      trainingStyles: ['Powerlifting', 'Strength Training', 'General Fitness', 'Bodybuilding'],
      categories: ['Compound', 'Barbell'],
      equipment: ['Barbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Hinge',
      goalTags: ['Strength', 'Full Body Power', 'Muscle Building'],
      isCompound: true,
      primaryMuscles: ['Lower Back', 'Glutes', 'Hamstrings'],
      secondaryMuscles: ['Traps', 'Core', 'Forearms', 'Quads'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Full Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['trap_bar_deadlift', 'romanian_deadlift', 'rack_pull'],
      progressions: ['heavy_deadlifts', 'deficit_deadlift'],
      regressions: ['kettlebell_deadlift', 'rack_pull'],
      thumbnail: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand with feet hip-width apart, with the barbell over the middle of your feet.',
        'Hinge at your hips and bend your knees slightly to grip the bar with a shoulder-width overhand grip.',
        'Flatten your back, lower your hips, and pull your shoulder blades down and back.',
        'Push through your feet to stand up with the barbell, keeping it close to your shins.',
        'Squeeze your glutes at the top without hyperextending your spine.',
        'Lower the bar slowly by hinging at the hips and then bending knees once the bar clears them.'
      ],
      commonMistakes: ['Rounding the spine (cat back)', 'Holding the bar too far from the shins', 'Squatting the weight up instead of hinging'],
      safetyTips: ['Keep your back flat and locked', 'Maintain a neutral neck alignment', 'Brace your core deeply'],
      breathing: 'Inhale and brace core at bottom, hold breath during lift, exhale at top, inhale/hold lowering.',
      estimatedCaloriesPerMinute: 9.5,
      tags: ['Lower Back', 'Glutes', 'Hamstrings', 'Barbell', 'Intermediate', 'Compound', 'Back'],
    ),

    // 12. Deficit Deadlift
    Exercise(
      exerciseId: 'deficit_deadlift',
      name: 'Deficit Deadlift',
      aliases: ['Platform Deadlift', 'Extended Range Deadlift'],
      muscleGroup: 'Back',
      targetRegions: ['Lower Back', 'Glutes', 'Hamstrings'],
      exerciseType: 'Strength',
      trainingStyles: ['Powerlifting', 'Strength Training'],
      categories: ['Compound', 'Barbell'],
      equipment: ['Barbell', 'Weight Plate (to stand on)'],
      difficulty: 'Advanced',
      movementPattern: 'Hinge',
      goalTags: ['Strength', 'Leg Drive', 'Power'],
      isCompound: true,
      primaryMuscles: ['Lower Back', 'Glutes', 'Hamstrings'],
      secondaryMuscles: ['Quads', 'Core', 'Traps'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Full Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['deadlift', 'trap_bar_deadlift'],
      progressions: ['heavy_deficit_deadlift'],
      regressions: ['deadlift', 'rack_pull'],
      thumbnail: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand on a weight plate or a low platform (1-3 inches high) positioned in front of a loaded barbell.',
        'Set your feet hip-width apart and hinge down to grip the bar.',
        'Pull your shoulder blades back, drop your hips slightly lower than conventional deadlifts, and flatten your back.',
        'Drive through your heels to stand up, keeping the bar close to your shins.',
        'Squeeze your glutes at lockout and lower the bar back to the floor under control.'
      ],
      commonMistakes: ['Rounding the spine due to increased range of motion', 'Allowing hips to shoot up too quickly', 'Using a platform that is too high'],
      safetyTips: ['Ensure your back remains flat throughout the lift', 'Use a moderate deficit (1-2 inches) starting out'],
      breathing: 'Inhale and brace at bottom, exhale at top.',
      estimatedCaloriesPerMinute: 10.0,
      tags: ['Lower Back', 'Glutes', 'Hamstrings', 'Barbell', 'Advanced', 'Compound', 'Back'],
    ),

    // 13. Dumbbell Rear Delt Fly
    Exercise(
      exerciseId: 'dumbbell_rear_delt_fly',
      name: 'Dumbbell Rear Delt Fly',
      aliases: ['Bent Over Rear Delt Raise', 'Dumbbell Rear Delt Raise'],
      muscleGroup: 'Back',
      targetRegions: ['Rear Delts', 'Upper Back'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Dumbbell'],
      equipment: ['Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Horizontal Row',
      goalTags: ['Muscle Gain', 'Shoulder Health', 'Posture'],
      isCompound: false,
      primaryMuscles: ['Rear Delts'],
      secondaryMuscles: ['Upper Back', 'Rhomboids', 'Traps'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['rear_delt_cable_fly', 'reverse_pec_deck'],
      progressions: ['weighted_rear_delt_fly_heavy'],
      regressions: ['resistance_band_pull_apart'],
      thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding dumbbells at your sides.',
        'Hinge forward from the hips with a flat back and a slight bend in your knees until your torso is almost parallel to the floor.',
        'Let the dumbbells hang below your shoulders, palms facing each other, elbows slightly bent.',
        'Raise your arms out to the sides in an arc, squeezing your rear delts and shoulder blades at the top.',
        'Slowly lower the dumbbells back to starting position.'
      ],
      commonMistakes: ['Using momentum (swinging)', 'Bending elbows too much during fly', 'Rounding the back'],
      safetyTips: ['Keep your spine neutral; do not strain your neck', 'Use lighter weights for optimal rear delt activation'],
      breathing: 'Exhale raising weights, inhale lowering.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Rear Delts', 'Upper Back', 'Dumbbell', 'Beginner', 'Isolation', 'Back'],
    ),

    // 14. Dumbbell Row
    Exercise(
      exerciseId: 'dumbbell_row',
      name: 'Dumbbell Row',
      aliases: ['Bent Over Dumbbell Row', 'Two Arm Dumbbell Row'],
      muscleGroup: 'Back',
      targetRegions: ['Lats', 'Mid Back', 'Upper Back'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'General Fitness', 'Strength Training'],
      categories: ['Compound', 'Dumbbell'],
      equipment: ['Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Horizontal Row',
      goalTags: ['Muscle Gain', 'Strength'],
      isCompound: true,
      primaryMuscles: ['Lats', 'Upper Back'],
      secondaryMuscles: ['Biceps', 'Rhomboids', 'Rear Delts', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['single_arm_dumbbell_row', 'bent_over_barbell_row'],
      progressions: ['heavy_dumbbell_row'],
      regressions: ['chest_supported_row', 'machine_row'],
      thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding dumbbells with palms facing each other.',
        'Hinge at hips, bend knees slightly, and lower your torso until it is nearly parallel to the floor.',
        'Keep your spine completely flat.',
        'Pull the dumbbells to your ribs, keeping elbows close to your body.',
        'Slowly lower the dumbbells back to starting hang.'
      ],
      commonMistakes: ['Rounding the spine', 'Using too much momentum', 'Flaring elbows outward'],
      safetyTips: ['Brace your core throughout the movement', 'Keep neck neutral'],
      breathing: 'Exhale pulling up, inhale lowering.',
      estimatedCaloriesPerMinute: 7.0,
      tags: ['Lats', 'Mid Back', 'Upper Back', 'Dumbbell', 'Beginner', 'Compound', 'Back'],
    ),

    // 15. Face Pull
    Exercise(
      exerciseId: 'face_pull',
      name: 'Face Pull',
      aliases: ['Cable Face Pull', 'Rope Face Pull'],
      muscleGroup: 'Back',
      targetRegions: ['Rear Delts', 'Upper Traps', 'Rotator Cuff'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness', 'Rehabilitation'],
      categories: ['Isolation', 'Cable'],
      equipment: ['Cable', 'Rope Attachment'],
      difficulty: 'Beginner',
      movementPattern: 'Horizontal Row',
      goalTags: ['Posture', 'Shoulder Health', 'Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Rear Delts', 'Upper Back'],
      secondaryMuscles: ['Traps', 'Rhomboids', 'Rotator Cuff'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['dumbbell_rear_delt_fly', 'resistance_band_pull_apart'],
      progressions: ['heavy_face_pull'],
      regressions: ['band_face_pull'],
      thumbnail: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Set a cable pulley to upper chest/eye height and attach a rope handle.',
        'Grip the rope ends with your thumbs pointing backward.',
        'Step back to create tension and stand tall with a braced core.',
        'Pull the rope directly toward your face, separating the ends of the rope as they approach your ears.',
        'Focus on external rotation, squeezing your rear delts and upper back at the end of the pull.',
        'Slowly return the weight to starting position.'
      ],
      commonMistakes: ['Pulling with the biceps instead of rear delts', 'Hyperextending the neck', 'Using too much weight'],
      safetyTips: ['Keep the movement controlled; do not jerk', 'Maintain vertical spine'],
      breathing: 'Exhale pulling, inhale returning.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Rear Delts', 'Upper Traps', 'Cable', 'Beginner', 'Isolation', 'Back'],
    ),

    // 16. Good Morning
    Exercise(
      exerciseId: 'good_morning',
      name: 'Good Morning',
      aliases: ['Barbell Good Morning'],
      muscleGroup: 'Back',
      targetRegions: ['Lower Back', 'Hamstrings', 'Glutes'],
      exerciseType: 'Strength',
      trainingStyles: ['Powerlifting', 'Strength Training'],
      categories: ['Compound', 'Barbell'],
      equipment: ['Barbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Hinge',
      goalTags: ['Posterior Chain Strength', 'Core Stability'],
      isCompound: true,
      primaryMuscles: ['Lower Back', 'Hamstrings'],
      secondaryMuscles: ['Glutes', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Full Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['romanian_deadlift', 'back_extension'],
      progressions: ['heavy_good_morning'],
      regressions: ['bodyweight_good_morning', 'back_extension'],
      thumbnail: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Place a barbell across your upper back (traps) as in a back squat.',
        'Stand with feet shoulder-width apart, knees slightly bent.',
        'Brace your core and hinge at your hips, pushing them backward to lower your torso forward.',
        'Maintain a completely flat back and go down until your torso is almost parallel to the floor.',
        'Drive through your glutes and lower back to return to standing.'
      ],
      commonMistakes: ['Rounding the spine', 'Bending the knees too much (squatting instead of hinging)', 'Going too heavy'],
      safetyTips: ['Start light to master the hinge pattern', 'Keep your spine strictly neutral'],
      breathing: 'Inhale lowering, exhale standing up.',
      estimatedCaloriesPerMinute: 6.8,
      tags: ['Lower Back', 'Hamstrings', 'Barbell', 'Intermediate', 'Compound', 'Back'],
    ),

    // 17. Hyperextension
    Exercise(
      exerciseId: 'hyperextension',
      name: 'Hyperextension',
      aliases: ['Flat Bench Back Extension', 'Back Extension Lifts'],
      muscleGroup: 'Back',
      targetRegions: ['Lower Back', 'Glutes'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Rehabilitation', 'Calisthenics'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Hinge',
      goalTags: ['Core Stability', 'Posture'],
      isCompound: false,
      primaryMuscles: ['Lower Back'],
      secondaryMuscles: ['Glutes', 'Hamstrings'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['superman', 'bird_dog'],
      progressions: ['back_extension', 'weighted_back_extension'],
      regressions: ['bird_dog'],
      thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Lie face down on a mat or flat bench with your lower body secured.',
        'Cross your arms over your chest.',
        'Gently raise your upper torso off the floor/bench, engaging your lower back muscles.',
        'Slowly lower back down.'
      ],
      commonMistakes: ['Hyperextending the neck', 'Using jerking movements', 'Arching too high'],
      safetyTips: ['Do not over-arch your back', 'Perform the movement with full control'],
      breathing: 'Exhale raising torso, inhale lowering.',
      estimatedCaloriesPerMinute: 4.0,
      tags: ['Lower Back', 'Glutes', 'Bodyweight', 'Beginner', 'Isolation', 'Back'],
    ),

    // 18. Inverted Row
    Exercise(
      exerciseId: 'inverted_row',
      name: 'Inverted Row',
      aliases: ['Bodyweight Row', 'Horizontal Pull-Up'],
      muscleGroup: 'Back',
      targetRegions: ['Mid Back', 'Upper Back', 'Lats'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'General Fitness', 'Strength Training'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Barbell', 'Smith Machine'],
      difficulty: 'Beginner',
      movementPattern: 'Horizontal Row',
      goalTags: ['Strength', 'Posture', 'Pull-Up Preparation'],
      isCompound: true,
      primaryMuscles: ['Upper Back', 'Lats'],
      secondaryMuscles: ['Biceps', 'Core', 'Rear Delts'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['trx_row', 'chest_supported_row'],
      progressions: ['weighted_inverted_row', 'pull_up'],
      regressions: ['assisted_inverted_row'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-a6f9d1f6b1b8?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Set a barbell in a rack (or Smith machine) to waist height.',
        'Lie face-up under the bar, and grip it with an overhand grip slightly wider than shoulders.',
        'Keep your body in a straight line (plank position) with heels on the floor.',
        'Pull your chest up to the bar by driving your elbows back and squeezing your back.',
        'Slowly lower back to full arm extension.'
      ],
      commonMistakes: ['Sagging hips', 'Not touching chest to bar', 'Shrugging shoulders'],
      safetyTips: ['Ensure the bar is secure and won\'t pop out of the rack', 'Engage core and glutes to keep body rigid'],
      breathing: 'Exhale pulling up, inhale lowering down.',
      estimatedCaloriesPerMinute: 6.5,
      tags: ['Mid Back', 'Upper Back', 'Lats', 'Bodyweight', 'Beginner', 'Compound', 'Back'],
    ),

    // 19. Kettlebell Deadlift
    Exercise(
      exerciseId: 'kettlebell_deadlift',
      name: 'Kettlebell Deadlift',
      aliases: ['KB Deadlift'],
      muscleGroup: 'Back',
      targetRegions: ['Lower Back', 'Glutes', 'Hamstrings'],
      exerciseType: 'Strength',
      trainingStyles: ['Functional Fitness', 'General Fitness', 'Strength Training'],
      categories: ['Compound', 'Kettlebell'],
      equipment: ['Kettlebell'],
      difficulty: 'Beginner',
      movementPattern: 'Hinge',
      goalTags: ['Strength', 'Posterior Chain', 'Hinge Pattern Mastery'],
      isCompound: true,
      primaryMuscles: ['Glutes', 'Hamstrings'],
      secondaryMuscles: ['Lower Back', 'Core', 'Forearms'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: ['Beginner Friendly'],
      alternatives: ['deadlift', 'trap_bar_deadlift'],
      progressions: ['deadlift', 'romanian_deadlift'],
      regressions: ['glute_bridge'],
      thumbnail: 'https://images.unsplash.com/photo-1517838357463-d25dfeac3438?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand with feet shoulder-width apart, with a heavy kettlebell on the floor between your feet.',
        'Hinge at your hips and bend your knees to reach down, gripping the kettlebell handle with both hands.',
        'Keep your spine neutral and shoulders pulled back.',
        'Drive through your heels and stand up, squeezing your glutes at the top.',
        'Push hips back and bend knees to lower the kettlebell back to the floor.'
      ],
      commonMistakes: ['Rounding the back', 'Squatting instead of hinging', 'Shrugging at the top'],
      safetyTips: ['Keep the kettlebell close to your center of gravity', 'Keep your back flat'],
      breathing: 'Inhale down, exhale stand up.',
      estimatedCaloriesPerMinute: 7.0,
      tags: ['Lower Back', 'Glutes', 'Hamstrings', 'Kettlebell', 'Beginner', 'Compound', 'Back'],
    ),

    // 20. Lat Pulldown
    Exercise(
      exerciseId: 'lat_pulldown',
      name: 'Lat Pulldown',
      aliases: ['Wide Grip Lat Pulldown', 'Pulldown'],
      muscleGroup: 'Back',
      targetRegions: ['Lats', 'Upper Back'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'General Fitness', 'Strength Training'],
      categories: ['Compound', 'Machine'],
      equipment: ['Lat Pulldown Machine', 'Straight Bar'],
      difficulty: 'Beginner',
      movementPattern: 'Vertical Pull',
      goalTags: ['Muscle Gain', 'Strength', 'Back Width'],
      isCompound: true,
      primaryMuscles: ['Lats'],
      secondaryMuscles: ['Biceps', 'Rhomboids', 'Rear Delts', 'Upper Traps'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['pull_up', 'close_grip_lat_pulldown'],
      progressions: ['heavy_lat_pulldown', 'pull_up'],
      regressions: ['assisted_pull_up', 'straight_arm_pulldown'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit on a lat pulldown machine and adjust the thigh pad to lock yourself in.',
        'Grip the wide bar with an overhand grip, slightly wider than shoulder-width.',
        'Pull your shoulders down and back, lean back very slightly.',
        'Pull the bar down to your upper chest, leading with your elbows.',
        'Slowly allow the bar to return to full extension.'
      ],
      commonMistakes: ['Pulling the bar down behind the neck', 'Using excessive momentum (swinging back)', 'Not completing the full extension at the top'],
      safetyTips: ['Always pull the bar to your chest, not behind your head', 'Control the return phase completely'],
      breathing: 'Exhale pulling down, inhale returning up.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Lats', 'Upper Back', 'Machine', 'Beginner', 'Compound', 'Back'],
    ),

    // 21. Machine Pullover
    Exercise(
      exerciseId: 'machine_pullover',
      name: 'Machine Pullover',
      aliases: ['Plate Loaded Pullover Machine', 'Nautilus Pullover'],
      muscleGroup: 'Back',
      targetRegions: ['Lats'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Isolation', 'Machine'],
      equipment: ['Pullover Machine'],
      difficulty: 'Intermediate',
      movementPattern: 'Vertical Pull',
      goalTags: ['Muscle Gain', 'Lat Isolation'],
      isCompound: false,
      primaryMuscles: ['Lats'],
      secondaryMuscles: ['Serratus Anterior', 'Rear Delts', 'Chest'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['cable_pullover', 'straight_arm_dumbbell_pullover'],
      progressions: ['heavy_machine_pullover'],
      regressions: ['cable_pullover'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit in the pullover machine and adjust the seat so the pivot point aligns with your shoulders.',
        'Place your elbows on the pads and hold the overhead handles lightly.',
        'Drive your elbows down and back, pulling the pad arc in front of you down to your torso.',
        'Squeeze your lats tightly at the bottom.',
        'Slowly allow the pads to return to the starting position overhead, achieving a full lat stretch.'
      ],
      commonMistakes: ['Gripping the handles too tightly (using too much arm force)', 'Allowing the lower back to arch excessively off the pad', 'Rushing the stretch phase'],
      safetyTips: ['Maintain contact between your lower back and the seat pad', 'Warm up with lighter weights to protect shoulders'],
      breathing: 'Exhale pulling down, inhale returning up.',
      estimatedCaloriesPerMinute: 5.8,
      tags: ['Lats', 'Machine', 'Intermediate', 'Isolation', 'Back'],
    ),

    // 22. Machine Row
    Exercise(
      exerciseId: 'machine_row',
      name: 'Machine Row',
      aliases: ['Seated Machine Row', 'Leverage Row'],
      muscleGroup: 'Back',
      targetRegions: ['Mid Back', 'Lats'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Compound', 'Machine'],
      equipment: ['Row Machine'],
      difficulty: 'Beginner',
      movementPattern: 'Horizontal Row',
      goalTags: ['Muscle Gain', 'Strength', 'Posture'],
      isCompound: true,
      primaryMuscles: ['Lats', 'Upper Back'],
      secondaryMuscles: ['Biceps', 'Rhomboids', 'Rear Delts'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['seated_cable_row', 'chest_supported_row'],
      progressions: ['heavy_machine_row', 'bent_over_barbell_row'],
      regressions: ['trx_row', 'assisted_row'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Adjust the seat and chest support pad so your chest rests comfortably against the pad and you can reach the handles.',
        'Sit tall, grip the handles, and brace your core.',
        'Pull the handles backward by driving your elbows behind you, squeezing your back muscles.',
        'Slowly extend your arms to return to the start.'
      ],
      commonMistakes: ['Lifting the chest off the pad', 'Shrugging shoulders', 'Short range of motion'],
      safetyTips: ['Keep your spine straight', 'Do not drop the weight stack suddenly'],
      breathing: 'Exhale pulling, inhale extending.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Mid Back', 'Lats', 'Machine', 'Beginner', 'Compound', 'Back'],
    ),

    // 23. Meadows Row
    Exercise(
      exerciseId: 'meadows_row',
      name: 'Meadows Row',
      aliases: ['Single Arm Landmine Row'],
      muscleGroup: 'Back',
      targetRegions: ['Lats', 'Upper Back'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Strength Training'],
      categories: ['Compound', 'Barbell'],
      equipment: ['Barbell', 'Landmine Attachment'],
      difficulty: 'Intermediate',
      movementPattern: 'Horizontal Row',
      goalTags: ['Muscle Gain', 'Back Thickness'],
      isCompound: true,
      primaryMuscles: ['Upper Back', 'Lats'],
      secondaryMuscles: ['Biceps', 'Rear Delts', 'Forearms', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['single_arm_dumbbell_row', 't_bar_row'],
      progressions: ['heavy_meadows_row'],
      regressions: ['dumbbell_row', 'machine_row'],
      thumbnail: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Set up a barbell in a landmine attachment.',
        'Stand perpendicular to the barbell, with the bar tip near your rear foot.',
        'Hinge at hips, keeping your spine flat, and grasp the end of the bar (the sleeve) with an overhand grip.',
        'Pull the bar upward, driving your elbow toward the ceiling, keeping it flared out slightly to target the upper back/lats.',
        'Slowly lower the bar back to full arm extension.'
      ],
      commonMistakes: ['Rounding the back', 'Twisting the spine', 'Using too much weight'],
      safetyTips: ['Keep your core engaged to stabilize your pelvis', 'Maintain a flat back'],
      breathing: 'Exhale rowing up, inhale lowering.',
      estimatedCaloriesPerMinute: 7.2,
      tags: ['Lats', 'Upper Back', 'Barbell', 'Intermediate', 'Compound', 'Back'],
    ),

    // 24. Negative Pull-Up
    Exercise(
      exerciseId: 'negative_pull_up',
      name: 'Negative Pull-Up',
      aliases: ['Eccentric Pullup', 'Negative Pullup'],
      muscleGroup: 'Back',
      targetRegions: ['Lats', 'Upper Back'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Strength Training'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Pull-up Bar', 'Box'],
      difficulty: 'Intermediate',
      movementPattern: 'Vertical Pull',
      goalTags: ['Pull-Up Strength', 'Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Lats'],
      secondaryMuscles: ['Biceps', 'Rhomboids', 'Upper Back', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['assisted_pull_up', 'lat_pulldown'],
      progressions: ['pull_up'],
      regressions: ['assisted_pull_up', 'lat_pulldown'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-a6f9d1f6b1b8?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand on a box or bench below a pull-up bar.',
        'Jump or step up so your chin is above the bar, starting at the top of the pull-up position.',
        'Slowly lower your body down over a 3 to 5-second count until your arms are fully extended.',
        'Step back onto the box and repeat.'
      ],
      commonMistakes: ['Dropping too quickly', 'Not reaching full extension at the bottom', 'Shrugging shoulders'],
      safetyTips: ['Ensure box or bench is highly stable', 'Do not drop suddenly to avoid joint strain'],
      breathing: 'Inhale lowering down slowly, exhale stepping back up.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Lats', 'Upper Back', 'Bodyweight', 'Intermediate', 'Compound', 'Back'],
    ),

    // 25. Neutral Grip Pull-Up
    Exercise(
      exerciseId: 'neutral_grip_pull_up',
      name: 'Neutral Grip Pull-Up',
      aliases: ['Hammer Grip Pull-Up', 'Parallel Grip Pull-Up'],
      muscleGroup: 'Back',
      targetRegions: ['Lats', 'Upper Back'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Strength Training', 'Bodybuilding'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Pull-up Bar (Parallel Handles)'],
      difficulty: 'Intermediate',
      movementPattern: 'Vertical Pull',
      goalTags: ['Strength', 'Muscle Gain', 'Shoulder Health'],
      isCompound: true,
      primaryMuscles: ['Lats'],
      secondaryMuscles: ['Biceps', 'Brachialis', 'Rhomboids', 'Upper Back'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['pull_up', 'chin_up'],
      progressions: ['weighted_neutral_grip_pull_up'],
      regressions: ['assisted_pull_up', 'negative_pull_up'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-a6f9d1f6b1b8?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Grip the parallel handles of a pull-up bar with palms facing each other.',
        'Hang with fully extended arms, shoulders pulled down.',
        'Pull your body upward, driving your elbows toward your ribs.',
        'Continue until your chin clears the bar, squeezing your back muscles.',
        'Slowly lower yourself back to full extension.'
      ],
      commonMistakes: ['Swinging or kicking legs', 'Short range of motion', 'Shrugging shoulders'],
      safetyTips: ['Brace your core to minimize swinging', 'Control the eccentric phase'],
      breathing: 'Exhale pulling up, inhale lowering down.',
      estimatedCaloriesPerMinute: 7.2,
      tags: ['Lats', 'Upper Back', 'Bodyweight', 'Intermediate', 'Compound', 'Back'],
    ),

    // 26. Pendlay Row
    Exercise(
      exerciseId: 'pendlay_row',
      name: 'Pendlay Row',
      aliases: ['Strict Barbell Row', 'Dead Stop Row'],
      muscleGroup: 'Back',
      targetRegions: ['Mid Back', 'Upper Back', 'Lats'],
      exerciseType: 'Strength',
      trainingStyles: ['Powerlifting', 'Strength Training', 'Bodybuilding'],
      categories: ['Compound', 'Barbell'],
      equipment: ['Barbell'],
      difficulty: 'Advanced',
      movementPattern: 'Horizontal Row',
      goalTags: ['Power', 'Strength', 'Back Thickness'],
      isCompound: true,
      primaryMuscles: ['Upper Back', 'Lats'],
      secondaryMuscles: ['Core', 'Rear Delts', 'Biceps', 'Lower Back'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['bent_over_barbell_row', 't_bar_row'],
      progressions: ['heavy_pendlay_row'],
      regressions: ['chest_supported_row', 'dumbbell_row'],
      thumbnail: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand over a barbell with feet shoulder-width apart, bar over mid-foot.',
        'Hinge at hips, bending knees slightly, until your torso is parallel to the floor (keep spine completely flat).',
        'Grip the bar with an overhand grip, slightly wider than shoulder-width.',
        'Pull the bar explosively to your lower chest, keeping your torso locked and parallel to the floor.',
        'Return the bar all the way to the floor, allowing it to come to a dead stop before the next rep.'
      ],
      commonMistakes: ['Lifting the torso to row the weight', 'Rounding the back', 'Using leg drive (bouncing)'],
      safetyTips: ['Keep your back completely parallel to the floor', 'Engage core intensely to protect the spine'],
      breathing: 'Exhale pulling up, inhale lowering.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Mid Back', 'Upper Back', 'Lats', 'Barbell', 'Advanced', 'Compound', 'Back'],
    ),

    // 27. Pull-Up
    Exercise(
      exerciseId: 'pull_up',
      name: 'Pull-Up',
      aliases: ['Wide Grip Pullup', 'Pullup', 'Overhand Pull-Up'],
      muscleGroup: 'Back',
      targetRegions: ['Lats', 'Upper Back'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Strength Training', 'Bodybuilding', 'General Fitness'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Pull-up Bar'],
      difficulty: 'Intermediate',
      movementPattern: 'Vertical Pull',
      goalTags: ['Strength', 'Back Width', 'Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Lats', 'Upper Back'],
      secondaryMuscles: ['Biceps', 'Rhomboids', 'Rear Delts', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['lat_pulldown', 'chin_up', 'neutral_grip_pull_up'],
      progressions: ['weighted_pull_up', 'muscle_up'],
      regressions: ['assisted_pull_up', 'negative_pull_up', 'lat_pulldown'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-a6f9d1f6b1b8?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Grip the pull-up bar with an overhand (pronated) grip, slightly wider than shoulder-width.',
        'Hang with fully extended arms, shoulders pulled down and back.',
        'Pull your body upward, driving your elbows down toward your ribs.',
        'Continue until your chin clears the bar, squeezing your shoulder blades together.',
        'Slowly lower yourself back to full extension under control.'
      ],
      commonMistakes: ['Using momentum (swinging)', 'Kicking legs', 'Shrugging shoulders', 'Not extending arms fully at bottom'],
      safetyTips: ['Keep your spine straight and core braced', 'Control the eccentric phase'],
      breathing: 'Exhale pulling up, inhale lowering down.',
      estimatedCaloriesPerMinute: 7.5,
      tags: ['Lats', 'Upper Back', 'Bodyweight', 'Intermediate', 'Compound', 'Back'],
    ),

    // 28. Rack Pull
    Exercise(
      exerciseId: 'rack_pull',
      name: 'Rack Pull',
      aliases: ['Partial Deadlift'],
      muscleGroup: 'Back',
      targetRegions: ['Lower Back', 'Traps', 'Glutes'],
      exerciseType: 'Strength',
      trainingStyles: ['Powerlifting', 'Strength Training', 'Bodybuilding'],
      categories: ['Compound', 'Barbell'],
      equipment: ['Barbell', 'Power Rack'],
      difficulty: 'Intermediate',
      movementPattern: 'Hinge',
      goalTags: ['Strength', 'Lockout Power', 'Upper Back Thickness'],
      isCompound: true,
      primaryMuscles: ['Lower Back', 'Traps'],
      secondaryMuscles: ['Glutes', 'Hamstrings', 'Forearms'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Full Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['deadlift', 'block_pull'],
      progressions: ['heavy_rack_pull'],
      regressions: ['deadlift', 'kettlebell_deadlift'],
      thumbnail: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Set the safety pins in a power rack so the barbell rests just below or above your knees.',
        'Stand with feet hip-width apart, shins close to the bar.',
        'Hinge at hips, keep your spine flat, and grip the bar with a shoulder-width overhand grip.',
        'Pull your shoulders back and drive your hips forward to lift the bar, locking out your hips at the top.',
        'Squeeze your traps and glutes, then slowly lower the bar back to the safety pins.'
      ],
      commonMistakes: ['Rounding the spine', 'Hyperextending the back at the top', 'Bending knees too much'],
      safetyTips: ['Ensure the rack is stable and secure', 'Keep bar close to thighs throughout lift'],
      breathing: 'Inhale and brace at bottom, exhale at top.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Lower Back', 'Traps', 'Barbell', 'Intermediate', 'Compound', 'Back'],
    ),

    // 29. Rear Delt Cable Fly
    Exercise(
      exerciseId: 'rear_delt_cable_fly',
      name: 'Rear Delt Cable Fly',
      aliases: ['Cable Rear Delt Fly', 'Standing Rear Delt Cable Fly'],
      muscleGroup: 'Back',
      targetRegions: ['Rear Delts', 'Upper Back'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Isolation', 'Cable'],
      equipment: ['Cable'],
      difficulty: 'Beginner',
      movementPattern: 'Horizontal Row',
      goalTags: ['Muscle Gain', 'Posture', 'Shoulder Stability'],
      isCompound: false,
      primaryMuscles: ['Rear Delts'],
      secondaryMuscles: ['Upper Back', 'Rhomboids', 'Traps'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['dumbbell_rear_delt_fly', 'reverse_pec_deck'],
      progressions: ['heavy_cable_rear_delt_fly'],
      regressions: ['resistance_band_pull_apart'],
      thumbnail: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Set dual cable pulleys to chest/shoulder height (without handles, or use standard handles).',
        'Cross your arms to grip the left cable with your right hand, and the right cable with your left hand.',
        'Step back to create tension, standing tall with soft knees.',
        'Pull your hands backward in an arc to your sides, keeping a slight bend in your elbows.',
        'Squeeze your rear delts and shoulder blades at the top.',
        'Slowly return to the start.'
      ],
      commonMistakes: ['Bending elbows too much (turning it into a row)', 'Using too much weight', 'Shrugging shoulders'],
      safetyTips: ['Keep shoulders depressed', 'Perform the movement under control'],
      breathing: 'Exhale pulling back, inhale returning.',
      estimatedCaloriesPerMinute: 4.2,
      tags: ['Rear Delts', 'Upper Back', 'Cable', 'Beginner', 'Isolation', 'Back'],
    ),

    // 30. Resistance Band Pull Apart
    Exercise(
      exerciseId: 'resistance_band_pull_apart',
      name: 'Resistance Band Pull Apart',
      aliases: ['Band Pull Apart', 'Band Pull-Apart'],
      muscleGroup: 'Back',
      targetRegions: ['Rear Delts', 'Upper Back', 'Rhomboids'],
      exerciseType: 'Warm-up',
      trainingStyles: ['General Fitness', 'Rehabilitation', 'Bodybuilding'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Resistance Band'],
      difficulty: 'Beginner',
      movementPattern: 'Horizontal Row',
      goalTags: ['Posture', 'Shoulder Health', 'Warm-Up'],
      isCompound: false,
      primaryMuscles: ['Rear Delts', 'Upper Back'],
      secondaryMuscles: ['Rhomboids', 'Traps'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Shoulder Friendly', 'Lower Back Friendly'],
      alternatives: ['face_pull', 'dumbbell_rear_delt_fly'],
      progressions: ['double_band_pull_apart'],
      regressions: ['single_band_pull_apart_light'],
      thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand tall holding a resistance band in front of your chest with hands shoulder-width apart, palms down.',
        'Keep a very slight bend in your elbows.',
        'Squeeze your shoulder blades together and pull the band apart by moving your arms out to the sides.',
        'Touch the band to your chest at the end of the movement.',
        'Slowly return to the starting position.'
      ],
      commonMistakes: ['Shrugging shoulders', 'Using momentum', 'Arching lower back'],
      safetyTips: ['Use a band with appropriate resistance to maintain form', 'Keep neck relaxed'],
      breathing: 'Exhale pulling apart, inhale returning.',
      estimatedCaloriesPerMinute: 3.5,
      tags: ['Rear Delts', 'Upper Back', 'Rhomboids', 'Resistance Band', 'Beginner', 'Isolation', 'Back'],
    ),

    // 31. Reverse Grip Lat Pulldown
    Exercise(
      exerciseId: 'reverse_grip_lat_pulldown',
      name: 'Reverse Grip Lat Pulldown',
      aliases: ['Underhand Lat Pulldown', 'Reverse Grip Pulldown'],
      muscleGroup: 'Back',
      targetRegions: ['Lats', 'Lower Traps'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Compound', 'Machine'],
      equipment: ['Lat Pulldown Machine', 'Straight Bar'],
      difficulty: 'Beginner',
      movementPattern: 'Vertical Pull',
      goalTags: ['Muscle Gain', 'Bicep Development'],
      isCompound: true,
      primaryMuscles: ['Lats', 'Biceps'],
      secondaryMuscles: ['Rhomboids', 'Lower Traps', 'Upper Back'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['lat_pulldown', 'chin_up'],
      progressions: ['heavy_reverse_grip_pulldown'],
      regressions: ['assisted_pull_up', 'straight_arm_pulldown'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Grip the lat pulldown bar with an underhand (supinated) grip, shoulder-width apart.',
        'Sit down, securing your thighs under the pads.',
        'Keep your chest up and shoulders back.',
        'Pull the bar down to your upper chest, focusing on pulling through your elbows.',
        'Slowly return the bar to the top under control.'
      ],
      commonMistakes: ['Leaning back too far', 'Pulling the bar down too low (past chest)', 'Shrugging shoulders'],
      safetyTips: ['Keep the movement strict and controlled', 'Drive elbows straight down'],
      breathing: 'Exhale pulling down, inhale returning up.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Lats', 'Lower Traps', 'Machine', 'Beginner', 'Compound', 'Back'],
    ),

    // 32. Reverse Pec Deck
    Exercise(
      exerciseId: 'reverse_pec_deck',
      name: 'Reverse Pec Deck',
      aliases: ['Machine Rear Delt Fly', 'Rear Delt Pec Deck'],
      muscleGroup: 'Back',
      targetRegions: ['Rear Delts', 'Upper Back'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Machine'],
      equipment: ['Pec Deck Machine'],
      difficulty: 'Beginner',
      movementPattern: 'Horizontal Row',
      goalTags: ['Muscle Gain', 'Shoulder Stability', 'Posture'],
      isCompound: false,
      primaryMuscles: ['Rear Delts'],
      secondaryMuscles: ['Rhomboids', 'Upper Traps', 'Upper Back'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['dumbbell_rear_delt_fly', 'rear_delt_cable_fly'],
      progressions: ['heavy_reverse_pec_deck'],
      regressions: ['resistance_band_pull_apart'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit facing the chest press/fly machine, adjusting seat height so the handles are at shoulder level.',
        'Grip the handles with your hands, keeping a slight bend in your elbows.',
        'Push the handles backward in an arc, squeezing your rear delts and shoulder blades at the top.',
        'Slowly return the handles to starting position.'
      ],
      commonMistakes: ['Shrugging shoulders', 'Using body momentum', 'Bending elbows too much'],
      safetyTips: ['Adjust seat correctly to avoid shoulder impingement', 'Keep chest firmly against pad'],
      breathing: 'Exhale pushing back, inhale returning.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Rear Delts', 'Upper Back', 'Machine', 'Beginner', 'Isolation', 'Back'],
    ),

    // 33. Romanian Deadlift
    Exercise(
      exerciseId: 'romanian_deadlift',
      name: 'Romanian Deadlift',
      aliases: ['RDL', 'Barbell Romanian Deadlift'],
      muscleGroup: 'Back',
      targetRegions: ['Lower Back', 'Hamstrings', 'Glutes'],
      exerciseType: 'Strength',
      trainingStyles: ['Powerlifting', 'Strength Training', 'Bodybuilding', 'General Fitness'],
      categories: ['Compound', 'Barbell'],
      equipment: ['Barbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Hinge',
      goalTags: ['Posterior Chain Strength', 'Muscle Gain', 'Hamstring Flexibility'],
      isCompound: true,
      primaryMuscles: ['Hamstrings', 'Glutes'],
      secondaryMuscles: ['Lower Back', 'Core', 'Forearms'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Full Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['deadlift', 'good_morning', 'dumbbell_romanian_deadlift'],
      progressions: ['heavy_romanian_deadlift'],
      regressions: ['kettlebell_deadlift', 'back_extension'],
      thumbnail: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding a barbell at your thighs with an overhand grip, feet hip-width apart.',
        'Pull shoulders back, chest up, and bend knees very slightly.',
        'Hinge at hips, pushing them backward, and lower the bar slowly along your thighs/shins.',
        'Maintain a completely flat back, lowering until you feel a deep stretch in your hamstrings.',
        'Drive hips forward to return to standing, squeezing glutes at top.'
      ],
      commonMistakes: ['Rounding the spine', 'Lowering the bar too far (bending knees too much)', 'Holding the bar away from thighs'],
      safetyTips: ['Keep the bar in contact with your legs throughout the lift', 'Keep your spine flat and neck neutral'],
      breathing: 'Inhale lowering, exhale standing up.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Lower Back', 'Hamstrings', 'Glutes', 'Barbell', 'Intermediate', 'Compound', 'Back'],
    ),

    // 34. Scapular Pull-Up
    Exercise(
      exerciseId: 'scapular_pull_up',
      name: 'Scapular Pull-Up',
      aliases: ['Scapula Pullup', 'Active Hang Lifts'],
      muscleGroup: 'Back',
      targetRegions: ['Lower Traps', 'Rhomboids', 'Lats'],
      exerciseType: 'Warm-up',
      trainingStyles: ['Calisthenics', 'General Fitness', 'Rehabilitation'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Pull-up Bar'],
      difficulty: 'Beginner',
      movementPattern: 'Vertical Pull',
      goalTags: ['Shoulder Stability', 'Grip Strength', 'Pull-Up Strength'],
      isCompound: false,
      primaryMuscles: ['Rhomboids', 'Lower Traps'],
      secondaryMuscles: ['Lats', 'Forearms'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['passive_hang', 'assisted_pull_up'],
      progressions: ['pull_up', 'negative_pull_up'],
      regressions: ['assisted_scapular_pull_up'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-a6f9d1f6b1b8?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Hang from a pull-up bar with an overhand grip, shoulder-width apart (passive hang).',
        'Without bending your elbows, pull your shoulder blades down and together, lifting your body slightly.',
        'Hold the active position for 1-2 seconds.',
        'Slowly release the scapular contraction back to a passive hang.'
      ],
      commonMistakes: ['Bending elbows (using biceps)', 'Swinging body', 'Holding breath'],
      safetyTips: ['Perform the movement slowly and intentionally', 'Focus purely on scapular movement'],
      breathing: 'Exhale contracting, inhale releasing.',
      estimatedCaloriesPerMinute: 4.0,
      tags: ['Lower Traps', 'Rhomboids', 'Bodyweight', 'Beginner', 'Isolation', 'Back'],
    ),

    // 35. Seated Cable Row
    Exercise(
      exerciseId: 'seated_cable_row',
      name: 'Seated Cable Row',
      aliases: ['Cable Row', 'Seated Row'],
      muscleGroup: 'Back',
      targetRegions: ['Mid Back', 'Lats', 'Upper Back'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'General Fitness', 'Strength Training'],
      categories: ['Compound', 'Cable'],
      equipment: ['Cable', 'Straight Bar or V-Bar'],
      difficulty: 'Beginner',
      movementPattern: 'Horizontal Row',
      goalTags: ['Muscle Gain', 'Strength', 'Posture'],
      isCompound: true,
      primaryMuscles: ['Lats', 'Upper Back'],
      secondaryMuscles: ['Biceps', 'Rhomboids', 'Rear Delts'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['machine_row', 'chest_supported_row'],
      progressions: ['heavy_seated_cable_row', 'bent_over_barbell_row'],
      regressions: ['trx_row', 'machine_row'],
      thumbnail: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit at a cable row station, place feet on plates, knees slightly bent.',
        'Grip the bar/handles, sit up tall with spine straight.',
        'Pull the handle to your abdomen, driving elbows backward.',
        'Squeeze your back at the top, then slowly extend your arms back to the start.'
      ],
      commonMistakes: ['Swinging torso excessively', 'Rounding back', 'Shrugging shoulders'],
      safetyTips: ['Keep spine vertical and neutral', 'Do not lock out knees fully on footrests'],
      breathing: 'Exhale rowing, inhale returning.',
      estimatedCaloriesPerMinute: 6.5,
      tags: ['Mid Back', 'Lats', 'Cable', 'Beginner', 'Compound', 'Back'],
    ),

    // 36. Single Arm Cable Row
    Exercise(
      exerciseId: 'single_arm_cable_row',
      name: 'Single Arm Cable Row',
      aliases: ['One Arm Cable Row', 'Seated One Arm Cable Row'],
      muscleGroup: 'Back',
      targetRegions: ['Lats', 'Mid Back'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'General Fitness', 'Functional Fitness'],
      categories: ['Compound', 'Cable'],
      equipment: ['Cable', 'Single D-Handle'],
      difficulty: 'Beginner',
      movementPattern: 'Horizontal Row',
      goalTags: ['Muscle Balance', 'Muscle Gain', 'Core Stability'],
      isCompound: true,
      primaryMuscles: ['Lats'],
      secondaryMuscles: ['Biceps', 'Upper Back', 'Core', 'Rear Delts'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['single_arm_dumbbell_row', 'seated_cable_row'],
      progressions: ['heavy_single_arm_cable_row'],
      regressions: ['two_arm_seated_cable_row'],
      thumbnail: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Attach a single D-handle to a seated cable row station.',
        'Sit tall with your spine straight, knees soft, gripping the handle in one hand.',
        'Pull the handle back to your hip, driving your elbow behind you while resisting rotation in your torso.',
        'Squeeze your lat at the top, then slowly extend your arm back to full stretch.'
      ],
      commonMistakes: ['Twisting the torso to pull the weight', 'Shrugging the shoulder', 'Moving too quickly'],
      safetyTips: ['Maintain core stability to prevent rotation', 'Keep spine straight'],
      breathing: 'Exhale pulling, inhale extending.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Lats', 'Mid Back', 'Cable', 'Beginner', 'Compound', 'Back'],
    ),

    // 37. Single Arm Dumbbell Row
    Exercise(
      exerciseId: 'single_arm_dumbbell_row',
      name: 'Single Arm Dumbbell Row',
      aliases: ['One Arm Dumbbell Row', 'Dumbbell Row on Bench'],
      muscleGroup: 'Back',
      targetRegions: ['Lats', 'Mid Back', 'Upper Back'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Strength Training', 'General Fitness'],
      categories: ['Compound', 'Dumbbell'],
      equipment: ['Bench', 'Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Horizontal Row',
      goalTags: ['Muscle Gain', 'Strength', 'Muscle Balance'],
      isCompound: true,
      primaryMuscles: ['Lats', 'Upper Back'],
      secondaryMuscles: ['Biceps', 'Rhomboids', 'Rear Delts', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['dumbbell_row', 'seated_cable_row'],
      progressions: ['heavy_single_arm_dumbbell_row', 'meadows_row'],
      regressions: ['chest_supported_row', 'machine_row'],
      thumbnail: 'https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Place your right knee and right hand flat on a flat bench.',
        'Keep your torso parallel to the floor, left foot flat on the floor, spine straight.',
        'Hold a dumbbell in your left hand with an extended arm.',
        'Pull the dumbbell up to your hip/ribs, keeping your elbow tucked close to your side.',
        'Slowly lower the dumbbell back to full stretch.'
      ],
      commonMistakes: ['Rounding the back', 'Twisting the torso at the top', 'Pulling weight to chest instead of hip'],
      safetyTips: ['Keep your spine neutral and flat', 'Brace your core to prevent twisting'],
      breathing: 'Exhale rowing up, inhale lowering.',
      estimatedCaloriesPerMinute: 7.0,
      tags: ['Lats', 'Mid Back', 'Upper Back', 'Dumbbell', 'Beginner', 'Compound', 'Back'],
    ),

    // 38. Snatch Grip Deadlift
    Exercise(
      exerciseId: 'snatch_grip_deadlift',
      name: 'Snatch Grip Deadlift',
      aliases: ['Wide Grip Deadlift'],
      muscleGroup: 'Back',
      targetRegions: ['Lower Back', 'Upper Back', 'Traps', 'Glutes', 'Hamstrings'],
      exerciseType: 'Strength',
      trainingStyles: ['Weightlifting', 'Powerlifting', 'Strength Training'],
      categories: ['Compound', 'Barbell'],
      equipment: ['Barbell'],
      difficulty: 'Advanced',
      movementPattern: 'Hinge',
      goalTags: ['Upper Back Thickness', 'Pulling Power', 'Posterior Chain Strength'],
      isCompound: true,
      primaryMuscles: ['Lower Back', 'Glutes', 'Traps'],
      secondaryMuscles: ['Hamstrings', 'Upper Back', 'Forearms', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Full Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['deadlift', 'deficit_deadlift'],
      progressions: ['heavy_snatch_grip_deadlift'],
      regressions: ['deadlift', 'kettlebell_deadlift'],
      thumbnail: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand with feet hip-width apart, barbell over mid-foot.',
        'Hinge down and grip the bar with a very wide (snatch) grip (typically 1.5 times wider than standard deadlift).',
        'Flatten your back, lower your hips slightly more than a conventional deadlift, and pack your shoulders.',
        'Drive through your heels to stand up, keeping the bar close to your body.',
        'Lock out your hips and squeeze your traps and glutes.',
        'Lower the bar slowly under control.'
      ],
      commonMistakes: ['Rounding the spine due to wide grip demands', 'Allowing hips to shoot up first', 'Grip slipping'],
      safetyTips: ['Ensure back stays completely flat', 'Consider using lifting straps if grip is a limiting factor'],
      breathing: 'Inhale/brace at bottom, exhale at top.',
      estimatedCaloriesPerMinute: 9.8,
      tags: ['Lower Back', 'Upper Back', 'Traps', 'Barbell', 'Advanced', 'Compound', 'Back'],
    ),

    // 39. Straight Arm Dumbbell Pullover
    Exercise(
      exerciseId: 'straight_arm_dumbbell_pullover',
      name: 'Straight Arm Dumbbell Pullover',
      aliases: ['Dumbbell Pullover', 'Dumbbell Lat Pullover'],
      muscleGroup: 'Back',
      targetRegions: ['Lats', 'Serratus Anterior'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Dumbbell'],
      equipment: ['Bench', 'Dumbbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Vertical Pull',
      goalTags: ['Muscle Gain', 'Lat Expansion', 'Chest Expansion'],
      isCompound: false,
      primaryMuscles: ['Lats'],
      secondaryMuscles: ['Chest', 'Triceps', 'Serratus Anterior'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['cable_pullover', 'machine_pullover'],
      progressions: ['heavy_dumbbell_pullover'],
      regressions: ['resistance_band_pullover'],
      thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Lie flat on a bench, holding a dumbbell with both hands in a diamond grip above your chest (arms extended).',
        'Keep a very slight bend in your elbows.',
        'Slowly lower the dumbbell backward in an arc behind your head until your arms are in line with your torso.',
        'Feel the stretch in your lats and chest.',
        'Contract your lats to pull the dumbbell back over your chest in the same arc.'
      ],
      commonMistakes: ['Bending elbows too much (turning it into a tricep extension)', 'Arching the lower back off the bench', 'Lowering weight too far'],
      safetyTips: ['Keep your feet planted flat on the floor', 'Hold the dumbbell securely'],
      breathing: 'Inhale lowering the weight, exhale pulling it up.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Lats', 'Serratus Anterior', 'Dumbbell', 'Intermediate', 'Isolation', 'Back'],
    ),

    // 40. Straight Arm Pulndown
    Exercise(
      exerciseId: 'straight_arm_pulldown',
      name: 'Straight Arm Pulldown',
      aliases: ['Standing Lat Pushdown', 'Straight Arm Lat Pulldown'],
      muscleGroup: 'Back',
      targetRegions: ['Lats'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Cable'],
      equipment: ['Cable', 'Straight Bar'],
      difficulty: 'Beginner',
      movementPattern: 'Vertical Pull',
      goalTags: ['Muscle Gain', 'Lat Isolation'],
      isCompound: false,
      primaryMuscles: ['Lats'],
      secondaryMuscles: ['Triceps', 'Rear Delts', 'Core'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['cable_pullover', 'machine_pullover'],
      progressions: ['heavy_straight_arm_pulldown'],
      regressions: ['resistance_band_lat_pulldown'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Grip a straight bar attached to a high pulley cable station.',
        'Step back, keeping torso upright or slightly bent forward, spine neutral.',
        'Keep arms fully extended, pull the bar down in a wide arc until it touches your thighs.',
        'Squeeze your lats, then slowly return to overhead stretch.'
      ],
      commonMistakes: ['Bending the elbows', 'Rounding upper back', 'Using body swing'],
      safetyTips: ['Do not use too much weight that breaks form', 'Keep core braced'],
      breathing: 'Exhale pulling down, inhale returning.',
      estimatedCaloriesPerMinute: 5.2,
      tags: ['Lats', 'Cable', 'Beginner', 'Isolation', 'Back'],
    ),

    // 41. Superman
    Exercise(
      exerciseId: 'superman',
      name: 'Superman',
      aliases: ['Prone Arch', 'Superman Hold'],
      muscleGroup: 'Back',
      targetRegions: ['Lower Back', 'Glutes', 'Erector Spinae'],
      exerciseType: 'Warm-up',
      trainingStyles: ['General Fitness', 'Calisthenics', 'Rehabilitation'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Hinge',
      goalTags: ['Posture', 'Core Strength', 'Lower Back Strength'],
      isCompound: false,
      primaryMuscles: ['Lower Back'],
      secondaryMuscles: ['Glutes', 'Hamstrings', 'Shoulders'],
      mechanics: 'Isolation',
      forceType: 'Isometric',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Office', 'Travel'],
      injuryFriendly: ['Lower Back Friendly', 'Knee Friendly'],
      alternatives: ['bird_dog', 'back_extension'],
      progressions: ['superman_rocks', 'aquaman_alternating'],
      regressions: ['single_leg_lifts', 'bird_dog'],
      thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Lie face down on a mat with arms extended straight overhead and legs straight.',
        'Brace your core and squeeze your glutes.',
        'Slowly lift your arms, chest, and legs off the floor simultaneously.',
        'Hold the contracted position for 2 seconds, looking down at the mat.',
        'Slowly lower back to starting flat position.'
      ],
      commonMistakes: ['Craning the neck (looking up)', 'Arching too aggressively', 'Holding breath'],
      safetyTips: ['Avoid jerking or lifting too high; look down to keep neck aligned', 'Squeeze glutes to stabilize pelvis'],
      breathing: 'Exhale lifting, inhale lowering.',
      estimatedCaloriesPerMinute: 3.5,
      tags: ['Lower Back', 'Glutes', 'Bodyweight', 'Beginner', 'Isolation', 'Back'],
    ),

    // 42. T-Bar Row
    Exercise(
      exerciseId: 't_bar_row',
      name: 'T-Bar Row',
      aliases: ['T Bar Row', 'Barbell T-Bar Row'],
      muscleGroup: 'Back',
      targetRegions: ['Mid Back', 'Upper Back', 'Lats'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Strength Training', 'Powerlifting'],
      categories: ['Compound', 'Barbell'],
      equipment: ['Barbell', 'T-Bar Row Machine', 'Landmine Attachment'],
      difficulty: 'Intermediate',
      movementPattern: 'Horizontal Row',
      goalTags: ['Muscle Gain', 'Strength', 'Back Thickness'],
      isCompound: true,
      primaryMuscles: ['Lats', 'Upper Back'],
      secondaryMuscles: ['Biceps', 'Rhomboids', 'Rear Delts', 'Lower Back'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['bent_over_barbell_row', 'chest_supported_row'],
      progressions: ['heavy_t_bar_row'],
      regressions: ['chest_supported_row', 'seated_cable_row'],
      thumbnail: 'https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand straddling a T-bar row machine, placing feet flat on platforms.',
        'Hinge at hips, bend knees slightly, keeping your spine flat.',
        'Grip the handles with an overhand or neutral grip.',
        'Pull the bar weight to your chest, driving elbows back.',
        'Slowly lower the weight back to full extension.'
      ],
      commonMistakes: ['Rounding the spine', 'Standing up too straight to lift the weight', 'Shrugging shoulders at the top'],
      safetyTips: ['Keep your spine flat; do not round your back', 'Engage core deeply to protect the lower back'],
      breathing: 'Exhale pulling up, inhale extending down.',
      estimatedCaloriesPerMinute: 7.2,
      tags: ['Mid Back', 'Upper Back', 'Lats', 'Barbell', 'Intermediate', 'Compound', 'Back'],
    ),

    // 43. Trap Bar Deadlift
    Exercise(
      exerciseId: 'trap_bar_deadlift',
      name: 'Trap Bar Deadlift',
      aliases: ['Hex Bar Deadlift'],
      muscleGroup: 'Back',
      targetRegions: ['Lower Back', 'Glutes', 'Quads', 'Hamstrings'],
      exerciseType: 'Strength',
      trainingStyles: ['Strength Training', 'General Fitness', 'Powerlifting', 'Sports Conditioning'],
      categories: ['Compound', 'Barbell'],
      equipment: ['Trap Bar'],
      difficulty: 'Beginner',
      movementPattern: 'Hinge',
      goalTags: ['Strength', 'Full Body Strength', 'Leg Power'],
      isCompound: true,
      primaryMuscles: ['Glutes', 'Quadriceps', 'Lower Back'],
      secondaryMuscles: ['Hamstrings', 'Traps', 'Forearms', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Full Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['deadlift', 'kettlebell_deadlift'],
      progressions: ['heavy_trap_bar_deadlift'],
      regressions: ['kettlebell_deadlift', 'glute_bridge'],
      thumbnail: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand inside the trap bar with feet shoulder-width apart.',
        'Hinge at your hips and bend your knees to grip the handles at your sides.',
        'Flatten your back, lower your hips, and pull your shoulder blades down and back.',
        'Drive through your heels to stand up, extending your hips and knees fully.',
        'Squeeze your glutes at the top.',
        'Lower the bar back to the floor by hinging and bending knees under control.'
      ],
      commonMistakes: ['Knees caving inward', 'Rounding the spine', 'Starting with hips too high or low'],
      safetyTips: ['Keep back flat throughout the lift', 'Brace core deeply'],
      breathing: 'Inhale down, exhale standing up.',
      estimatedCaloriesPerMinute: 9.0,
      tags: ['Lower Back', 'Glutes', 'Quads', 'Barbell', 'Beginner', 'Compound', 'Back'],
    ),

    // 44. TRX Row
    Exercise(
      exerciseId: 'trx_row',
      name: 'TRX Row',
      aliases: ['Suspension Trainer Row', 'TRX Suspension Row'],
      muscleGroup: 'Back',
      targetRegions: ['Mid Back', 'Upper Back', 'Lats'],
      exerciseType: 'Strength',
      trainingStyles: ['Functional Fitness', 'General Fitness', 'Calisthenics'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Suspension Trainer (TRX)'],
      difficulty: 'Beginner',
      movementPattern: 'Horizontal Row',
      goalTags: ['Core Stability', 'Strength', 'Posture'],
      isCompound: true,
      primaryMuscles: ['Upper Back', 'Lats'],
      secondaryMuscles: ['Biceps', 'Core', 'Rear Delts'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Lower Back Friendly', 'Shoulder Friendly'],
      alternatives: ['inverted_row', 'seated_cable_row'],
      progressions: ['one_leg_trx_row', 'weighted_trx_row'],
      regressions: ['trx_row_high_angle'],
      thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Grab the TRX handles and lean back, walking your feet forward until your body is at an angle.',
        'Keep your body in a rigid straight line (plank position) with arms extended.',
        'Pull your chest up to the handles by driving your elbows backward and squeezing your back.',
        'Slowly lower yourself back to standard extension under control.'
      ],
      commonMistakes: ['Hips sagging', 'Not completing full range of motion', 'Leading with the chin/neck'],
      safetyTips: ['Maintain a solid core brace and glute contraction', 'Ensure anchor point is highly secure'],
      breathing: 'Exhale pulling up, inhale lowering.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Mid Back', 'Upper Back', 'Lats', 'Suspension Trainer (TRX)', 'Beginner', 'Compound', 'Back'],
    ),

    // 45. Wide Grip Pull-Up
    Exercise(
      exerciseId: 'wide_grip_pull_up',
      name: 'Wide Grip Pull-Up',
      aliases: ['Wide Grip Pullup', 'Wide Pullup'],
      muscleGroup: 'Back',
      targetRegions: ['Lats', 'Upper Back'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Strength Training', 'Bodybuilding'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Pull-up Bar'],
      difficulty: 'Advanced',
      movementPattern: 'Vertical Pull',
      goalTags: ['Strength', 'Back Width', 'Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Lats'],
      secondaryMuscles: ['Biceps', 'Rhomboids', 'Upper Traps', 'Upper Back'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['pull_up', 'lat_pulldown'],
      progressions: ['weighted_wide_grip_pull_up'],
      regressions: ['assisted_pull_up', 'negative_pull_up'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-a6f9d1f6b1b8?w=400&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Grip the pull-up bar with an overhand grip, significantly wider than shoulder-width.',
        'Hang with fully extended arms, shoulders pulled down.',
        'Pull your body upward, driving your elbows down and back.',
        'Continue until your chin clears the bar, squeezing your shoulder blades together.',
        'Slowly lower yourself back to full extension under control.'
      ],
      commonMistakes: ['Using momentum (swinging)', 'Short range of motion', 'Shrugging shoulders'],
      safetyTips: ['Avoid wide grip pull-ups if you have active shoulder impingement/injury', 'Control the eccentric phase'],
      breathing: 'Exhale pulling up, inhale lowering down.',
      estimatedCaloriesPerMinute: 7.8,
      tags: ['Lats', 'Upper Back', 'Bodyweight', 'Advanced', 'Compound', 'Back'],
    ),
  ];
}
