import '../../models/models.dart';

class BicepsExercises {
  static final List<Exercise> exercises = [
    // 1. Alternating Dumbbell Curl
    Exercise(
      exerciseId: 'alternating_dumbbell_curl',
      name: 'Alternating Dumbbell Curl',
      aliases: ['Dumbbell Alternating Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head', 'Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Dumbbell'],
      equipment: ['Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: ['Lower Back Safe'],
      alternatives: ['standing_dumbbell_curl', 'barbell_curl'],
      progressions: ['incline_dumbbell_curl'],
      regressions: ['resistance_band_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand tall with dumbbells in hands, palms facing forward.',
        'Curl one dumbbell up toward your shoulder while keeping your elbow tucked at your side.',
        'Squeeze your bicep at the top, then slowly lower the dumbbell back to full extension.',
        'Repeat on the opposite arm, alternating back and forth.'
      ],
      commonMistakes: ['Swinging torso', 'Elbow drifting forward', 'Incomplete range of motion'],
      safetyTips: ['Keep your spine straight and core braced'],
      breathing: 'Exhale curling up, inhale lowering down.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Short Head', 'Long Head', 'Dumbbell', 'Beginner', 'Isolation', 'Bodybuilding', 'Pull', 'Upper Body', 'Biceps'],
    ),

    // 2. Barbell Curl
    Exercise(
      exerciseId: 'barbell_curl',
      name: 'Barbell Curl',
      aliases: ['Barbell Bicep Curl', 'EZ Bar Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head', 'Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Bodybuilding', 'General Fitness', 'Isolation'],
      equipment: ['Barbell'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Safe'],
      alternatives: ['hammer_curl', 'standing_dumbbell_curl'],
      progressions: ['heavy_barbell_curl'],
      regressions: ['resistance_band_curl', 'cable_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand tall holding a barbell with underhand grip, shoulder-width apart.',
        'Keep elbows tucked close to your ribs.',
        'Curl the bar up toward your shoulders, squeezing the biceps at the top.',
        'Lower the bar slowly back to full extension.'
      ],
      commonMistakes: ['Swinging body to lift bar', 'Not completing full stretch at bottom', 'Elbows moving forward'],
      safetyTips: ['Keep wrists aligned and straight', 'Stand firmly with braced core'],
      breathing: 'Exhale curling up, inhale extending down.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Short Head', 'Long Head', 'Barbell', 'Beginner', 'Isolation', 'Bodybuilding', 'Pull', 'Upper Body', 'Biceps'],
    ),

    // 3. Bayesian Curl
    Exercise(
      exerciseId: 'bayesian_curl',
      name: 'Bayesian Curl',
      aliases: ['Cable Bayesian Curl', 'Face Away Cable Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Isolation', 'Cable'],
      equipment: ['Cable'],
      difficulty: 'Intermediate',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['behind_the_back_cable_curl', 'incline_dumbbell_curl'],
      progressions: ['heavy_bayesian_curl'],
      regressions: ['cable_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Attach a D-handle to a low pulley cable station.',
        'Hold the handle in your hand, step forward facing away from the stack, allowing your arm to extend behind your body.',
        'Curl the handle forward and upward while keeping your shoulder slightly extended to load the long head.',
        'Squeeze at the top, then slowly return to the starting stretched position.'
      ],
      commonMistakes: ['Using shoulder flexion to lift weight', 'Losing core brace'],
      safetyTips: ['Do not overstretch the shoulder joint'],
      breathing: 'Exhale curling up, inhale extending.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Long Head', 'Cable', 'Intermediate', 'Isolation', 'Bodybuilding', 'Biceps'],
    ),

    // 4. Behind The Back Cable Curl
    Exercise(
      exerciseId: 'behind_the_back_cable_curl',
      name: 'Behind The Back Cable Curl',
      aliases: ['Behind Back Cable Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Isolation', 'Cable'],
      equipment: ['Cable'],
      difficulty: 'Intermediate',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['bayesian_curl', 'incline_dumbbell_curl'],
      progressions: ['heavy_behind_back_cable_curl'],
      regressions: ['cable_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Set up a low cable pulley and attach a D-handle.',
        'Grip the handle, face away from the cable machine, and step forward so your arm is drawn slightly behind your torso.',
        'Curl the handle upward, keeping your elbow pinned in place behind your body.',
        'Slowly return to starting stretch.'
      ],
      commonMistakes: ['Elbow shifting forward', 'Leaning torso forward too much'],
      safetyTips: ['Ensure the shoulder joint is comfortable at stretch'],
      breathing: 'Exhale curling up, inhale extending.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Long Head', 'Cable', 'Intermediate', 'Isolation', 'Biceps'],
    ),

    // 5. Cable Curl
    Exercise(
      exerciseId: 'cable_curl',
      name: 'Cable Curl',
      aliases: ['Standing Cable Curl', 'Cable Bicep Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head', 'Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Cable'],
      equipment: ['Cable'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Safe'],
      alternatives: ['barbell_curl', 'standing_dumbbell_curl'],
      progressions: ['heavy_cable_curl'],
      regressions: ['resistance_band_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Attach a straight or EZ-bar to a low pulley cable station.',
        'Grip the bar underhand, stand close to the machine, and keep elbows tucked to ribs.',
        'Curl the bar upward toward shoulders, squeezing biceps at the top.',
        'Slowly lower the bar back to full extension.'
      ],
      commonMistakes: ['Letting elbows drift forward', 'Swinging hips to pull weight'],
      safetyTips: ['Keep core engaged throughout'],
      breathing: 'Exhale curling up, inhale extending.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Short Head', 'Long Head', 'Cable', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 6. Cable Drag Curl
    Exercise(
      exerciseId: 'cable_drag_curl',
      name: 'Cable Drag Curl',
      aliases: ['Cable Bicep Drag Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Isolation', 'Cable'],
      equipment: ['Cable'],
      difficulty: 'Intermediate',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['drag_curl', 'dumbbell_drag_curl'],
      progressions: ['heavy_cable_drag_curl'],
      regressions: ['cable_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Attach a straight bar to a low pulley and stand facing the machine.',
        'As you curl the bar up, pull your elbows backward so the bar "drags" straight up your torso.',
        'Squeeze the biceps at the peak, then slowly lower back down.'
      ],
      commonMistakes: ['Shrugging shoulders', 'Letting elbows move forward'],
      safetyTips: ['Keep shoulders pulled back and down'],
      breathing: 'Exhale curling up, inhale extending.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Long Head', 'Cable', 'Intermediate', 'Isolation', 'Biceps'],
    ),

    // 7. Cable Preacher Curl
    Exercise(
      exerciseId: 'cable_preacher_curl',
      name: 'Cable Preacher Curl',
      aliases: ['Cable Preacher Bench Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Isolation', 'Cable'],
      equipment: ['Cable', 'Preacher Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['preacher_dumbbell_curl', 'machine_preacher_curl'],
      progressions: ['heavy_cable_preacher_curl'],
      regressions: ['cable_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Place a preacher bench in front of a low cable station.',
        'Sit on the bench, resting your upper arms flat against the pad.',
        'Grip the cable attachment (straight bar or EZ bar) underhand.',
        'Curl the bar upward toward your chin, squeezing the biceps.',
        'Slowly lower the bar back to full extension.'
      ],
      commonMistakes: ['Lifting elbows off the pad', 'Not extending arms fully at bottom'],
      safetyTips: ['Adjust preacher bench height correctly for shoulder comfort'],
      breathing: 'Exhale curling up, inhale extending.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Short Head', 'Cable', 'Intermediate', 'Isolation', 'Biceps'],
    ),

    // 8. Cable Reverse Curl
    Exercise(
      exerciseId: 'cable_reverse_curl',
      name: 'Cable Reverse Curl',
      aliases: ['Reverse Grip Cable Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Brachioradialis', 'Brachialis'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Cable'],
      equipment: ['Cable'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain', 'Forearm Strength'],
      isCompound: false,
      primaryMuscles: ['Brachioradialis', 'Brachialis'],
      secondaryMuscles: ['Biceps', 'Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['reverse_barbell_curl', 'reverse_dumbbell_curl'],
      progressions: ['heavy_cable_reverse_curl'],
      regressions: ['resistance_band_reverse_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Attach a straight bar or EZ-bar to a low cable station.',
        'Grip the bar with an overhand (pronated) grip, hands shoulder-width apart.',
        'Keep elbows tucked close to your ribs.',
        'Curl the bar upward, maintaining the overhand grip, then slowly lower back down.'
      ],
      commonMistakes: ['Flaring elbows out', 'Wrist bending or flexing during curl'],
      safetyTips: ['Keep wrists locked and neutral'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Brachioradialis', 'Brachialis', 'Cable', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 9. Cheat Curl
    Exercise(
      exerciseId: 'cheat_curl',
      name: 'Cheat Curl',
      aliases: ['Cheat Barbell Curl', 'Heavy Cheat Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head', 'Long Head'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Strength Training'],
      categories: ['Isolation', 'Barbell'],
      equipment: ['Barbell'],
      difficulty: 'Advanced',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain', 'Overload Strength'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms', 'Lower Back', 'Glutes'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['barbell_curl'],
      progressions: ['heavy_cheat_curl'],
      regressions: ['barbell_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Load a barbell heavier than your standard curl weight.',
        'Use a slight hip hinge and knee bend to initiate momentum (hip drive).',
        'Curl the bar upward using momentum to bypass the sticking point, but control the eccentric (lowering) phase for 3-4 seconds.'
      ],
      commonMistakes: ['Excessive arching of lower back', 'No control on eccentric phase'],
      safetyTips: ['Do not use cheat curls if you have active lower back pain', 'Brace core deeply'],
      breathing: 'Exhale lifting, inhale lowering slowly.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Short Head', 'Long Head', 'Barbell', 'Advanced', 'Isolation', 'Biceps'],
    ),

    // 10. Close Grip Barbell Curl
    Exercise(
      exerciseId: 'close_grip_barbell_curl',
      name: 'Close Grip Barbell Curl',
      aliases: ['Narrow Grip Barbell Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Barbell'],
      equipment: ['Barbell'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['barbell_curl', 'preacher_dumbbell_curl'],
      progressions: ['heavy_close_grip_barbell_curl'],
      regressions: ['cable_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding a barbell with underhand grip, hands closer than shoulder-width.',
        'Keep elbows tucked close to sides.',
        'Curl the bar up toward shoulders, then slowly lower back down.'
      ],
      commonMistakes: ['Flaring elbows out', 'Shoulder shrugging'],
      safetyTips: ['Maintain neutral wrists'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 5.2,
      tags: ['Long Head', 'Barbell', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 11. Concentration Curl
    Exercise(
      exerciseId: 'concentration_curl',
      name: 'Concentration Curl',
      aliases: ['Seated Concentration Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Dumbbell'],
      equipment: ['Dumbbell', 'Bench'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: ['Lower Back Safe'],
      alternatives: ['preacher_dumbbell_curl', 'bayesian_curl'],
      progressions: ['heavy_concentration_curl'],
      regressions: ['cable_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit on a bench, legs spread, and hold a dumbbell in one hand.',
        'Rest your elbow/tricep against the inside of your thigh.',
        'Curl the dumbbell upward toward your face, focusing strictly on bicep contraction.',
        'Slowly lower the dumbbell to starting hang.'
      ],
      commonMistakes: ['Pushing thigh with elbow to create leverage', 'Rounding lower back'],
      safetyTips: ['Keep back straight, avoid twisting'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Short Head', 'Dumbbell', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 12. Cross Body Hammer Curl
    Exercise(
      exerciseId: 'cross_body_hammer_curl',
      name: 'Cross Body Hammer Curl',
      aliases: ['Pinwheel Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Brachialis', 'Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Dumbbell'],
      equipment: ['Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain', 'Forearm Thickness'],
      isCompound: false,
      primaryMuscles: ['Biceps', 'Brachialis'],
      secondaryMuscles: ['Forearms', 'Brachioradialis'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['hammer_curl', 'zottman_curl'],
      progressions: ['heavy_pinwheel_curl'],
      regressions: ['cable_hammer_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding dumbbells with a neutral grip (palms facing each other).',
        'Curl one dumbbell across your body toward your opposite shoulder.',
        'Squeeze the contraction, then slowly lower back down.',
        'Alternate arms.'
      ],
      commonMistakes: ['Swinging torso', 'Wrist flexion'],
      safetyTips: ['Keep shoulders back and stable'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Brachialis', 'Long Head', 'Dumbbell', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 13. Drag Curl
    Exercise(
      exerciseId: 'drag_curl',
      name: 'Drag Curl',
      aliases: ['Barbell Drag Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Isolation', 'Barbell'],
      equipment: ['Barbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['dumbbell_drag_curl', 'cable_drag_curl'],
      progressions: ['heavy_drag_curl'],
      regressions: ['barbell_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding a barbell with underhand grip, hands shoulder-width apart.',
        'Instead of curling the bar in an arc, pull your elbows straight back as you lift the bar up along your torso.',
        'Squeeze the contraction, then slowly lower the bar back down.'
      ],
      commonMistakes: ['Shrugging shoulders (using upper traps)', 'Elbows moving forward'],
      safetyTips: ['Keep shoulders depressed'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Long Head', 'Barbell', 'Intermediate', 'Isolation', 'Biceps'],
    ),

    // 14. Dual Cable Curl
    Exercise(
      exerciseId: 'dual_cable_curl',
      name: 'Dual Cable Curl',
      aliases: ['Two Arm Cable Curl', 'Dual Cable Bicep Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head', 'Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Isolation', 'Cable'],
      equipment: ['Cable'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['cable_curl', 'high_cable_curl'],
      progressions: ['heavy_dual_cable_curl'],
      regressions: ['single_arm_cable_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Set up two low pulleys with D-handles and stand in the middle.',
        'Grip the handles underhand and tuck your elbows to sides.',
        'Curl both handles upward simultaneously, then slowly lower back down.'
      ],
      commonMistakes: ['Swinging torso', 'Asymmetric pulling'],
      safetyTips: ['Keep core braced'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 5.2,
      tags: ['Short Head', 'Long Head', 'Cable', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 15. Dumbbell Drag Curl
    Exercise(
      exerciseId: 'dumbbell_drag_curl',
      name: 'Dumbbell Drag Curl',
      aliases: ['Dumbbell Bicep Drag Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Isolation', 'Dumbbell'],
      equipment: ['Dumbbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['drag_curl', 'cable_drag_curl'],
      progressions: ['heavy_dumbbell_drag_curl'],
      regressions: ['standing_dumbbell_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand tall holding dumbbells with underhand grip.',
        'Pull your elbows backward as you lift the dumbbells straight up along your sides.',
        'Squeeze peak contraction, then slowly lower back down.'
      ],
      commonMistakes: ['Elbows drifting forward', 'Shrugging shoulders'],
      safetyTips: ['Keep neck aligned, avoid forward head posture'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Long Head', 'Dumbbell', 'Intermediate', 'Isolation', 'Biceps'],
    ),

    // 16. EZ Bar Curl
    Exercise(
      exerciseId: 'ez_bar_curl',
      name: 'EZ Bar Curl',
      aliases: ['EZ Bar Bicep Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head', 'Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Barbell'],
      equipment: ['EZ Bar'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Wrist Friendly'],
      alternatives: ['barbell_curl', 'dumbbell_curl'],
      progressions: ['heavy_ez_bar_curl'],
      regressions: ['cable_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding an EZ-bar on the outer knurled angled grips (underhand).',
        'Keep elbows tucked close to your ribs.',
        'Curl the bar upward toward shoulders, squeeze at top, and slowly lower back down.'
      ],
      commonMistakes: ['Swinging torso', 'Incomplete stretch at bottom'],
      safetyTips: ['EZ bar reduces wrist strain compared to straight barbell'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Short Head', 'Long Head', 'EZ Bar', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 17. Fat Grip Curl
    Exercise(
      exerciseId: 'fat_grip_curl',
      name: 'Fat Grip Curl',
      aliases: ['Fat Grip Barbell Curl', 'Thick Bar Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head', 'Long Head', 'Forearms'],
      exerciseType: 'Strength',
      trainingStyles: ['Strength Training', 'Strongman'],
      categories: ['Isolation', 'Barbell'],
      equipment: ['Barbell', 'Fat Grips'],
      difficulty: 'Intermediate',
      movementPattern: 'Curl',
      goalTags: ['Grip Strength', 'Forearm Mass', 'Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps', 'Forearms'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['barbell_curl', 'hammer_curl'],
      progressions: ['heavy_fat_grip_curl'],
      regressions: ['barbell_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Attach thick grip adaptors (Fat Grips) to a barbell or dumbbell.',
        'Grip the thick bar firmly, and curl the weight upward under strict control.',
        'Slowly lower back to start.'
      ],
      commonMistakes: ['Loose grip', 'Wrist extension at top of curl'],
      safetyTips: ['Use lighter weights initially due to increased grip demand'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 5.8,
      tags: ['Short Head', 'Long Head', 'Forearms', 'Fat Grips', 'Intermediate', 'Isolation', 'Biceps'],
    ),

    // 18. Hammer Curl
    Exercise(
      exerciseId: 'hammer_curl',
      name: 'Hammer Curl',
      aliases: ['Dumbbell Hammer Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Brachialis', 'Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Bodybuilding', 'General Fitness', 'Isolation'],
      equipment: ['Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps', 'Brachialis'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: ['Lower Back Safe'],
      alternatives: ['barbell_curl', 'cable_hammer_curls'],
      progressions: ['dumbbell_hammer_curls_heavy'],
      regressions: ['resistance_band_curls', 'cable_curls'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding dumbbells with palms facing each other (neutral grip).',
        'Keep elbows fixed at sides.',
        'Curl the weights upward while maintaining the neutral hand position.',
        'Squeeze at the top and lower under control.'
      ],
      commonMistakes: ['Flaring elbows outward', 'Torso swinging', 'Wrist flexion/extension'],
      safetyTips: ['Keep core engaged', 'Do not drop dumbbells too rapidly'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 5.2,
      tags: ['Brachialis', 'Long Head', 'Dumbbell', 'Beginner', 'Isolation', 'Bodybuilding', 'Pull', 'Upper Body', 'Biceps'],
    ),

    // 19. High Cable Curl
    Exercise(
      exerciseId: 'high_cable_curl',
      name: 'High Cable Curl',
      aliases: ['Crucifix Curl', 'Cable Overhead Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Isolation', 'Cable'],
      equipment: ['Cable'],
      difficulty: 'Intermediate',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain', 'Bicep Peak'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms', 'Shoulders'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['cable_curl', 'preacher_dumbbell_curl'],
      progressions: ['heavy_high_cable_curl'],
      regressions: ['cable_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand between two high pulley cable stations, holding handles underhand (crucifix stance).',
        'Extend arms fully parallel to the floor.',
        'Curl both handles inward toward your ears, keeping your upper arms stationary.',
        'Squeeze peak contraction, then slowly extend arms back.'
      ],
      commonMistakes: ['Elbows dropping down', 'Moving upper arms forward'],
      safetyTips: ['Ensure shoulder joints are comfortable in crucifix alignment'],
      breathing: 'Exhale curling in, inhale extending out.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Short Head', 'Cable', 'Intermediate', 'Isolation', 'Biceps'],
    ),

    // 20. Incline Dumbbell Curl
    Exercise(
      exerciseId: 'incline_dumbbell_curl',
      name: 'Incline Dumbbell Curl',
      aliases: ['Incline Curl', 'Incline Bench Bicep Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Dumbbell'],
      equipment: ['Bench', 'Dumbbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain', 'Bicep Peak'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['bayesian_curl', 'behind_the_back_cable_curl'],
      progressions: ['heavy_incline_dumbbell_curl'],
      regressions: ['seated_dumbbell_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Set an incline bench to 45-60 degrees.',
        'Sit back on the bench, letting dumbbells hang straight down at your sides, palms facing forward.',
        'Curl the weights upward while keeping your elbows stationary and behind your torso.',
        'Squeeze at the top, then slowly lower to full stretch.'
      ],
      commonMistakes: ['Elbows swinging forward', 'Head lifting off bench'],
      safetyTips: ['Do not let the dumbbells drop too fast at full stretch to protect the bicep tendon'],
      breathing: 'Exhale curling up, inhale extending.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Long Head', 'Dumbbell', 'Intermediate', 'Isolation', 'Biceps'],
    ),

    // 21. Machine Biceps Curl
    Exercise(
      exerciseId: 'machine_biceps_curl',
      name: 'Machine Biceps Curl',
      aliases: ['Seated Machine Curl', 'Machine Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head', 'Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Machine'],
      equipment: ['Machine'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Safe'],
      alternatives: ['barbell_curl', 'cable_curl'],
      progressions: ['heavy_machine_curl'],
      regressions: ['assisted_bicep_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Adjust the machine seat so your elbows align with the pivot point of the machine arms.',
        'Sit and grip handles underhand, placing back of arms flat on pad.',
        'Curl handles upward toward shoulders, squeeze at top, and slowly lower back down.'
      ],
      commonMistakes: ['Elbows lifting off the pad', 'Using upper body momentum to pull'],
      safetyTips: ['Do not lock elbows aggressively at full extension'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Short Head', 'Long Head', 'Machine', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 22. Machine Hammer Curl
    Exercise(
      exerciseId: 'machine_hammer_curl',
      name: 'Machine Hammer Curl',
      aliases: ['Hammer Grip Machine Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Brachialis', 'Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Isolation', 'Machine'],
      equipment: ['Machine'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain', 'Forearm Mass'],
      isCompound: false,
      primaryMuscles: ['Biceps', 'Brachialis'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Safe'],
      alternatives: ['hammer_curl', 'rope_hammer_curl'],
      progressions: ['heavy_machine_hammer_curl'],
      regressions: ['cable_hammer_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit at the machine, adjusting seat so elbows align with pivot point.',
        'Grip parallel (neutral) handles.',
        'Curl the handles upward, squeeze brachialis at peak, and slowly lower to full extension.'
      ],
      commonMistakes: ['Elbows lifting off pad', 'Rounding shoulders'],
      safetyTips: ['Keep chest pressed to pad if chest-supported machine'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Brachialis', 'Long Head', 'Machine', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 23. Machine Preacher Curl
    Exercise(
      exerciseId: 'machine_preacher_curl',
      name: 'Machine Preacher Curl',
      aliases: ['Seated Machine Preacher Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Isolation', 'Machine'],
      equipment: ['Machine', 'Preacher Bench'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Wrist Friendly'],
      alternatives: ['preacher_dumbbell_curl', 'cable_preacher_curl'],
      progressions: ['heavy_machine_preacher_curl'],
      regressions: ['cable_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit and place armpits snugly over the preacher pad, aligning elbows with pivot point.',
        'Grip handles underhand and curl upward under control.',
        'Slowly extend arms back down without popping the elbows.'
      ],
      commonMistakes: ['Lifting hips off seat to complete rep', 'Hyperextending elbows at bottom'],
      safetyTips: ['Maintain chest contact with the pad throughout'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Short Head', 'Machine', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 24. Preacher Dumbbell Curl
    Exercise(
      exerciseId: 'preacher_dumbbell_curl',
      name: 'Preacher Dumbbell Curl',
      aliases: ['One Arm Preacher Curl', 'Dumbbell Preacher Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Dumbbell'],
      equipment: ['Preacher Bench', 'Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain', 'Bicep Isolation'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['machine_preacher_curl', 'concentration_curl'],
      progressions: ['heavy_preacher_dumbbell_curl'],
      regressions: ['concentration_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit at a preacher bench and adjust the seat height.',
        'Grip a dumbbell in one hand and rest your arm flat against the pad.',
        'Curl the dumbbell up toward your shoulder, keeping your upper arm flat on the pad.',
        'Slowly lower the dumbbell back to full extension.'
      ],
      commonMistakes: ['Elbow lifting off the pad', 'Not reaching full stretch at the bottom'],
      safetyTips: ['Avoid hyper-extending the elbow at the bottom stretch phase'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Short Head', 'Dumbbell', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 25. Resistance Band Curl
    Exercise(
      exerciseId: 'resistance_band_curl',
      name: 'Resistance Band Curl',
      aliases: ['Band Bicep Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head', 'Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['General Fitness', 'Calisthenics', 'Travel Fitness'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Resistance Band'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain', 'Muscular Endurance'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Joint Friendly'],
      alternatives: ['dumbbell_curl', 'cable_curl'],
      progressions: ['heavier_band_curl'],
      regressions: ['lighter_band_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand on the middle of a resistance loop or tube band.',
        'Hold the handles/ends underhand, elbows tucked to ribs.',
        'Curl upward against the band resistance, squeezing at peak.',
        'Slowly lower back to standard stretch.'
      ],
      commonMistakes: ['Shrugging shoulders', 'Elbows moving backward'],
      safetyTips: ['Ensure band is securely stepped on so it does not snap up'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.2,
      tags: ['Short Head', 'Long Head', 'Resistance Band', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 26. Resistance Band Hammer Curl
    Exercise(
      exerciseId: 'resistance_band_hammer_curl',
      name: 'Resistance Band Hammer Curl',
      aliases: ['Band Hammer Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Brachialis', 'Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['General Fitness', 'Calisthenics', 'Travel Fitness'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Resistance Band'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain', 'Endurance'],
      isCompound: false,
      primaryMuscles: ['Biceps', 'Brachialis'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Joint Friendly'],
      alternatives: ['hammer_curl', 'rope_hammer_curl'],
      progressions: ['heavier_band_hammer_curl'],
      regressions: ['lighter_band_hammer_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand on a resistance band and hold the handles in a neutral grip (palms facing).',
        'Curl upward while maintaining the neutral hand position, then slowly lower.'
      ],
      commonMistakes: ['Wrists collapsing', 'Flaring elbows'],
      safetyTips: ['Check band for tears before using'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.2,
      tags: ['Brachialis', 'Long Head', 'Resistance Band', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 27. Resistance Band Reverse Curl
    Exercise(
      exerciseId: 'resistance_band_reverse_curl',
      name: 'Resistance Band Reverse Curl',
      aliases: ['Band Reverse Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Brachioradialis', 'Brachialis'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['General Fitness', 'Calisthenics', 'Travel Fitness'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Resistance Band'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain', 'Forearm Strength'],
      isCompound: false,
      primaryMuscles: ['Brachioradialis', 'Brachialis'],
      secondaryMuscles: ['Biceps', 'Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Joint Friendly'],
      alternatives: ['reverse_dumbbell_curl', 'cable_reverse_curl'],
      progressions: ['heavier_band_reverse_curl'],
      regressions: ['lighter_band_reverse_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand on a resistance band and grip handles/ends overhand (pronated).',
        'Curl upward maintaining the overhand grip, then slowly lower.'
      ],
      commonMistakes: ['Wrist bending', 'Using shoulder movement'],
      safetyTips: ['Maintain firm, locked wrists'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.0,
      tags: ['Brachioradialis', 'Brachialis', 'Resistance Band', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 28. Reverse Barbell Curl
    Exercise(
      exerciseId: 'reverse_barbell_curl',
      name: 'Reverse Barbell Curl',
      aliases: ['Reverse Grip Barbell Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Brachioradialis', 'Brachialis'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'Strength Training'],
      categories: ['Isolation', 'Barbell'],
      equipment: ['Barbell'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Forearm Growth', 'Grip Strength', 'Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Brachioradialis', 'Brachialis'],
      secondaryMuscles: ['Biceps', 'Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['cable_reverse_curl', 'reverse_dumbbell_curl'],
      progressions: ['heavy_reverse_barbell_curl'],
      regressions: ['resistance_band_reverse_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding a barbell with a shoulder-width overhand (pronated) grip.',
        'Keep elbows tucked close to your sides.',
        'Curl the bar upward toward shoulders, keeping wrists straight and locked.',
        'Slowly lower the bar back to full extension.'
      ],
      commonMistakes: ['Flaring elbows out', 'Letting wrists bend (flex/extend)', 'Using torso swing'],
      safetyTips: ['Keep wrists locked tight and neutral'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 5.2,
      tags: ['Brachioradialis', 'Brachialis', 'Barbell', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 29. Reverse Dumbbell Curl
    Exercise(
      exerciseId: 'reverse_dumbbell_curl',
      name: 'Reverse Dumbbell Curl',
      aliases: ['Reverse Grip Dumbbell Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Brachioradialis', 'Brachialis'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Dumbbell'],
      equipment: ['Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain', 'Forearm Growth'],
      isCompound: false,
      primaryMuscles: ['Brachioradialis', 'Brachialis'],
      secondaryMuscles: ['Biceps', 'Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['reverse_barbell_curl', 'cable_reverse_curl'],
      progressions: ['heavy_reverse_dumbbell_curl'],
      regressions: ['resistance_band_reverse_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding dumbbells with an overhand (pronated) grip.',
        'Keep elbows fixed at sides.',
        'Curl the dumbbells upward, keeping wrists locked straight.',
        'Slowly lower back down.'
      ],
      commonMistakes: ['Wrists curling downward', 'Elbows moving forward'],
      safetyTips: ['Do not use excessively heavy weights to protect wrist tendons'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Brachioradialis', 'Brachialis', 'Dumbbell', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 30. Ring Chin-Up
    Exercise(
      exerciseId: 'ring_chin_up',
      name: 'Ring Chin-Up',
      aliases: ['Gymnastic Ring Chinup'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head', 'Long Head'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Gymnastics'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Gymnastic Rings'],
      difficulty: 'Advanced',
      movementPattern: 'Vertical Pull',
      goalTags: ['Strength', 'Shoulder Stability', 'Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Biceps', 'Lats'],
      secondaryMuscles: ['Forearms', 'Core'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: ['Wrist Friendly', 'Shoulder Friendly'],
      alternatives: ['chin_up', 'towel_chin_up'],
      progressions: ['weighted_ring_chin_up'],
      regressions: ['assisted_pull_up', 'negative_pull_up'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-a6f9d1f6b1b8?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Hang from gymnastic rings with an overhand grip (pronated) or neutral grip.',
        'As you pull yourself upward, rotate the rings so your hands finish in an underhand (supinated) grip at the top.',
        'Pull until chin clears rings, squeeze biceps, and slowly lower back down, rotating rings to starting position.'
      ],
      commonMistakes: ['Swinging', 'Not completing full rotation'],
      safetyTips: ['Gymnastic rings allow natural wrist and shoulder rotation, reducing joint strain'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 7.8,
      tags: ['Short Head', 'Long Head', 'Gymnastic Rings', 'Advanced', 'Compound', 'Biceps'],
    ),

    // 31. Rope Hammer Curl
    Exercise(
      exerciseId: 'rope_hammer_curl',
      name: 'Rope Hammer Curl',
      aliases: ['Cable Rope Hammer Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Brachialis', 'Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Cable'],
      equipment: ['Cable', 'Rope Attachment'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain', 'Forearm Mass'],
      isCompound: false,
      primaryMuscles: ['Biceps', 'Brachialis'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Safe'],
      alternatives: ['hammer_curl', 'machine_hammer_curl'],
      progressions: ['heavy_rope_hammer_curl'],
      regressions: ['cable_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Attach a rope handle to a low cable pulley.',
        'Grip rope ends with neutral grip, stand tall, and tuck elbows to sides.',
        'Curl rope ends upward toward shoulders, separating them slightly at top.',
        'Slowly lower back to full extension.'
      ],
      commonMistakes: ['Elbows drifting forward', 'Torso swinging'],
      safetyTips: ['Keep core braced to protect lower back'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Brachialis', 'Long Head', 'Cable', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 32. Seated Dumbbell Curl
    Exercise(
      exerciseId: 'seated_dumbbell_curl',
      name: 'Seated Dumbbell Curl',
      aliases: ['Seated Bicep Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head', 'Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Dumbbell'],
      equipment: ['Bench', 'Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: ['Lower Back Safe'],
      alternatives: ['standing_dumbbell_curl', 'incline_dumbbell_curl'],
      progressions: ['heavy_seated_dumbbell_curl'],
      regressions: ['cable_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit on a flat or upright bench holding dumbbells at your sides, palms facing forward.',
        'Keep elbows tucked close to your ribs.',
        'Curl weights upward, squeeze at top, and slowly lower back to hang.'
      ],
      commonMistakes: ['Leaning side to side', 'Incomplete extension at bottom'],
      safetyTips: ['Seating prevents lower back swinging'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Short Head', 'Long Head', 'Dumbbell', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 33. Single Arm Cable Curl
    Exercise(
      exerciseId: 'single_arm_cable_curl',
      name: 'Single Arm Cable Curl',
      aliases: ['One Arm Cable Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head', 'Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Isolation', 'Cable'],
      equipment: ['Cable', 'Single D-Handle'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain', 'Muscle Balance'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['cable_curl', 'concentration_curl'],
      progressions: ['heavy_single_arm_cable_curl'],
      regressions: ['cable_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Attach a D-handle to a low pulley cable station.',
        'Hold the handle in one hand underhand, stand facing the pulley, and keep your elbow tucked to ribs.',
        'Curl the handle upward, squeeze at top, and slowly lower back down.'
      ],
      commonMistakes: ['Twisting torso', 'Elbow moving forward'],
      safetyTips: ['Maintain core stability to prevent twisting'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Short Head', 'Long Head', 'Cable', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 34. Spider Curl
    Exercise(
      exerciseId: 'spider_curl',
      name: 'Spider Curl',
      aliases: ['Incline Chest Down Bicep Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Isolation', 'Barbell'],
      equipment: ['Bench', 'EZ Bar', 'Dumbbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain', 'Peak Contraction'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['preacher_dumbbell_curl', 'concentration_curl'],
      progressions: ['heavy_spider_curl'],
      regressions: ['seated_dumbbell_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Set an incline bench to 45 degrees.',
        'Lie chest-down on the bench, letting your arms hang straight down over the top edge holding an EZ-bar or dumbbells (underhand).',
        'Curl the bar upward toward the bench head, keeping your upper arms vertical.',
        'Squeeze bicep at peak contraction, then slowly lower back down.'
      ],
      commonMistakes: ['Swinging arms forward', 'Lifting chest off pad'],
      safetyTips: ['Keep neck relaxed, do not strain neck forward'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Short Head', 'EZ Bar', 'Intermediate', 'Isolation', 'Biceps'],
    ),

    // 35. Standing Dumbbell Curl
    Exercise(
      exerciseId: 'standing_dumbbell_curl',
      name: 'Standing Dumbbell Curl',
      aliases: ['Dumbbell Curl', 'Standing Bicep Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head', 'Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Dumbbell'],
      equipment: ['Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: ['Lower Back Safe'],
      alternatives: ['barbell_curl', 'alternating_dumbbell_curl'],
      progressions: ['heavy_standing_dumbbell_curl'],
      regressions: ['cable_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand tall with dumbbells in hands at your sides, palms facing forward.',
        'Keep elbows tucked close to your ribs.',
        'Curl both dumbbells up toward your shoulders simultaneously, squeezing the biceps.',
        'Slowly lower the dumbbells back to full extension.'
      ],
      commonMistakes: ['Swinging body', 'Flaring elbows out', 'Wrist bending'],
      safetyTips: ['Stand with soft knees and a tight core'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 5.2,
      tags: ['Short Head', 'Long Head', 'Dumbbell', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 36. Towel Chin-Up
    Exercise(
      exerciseId: 'towel_chin_up',
      name: 'Towel Chin-Up',
      aliases: ['Towel Grip Chinup'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head', 'Long Head', 'Forearms'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Strongman'],
      categories: ['Compound', 'Bodyweight'],
      equipment: ['Pull-up Bar', 'Towels'],
      difficulty: 'Advanced',
      movementPattern: 'Vertical Pull',
      goalTags: ['Grip Strength', 'Forearm Strength', 'Strength'],
      isCompound: true,
      primaryMuscles: ['Biceps', 'Forearms', 'Lats'],
      secondaryMuscles: ['Core'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['chin_up', 'ring_chin_up'],
      progressions: ['weighted_towel_chin_up'],
      regressions: ['chin_up', 'assisted_pull_up'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-a6f9d1f6b1b8?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Drape two towels over a pull-up bar, shoulder-width apart.',
        'Grip the towels firmly (neutral or underhand grip).',
        'Hang with fully extended arms, then pull yourself upward until your chin clears your hands.',
        'Slowly lower back to starting hang.'
      ],
      commonMistakes: ['Grip slipping', 'Kicking legs'],
      safetyTips: ['Ensure towels are heavy-duty and secure'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Short Head', 'Long Head', 'Forearms', 'Towels', 'Advanced', 'Compound', 'Biceps'],
    ),

    // 37. Wide Grip Barbell Curl
    Exercise(
      exerciseId: 'wide_grip_barbell_curl',
      name: 'Wide Grip Barbell Curl',
      aliases: ['Wide Grip Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Barbell'],
      equipment: ['Barbell'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['barbell_curl', 'preacher_dumbbell_curl'],
      progressions: ['heavy_wide_grip_barbell_curl'],
      regressions: ['cable_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding a barbell with underhand grip, hands wider than shoulder-width.',
        'Keep elbows tucked close to your sides.',
        'Curl the bar up toward your shoulders, then slowly lower back down.'
      ],
      commonMistakes: ['Elbows flaring too far outward', 'Shrugging shoulders'],
      safetyTips: ['Keep wrists locked neutral'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 5.2,
      tags: ['Short Head', 'Barbell', 'Beginner', 'Isolation', 'Biceps'],
    ),

    // 38. Zottman Curl
    Exercise(
      exerciseId: 'zottman_curl',
      name: 'Zottman Curl',
      aliases: ['Dumbbell Zottman Curl'],
      muscleGroup: 'Biceps',
      targetRegions: ['Short Head', 'Long Head', 'Brachioradialis'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Dumbbell'],
      equipment: ['Dumbbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Curl',
      goalTags: ['Muscle Gain', 'Forearm Growth'],
      isCompound: false,
      primaryMuscles: ['Biceps', 'Brachioradialis'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['dumbbell_curl', 'reverse_dumbbell_curl'],
      progressions: ['heavy_zottman_curl'],
      regressions: ['alternating_dumbbell_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding dumbbells with an underhand grip (palms facing forward).',
        'Curl the dumbbells upward toward shoulders.',
        'At the top of the curl, rotate your wrists so your palms face downward (overhand).',
        'Slowly lower the dumbbells back to full extension using the overhand grip.',
        'At the bottom, rotate palms back to underhand position for next rep.'
      ],
      commonMistakes: ['Rotating wrists too early', 'Using too much weight'],
      safetyTips: ['Control the rotation phase completely'],
      breathing: 'Exhale up, rotate, inhale down.',
      estimatedCaloriesPerMinute: 5.2,
      tags: ['Short Head', 'Long Head', 'Brachioradialis', 'Dumbbell', 'Intermediate', 'Isolation', 'Biceps'],
    ),
  ];
}
