import '../../models/models.dart';

class CardioExercises {
  static final List<Exercise> exercises = [
    // 1. Air Bike
    Exercise(
      exerciseId: 'air_bike',
      name: 'Air Bike',
      aliases: ['Assault Bike', 'Fan Bike'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body'],
      exerciseType: 'HIIT',
      trainingStyles: ['HIIT', 'CrossFit', 'Athletic Performance', 'Conditioning'],
      categories: ['Machine', 'HIIT', 'Conditioning'],
      equipment: ['Air Bike'],
      difficulty: 'Advanced',
      movementPattern: 'Full Body Pull/Push',
      goalTags: ['Conditioning', 'Fat Loss', 'Explosive Power'],
      isCompound: true,
      primaryMuscles: ['Full Body'],
      secondaryMuscles: ['Quads', 'Shoulders', 'Glutes', 'Lats'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Full Body',
      environment: ['Gym'],
      injuryFriendly: ['Knee Friendly'],
      alternatives: ['stationary_bike', 'rowing_machine'],
      progressions: ['heavy_air_bike_intervals'],
      regressions: ['stationary_bike'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit on the bike and adjust the seat height so your knees have a slight bend at the bottom of the pedal stroke.',
        'Grip the handles firmly and place your feet on the pedals.',
        'Push and pull the handles with your arms while pedaling with your legs.',
        'Maintain a tall posture and push the pace to create wind resistance from the fan.'
      ],
      commonMistakes: ['Slouching over the handlebars', 'Using only legs or only arms', 'Flaring knees outward'],
      safetyTips: ['Keep your feet securely on the pedals', 'Warm up before sprinting'],
      breathing: 'Breathe continuously and dynamically in sync with your intensity.',
      estimatedCaloriesPerMinute: 12.0,
      tags: ['Full Body', 'Machine', 'Advanced', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 2. Backward Running
    Exercise(
      exerciseId: 'backward_running',
      name: 'Backward Running',
      aliases: ['Retro Running'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs'],
      exerciseType: 'LISS',
      trainingStyles: ['Athletic Performance', 'Rehabilitation', 'Conditioning'],
      categories: ['Bodyweight', 'Conditioning'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Run',
      goalTags: ['Balance', 'Coordination', 'Knee Health'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Quads', 'Calves', 'Hamstrings', 'Glutes'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Outdoor', 'Gym'],
      injuryFriendly: ['Knee Friendly'],
      alternatives: ['running', 'jogging'],
      progressions: ['backward_running_sprints'],
      regressions: ['backward_walking'],
      thumbnail: 'https://images.unsplash.com/photo-1538388149542-5e24932d11a8?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Find a flat, clear path with no obstacles.',
        'Lean slightly forward and push off the balls of your feet, moving backward.',
        'Pump your arms in opposition to your legs.',
        'Periodically check over your shoulder for safety.'
      ],
      commonMistakes: ['Leaning too far backward', 'Landing on flat feet', 'Not looking where you are going'],
      safetyTips: ['Perform this only on a flat, even surface', 'Start at a walking pace first'],
      breathing: 'Maintain a steady, rhythmic breathing pattern.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Legs', 'Bodyweight', 'Intermediate', 'LISS', 'Conditioning', 'Cardio'],
    ),

    // 3. Battle Rope
    Exercise(
      exerciseId: 'battle_rope',
      name: 'Battle Rope',
      aliases: ['Battle Rope Waves', 'Heavy Ropes'],
      muscleGroup: 'Cardio',
      targetRegions: ['Upper Body', 'Full Body'],
      exerciseType: 'HIIT',
      trainingStyles: ['HIIT', 'Functional Fitness', 'Athletic Performance', 'Conditioning'],
      categories: ['Conditioning', 'Compound'],
      equipment: ['Battle Ropes'],
      difficulty: 'Advanced',
      movementPattern: 'Full Body Pull/Push',
      goalTags: ['Conditioning', 'Upper Body Endurance', 'Fat Loss'],
      isCompound: true,
      primaryMuscles: ['Full Body'],
      secondaryMuscles: ['Shoulders', 'Core', 'Forearms', 'Lats'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: ['Knee Friendly'],
      alternatives: ['medicine_ball_slam', 'rowing_machine'],
      progressions: ['heavy_battle_rope_slams'],
      regressions: ['single_arm_rope_waves'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand with feet shoulder-width apart, holding the ends of the battle ropes with an overhand grip.',
        'Hinge at hips, bending knees slightly into a half-squat position.',
        'Brace your core and rapidly wave your arms up and down to create continuous waves in the ropes.',
        'Keep your chest proud and avoid rounding your spine.'
      ],
      commonMistakes: ['Standing completely straight', 'Using only the wrists', 'Rounding the shoulders forward'],
      safetyTips: ['Maintain a flat back throughout', 'Stand at a distance that leaves slack in the ropes'],
      breathing: 'Exhale sharply with slams or breathe quickly in rhythm with waves.',
      estimatedCaloriesPerMinute: 10.5,
      tags: ['Upper Body', 'Full Body', 'Advanced', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 4. Bear Crawl
    Exercise(
      exerciseId: 'bear_crawl',
      name: 'Bear Crawl',
      aliases: ['Quadruped Crawl'],
      muscleGroup: 'Cardio',
      targetRegions: ['Core', 'Full Body'],
      exerciseType: 'HIIT',
      trainingStyles: ['Functional Fitness', 'Calisthenics', 'Conditioning'],
      categories: ['Bodyweight', 'Conditioning', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Crawl',
      goalTags: ['Core Strength', 'Conditioning', 'Shoulder Stability'],
      isCompound: true,
      primaryMuscles: ['Full Body'],
      secondaryMuscles: ['Core', 'Shoulders', 'Quads'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['crab_walk', 'mountain_climber'],
      progressions: ['weighted_bear_crawl', 'lateral_bear_crawl'],
      regressions: ['tabletop_crawl', 'plank'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Start on your hands and knees, hands under shoulders and knees under hips.',
        'Lift your knees slightly off the floor, keeping your back flat and core tight.',
        'Move your right hand and left foot forward simultaneously.',
        'Repeat on the opposite side, crawling forward with controlled steps.'
      ],
      commonMistakes: ['Lifting the hips too high', 'Letting the back sag', 'Looking straight up (straining neck)'],
      safetyTips: ['Keep your knees close to the floor (1-2 inches) to keep core loaded', 'Keep spine neutral'],
      breathing: 'Breathe steadily in rhythm with your crawl.',
      estimatedCaloriesPerMinute: 7.5,
      tags: ['Core', 'Full Body', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 5. Boxer Skip
    Exercise(
      exerciseId: 'boxer_skip',
      name: 'Boxer Skip',
      aliases: ['Boxer Shuffle Jump Rope', 'Alternating Boxer Skip'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs'],
      exerciseType: 'LISS',
      trainingStyles: ['Athletic Performance', 'General Fitness', 'Conditioning'],
      categories: ['Conditioning', 'Compound'],
      equipment: ['Jump Rope'],
      difficulty: 'Intermediate',
      movementPattern: 'Jump',
      goalTags: ['Conditioning', 'Coordination', 'Footwork'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Calves', 'Shoulders', 'Core'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['jump_rope', 'speed_rope'],
      progressions: ['double_under'],
      regressions: ['jumping_jacks'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Hold the jump rope handles and stand with feet close together.',
        'As you swing the rope, shift your weight from one foot to the other with small, low bounces.',
        'Keep your bounces light and springy, mimicking a boxer\'s shuffle.',
        'Keep elbows close to your torso and rotate rope primarily using wrists.'
      ],
      commonMistakes: ['Bouncing too high', 'Using the entire arms to spin the rope', 'Tense shoulders'],
      safetyTips: ['Land softly on the balls of your feet', 'Wear supportive athletic shoes'],
      breathing: 'Maintain a steady, relaxed breathing pattern.',
      estimatedCaloriesPerMinute: 9.0,
      tags: ['Legs', 'Jump Rope', 'Intermediate', 'LISS', 'Conditioning', 'Cardio'],
    ),

    // 6. Brisk Walking
    Exercise(
      exerciseId: 'brisk_walking',
      name: 'Brisk Walking',
      aliases: ['Fast Walk', 'Power Walk'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs', 'Cardiovascular System'],
      exerciseType: 'LISS',
      trainingStyles: ['General Fitness', 'Fat Loss', 'LISS', 'Conditioning'],
      categories: ['Bodyweight', 'LISS'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Walk',
      goalTags: ['Fat Loss', 'Cardiovascular Health', 'Active Recovery'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Hamstrings', 'Calves', 'Glutes'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Outdoor', 'Home', 'Gym', 'Travel'],
      injuryFriendly: ['Knee Friendly', 'Beginner Friendly', 'Lower Back Friendly'],
      alternatives: ['walking', 'jogging'],
      progressions: ['jogging', 'incline_treadmill_walk'],
      regressions: ['walking'],
      thumbnail: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Walk at a fast pace, faster than a casual stroll (typically 3.0 to 4.5 mph).',
        'Pump your arms naturally at your sides.',
        'Keep your spine straight, chest open, and shoulders relaxed.'
      ],
      commonMistakes: ['Overstriding', 'Slouching forward', 'Looking down at feet'],
      safetyTips: ['Wear supportive shoes', 'Keep aware of surroundings outdoors'],
      breathing: 'Inhale deeply through your nose, exhale through your mouth.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Legs', 'Bodyweight', 'Beginner', 'LISS', 'Conditioning', 'Cardio'],
    ),

    // 7. Broad Jump
    Exercise(
      exerciseId: 'broad_jump',
      name: 'Broad Jump',
      aliases: ['Standing Long Jump'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs'],
      exerciseType: 'HIIT',
      trainingStyles: ['Athletic Performance', 'Plyometrics', 'Functional Fitness'],
      categories: ['Bodyweight', 'HIIT', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Jump',
      goalTags: ['Explosive Power', 'Conditioning', 'Leg Strength'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Glutes', 'Hamstrings', 'Quads', 'Core'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['frog_jump', 'tuck_jump'],
      progressions: ['weighted_broad_jump'],
      regressions: ['squat_jump'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand with feet shoulder-width apart behind a starting line.',
        'Swing your arms backward and hinge at hips and knees.',
        'Explode forward, swinging your arms forward and pushing off the floor.',
        'Land softly on both feet, absorbing the impact by bending your knees.'
      ],
      commonMistakes: ['Landing with locked knees', 'Leaning too far forward at landing', 'Hard heavy landings'],
      safetyTips: ['Absorb landing impact through a full squat shape', 'Ensure landing surface is non-slip'],
      breathing: 'Inhale preparing, exhale as you jump.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Legs', 'Bodyweight', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 8. Burpee
    Exercise(
      exerciseId: 'burpee',
      name: 'Burpee',
      aliases: ['Classic Burpee', 'Full Burpee'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body'],
      exerciseType: 'HIIT',
      trainingStyles: ['CrossFit', 'HIIT', 'Calisthenics', 'Conditioning', 'Fat Loss'],
      categories: ['HIIT', 'Conditioning', 'Compound', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Jump',
      goalTags: ['Conditioning', 'Fat Loss', 'Explosive Power'],
      isCompound: true,
      primaryMuscles: ['Full Body'],
      secondaryMuscles: ['Chest', 'Shoulders', 'Triceps', 'Core', 'Quads'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['half_burpee', 'squat_thrust'],
      progressions: ['weighted_burpee', 'burpee_pull_up'],
      regressions: ['half_burpee', 'squat_thrust'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand tall, then drop into a squat and place your hands on the floor in front of you.',
        'Kick your feet back into a push-up position.',
        'Lower your chest to the floor (push-up).',
        'Push your chest back up and snap your feet forward to return to the squat position.',
        'Explode upward into a jump, reaching your hands overhead.'
      ],
      commonMistakes: ['Sagging hips during the push-up phase', 'Hard/flat-footed landings', 'Rounding the spine'],
      safetyTips: ['Absorb landings by bending your knees', 'Maintain core tension to protect the lower back'],
      breathing: 'Exhale exploding up, inhale dropping down.',
      estimatedCaloriesPerMinute: 9.5,
      tags: ['Full Body', 'Bodyweight', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 9. Butt Kicks
    Exercise(
      exerciseId: 'butt_kicks',
      name: 'Butt Kicks',
      aliases: ['Butt Kickers', 'Ankle Flicks'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs'],
      exerciseType: 'HIIT',
      trainingStyles: ['General Fitness', 'Athletic Performance', 'HIIT', 'Conditioning'],
      categories: ['Bodyweight', 'HIIT', 'Conditioning'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Run',
      goalTags: ['Conditioning', 'Agility', 'Warm-Up'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Hamstrings', 'Calves', 'Quadriceps'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Beginner Friendly'],
      alternatives: ['high_knees', 'jumping_jacks'],
      progressions: ['fast_butt_kicks'],
      regressions: ['walking_butt_kicks'],
      thumbnail: 'https://images.unsplash.com/photo-1538388149542-5e24932d11a8?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand tall with feet hip-width apart.',
        'Jog in place, pulling your heels up toward your glutes on each stride.',
        'Keep your thighs relatively vertical and pump your arms in rhythm.'
      ],
      commonMistakes: ['Leaning too far forward', 'Letting knees travel forward too much'],
      safetyTips: ['Land softly on the balls of your feet'],
      breathing: 'Maintain a steady, rhythmic breathing pattern.',
      estimatedCaloriesPerMinute: 7.0,
      tags: ['Legs', 'Bodyweight', 'Beginner', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 10. Crab Walk
    Exercise(
      exerciseId: 'crab_walk',
      name: 'Crab Walk',
      aliases: ['Supine Crawl'],
      muscleGroup: 'Cardio',
      targetRegions: ['Core', 'Upper Body'],
      exerciseType: 'HIIT',
      trainingStyles: ['Functional Fitness', 'Calisthenics', 'Conditioning'],
      categories: ['Bodyweight', 'Conditioning', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Crawl',
      goalTags: ['Conditioning', 'Shoulder Stability', 'Tricep Endurance'],
      isCompound: true,
      primaryMuscles: ['Core', 'Shoulders'],
      secondaryMuscles: ['Triceps', 'Hamstrings', 'Glutes'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['bear_crawl', 'plank'],
      progressions: ['fast_crab_walk'],
      regressions: ['supine_plank_hold'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit on the floor with knees bent and feet flat, placing hands on the floor behind you.',
        'Lift your hips off the floor, supporting your weight on your hands and feet.',
        'Step forward with your left hand and right foot, then right hand and left foot.',
        'Walk backward or forward while maintaining lifted hips.'
      ],
      commonMistakes: ['Letting hips sag to the floor', 'Flaring shoulders upward', 'Rushing'],
      safetyTips: ['Do not hyperextend your wrists; point fingers outward slightly for comfort'],
      breathing: 'Breathe steadily.',
      estimatedCaloriesPerMinute: 6.8,
      tags: ['Core', 'Upper Body', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 11. Cycling
    Exercise(
      exerciseId: 'cycling',
      name: 'Cycling',
      aliases: ['Road Cycling', 'Outdoor Biking'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs', 'Cardiovascular System'],
      exerciseType: 'LISS',
      trainingStyles: ['Sports Performance', 'General Fitness', 'Fat Loss', 'LISS', 'Conditioning'],
      categories: ['LISS', 'Conditioning', 'Compound'],
      equipment: ['Bicycle'],
      difficulty: 'Beginner',
      movementPattern: 'Pedal',
      goalTags: ['Cardiovascular Health', 'Leg Strength', 'Fat Loss'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Quads', 'Hamstrings', 'Calves', 'Glutes'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Outdoor'],
      injuryFriendly: ['Knee Friendly', 'Joint Friendly'],
      alternatives: ['stationary_bike', 'running'],
      progressions: ['incline_cycling', 'sprint_cycling'],
      regressions: ['stationary_bike'],
      thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Adjust the bicycle seat height correctly.',
        'Mount the bicycle and peddle continuously on roads, paths, or trails.',
        'Use gear shifts to manage resistance on hills.'
      ],
      commonMistakes: ['Low seat height straining knees', 'Slouching spine'],
      safetyTips: ['Always wear a helmet', 'Follow local traffic laws'],
      breathing: 'Breathe deeply and rhythmically.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Legs', 'Bicycle', 'Beginner', 'LISS', 'Conditioning', 'Cardio'],
    ),

    // 12. Double Under
    Exercise(
      exerciseId: 'double_under',
      name: 'Double Under',
      aliases: ['Double Unders'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs'],
      exerciseType: 'HIIT',
      trainingStyles: ['CrossFit', 'Athletic Performance', 'HIIT', 'Conditioning'],
      categories: ['Conditioning', 'Compound'],
      equipment: ['Speed Rope'],
      difficulty: 'Advanced',
      movementPattern: 'Jump',
      goalTags: ['Explosive Power', 'Coordination', 'Conditioning'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Calves', 'Shoulders', 'Core'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['speed_rope', 'jump_rope'],
      progressions: ['triple_under'],
      regressions: ['jump_rope', 'boxer_skip'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Hold jump rope handles and stand with feet close together.',
        'Jump slightly higher than a standard skip.',
        'Rotate your wrists twice as fast to pass the rope under your feet twice per jump.',
        'Land softly on the balls of your feet and repeat in a continuous flow.'
      ],
      commonMistakes: ['Jumping with bent knees (tucking)', 'Using whole arms to spin rope', 'Landing flat-footed'],
      safetyTips: ['Keep your shoulders relaxed and elbows tucked in tight'],
      breathing: 'Breathe fast and in sync with jumps.',
      estimatedCaloriesPerMinute: 11.0,
      tags: ['Legs', 'Speed Rope', 'Advanced', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 13. Elliptical
    Exercise(
      exerciseId: 'elliptical',
      name: 'Elliptical',
      aliases: ['Elliptical Trainer', 'Cross Trainer'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs', 'Full Body'],
      exerciseType: 'LISS',
      trainingStyles: ['General Fitness', 'LISS', 'Rehabilitation', 'Conditioning'],
      categories: ['Machine', 'LISS', 'Conditioning'],
      equipment: ['Elliptical Machine'],
      difficulty: 'Beginner',
      movementPattern: 'Stride',
      goalTags: ['Cardiovascular Health', 'Active Recovery', 'Low Impact Conditioning'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Quads', 'Hamstrings', 'Glutes', 'Calves', 'Chest', 'Back'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: ['Knee Friendly', 'Joint Friendly', 'Lower Back Friendly'],
      alternatives: ['stationary_bike', 'walking'],
      progressions: ['high_resistance_elliptical'],
      regressions: ['walking'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Step onto the machine pedals and grip the moving handles.',
        'Start striding in a smooth, oval motion.',
        'Keep your spine straight, shoulders back, and push/pull handles with your arms.'
      ],
      commonMistakes: ['Leaning on display panel', 'Lifting heels off pedals completely', 'Incorrect posture'],
      safetyTips: ['Ensure machine is locked or stopped before stepping on/off'],
      breathing: 'Maintain slow, deep nasal breathing.',
      estimatedCaloriesPerMinute: 6.5,
      tags: ['Legs', 'Machine', 'Beginner', 'LISS', 'Conditioning', 'Cardio'],
    ),

    // 14. Frog Jump
    Exercise(
      exerciseId: 'frog_jump',
      name: 'Frog Jump',
      aliases: ['Frogger Jump', 'Frog Leap'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs'],
      exerciseType: 'HIIT',
      trainingStyles: ['Plyometrics', 'HIIT', 'Calisthenics', 'Conditioning'],
      categories: ['Bodyweight', 'HIIT', 'Conditioning', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Jump',
      goalTags: ['Explosive Power', 'Leg Strength', 'Conditioning'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Glutes', 'Hamstrings', 'Quads', 'Calves'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Gym', 'Outdoor', 'Home'],
      injuryFriendly: [],
      alternatives: ['broad_jump', 'tuck_jump'],
      progressions: ['weighted_frog_jump'],
      regressions: ['squats'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand with feet wider than shoulder-width, toes turned slightly out.',
        'Drop down into a deep squat, touching the floor with your fingers.',
        'Explode forward and upward, jumping as far as possible.',
        'Land softly back into a deep squat, touching floor to transition to next jump.'
      ],
      commonMistakes: ['Landing with flat feet', 'Rounding back during squat', 'Valgus (inward caving) knees'],
      safetyTips: ['Keep chest up in bottom position', 'Absorb impact fully through hips and knees'],
      breathing: 'Exhale jumping, inhale landing.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Legs', 'Bodyweight', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 15. Half Burpee
    Exercise(
      exerciseId: 'half_burpee',
      name: 'Half Burpee',
      aliases: ['No Push-up Burpee', 'Low Impact Burpee'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body'],
      exerciseType: 'HIIT',
      trainingStyles: ['General Fitness', 'HIIT', 'Conditioning', 'Fat Loss'],
      categories: ['HIIT', 'Conditioning', 'Compound', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Jump',
      goalTags: ['Conditioning', 'Fat Loss', 'Agility'],
      isCompound: true,
      primaryMuscles: ['Full Body'],
      secondaryMuscles: ['Core', 'Shoulders', 'Quads'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['burpee', 'squat_thrust'],
      progressions: ['burpee'],
      regressions: ['squat_thrust'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand tall, then drop down and place hands on the floor.',
        'Kick feet back into high plank position.',
        'Immediately jump feet forward back to hand position.',
        'Explode upward into a vertical jump, reaching arms overhead.'
      ],
      commonMistakes: ['Hips sagging in plank', 'Landing hard on heels'],
      safetyTips: ['Keep core braced to protect spine in plank'],
      breathing: 'Exhale jumping, inhale dropping.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Full Body', 'Bodyweight', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 16. High Knees
    Exercise(
      exerciseId: 'high_knees',
      name: 'High Knees',
      aliases: ['High Knee Run'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs'],
      exerciseType: 'HIIT',
      trainingStyles: ['HIIT', 'Athletic Performance', 'Calisthenics', 'Conditioning'],
      categories: ['Bodyweight', 'HIIT', 'Conditioning', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Run',
      goalTags: ['Conditioning', 'Fat Loss', 'Agility'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Hip Flexors', 'Core', 'Calves'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['butt_kicks', 'jumping_jacks'],
      progressions: ['fast_high_knees'],
      regressions: ['marching_in_place'],
      thumbnail: 'https://images.unsplash.com/photo-1538388149542-5e24932d11a8?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand tall with feet hip-width apart.',
        'Run in place, lifting your knees up toward chest, aiming to get thighs parallel to floor.',
        'Pump your arms naturally and rapidly.'
      ],
      commonMistakes: ['Leaning backward', 'Low knee height', 'Landing flat-footed'],
      safetyTips: ['Maintain vertical spine alignment', 'Land softly on balls of feet'],
      breathing: 'Rhythmic, rapid breathing pattern.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Legs', 'Bodyweight', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 17. Hill Sprint
    Exercise(
      exerciseId: 'hill_sprint',
      name: 'Hill Sprint',
      aliases: ['Incline Sprint', 'Hill Running'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs', 'Cardiovascular System'],
      exerciseType: 'HIIT',
      trainingStyles: ['Athletic Performance', 'HIIT', 'Sports Performance', 'Conditioning'],
      categories: ['Bodyweight', 'HIIT', 'Conditioning', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Advanced',
      movementPattern: 'Run',
      goalTags: ['Leg Power', 'Conditioning', 'Sprinting Speed'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Glutes', 'Hamstrings', 'Quads', 'Calves', 'Core'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Outdoor'],
      injuryFriendly: [],
      alternatives: ['sprint', 'treadmill_run'],
      progressions: ['weighted_hill_sprints'],
      regressions: ['hill_walking', 'jogging'],
      thumbnail: 'https://images.unsplash.com/photo-1538388149542-5e24932d11a8?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Find a moderately steep hill (10-15% grade) free of obstacles.',
        'Warm up thoroughly.',
        'Sprint uphill at maximum effort for 10-20 seconds, pumping arms and lifting knees.',
        'Walk back down slowly to recover fully before the next sprint.'
      ],
      commonMistakes: ['Rounding shoulders', 'Overstriding', 'Inadequate recovery time'],
      safetyTips: ['Do not sprint if you have hamstring or calf tightness', 'Ensure stable footing'],
      breathing: 'Deep, forced breathing during sprint, relaxed recovery breathing.',
      estimatedCaloriesPerMinute: 13.0,
      tags: ['Legs', 'Bodyweight', 'Advanced', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 18. Incline Treadmill Walk
    Exercise(
      exerciseId: 'incline_treadmill_walk',
      name: 'Incline Treadmill Walk',
      aliases: ['Incline Walk', 'Treadmill Hill Walk'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs', 'Cardiovascular System'],
      exerciseType: 'LISS',
      trainingStyles: ['General Fitness', 'Fat Loss', 'LISS', 'Conditioning'],
      categories: ['Machine', 'LISS', 'Conditioning'],
      equipment: ['Treadmill'],
      difficulty: 'Beginner',
      movementPattern: 'Walk',
      goalTags: ['Cardiovascular Health', 'Active Recovery', 'Posterior Chain Activation'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Hamstrings', 'Glutes', 'Calves'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Gym'],
      injuryFriendly: ['Knee Friendly', 'Joint Friendly'],
      alternatives: ['walking', 'elliptical'],
      progressions: ['jogging', 'higher_incline_walk'],
      regressions: ['treadmill_walk'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Step onto the treadmill, set a moderate walking speed (2.5 to 3.5 mph), and increase the incline (typically 6-12%).',
        'Walk naturally with a tall spine, pushing through your heels.',
        'Avoid holding onto the handrails if possible to maximize calorie burn.'
      ],
      commonMistakes: ['Holding the handrails and leaning back (negates incline benefit)', 'Overstriding', 'Slouching forward'],
      safetyTips: ['Use safety clip', 'Start with lower incline (3-5%) if beginner'],
      breathing: 'Steady deep nasal breathing.',
      estimatedCaloriesPerMinute: 7.0,
      tags: ['Legs', 'Machine', 'Beginner', 'LISS', 'Conditioning', 'Cardio'],
    ),

    // 19. Jogging
    Exercise(
      exerciseId: 'jogging',
      name: 'Jogging',
      aliases: ['Slow Run', 'Easy Run'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs', 'Cardiovascular System'],
      exerciseType: 'LISS',
      trainingStyles: ['General Fitness', 'LISS', 'Conditioning', 'Fat Loss'],
      categories: ['Bodyweight', 'LISS', 'Conditioning'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Run',
      goalTags: ['Endurance', 'Cardiovascular Health', 'Fat Loss'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Calves', 'Hamstrings', 'Quads', 'Glutes'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Outdoor', 'Gym', 'Travel'],
      injuryFriendly: [],
      alternatives: ['running', 'brisk_walking'],
      progressions: ['running', 'hill_sprint'],
      regressions: ['brisk_walking'],
      thumbnail: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Maintain a steady, moderate running pace (typically 4.5 to 6.0 mph).',
        'Keep your posture upright, elbows bent at 90 degrees, and shoulders relaxed.',
        'Land mid-foot to reduce joint impact and roll forward to toes.'
      ],
      commonMistakes: ['Heel striking heavily', 'Tensing shoulders', 'Overstriding'],
      safetyTips: ['Choose flat, stable surfaces', 'Increase distance gradually'],
      breathing: 'Breathe in rhythm with your footfalls (e.g., inhale 3 steps, exhale 2).',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Legs', 'Bodyweight', 'Intermediate', 'LISS', 'Conditioning', 'Cardio'],
    ),

    // 20. Jump Rope
    Exercise(
      exerciseId: 'jump_rope',
      name: 'Jump Rope',
      aliases: ['Rope Skipping', 'Basic Skip'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs'],
      exerciseType: 'LISS',
      trainingStyles: ['General Fitness', 'Athletic Performance', 'LISS', 'Conditioning'],
      categories: ['Conditioning', 'Compound'],
      equipment: ['Jump Rope'],
      difficulty: 'Intermediate',
      movementPattern: 'Jump',
      goalTags: ['Conditioning', 'Coordination', 'Footwork'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Calves', 'Shoulders', 'Core'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['speed_rope', 'boxer_skip'],
      progressions: ['double_under', 'boxer_skip'],
      regressions: ['jumping_jacks'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Hold the rope handles, keeping elbows close to torso.',
        'Jump just high enough to clear the rope (1-2 inches off floor).',
        'Rotate rope using wrists rather than whole arms.',
        'Land softly on the balls of your feet.'
      ],
      commonMistakes: ['Jumping too high', 'Using arms/shoulders to turn rope', 'Flat-footed landing'],
      safetyTips: ['Keep shoulders relaxed', 'Ensure correct rope length'],
      breathing: 'Steady and relaxed.',
      estimatedCaloriesPerMinute: 9.0,
      tags: ['Legs', 'Jump Rope', 'Intermediate', 'LISS', 'Conditioning', 'Cardio'],
    ),

    // 21. Jumping Jacks
    Exercise(
      exerciseId: 'jumping_jacks',
      name: 'Jumping Jacks',
      aliases: ['Side Straddle Hop'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body'],
      exerciseType: 'HIIT',
      trainingStyles: ['General Fitness', 'HIIT', 'Calisthenics', 'Conditioning'],
      categories: ['Bodyweight', 'HIIT', 'Conditioning'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Jump',
      goalTags: ['Conditioning', 'Warm-Up', 'Fat Loss'],
      isCompound: true,
      primaryMuscles: ['Full Body'],
      secondaryMuscles: ['Calves', 'Shoulders', 'Glutes'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Beginner Friendly'],
      alternatives: ['seal_jacks', 'high_knees'],
      progressions: ['star_jump', 'seal_jacks'],
      regressions: ['step_jacks'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand with feet together and arms at your sides.',
        'Jump feet out to the sides while bringing arms overhead.',
        'Immediately jump back to starting position, returning feet together and arms to sides.'
      ],
      commonMistakes: ['Landing heavy on heels', 'Keeping arms bent', 'Short range of motion'],
      safetyTips: ['Land softly on the balls of your feet'],
      breathing: 'Breathe steadily in rhythm with your jumps.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Full Body', 'Bodyweight', 'Beginner', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 22. Kettlebell Swing
    Exercise(
      exerciseId: 'kettlebell_swing',
      name: 'Kettlebell Swing',
      aliases: ['KB Swing', 'Russian Kettlebell Swing'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Legs'],
      exerciseType: 'HIIT',
      trainingStyles: ['Functional Fitness', 'HIIT', 'Strength Training', 'Conditioning'],
      categories: ['Compound', 'Conditioning'],
      equipment: ['Kettlebell'],
      difficulty: 'Intermediate',
      movementPattern: 'Hinge',
      goalTags: ['Explosive Power', 'Posterior Chain', 'Conditioning'],
      isCompound: true,
      primaryMuscles: ['Glutes', 'Hamstrings'],
      secondaryMuscles: ['Lower Back', 'Core', 'Shoulders', 'Forearms'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['kettlebell_deadlift', 'medicine_ball_slam'],
      progressions: ['one_arm_kettlebell_swing'],
      regressions: ['kettlebell_deadlift'],
      thumbnail: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand with feet shoulder-width apart, kettlebell on the floor in front of you.',
        'Hinge at hips, bend knees slightly, and grip the kettlebell with both hands.',
        'Swing the bell back between your legs (hike phase).',
        'Snap your hips forward explosively, standing tall and projecting the kettlebell to chest height.',
        'Let the bell pull you back into the hinge pattern for the next rep.'
      ],
      commonMistakes: ['Squatting instead of hinging', 'Using shoulders to lift the bell', 'Rounding the back'],
      safetyTips: ['Keep your spine straight throughout', 'Do not arch back at top of movement'],
      breathing: 'Inhale hinging down, exhale sharply snapping hips forward.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Full Body', 'Legs', 'Kettlebell', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 23. Plank Jack
    Exercise(
      exerciseId: 'plank_jack',
      name: 'Plank Jack',
      aliases: ['Plank Jumping Jacks'],
      muscleGroup: 'Cardio',
      targetRegions: ['Core'],
      exerciseType: 'HIIT',
      trainingStyles: ['HIIT', 'Calisthenics', 'Conditioning'],
      categories: ['Bodyweight', 'HIIT', 'Conditioning'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Jump',
      goalTags: ['Core Stability', 'Conditioning'],
      isCompound: true,
      primaryMuscles: ['Core'],
      secondaryMuscles: ['Shoulders', 'Glutes', 'Calves'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Core',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['jumping_jacks', 'mountain_climber'],
      progressions: ['forearm_plank_jacks'],
      regressions: ['plank_steps'],
      thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Start in a high plank position, hands under shoulders, core tight.',
        'Jump your feet out wide, then immediately jump them back together, maintaining a stable torso.'
      ],
      commonMistakes: ['Hips bouncing up and down', 'Hands drifting forward of shoulders'],
      safetyTips: ['Keep your core fully braced to protect lower back'],
      breathing: 'Rhythmic, steady breathing.',
      estimatedCaloriesPerMinute: 7.0,
      tags: ['Core', 'Bodyweight', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 24. Power Skip
    Exercise(
      exerciseId: 'power_skip',
      name: 'Power Skip',
      aliases: ['High Skip', 'Vertical Skip'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs'],
      exerciseType: 'HIIT',
      trainingStyles: ['Athletic Performance', 'Plyometrics', 'Conditioning'],
      categories: ['Bodyweight', 'HIIT', 'Conditioning', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Jump',
      goalTags: ['Explosive Power', 'Vertical Jump', 'Conditioning'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Glutes', 'Calves', 'Core'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Outdoor', 'Gym'],
      injuryFriendly: [],
      alternatives: ['high_knees', 'broad_jump'],
      progressions: ['weighted_power_skip'],
      regressions: ['standard_skipping'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Skip forward, exploding upward on each skip.',
        'Drive your right knee up while pushing off your left foot, throwing your left arm upward for maximum height.',
        'Land softly and immediately repeat on the opposite side.'
      ],
      commonMistakes: ['Flat-footed landings', 'Using minimal arm drive'],
      safetyTips: ['Ensure landing surface is flat', 'Land softly on balls of feet'],
      breathing: 'Exhale on upward drive, inhale on descent.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Legs', 'Bodyweight', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 25. Rowing Machine
    Exercise(
      exerciseId: 'rowing_machine',
      name: 'Rowing Machine',
      aliases: ['Ergometer', 'Rowing'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Upper Body'],
      exerciseType: 'LISS',
      trainingStyles: ['General Fitness', 'CrossFit', 'LISS', 'Conditioning'],
      categories: ['Machine', 'LISS', 'Conditioning', 'Compound'],
      equipment: ['Rowing Machine'],
      difficulty: 'Intermediate',
      movementPattern: 'Full Body Pull/Push',
      goalTags: ['Cardiovascular Health', 'Full Body Endurance'],
      isCompound: true,
      primaryMuscles: ['Full Body'],
      secondaryMuscles: ['Back', 'Legs', 'Core', 'Forearms'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Full Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['elliptical', 'air_bike'],
      progressions: ['high_spm_rowing'],
      regressions: ['stationary_bike'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit on the seat, strap your feet in securely, and slide forward to grip handle (Catch).',
        'Drive back with your legs first, then lean torso back slightly, and pull handle to lower ribs (Drive).',
        'Extend arms forward, hinge torso forward, and bend knees to slide forward to start (Recovery).'
      ],
      commonMistakes: ['Pulling with arms before leg drive', 'Rounding back at catch', 'Bending knees too early on recovery'],
      safetyTips: ['Keep your spine neutral throughout', 'Use moderate damper settings (4-6)'],
      breathing: 'Exhale driving back, inhale sliding forward.',
      estimatedCaloriesPerMinute: 7.5,
      tags: ['Full Body', 'Upper Body', 'Machine', 'Intermediate', 'LISS', 'Conditioning', 'Cardio'],
    ),

    // 26. Running
    Exercise(
      exerciseId: 'running',
      name: 'Running',
      aliases: ['Outdoor Run', 'Treadmill Running'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs', 'Cardiovascular System'],
      exerciseType: 'LISS',
      trainingStyles: ['Sports Performance', 'General Fitness', 'LISS', 'Conditioning', 'Fat Loss'],
      categories: ['Bodyweight', 'LISS', 'Conditioning'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Run',
      goalTags: ['Cardiovascular Health', 'Endurance', 'Fat Loss'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Calves', 'Hamstrings', 'Quads', 'Glutes', 'Core'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Outdoor', 'Gym', 'Travel'],
      injuryFriendly: [],
      alternatives: ['jogging', 'sprint'],
      progressions: ['sprint', 'hill_sprint'],
      regressions: ['jogging', 'brisk_walking'],
      thumbnail: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Maintain a steady running speed (typically 6.0+ mph).',
        'Keep spine upright, elbows at 90 degrees, and drive feet mid-foot to toe.',
        'Breathe in rhythm with your pace.'
      ],
      commonMistakes: ['Heel striking heavily', 'Rounding upper back', 'Overstriding'],
      safetyTips: ['Gradually increase running mileage to prevent shin splints', 'Wear proper running shoes'],
      breathing: 'Deep, rhythmic diaphragmatic breathing.',
      estimatedCaloriesPerMinute: 10.0,
      tags: ['Legs', 'Bodyweight', 'Intermediate', 'LISS', 'Conditioning', 'Cardio'],
    ),

    // 27. Sandbag Carry
    Exercise(
      exerciseId: 'sandbag_carry',
      name: 'Sandbag Carry',
      aliases: ['Sandbag Walk', 'Bear Hug Carry'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body'],
      exerciseType: 'HIIT',
      trainingStyles: ['Strongman', 'Functional Fitness', 'Conditioning'],
      categories: ['Compound', 'Conditioning'],
      equipment: ['Sandbag'],
      difficulty: 'Intermediate',
      movementPattern: 'Carry',
      goalTags: ['Core Strength', 'Conditioning', 'Full Body Power'],
      isCompound: true,
      primaryMuscles: ['Full Body'],
      secondaryMuscles: ['Core', 'Forearms', 'Glutes', 'Upper Back'],
      mechanics: 'Compound',
      forceType: 'Isometric',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['farmers_carry', 'sled_push'],
      progressions: ['heavy_sandbag_carry'],
      regressions: ['farmers_carry'],
      thumbnail: 'https://images.unsplash.com/photo-1627483297886-49710ae1fc22?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand over a heavy sandbag and clean it up to your chest (or bear hug it).',
        'Stand tall with shoulders pulled back, core tight, and spine straight.',
        'Walk forward in a straight line with short, rapid steps.'
      ],
      commonMistakes: ['Rounding back under sandbag load', 'Shrugging shoulders', 'Leaning backward'],
      safetyTips: ['Ensure back is flat when cleaning sandbag off floor', 'Keep core highly braced'],
      breathing: 'Breathe in short, shallow breaths.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Full Body', 'Sandbag', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 28. Seal Jacks
    Exercise(
      exerciseId: 'seal_jacks',
      name: 'Seal Jacks',
      aliases: ['Seal Jumping Jacks'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body'],
      exerciseType: 'HIIT',
      trainingStyles: ['General Fitness', 'HIIT', 'Calisthenics', 'Conditioning'],
      categories: ['Bodyweight', 'HIIT', 'Conditioning'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Jump',
      goalTags: ['Conditioning', 'Warm-Up', 'Shoulder Mobility'],
      isCompound: true,
      primaryMuscles: ['Full Body'],
      secondaryMuscles: ['Calves', 'Chest', 'Shoulders'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Beginner Friendly'],
      alternatives: ['jumping_jacks', 'high_knees'],
      progressions: ['star_jump'],
      regressions: ['step_jacks'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand with feet together and arms extended straight out in front of your chest (palms together).',
        'Jump feet out to the sides while swinging arms out wide to sides.',
        'Immediately jump back to starting position, returning feet together and arms together in front.'
      ],
      commonMistakes: ['Landing heavy', 'Bending elbows'],
      safetyTips: ['Land softly on balls of feet'],
      breathing: 'Steady, rhythmic breathing.',
      estimatedCaloriesPerMinute: 6.2,
      tags: ['Full Body', 'Bodyweight', 'Beginner', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 29. Single Leg Rope Jump
    Exercise(
      exerciseId: 'single_leg_rope_jump',
      name: 'Single Leg Rope Jump',
      aliases: ['Single Leg Skip', 'One Leg Jump Rope'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs'],
      exerciseType: 'HIIT',
      trainingStyles: ['Athletic Performance', 'HIIT', 'Conditioning'],
      categories: ['Conditioning', 'Compound'],
      equipment: ['Jump Rope'],
      difficulty: 'Advanced',
      movementPattern: 'Jump',
      goalTags: ['Balance', 'Calf Strength', 'Ankle Stability'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Calves', 'Core', 'Ankles'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['jump_rope', 'speed_rope'],
      progressions: ['double_under'],
      regressions: ['jump_rope', 'boxer_skip'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand on one leg, holding the jump rope handles.',
        'Swing the rope and hop continuously on that single leg (typically 5-10 reps).',
        'Switch to the opposite leg and repeat.'
      ],
      commonMistakes: ['Jumping too high', 'Landing flat-footed', 'Uneven hips'],
      safetyTips: ['Ensure ankle joints are warm', 'Keep hops low'],
      breathing: 'Maintain steady breathing.',
      estimatedCaloriesPerMinute: 9.5,
      tags: ['Legs', 'Jump Rope', 'Advanced', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 30. Skater Jumps
    Exercise(
      exerciseId: 'skater_jumps',
      name: 'Skater Jumps',
      aliases: ['Ice Skaters', 'Lateral Bound'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs'],
      exerciseType: 'HIIT',
      trainingStyles: ['HIIT', 'Athletic Performance', 'Plyometrics', 'Conditioning'],
      categories: ['Bodyweight', 'HIIT', 'Conditioning', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Jump',
      goalTags: ['Lateral Power', 'Conditioning', 'Balance'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Glutes', 'Calves', 'Core'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['jumping_jacks', 'frog_jump'],
      progressions: ['weighted_skater_jumps', 'high_speed_skaters'],
      regressions: ['lateral_steps'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand on your right foot with knee slightly bent, sweeping your left leg behind you.',
        'Push off your right foot to leap laterally to the left, landing softly on your left foot.',
        'Sweep your right leg behind you and immediately push off left foot to leap back to the right.'
      ],
      commonMistakes: ['Landing heavy', 'Not using arms for balance', 'Rounding spine'],
      safetyTips: ['Keep knee aligned over foot on landing; do not let it collapse inward'],
      breathing: 'Exhale leaping, inhale landing.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Legs', 'Bodyweight', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 31. Ski Erg
    Exercise(
      exerciseId: 'ski_erg',
      name: 'Ski Erg',
      aliases: ['Skiing Machine', 'Concept2 SkiErg'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Upper Body'],
      exerciseType: 'HIIT',
      trainingStyles: ['CrossFit', 'HIIT', 'Functional Fitness', 'Conditioning'],
      categories: ['Machine', 'HIIT', 'Conditioning', 'Compound'],
      equipment: ['Ski Erg'],
      difficulty: 'Advanced',
      movementPattern: 'Vertical Pull',
      goalTags: ['Conditioning', 'Core Strength', 'Upper Body Power'],
      isCompound: true,
      primaryMuscles: ['Full Body'],
      secondaryMuscles: ['Lats', 'Triceps', 'Core', 'Glutes', 'Calves'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Full Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['rowing_machine', 'battle_rope'],
      progressions: ['heavy_skierg_intervals'],
      regressions: ['stationary_bike'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand facing the SkiErg, feet hip-width apart, holding handles overhead.',
        'Drive handles down by hinging at your hips and bending knees, using your bodyweight to pull.',
        'Finish the pull with arms extended past your thighs (like cross-country skiing).',
        'Extend your hips and knees to raise arms overhead and repeat.'
      ],
      commonMistakes: ['Pulling with arms only (no hip hinge)', 'Rounding the spine', 'Starting too far from machine'],
      safetyTips: ['Keep your spine neutral throughout the hinge'],
      breathing: 'Exhale driving down, inhale raising up.',
      estimatedCaloriesPerMinute: 10.0,
      tags: ['Full Body', 'Upper Body', 'Machine', 'Advanced', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 32. Sled Pull
    Exercise(
      exerciseId: 'sled_pull',
      name: 'Sled Pull',
      aliases: ['Weighted Sled Pull', 'Prowler Sled Pull'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body'],
      exerciseType: 'HIIT',
      trainingStyles: ['Strongman', 'Functional Fitness', 'Conditioning'],
      categories: ['Compound', 'Conditioning'],
      equipment: ['Sled'],
      difficulty: 'Intermediate',
      movementPattern: 'Pull',
      goalTags: ['Strength Endurance', 'Leg Power', 'Conditioning'],
      isCompound: true,
      primaryMuscles: ['Full Body'],
      secondaryMuscles: ['Quads', 'Hamstrings', 'Glutes', 'Core', 'Upper Back'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: ['Knee Friendly'],
      alternatives: ['sled_push', 'rowing_machine'],
      progressions: ['heavy_sled_pull'],
      regressions: ['lighter_sled_pull'],
      thumbnail: 'https://images.unsplash.com/photo-1627483297886-49710ae1fc22?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Attach a harness or rope to a weighted sled.',
        'Face the sled, hold handles or ropes, and walk backward in a squat/hinge stance.',
        'Pull the sled continuously by driving through your heels, keeping your chest proud.'
      ],
      commonMistakes: ['Rounding lower back', 'Standing up too straight', 'Jerking rope'],
      safetyTips: ['Keep a straight spine', 'Brace core deeply'],
      breathing: 'Steady, forced breathing.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Full Body', 'Sled', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 33. Sled Push
    Exercise(
      exerciseId: 'sled_push',
      name: 'Sled Push',
      aliases: ['Prowler Sled Push', 'Weighted Sled Push'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs', 'Full Body'],
      exerciseType: 'HIIT',
      trainingStyles: ['Strongman', 'Functional Fitness', 'HIIT', 'Conditioning'],
      categories: ['Compound', 'Conditioning'],
      equipment: ['Sled'],
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      goalTags: ['Explosive Power', 'Leg Power', 'Conditioning'],
      isCompound: true,
      primaryMuscles: ['Full Body'],
      secondaryMuscles: ['Quads', 'Glutes', 'Calves', 'Core'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: ['Knee Friendly'],
      alternatives: ['sled_pull', 'farmers_carry'],
      progressions: ['heavy_sled_push'],
      regressions: ['lighter_sled_push'],
      thumbnail: 'https://images.unsplash.com/photo-1627483297886-49710ae1fc22?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand facing a weighted Prowler sled, gripping upright poles at chest height.',
        'Lean forward at a 45-degree angle, spine straight, core braced.',
        'Drive through your feet, taking powerful steps to push the sled forward.'
      ],
      commonMistakes: ['Rounding the spine', 'Hips shooting too high', 'Looking down at feet'],
      safetyTips: ['Keep arms locked straight or elbows bent close to chest for spine safety'],
      breathing: 'Forced, rhythmic breathing.',
      estimatedCaloriesPerMinute: 9.0,
      tags: ['Legs', 'Full Body', 'Sled', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 34. Speed Rope
    Exercise(
      exerciseId: 'speed_rope',
      name: 'Speed Rope',
      aliases: ['Speed Rope Jump', 'Fast Skip'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs'],
      exerciseType: 'HIIT',
      trainingStyles: ['HIIT', 'CrossFit', 'Athletic Performance', 'Conditioning'],
      categories: ['Conditioning', 'Compound'],
      equipment: ['Speed Rope'],
      difficulty: 'Intermediate',
      movementPattern: 'Jump',
      goalTags: ['Speed', 'Footwork', 'Conditioning'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Calves', 'Shoulders', 'Core'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['jump_rope', 'boxer_skip'],
      progressions: ['double_under'],
      regressions: ['jumping_jacks'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Hold speed rope handles, elbows tight at your sides.',
        'Jump lightly and rapidly, turning the rope as fast as possible using wrist rotation.'
      ],
      commonMistakes: ['Arms flaring out', 'Flat-footed landing'],
      safetyTips: ['Land softly on balls of feet'],
      breathing: 'Steady, fast breathing.',
      estimatedCaloriesPerMinute: 10.0,
      tags: ['Legs', 'Speed Rope', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 35. Split Jump
    Exercise(
      exerciseId: 'split_jump',
      name: 'Split Jump',
      aliases: ['Jumping Lunge', 'Lunge Jump'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs'],
      exerciseType: 'HIIT',
      trainingStyles: ['HIIT', 'Plyometrics', 'Conditioning'],
      categories: ['Bodyweight', 'HIIT', 'Conditioning', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Lunge',
      goalTags: ['Explosive Power', 'Leg Power', 'Conditioning'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Glutes', 'Quads', 'Hamstrings', 'Calves'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['jumping_jacks', 'frog_jump'],
      progressions: ['weighted_split_jumps'],
      regressions: ['lunges', 'stepping_lunges'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Start in a lunge position, right foot forward, left foot back.',
        'Drop your hips slightly and explode upward into a jump.',
        'Switch your legs in mid-air, landing softly with your left foot forward and right foot back.'
      ],
      commonMistakes: ['Valgus knee (knee caving)', 'Hard landings', 'Not using arms for momentum'],
      safetyTips: ['Absorb landing impact through hips and knees; do not crash knee into floor'],
      breathing: 'Exhale jumping, inhale landing.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Legs', 'Bodyweight', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 36. Sprint
    Exercise(
      exerciseId: 'sprint',
      name: 'Sprint',
      aliases: ['Full Sprint', 'Speed Running'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs', 'Cardiovascular System'],
      exerciseType: 'HIIT',
      trainingStyles: ['Athletic Performance', 'HIIT', 'Sports Performance', 'Conditioning'],
      categories: ['Bodyweight', 'HIIT', 'Conditioning', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Run',
      goalTags: ['Explosive Power', 'Speed', 'Conditioning'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Glutes', 'Hamstrings', 'Quads', 'Calves', 'Core'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Outdoor', 'Gym'],
      injuryFriendly: [],
      alternatives: ['running', 'hill_sprint'],
      progressions: ['hill_sprint'],
      regressions: ['jogging'],
      thumbnail: 'https://images.unsplash.com/photo-1538388149542-5e24932d11a8?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Start in a semi-crouch or standing stance.',
        'Sprint forward at maximum effort (90-100% capacity), pumping arms and driving knees.',
        'Slow down gradually to stop.'
      ],
      commonMistakes: ['Tensing neck and shoulders', 'Overstriding', 'Not warming up'],
      safetyTips: ['Do not sprint without a thorough warm-up'],
      breathing: 'Forced, fast breathing.',
      estimatedCaloriesPerMinute: 12.0,
      tags: ['Legs', 'Bodyweight', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 37. Squat Thrust
    Exercise(
      exerciseId: 'squat_thrust',
      name: 'Squat Thrust',
      aliases: ['Thrusts', 'Bodyweight Squat Thrust'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body'],
      exerciseType: 'HIIT',
      trainingStyles: ['HIIT', 'Calisthenics', 'Conditioning'],
      categories: ['HIIT', 'Conditioning', 'Compound', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Squat/Push',
      goalTags: ['Conditioning', 'Fat Loss', 'Leg Power'],
      isCompound: true,
      primaryMuscles: ['Full Body'],
      secondaryMuscles: ['Core', 'Shoulders', 'Quads', 'Glutes'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['burpee', 'half_burpee'],
      progressions: ['half_burpee', 'burpee'],
      regressions: ['squat_holds', 'plank'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand tall, drop into a squat, and place hands on floor.',
        'Kick feet back to a high plank position.',
        'Immediately jump feet back to hand position, and stand up (do not jump at top).'
      ],
      commonMistakes: ['Hips sagging in plank', 'Standing up with rounded spine'],
      safetyTips: ['Keep core braced to protect spine'],
      breathing: 'Exhale snapping feet back, inhale standing up.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Full Body', 'Bodyweight', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 38. Stair Climber
    Exercise(
      exerciseId: 'stair_climber',
      name: 'Stair Climber',
      aliases: ['Step Mill', 'Stair Master'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs', 'Cardiovascular System'],
      exerciseType: 'LISS',
      trainingStyles: ['General Fitness', 'LISS', 'Conditioning', 'Fat Loss'],
      categories: ['Machine', 'LISS', 'Conditioning'],
      equipment: ['Stair Climber'],
      difficulty: 'Intermediate',
      movementPattern: 'Step',
      goalTags: ['Leg Strength', 'Conditioning', 'Fat Loss'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Quads', 'Hamstrings', 'Glutes', 'Calves'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['stair_running', 'incline_treadmill_walk'],
      progressions: ['high_speed_stairmill'],
      regressions: ['treadmill_walk'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Step onto the machine platform, set speed, and start stepping.',
        'Maintain an upright posture, pushing through your heels.',
        'Avoid leaning on handles.'
      ],
      commonMistakes: ['Hanging on handrails', 'Taking short, shallow steps', 'Slouching forward'],
      safetyTips: ['Use emergency stop button if losing balance'],
      breathing: 'Deep, rhythmic breathing.',
      estimatedCaloriesPerMinute: 9.0,
      tags: ['Legs', 'Machine', 'Intermediate', 'LISS', 'Conditioning', 'Cardio'],
    ),

    // 39. Stair Running
    Exercise(
      exerciseId: 'stair_running',
      name: 'Stair Running',
      aliases: ['Running Up Stairs', 'Stair Sprints'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs', 'Cardiovascular System'],
      exerciseType: 'HIIT',
      trainingStyles: ['Athletic Performance', 'HIIT', 'Conditioning'],
      categories: ['Bodyweight', 'HIIT', 'Conditioning', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Step',
      goalTags: ['Leg Power', 'Conditioning', 'Leg Endurance'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Quads', 'Hamstrings', 'Glutes', 'Calves'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Outdoor', 'Gym'],
      injuryFriendly: [],
      alternatives: ['stair_climber', 'hill_sprint'],
      progressions: ['stair_sprints'],
      regressions: ['stair_walking'],
      thumbnail: 'https://images.unsplash.com/photo-1538388149542-5e24932d11a8?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Find a long set of clear, stable stairs.',
        'Run up the stairs as fast as possible, lifting knees high.',
        'Walk back down slowly to recover.'
      ],
      commonMistakes: ['Looking up instead of at stairs', 'Skipping too many steps and tripping', 'Running down fast'],
      safetyTips: ['Never run down the stairs; walk down carefully', 'Keep eyes focused on steps'],
      breathing: 'Forced breathing.',
      estimatedCaloriesPerMinute: 10.0,
      tags: ['Legs', 'Bodyweight', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 40. Star Jump
    Exercise(
      exerciseId: 'star_jump',
      name: 'Star Jump',
      aliases: ['Air Jack', 'Star Jump Squat'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body'],
      exerciseType: 'HIIT',
      trainingStyles: ['HIIT', 'Plyometrics', 'Conditioning'],
      categories: ['Bodyweight', 'HIIT', 'Conditioning', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Advanced',
      movementPattern: 'Jump',
      goalTags: ['Explosive Power', 'Conditioning'],
      isCompound: true,
      primaryMuscles: ['Full Body'],
      secondaryMuscles: ['Glutes', 'Calves', 'Shoulders', 'Core'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['jumping_jacks', 'seal_jacks'],
      progressions: ['weighted_star_jumps'],
      regressions: ['jumping_jacks'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Start in a half squat position, feet together, hands at chest.',
        'Explode upward into a high jump, extending arms and legs out to sides in a star shape in mid-air.',
        'Snap limbs back together, landing softly in starting squat position.'
      ],
      commonMistakes: ['Landing heavy', 'Not absorbing impact with bent knees', 'Short air time'],
      safetyTips: ['Land softly on balls of feet, transitioning to squat'],
      breathing: 'Exhale leaping, inhale landing.',
      estimatedCaloriesPerMinute: 9.5,
      tags: ['Full Body', 'Bodyweight', 'Advanced', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 41. Stationary Bike
    Exercise(
      exerciseId: 'stationary_bike',
      name: 'Stationary Bike',
      aliases: ['Spin Bike', 'Upright Bike'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs', 'Cardiovascular System'],
      exerciseType: 'LISS',
      trainingStyles: ['General Fitness', 'LISS', 'Rehabilitation', 'Conditioning'],
      categories: ['Machine', 'LISS', 'Conditioning'],
      equipment: ['Stationary Bike'],
      difficulty: 'Beginner',
      movementPattern: 'Pedal',
      goalTags: ['Cardiovascular Health', 'Active Recovery', 'Leg Strength'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Quads', 'Hamstrings', 'Calves', 'Glutes'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: ['Knee Friendly', 'Joint Friendly', 'Lower Back Friendly'],
      alternatives: ['air_bike', 'cycling'],
      progressions: ['incline_spin_bike'],
      regressions: ['recumbent_bike'],
      thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Adjust the seat height so your leg has a slight bend at the bottom of the pedal stroke.',
        'Sit upright, place feet on pedals, and pedal continuously at a set resistance.'
      ],
      commonMistakes: ['Seat too low straining knees', 'Slouching spine'],
      safetyTips: ['Ensure straps on pedals are secure'],
      breathing: 'Steady nasal breathing.',
      estimatedCaloriesPerMinute: 6.5,
      tags: ['Legs', 'Machine', 'Beginner', 'LISS', 'Conditioning', 'Cardio'],
    ),

    // 42. Swimming
    Exercise(
      exerciseId: 'swimming',
      name: 'Swimming',
      aliases: ['Pool Laps', 'Freestyle Swim'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'LISS',
      trainingStyles: ['Sports Performance', 'General Fitness', 'Fat Loss', 'LISS', 'Conditioning'],
      categories: ['LISS', 'Conditioning', 'Compound'],
      equipment: ['Pool'],
      difficulty: 'Intermediate',
      movementPattern: 'Full Body Pull/Push',
      goalTags: ['Cardiovascular Health', 'Low Impact Conditioning', 'Full Body Endurance'],
      isCompound: true,
      primaryMuscles: ['Full Body'],
      secondaryMuscles: ['Shoulders', 'Lats', 'Core', 'Legs'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Full Body',
      environment: ['Pool', 'Outdoor'],
      injuryFriendly: ['Joint Friendly', 'Knee Friendly', 'Lower Back Friendly'],
      alternatives: ['elliptical', 'rowing_machine'],
      progressions: ['fast_swim_laps'],
      regressions: ['pool_walking'],
      thumbnail: 'https://images.unsplash.com/photo-1519315901367-f34ff9154487?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Enter pool and swim laps using freestyle, breaststroke, or backstroke.',
        'Maintain a streamlined body position and constant kick.'
      ],
      commonMistakes: ['Holding breath', 'Poor hip alignment (hips sinking)'],
      safetyTips: ['Do not swim alone', 'Pace yourself correctly'],
      breathing: 'Breathe in rhythm with strokes.',
      estimatedCaloriesPerMinute: 9.0,
      tags: ['Full Body', 'Pool', 'Intermediate', 'LISS', 'Conditioning', 'Cardio'],
    ),

    // 43. Tire Flip
    Exercise(
      exerciseId: 'tire_flip',
      name: 'Tire Flip',
      aliases: ['Heavy Tire Flip'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body'],
      exerciseType: 'HIIT',
      trainingStyles: ['Strongman', 'Functional Fitness', 'HIIT', 'Conditioning'],
      categories: ['Compound', 'Conditioning'],
      equipment: ['Tire'],
      difficulty: 'Advanced',
      movementPattern: 'Hinge/Push',
      goalTags: ['Explosive Power', 'Conditioning', 'Leg Power'],
      isCompound: true,
      primaryMuscles: ['Full Body'],
      secondaryMuscles: ['Glutes', 'Quads', 'Hamstrings', 'Core', 'Shoulders'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['kettlebell_swing', 'sled_push'],
      progressions: ['heavy_tire_flip'],
      regressions: ['sled_push'],
      thumbnail: 'https://images.unsplash.com/photo-1627483297886-49710ae1fc22?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand close to a heavy tire lying flat on the floor.',
        'Hinge at hips, drop hips low, and place hands under tire edge (flat back).',
        'Drive through heels to lift tire explosively, stepping forward and pushing it over.'
      ],
      commonMistakes: ['Rounding back (lifting like biceps curl)', 'Starting with feet too far back'],
      safetyTips: ['Ensure spine is flat during lift', 'Use leg power to push tire over'],
      breathing: 'Exhale lifting, inhale walking to next flip.',
      estimatedCaloriesPerMinute: 9.5,
      tags: ['Full Body', 'Tire', 'Advanced', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 44. Treadmill Run
    Exercise(
      exerciseId: 'treadmill_run',
      name: 'Treadmill Run',
      aliases: ['Treadmill Running'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs', 'Cardiovascular System'],
      exerciseType: 'LISS',
      trainingStyles: ['General Fitness', 'Fat Loss', 'LISS', 'Conditioning'],
      categories: ['Machine', 'LISS', 'Conditioning'],
      equipment: ['Treadmill'],
      difficulty: 'Intermediate',
      movementPattern: 'Run',
      goalTags: ['Endurance', 'Fat Loss', 'Cardiovascular Health'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Calves', 'Hamstrings', 'Quads', 'Glutes'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['running', 'treadmill_walk'],
      progressions: ['incline_treadmill_run'],
      regressions: ['treadmill_walk'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Mount treadmill, clip on safety key, and set running speed (6.0+ mph).',
        'Run with steady stride, upright posture, and landing mid-foot.'
      ],
      commonMistakes: ['Stepping off moving belt', 'Heel striking heavily'],
      safetyTips: ['Always use safety clip', 'Slow belt down gradually'],
      breathing: 'Steady diaphragmatic breathing.',
      estimatedCaloriesPerMinute: 9.5,
      tags: ['Legs', 'Machine', 'Intermediate', 'LISS', 'Conditioning', 'Cardio'],
    ),

    // 45. Treadmill Walk
    Exercise(
      exerciseId: 'treadmill_walk',
      name: 'Treadmill Walk',
      aliases: ['Treadmill Walking'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs', 'Cardiovascular System'],
      exerciseType: 'LISS',
      trainingStyles: ['General Fitness', 'LISS', 'Conditioning'],
      categories: ['Machine', 'LISS', 'Conditioning'],
      equipment: ['Treadmill'],
      difficulty: 'Beginner',
      movementPattern: 'Walk',
      goalTags: ['Active Recovery', 'Cardiovascular Health'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Hamstrings', 'Calves', 'Glutes'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Gym'],
      injuryFriendly: ['Knee Friendly', 'Joint Friendly', 'Beginner Friendly'],
      alternatives: ['walking', 'incline_treadmill_walk'],
      progressions: ['incline_treadmill_walk', 'treadmill_run'],
      regressions: ['walking_slow'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Mount treadmill, set flat angle, and set moderate walking speed (2.0 to 3.0 mph).',
        'Walk with upright spine naturally.'
      ],
      commonMistakes: ['Holding handles', 'Slouching'],
      safetyTips: ['Ensure safety clip is attached'],
      breathing: 'Relaxed deep breathing.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Legs', 'Machine', 'Beginner', 'LISS', 'Conditioning', 'Cardio'],
    ),

    // 46. Tuck Jump
    Exercise(
      exerciseId: 'tuck_jump',
      name: 'Tuck Jump',
      aliases: ['Knee Tuck Jump'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs'],
      exerciseType: 'HIIT',
      trainingStyles: ['Plyometrics', 'HIIT', 'Conditioning'],
      categories: ['Bodyweight', 'HIIT', 'Conditioning', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Jump',
      goalTags: ['Explosive Power', 'Vertical Jump', 'Conditioning'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Core', 'Glutes', 'Calves'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['jumping_jacks', 'frog_jump'],
      progressions: ['weighted_tuck_jumps'],
      regressions: ['squat_jumps'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand with feet hip-width apart, knees slightly bent.',
        'Explode upward into a high jump, pulling your knees up toward your chest.',
        'Land softly on the balls of your feet, immediately absorbing impact.'
      ],
      commonMistakes: ['Landing flat-footed', 'Dropping chest down to knees (knees must come to chest)'],
      safetyTips: ['Ensure high shock-absorption surface', 'Land with bent knees'],
      breathing: 'Exhale leaping, inhale landing.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Legs', 'Bodyweight', 'Intermediate', 'HIIT', 'Conditioning', 'Cardio'],
    ),

    // 47. Walking
    Exercise(
      exerciseId: 'walking',
      name: 'Walking',
      aliases: ['Outdoor Walk', 'Stroll'],
      muscleGroup: 'Cardio',
      targetRegions: ['Legs', 'Cardiovascular System'],
      exerciseType: 'LISS',
      trainingStyles: ['General Fitness', 'LISS', 'Active Recovery'],
      categories: ['Bodyweight', 'LISS'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Walk',
      goalTags: ['Active Recovery', 'Mental Health', 'Cardiovascular Health'],
      isCompound: true,
      primaryMuscles: ['Legs'],
      secondaryMuscles: ['Calves', 'Glutes', 'Hamstrings'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Lower Body',
      environment: ['Outdoor', 'Home', 'Gym', 'Office', 'Travel'],
      injuryFriendly: ['Beginner Friendly', 'Knee Friendly', 'Joint Friendly', 'Lower Back Friendly'],
      alternatives: ['brisk_walking', 'elliptical'],
      progressions: ['brisk_walking'],
      regressions: ['walking_slow'],
      thumbnail: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Walk at a natural, comfortable pace (typically 2.0 to 3.0 mph).',
        'Keep spine upright, gaze forward, and swing arms naturally.'
      ],
      commonMistakes: ['Slouching', 'Looking down continuously'],
      safetyTips: ['Wear comfortable walking shoes'],
      breathing: 'Relaxed, natural breathing.',
      estimatedCaloriesPerMinute: 4.0,
      tags: ['Legs', 'Bodyweight', 'Beginner', 'LISS', 'Active Recovery', 'Cardio'],
    ),
  ];
}
