import '../../models/models.dart';

class CardioExercises {
  static final List<Exercise> exercises = [
    Exercise(
      exerciseId: '5_dot_drills',
      name: '5 Dot Drills',
      aliases: ['5 Dot Drills'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/5_dot_drills.gif',
      videoUrl: '',
      steps: ['Set up properly for 5 Dot Drills with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'assault_air_runner',
      name: 'Assault Air Runner',
      aliases: ['Assault Air Runner'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/assault_air_runner.gif',
      videoUrl: '',
      steps: ['Set up properly for Assault Air Runner with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'assault_airbike',
      name: 'Assault Airbike',
      aliases: ['Assault Airbike'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/assault_airbike.gif',
      videoUrl: '',
      steps: ['Set up properly for Assault Airbike with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'band_assisted_sprinter_run',
      name: 'Band Assisted Sprinter Run',
      aliases: ['Band Assisted Sprinter Run'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Resistance Band'],
      difficulty: 'Beginner',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/band_assisted_sprinter_run.gif',
      videoUrl: '',
      steps: ['Set up properly for Band Assisted Sprinter Run with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Beginner', 'Legs', 'Resistance Band', 'Full Body', 'Cardio', 'Core'],
    ),
    Exercise(
      exerciseId: 'battle_rope',
      name: 'Battle Rope',
      aliases: ['Battle Rope'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/battle_rope.gif',
      videoUrl: '',
      steps: ['Set up properly for Battle Rope with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'bike',
      name: 'Bike',
      aliases: ['Bike'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/bike.gif',
      videoUrl: '',
      steps: ['Set up properly for Bike with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'boxer_shuffle_cardio',
      name: 'Boxer Shuffle Cardio',
      aliases: ['Boxer Shuffle Cardio'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/boxer_shuffle_cardio.gif',
      videoUrl: '',
      steps: ['Set up properly for Boxer Shuffle Cardio with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'briskly_walking',
      name: 'Briskly Walking',
      aliases: ['Briskly Walking'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/briskly_walking.gif',
      videoUrl: '',
      steps: ['Set up properly for Briskly Walking with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Beginner', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core'],
    ),
    Exercise(
      exerciseId: 'burpees',
      name: 'Burpees',
      aliases: ['Burpees'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/burpees.gif',
      videoUrl: '',
      steps: ['Set up properly for Burpees with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'butt_kicks',
      name: 'Butt Kicks',
      aliases: ['Butt Kicks'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/butt_kicks.gif',
      videoUrl: '',
      steps: ['Set up properly for Butt Kicks with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'depth_jump_to_hurdle_hop',
      name: 'Depth Jump To Hurdle Hop',
      aliases: ['Depth Jump To Hurdle Hop'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/depth_jump_to_hurdle_hop.gif',
      videoUrl: '',
      steps: ['Set up properly for Depth Jump To Hurdle Hop with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'dumbbell_burpees',
      name: 'Dumbbell Burpees',
      aliases: ['Dumbbell Burpees'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Dumbbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/dumbbell_burpees.gif',
      videoUrl: '',
      steps: ['Set up properly for Dumbbell Burpees with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Dumbbell', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'elliptical_machine',
      name: 'Elliptical Machine',
      aliases: ['Elliptical Machine'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Machine'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/elliptical_machine.gif',
      videoUrl: '',
      steps: ['Set up properly for Elliptical Machine with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Machine', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'fast_feet_run',
      name: 'Fast Feet Run',
      aliases: ['Fast Feet Run'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/fast_feet_run.gif',
      videoUrl: '',
      steps: ['Set up properly for Fast Feet Run with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'hands_bike',
      name: 'Hands Bike',
      aliases: ['Hands Bike'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/hands_bike.gif',
      videoUrl: '',
      steps: ['Set up properly for Hands Bike with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'high_knee_run',
      name: 'High Knee Run',
      aliases: ['High Knee Run'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/high_knee_run.gif',
      videoUrl: '',
      steps: ['Set up properly for High Knee Run with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Beginner', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core'],
    ),
    Exercise(
      exerciseId: 'high_knee_skips',
      name: 'High Knee Skips',
      aliases: ['High Knee Skips'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/high_knee_skips.gif',
      videoUrl: '',
      steps: ['Set up properly for High Knee Skips with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Beginner', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core'],
    ),
    Exercise(
      exerciseId: 'high_knees_lift_run',
      name: 'High Knees Lift Run',
      aliases: ['High Knees Lift Run'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/high_knees_lift_run.gif',
      videoUrl: '',
      steps: ['Set up properly for High Knees Lift Run with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Beginner', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core'],
    ),
    Exercise(
      exerciseId: 'incline_treadmill',
      name: 'Incline Treadmill',
      aliases: ['Incline Treadmill'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/incline_treadmill.gif',
      videoUrl: '',
      steps: ['Set up properly for Incline Treadmill with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'jack_burpee',
      name: 'Jack Burpee',
      aliases: ['Jack Burpee'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/jack_burpee.gif',
      videoUrl: '',
      steps: ['Set up properly for Jack Burpee with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'jump_rope',
      name: 'Jump Rope',
      aliases: ['Jump Rope'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/jump_rope.gif',
      videoUrl: '',
      steps: ['Set up properly for Jump Rope with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'jumping_jack',
      name: 'Jumping Jack',
      aliases: ['Jumping Jack'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/jumping_jack.gif',
      videoUrl: '',
      steps: ['Set up properly for Jumping Jack with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'navy_seal_burpee',
      name: 'Navy Seal Burpee',
      aliases: ['Navy Seal Burpee'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/navy_seal_burpee.gif',
      videoUrl: '',
      steps: ['Set up properly for Navy Seal Burpee with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'plyo_jacks',
      name: 'Plyo Jacks',
      aliases: ['Plyo Jacks'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/plyo_jacks.gif',
      videoUrl: '',
      steps: ['Set up properly for Plyo Jacks with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'power_lunge',
      name: 'Power Lunge',
      aliases: ['Power Lunge'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/power_lunge.gif',
      videoUrl: '',
      steps: ['Set up properly for Power Lunge with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'power_skips',
      name: 'Power Skips',
      aliases: ['Power Skips'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/power_skips.gif',
      videoUrl: '',
      steps: ['Set up properly for Power Skips with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'recumbent_exercise_bike',
      name: 'Recumbent Exercise Bike',
      aliases: ['Recumbent Exercise Bike'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/recumbent_exercise_bike.gif',
      videoUrl: '',
      steps: ['Set up properly for Recumbent Exercise Bike with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'riding_outdoor_bicycle',
      name: 'Riding Outdoor Bicycle',
      aliases: ['Riding Outdoor Bicycle'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/riding_outdoor_bicycle.gif',
      videoUrl: '',
      steps: ['Set up properly for Riding Outdoor Bicycle with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'rowing_machine',
      name: 'Rowing Machine',
      aliases: ['Rowing Machine'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Machine'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/rowing_machine.gif',
      videoUrl: '',
      steps: ['Set up properly for Rowing Machine with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Machine', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'run_in_place',
      name: 'Run In Place',
      aliases: ['Run In Place'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/run_in_place.gif',
      videoUrl: '',
      steps: ['Set up properly for Run In Place with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'running',
      name: 'Running',
      aliases: ['Running'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/running.gif',
      videoUrl: '',
      steps: ['Set up properly for Running with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'shadow_boxing',
      name: 'Shadow Boxing',
      aliases: ['Shadow Boxing'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/shadow_boxing.gif',
      videoUrl: '',
      steps: ['Set up properly for Shadow Boxing with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'short_stride_run',
      name: 'Short Stride Run',
      aliases: ['Short Stride Run'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/short_stride_run.gif',
      videoUrl: '',
      steps: ['Set up properly for Short Stride Run with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'split_jacks',
      name: 'Split Jacks',
      aliases: ['Split Jacks'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/split_jacks.gif',
      videoUrl: '',
      steps: ['Set up properly for Split Jacks with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'sprint',
      name: 'Sprint',
      aliases: ['Sprint'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/sprint.gif',
      videoUrl: '',
      steps: ['Set up properly for Sprint with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'stair_climber_machine',
      name: 'Stair Climber Machine',
      aliases: ['Stair Climber Machine'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Machine'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/stair_climber_machine.gif',
      videoUrl: '',
      steps: ['Set up properly for Stair Climber Machine with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Machine', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'stationary_bike_run',
      name: 'Stationary Bike Run',
      aliases: ['Stationary Bike Run'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/stationary_bike_run.gif',
      videoUrl: '',
      steps: ['Set up properly for Stationary Bike Run with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'swimming',
      name: 'Swimming',
      aliases: ['Swimming'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/swimming.gif',
      videoUrl: '',
      steps: ['Set up properly for Swimming with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'tire_flip',
      name: 'Tire Flip',
      aliases: ['Tire Flip'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/tire_flip.gif',
      videoUrl: '',
      steps: ['Set up properly for Tire Flip with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'treadmill',
      name: 'Treadmill',
      aliases: ['Treadmill'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/treadmill.gif',
      videoUrl: '',
      steps: ['Set up properly for Treadmill with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'tuck_jump',
      name: 'Tuck Jump',
      aliases: ['Tuck Jump'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/tuck_jump.gif',
      videoUrl: '',
      steps: ['Set up properly for Tuck Jump with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    ),
    Exercise(
      exerciseId: 'walking',
      name: 'Walking',
      aliases: ['Walking'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/walking.gif',
      videoUrl: '',
      steps: ['Set up properly for Walking with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Beginner', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core'],
    ),
    Exercise(
      exerciseId: 'wheel_run',
      name: 'Wheel Run',
      aliases: ['Wheel Run'],
      muscleGroup: 'Cardio',
      targetRegions: ['Full Body', 'Cardiovascular System'],
      exerciseType: 'Cardio',
      trainingStyles: ['Cardio', 'Fat Loss', 'HIIT'],
      categories: ['Cardio', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Compound Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: true,
      primaryMuscles: ['Full Body', 'Cardiovascular System'],
      secondaryMuscles: ['Legs', 'Core'],
      mechanics: 'Compound',
      forceType: 'Pull',
      bodyRegion: 'Cardio',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/wheel_run.gif',
      videoUrl: '',
      steps: ['Set up properly for Wheel Run with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Cardiovascular System', 'Legs', 'Bodyweight', 'Full Body', 'Cardio', 'Core', 'Intermediate'],
    )
  ];
}
