import '../../models/models.dart';

class ChestExercises {
  static final List<Exercise> exercises = [
    // 1. Archer Push Ups
    Exercise(
      exerciseId: 'archer_push_ups',
      name: 'Archer Push Ups',
      aliases: ['Archer Pushups'],
      muscleGroup: 'Chest',
      targetRegions: ['Middle Chest', 'Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Athletic Performance'],
      categories: ['Calisthenics', 'Strength', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Advanced',
      movementPattern: 'Push',
      goalTags: ['Strength', 'Muscle Gain', 'Core Stability'],
      isCompound: true,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Shoulders', 'Core'],
      mechanics: 'Unilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['push_ups', 'ring_push_ups'],
      progressions: ['one_arm_push_ups'],
      regressions: ['push_ups', 'assisted_archer_push_ups'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/archer_push_ups.gif',
      videoUrl: '',
      steps: [
        'Get into a pushup position but with your hands placed much wider than normal, fingers pointing outward.',
        'Lower yourself to one side, keeping that arm close to your body while extending the opposite arm straight out.',
        'Push yourself back up to the center using the bent arm.',
        'Repeat on the opposite side to complete one rep.'
      ],
      commonMistakes: ['Bending the extended arm', 'Twisting the hips'],
      safetyTips: ['Ensure shoulder joints are thoroughly warmed up', 'Control the tempo of descent'],
      breathing: 'Inhale while descending to one side, exhale as you push up.',
      estimatedCaloriesPerMinute: 7.2,
      tags: ['Middle Chest', 'Upper Chest', 'Bodyweight', 'Advanced', 'Compound', 'Calisthenics', 'Push', 'Upper Body'],
    ),

    // 2. Assisted Dip
    Exercise(
      exerciseId: 'assisted_dip',
      name: 'Assisted Dip',
      aliases: ['Machine Assisted Dip', 'Band Assisted Dip'],
      muscleGroup: 'Chest',
      targetRegions: ['Lower Chest', 'Middle Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Bodybuilding'],
      categories: ['Compound', 'Machine'],
      equipment: ['Assisted Pull-Up Machine', 'Resistance Band'],
      difficulty: 'Beginner',
      movementPattern: 'Push',
      goalTags: ['Strength', 'Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Lower Chest', 'Triceps'],
      secondaryMuscles: ['Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['dips', 'chest_press_machine'],
      progressions: ['dips'],
      regressions: ['bench_dips'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/assisted_dip.gif',
      videoUrl: '',
      steps: [
        'Set weight assistance on machine and place knees/feet on pad.',
        'Grip parallel handles, keep elbows slightly flared for chest (tucked for triceps).',
        'Lower your body by bending elbows, then press back up to starting lockout.'
      ],
      commonMistakes: ['Shrugging shoulders', 'Lowering too deep'],
      safetyTips: ['Avoid sudden movements'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Lower Chest', 'Middle Chest', 'Machine', 'Beginner', 'Compound', 'Push', 'Upper Body'],
    ),

    // 3. Bench Press
    Exercise(
      exerciseId: 'bench_press',
      name: 'Bench Press',
      aliases: ['Flat Bench Press', 'Barbell Bench Press'],
      muscleGroup: 'Chest',
      targetRegions: ['Middle Chest', 'Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Powerlifting', 'Strength Training', 'General Fitness'],
      categories: ['Strength', 'Powerlifting', 'Compound'],
      equipment: ['Barbell', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      goalTags: ['Muscle Gain', 'Strength'],
      isCompound: true,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['incline_db_press', 'chest_press_machine', 'push_ups'],
      progressions: ['push_ups', 'dumbbell_bench_press', 'bench_press'],
      regressions: ['chest_press_machine', 'incline_push_ups'],
      thumbnail: 'https://images.unsplash.com/photo-1534368786749-b63e05c4a4fb?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/bench_press.gif',
      videoUrl: '',
      steps: [
        'Lie flat on the bench, feet flat on the floor. Grip the barbell slightly wider than shoulder-width.',
        'Unrack the bar and hold it directly over your chest with elbows locked.',
        'Lower the bar slowly to your mid-chest while keeping your elbows at a 45-degree angle.',
        'Push the bar back up powerfully to the starting position, extending your arms fully.'
      ],
      commonMistakes: ['Bouncing the bar off chest', 'Flaring elbows too wide', 'Lifting hips off the bench'],
      safetyTips: ['Use a spotter', 'Keep feet flat on floor', 'Do not lock elbows aggressively at top'],
      breathing: 'Inhale while lowering the bar. Exhale while pressing.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Middle Chest', 'Upper Chest', 'Barbell', 'Intermediate', 'Compound', 'Strength', 'Push', 'Upper Body'],
    ),

    // 4. Cable Fly
    Exercise(
      exerciseId: 'cable_fly',
      name: 'Cable Fly',
      aliases: ['Cable Chest Fly'],
      muscleGroup: 'Chest',
      targetRegions: ['Inner Chest', 'Middle Chest'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Bodybuilding', 'General Fitness', 'Isolation'],
      equipment: ['Cable'],
      difficulty: 'Intermediate',
      movementPattern: 'Fly',
      goalTags: ['Muscle Gain', 'Posture'],
      isCompound: false,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Safe'],
      alternatives: ['pec_deck', 'dumbbell_fly'],
      progressions: ['weighted_cable_fly'],
      regressions: ['pec_deck', 'resistance_band_fly'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/cable_fly.gif',
      videoUrl: '',
      steps: [
        'Set the pulleys of a cable crossover machine to shoulder height.',
        'Hold the handles, step forward to create tension, and lean slightly forward.',
        'Bring your hands forward in a wide hugging motion, meeting in the center.',
        'Slowly release back, keeping a slight bend in your elbows.'
      ],
      commonMistakes: ['Pressing the weight instead of flying', 'Overstretching at start position'],
      safetyTips: ['Step forward with one foot for stance stability', 'Maintain slight bend in elbows'],
      breathing: 'Exhale while squeezing, inhale while returning.',
      estimatedCaloriesPerMinute: 6.2,
      tags: ['Inner Chest', 'Middle Chest', 'Cable', 'Intermediate', 'Isolation', 'Bodybuilding', 'Push', 'Upper Body'],
    ),

    // 5. Chest Dip
    Exercise(
      exerciseId: 'chest_dip',
      name: 'Chest Dip',
      aliases: ['Dips', 'Parallel Bar Chest Dips'],
      muscleGroup: 'Chest',
      targetRegions: ['Lower Chest', 'Middle Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Bodybuilding', 'CrossFit'],
      categories: ['Calisthenics', 'Strength', 'Compound'],
      equipment: ['Dip Station'],
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      goalTags: ['Strength', 'Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Lower Chest', 'Triceps'],
      secondaryMuscles: ['Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: ['Lower Back Safe'],
      alternatives: ['bench_press', 'push_ups', 'close_grip_bench_press'],
      progressions: ['weighted_dips', 'ring_dips'],
      regressions: ['bench_dips', 'band_assisted_dips'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/chest_dip.gif',
      videoUrl: '',
      steps: [
        'Hoist yourself up on parallel bars, arms fully locked out.',
        'Lean your torso slightly forward to target the chest (keep upright for triceps).',
        'Lower your body by bending your elbows until your shoulders are below your elbows.',
        'Push back up to the starting locked position.'
      ],
      commonMistakes: ['Going too deep too fast', 'Not leaning forward (targets triceps instead)', 'Kipping or using momentum'],
      safetyTips: ['Do not shrug or drop into shoulders', 'Control down-motion fully'],
      breathing: 'Inhale on the way down, exhale as you drive up.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Lower Chest', 'Middle Chest', 'Bodyweight', 'Intermediate', 'Compound', 'Calisthenics', 'Push', 'Upper Body'],
    ),

    // 6. Chest Press Machine
    Exercise(
      exerciseId: 'chest_press_machine',
      name: 'Chest Press Machine',
      aliases: ['Machine Chest Press'],
      muscleGroup: 'Chest',
      targetRegions: ['Middle Chest', 'Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'General Fitness', 'Rehabilitation'],
      categories: ['Bodybuilding', 'General Fitness', 'Compound'],
      equipment: ['Machine'],
      difficulty: 'Beginner',
      movementPattern: 'Push',
      goalTags: ['Muscle Gain', 'Injury Prevention'],
      isCompound: true,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Shoulders'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Shoulder Friendly', 'Wrist Friendly'],
      alternatives: ['bench_press', 'pec_deck'],
      progressions: ['bench_press', 'incline_db_press'],
      regressions: ['push_ups', 'chest_press_machine_light'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/chest_press_machine.gif',
      videoUrl: '',
      steps: [
        'Adjust the seat height so the handles align with your mid-chest level.',
        'Sit back flat against the pad, feet firmly on the ground.',
        'Push the handles away from you, fully extending your arms without locking the elbows.',
        'Slowly bring the handles back toward your chest.'
      ],
      commonMistakes: ['Arching the lower back off the pad', 'Locking elbows too hard at top'],
      safetyTips: ['Keep head and shoulders flat against support pad', 'Ensure settings fit range safely'],
      breathing: 'Inhale returning, exhale pushing.',
      estimatedCaloriesPerMinute: 6.8,
      tags: ['Middle Chest', 'Upper Chest', 'Machine', 'Beginner', 'Compound', 'Bodybuilding', 'Push', 'Upper Body'],
    ),

    // 7. Clap Push Up
    Exercise(
      exerciseId: 'clap_push_up',
      name: 'Clap Push Up',
      aliases: ['Clapping Pushup', 'Plyo Push Up'],
      muscleGroup: 'Chest',
      targetRegions: ['Middle Chest', 'Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Plyometrics', 'Calisthenics', 'Athletic Performance'],
      categories: ['Calisthenics', 'HIIT', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Advanced',
      movementPattern: 'Push',
      goalTags: ['Explosive Power', 'Strength'],
      isCompound: true,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Shoulders', 'Core'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['plyometric_push_up', 'push_ups'],
      progressions: ['one_arm_push_up'],
      regressions: ['push_ups'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/clap_push_up.gif',
      videoUrl: '',
      steps: [
        'Start in standard push-up plank.',
        'Lower chest to floor, then push up explosively so your hands leave the floor.',
        'Clap hands together in mid-air, then land softly with bent elbows to absorb impact.'
      ],
      commonMistakes: ['Landing with locked elbows', 'Sagging hips'],
      safetyTips: ['Only perform on supportive surfaces', 'Warm up wrists thoroughly'],
      breathing: 'Inhale down, exhale exploding up.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Middle Chest', 'Upper Chest', 'Bodyweight', 'Advanced', 'Compound', 'Calisthenics', 'Push', 'Upper Body'],
    ),

    // 8. Close Grip Bench Press
    Exercise(
      exerciseId: 'close_grip_bench_press',
      name: 'Close Grip Bench Press',
      aliases: ['Close-Grip Bench Press'],
      muscleGroup: 'Chest',
      targetRegions: ['Inner Chest', 'Middle Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Powerlifting', 'Bodybuilding', 'Strength Training'],
      categories: ['Powerlifting', 'Bodybuilding', 'Compound'],
      equipment: ['Barbell', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      goalTags: ['Strength', 'Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Triceps', 'Inner Chest'],
      secondaryMuscles: ['Chest', 'Shoulders'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['bench_press', 'tricep_pushdowns'],
      progressions: ['weighted_dips', 'close_grip_paused_bench'],
      regressions: ['tricep_pushdowns', 'push_ups'],
      thumbnail: 'https://images.unsplash.com/photo-1534368786749-b63e05c4a4fb?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/close_grip_bench_press.gif',
      videoUrl: '',
      steps: [
        'Lie on a flat bench and grip the bar with a narrow grip (shoulder-width or narrower).',
        'Lower the bar slowly to your lower chest, keeping your elbows tucked close to your torso.',
        'Press the bar straight back up, focusing on pushing with your triceps.'
      ],
      commonMistakes: ['Placing hands too close (causes wrist strain)', 'Flaring elbows outward'],
      safetyTips: ['Keep grip about 8-12 inches apart', 'Maintain wrist alignment'],
      breathing: 'Inhale lowering, exhale pressing.',
      estimatedCaloriesPerMinute: 8.2,
      tags: ['Inner Chest', 'Middle Chest', 'Barbell', 'Intermediate', 'Compound', 'Powerlifting', 'Push', 'Upper Body'],
    ),

    // 9. Decline Bench Press
    Exercise(
      exerciseId: 'decline_bench_press',
      name: 'Decline Bench Press',
      aliases: ['Decline Barbell Bench Press'],
      muscleGroup: 'Chest',
      targetRegions: ['Lower Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Powerlifting', 'Strength Training'],
      categories: ['Strength', 'Compound'],
      equipment: ['Barbell', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      goalTags: ['Muscle Gain', 'Strength'],
      isCompound: true,
      primaryMuscles: ['Lower Chest'],
      secondaryMuscles: ['Triceps', 'Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['bench_press', 'chest_dip'],
      progressions: ['heavy_decline_press'],
      regressions: ['decline_dumbbell_press'],
      thumbnail: 'https://images.unsplash.com/photo-1534368786749-b63e05c4a4fb?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/decline_bench_press.gif',
      videoUrl: '',
      steps: [
        'Secure your legs at the end of a decline bench and lie back flat.',
        'Unrack the barbell, lower it to your lower chest, then press it back to lockout.'
      ],
      commonMistakes: ['Bouncing bar off chest', 'Wrong landing point (too high)'],
      safetyTips: ['Always use safety pins or a spotter on decline'],
      breathing: 'Inhale lowering, exhale pressing.',
      estimatedCaloriesPerMinute: 8.2,
      tags: ['Lower Chest', 'Barbell', 'Intermediate', 'Compound', 'Push', 'Upper Body'],
    ),

    // 10. Decline Chest Press Machine
    Exercise(
      exerciseId: 'decline_chest_press_machine',
      name: 'Decline Chest Press Machine',
      aliases: ['Machine Decline Press'],
      muscleGroup: 'Chest',
      targetRegions: ['Lower Chest'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Machine', 'Compound'],
      equipment: ['Machine'],
      difficulty: 'Beginner',
      movementPattern: 'Push',
      goalTags: ['Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Lower Chest'],
      secondaryMuscles: ['Triceps', 'Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['decline_bench_press', 'chest_dip'],
      progressions: ['decline_bench_press'],
      regressions: ['assisted_dip'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/decline_chest_press_machine.gif',
      videoUrl: '',
      steps: [
        'Adjust machine seat so handles align with lower chest.',
        'Sit back flat and press handles forward to lockout.',
        'Slowly return to start.'
      ],
      commonMistakes: ['Shrugging shoulders', 'Glutes lifting off pad'],
      safetyTips: ['Keep head and back fully supported'],
      breathing: 'Exhale pressing, inhale returning.',
      estimatedCaloriesPerMinute: 6.5,
      tags: ['Lower Chest', 'Machine', 'Beginner', 'Compound', 'Push', 'Upper Body'],
    ),

    // 11. Decline Dumbbell Fly
    Exercise(
      exerciseId: 'decline_dumbbell_fly',
      name: 'Decline Dumbbell Fly',
      aliases: ['Decline DB Fly'],
      muscleGroup: 'Chest',
      targetRegions: ['Lower Chest', 'Inner Chest'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Dumbbell', 'Bench', 'Isolation'],
      equipment: ['Dumbbell', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Fly',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Lower Chest'],
      secondaryMuscles: ['Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['decline_dumbbell_press', 'pec_deck'],
      progressions: ['cable_fly'],
      regressions: ['decline_dumbbell_fly_light'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/decline_dumbbell_fly.gif',
      videoUrl: '',
      steps: [
        'Lie on a decline bench with dumbbells held above lower chest.',
        'Lower weights in a wide arc outward, keeping elbows slightly bent.',
        'Squeeze lower chest to return to center.'
      ],
      commonMistakes: ['Bending elbows too much', 'Clashing weights at top'],
      safetyTips: ['Ensure feet are locked securely'],
      breathing: 'Inhale lowering, exhale squeezing up.',
      estimatedCaloriesPerMinute: 5.8,
      tags: ['Lower Chest', 'Inner Chest', 'Dumbbell', 'Intermediate', 'Isolation', 'Push', 'Upper Body'],
    ),

    // 12. Decline Dumbbell Press
    Exercise(
      exerciseId: 'decline_dumbbell_press',
      name: 'Decline Dumbbell Press',
      aliases: ['Decline DB Press'],
      muscleGroup: 'Chest',
      targetRegions: ['Lower Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Strength Training'],
      categories: ['Dumbbell', 'Bench', 'Compound'],
      equipment: ['Dumbbell', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      goalTags: ['Muscle Gain', 'Strength'],
      isCompound: true,
      primaryMuscles: ['Lower Chest'],
      secondaryMuscles: ['Triceps', 'Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['decline_bench_press', 'chest_dip'],
      progressions: ['decline_bench_press'],
      regressions: ['chest_press_machine'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/decline_dumbbell_press.gif',
      videoUrl: '',
      steps: [
        'Secure feet at end of decline bench and lie back with dumbbells.',
        'Hold dumbbells at lower chest level, elbows at 45 degrees.',
        'Press weights straight up to lockout, then lower under control.'
      ],
      commonMistakes: ['Drifting weights over face', 'Bouncing off chest'],
      safetyTips: ['Ensure feet are properly secured'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 7.5,
      tags: ['Lower Chest', 'Dumbbell', 'Intermediate', 'Compound', 'Push', 'Upper Body'],
    ),

    // 13. Decline Push Ups
    Exercise(
      exerciseId: 'decline_push_ups',
      name: 'Decline Push Ups',
      aliases: ['Decline Push-ups'],
      muscleGroup: 'Chest',
      targetRegions: ['Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'General Fitness'],
      categories: ['Calisthenics', 'Strength', 'Compound'],
      equipment: ['Bodyweight', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      goalTags: ['Muscle Gain', 'Strength'],
      isCompound: true,
      primaryMuscles: ['Upper Chest'],
      secondaryMuscles: ['Shoulders', 'Triceps', 'Core'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: ['Lower Back Safe'],
      alternatives: ['push_ups', 'dips'],
      progressions: ['archer_push_ups', 'ring_push_ups'],
      regressions: ['push_ups'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/decline_push_ups.gif',
      videoUrl: '',
      steps: [
        'Place your feet on an elevated surface like a bench or step, and hands on the floor in front of you.',
        'Maintain a straight body plank, elbows extended.',
        'Lower your chest slowly toward the floor.',
        'Push back up to the starting position.'
      ],
      commonMistakes: ['Arching the lower back', 'Looking straight down or craning the neck'],
      safetyTips: ['Ensure the foot elevation surface is stable', 'Lock core alignment throughout'],
      breathing: 'Inhale lowering, exhale pressing up.',
      estimatedCaloriesPerMinute: 6.5,
      tags: ['Upper Chest', 'Bodyweight', 'Intermediate', 'Compound', 'Calisthenics', 'Push', 'Upper Body'],
    ),

    // 14. Decline Smith Machine Press
    Exercise(
      exerciseId: 'decline_smith_machine_press',
      name: 'Decline Smith Machine Press',
      aliases: ['Smith Machine Decline Press'],
      muscleGroup: 'Chest',
      targetRegions: ['Lower Chest'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Machine', 'Compound'],
      equipment: ['Smith Machine', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      goalTags: ['Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Lower Chest'],
      secondaryMuscles: ['Triceps', 'Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['decline_bench_press', 'decline_chest_press_machine'],
      progressions: ['decline_bench_press'],
      regressions: ['assisted_dip'],
      thumbnail: 'https://images.unsplash.com/photo-1534368786749-b63e05c4a4fb?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/decline_smith_machine_press.gif',
      videoUrl: '',
      steps: [
        'Set decline bench inside Smith machine and align bar to lower chest.',
        'Lie back, unlock the bar, lower it slowly to your lower chest, and press back to lockout.'
      ],
      commonMistakes: ['Misaligned bench position', 'Flaring elbows too wide'],
      safetyTips: ['Set the safety stops correctly on the Smith machine track'],
      breathing: 'Inhale lowering, exhale pressing.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Lower Chest', 'Machine', 'Intermediate', 'Compound', 'Push', 'Upper Body'],
    ),

    // 15. Diamond Push Up
    Exercise(
      exerciseId: 'diamond_push_up',
      name: 'Diamond Push Up',
      aliases: ['Close Grip Pushup', 'Diamond Pushup'],
      muscleGroup: 'Chest',
      targetRegions: ['Inner Chest', 'Middle Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'General Fitness'],
      categories: ['Calisthenics', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      goalTags: ['Strength', 'Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Triceps', 'Inner Chest'],
      secondaryMuscles: ['Chest', 'Shoulders', 'Core'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['push_ups', 'close_grip_bench_press'],
      progressions: ['weighted_diamond_push_up'],
      regressions: ['knee_diamond_push_up', 'incline_diamond_push_up'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/diamond_push_up.gif',
      videoUrl: '',
      steps: [
        'Set up in a push-up plank, placing hands close together under your chest so thumbs and index fingers form a diamond shape.',
        'Lower your chest to meet your hands, keeping elbows close to your sides.',
        'Press back up to starting plank position.'
      ],
      commonMistakes: ['Flaring elbows out', 'Hips sagging', 'Placing hands too high (straining shoulders)'],
      safetyTips: ['If wrist discomfort occurs, turn hands slightly out'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 6.8,
      tags: ['Inner Chest', 'Middle Chest', 'Bodyweight', 'Intermediate', 'Compound', 'Calisthenics', 'Push', 'Upper Body'],
    ),

    // 16. Dumbbell Bench Press
    Exercise(
      exerciseId: 'dumbbell_bench_press',
      name: 'Dumbbell Bench Press',
      aliases: ['Flat Dumbbell Press', 'DB Bench Press'],
      muscleGroup: 'Chest',
      targetRegions: ['Middle Chest', 'Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Strength Training', 'General Fitness'],
      categories: ['Dumbbell', 'Bench', 'Compound'],
      equipment: ['Dumbbell', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      goalTags: ['Muscle Gain', 'Strength', 'Muscle Balance'],
      isCompound: true,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['bench_press', 'incline_db_press', 'chest_press_machine'],
      progressions: ['heavy_dumbbell_bench_press'],
      regressions: ['chest_press_machine', 'floor_press'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/dumbbell_bench_press.gif',
      videoUrl: '',
      steps: [
        'Lie flat on a bench, holding dumbbells at chest height, palms facing forward.',
        'Press the weights straight up over your chest to lockout, then lower them slowly back down.'
      ],
      commonMistakes: ['Clashing weights at top', 'Dropping elbows below bench level too far'],
      safetyTips: ['Keep feet flat on floor', 'Brace core'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Middle Chest', 'Upper Chest', 'Dumbbell', 'Intermediate', 'Compound', 'Push', 'Upper Body'],
    ),

    // 17. Dumbbell Fly
    Exercise(
      exerciseId: 'dumbbell_fly',
      name: 'Dumbbell Fly',
      aliases: ['Dumbbell Chest Fly', 'DB Fly'],
      muscleGroup: 'Chest',
      targetRegions: ['Inner Chest', 'Middle Chest'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Bodybuilding', 'General Fitness', 'Isolation'],
      equipment: ['Dumbbell', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Fly',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: ['Lower Back Safe'],
      alternatives: ['pec_deck', 'cable_fly'],
      progressions: ['cable_fly'],
      regressions: ['resistance_band_fly', 'floor_db_fly'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/dumbbell_fly.gif',
      videoUrl: '',
      steps: [
        'Lie on a flat bench with a dumbbell in each hand, arms extended above your chest.',
        'Lower the weights out to the sides in a wide arc, keeping a slight bend in your elbows.',
        'Squeeze your chest muscles to bring the dumbbells back to the starting position.'
      ],
      commonMistakes: ['Bending elbows too much (turns into a press)', 'Lowering weights below bench level'],
      safetyTips: ['Keep elbows slightly bent to protect joint integrity', 'Select conservative weights'],
      breathing: 'Inhale opening up, exhale closing to center.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Inner Chest', 'Middle Chest', 'Dumbbell', 'Intermediate', 'Isolation', 'Bodybuilding', 'Push', 'Upper Body'],
    ),

    // 18. Dumbbell Pullover
    Exercise(
      exerciseId: 'dumbbell_pullover',
      name: 'Dumbbell Pullover',
      aliases: ['Chest Pullover', 'DB Pullover'],
      muscleGroup: 'Chest',
      targetRegions: ['Serratus Anterior', 'Lower Chest'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Dumbbell', 'Bench', 'Isolation'],
      equipment: ['Dumbbell', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Fly',
      goalTags: ['Muscle Gain', 'Chest Expansion'],
      isCompound: false,
      primaryMuscles: ['Chest', 'Serratus Anterior'],
      secondaryMuscles: ['Lats', 'Triceps'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['straight_arm_dumbbell_pullover', 'cable_pullover'],
      progressions: ['heavy_dumbbell_pullover'],
      regressions: ['resistance_band_pullover'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/dumbbell_pullover.gif',
      videoUrl: '',
      steps: [
        'Lie flat across a bench, supporting upper back, feet flat on floor.',
        'Hold dumbbell in both hands (diamond grip) straight above your chest.',
        'Slowly lower weight backward in an arc behind your head, then pull back to vertical.'
      ],
      commonMistakes: ['Bending elbows too much', 'Arching lower back off bench'],
      safetyTips: ['Ensure firm grip on dumbbell'],
      breathing: 'Inhale lowering, exhale pulling up.',
      estimatedCaloriesPerMinute: 5.8,
      tags: ['Serratus Anterior', 'Lower Chest', 'Dumbbell', 'Intermediate', 'Isolation', 'Upper Body'],
    ),

    // 19. Floor Press
    Exercise(
      exerciseId: 'floor_press',
      name: 'Floor Press',
      aliases: ['Barbell Floor Press', 'Dumbbell Floor Press'],
      muscleGroup: 'Chest',
      targetRegions: ['Middle Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Powerlifting', 'Strength Training'],
      categories: ['Strength', 'Compound'],
      equipment: ['Barbell', 'Dumbbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      goalTags: ['Strength', 'Lockout Power'],
      isCompound: true,
      primaryMuscles: ['Chest', 'Triceps'],
      secondaryMuscles: ['Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['bench_press', 'close_grip_bench_press'],
      progressions: ['bench_press'],
      regressions: ['push_ups'],
      thumbnail: 'https://images.unsplash.com/photo-1534368786749-b63e05c4a4fb?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/floor_press.gif',
      videoUrl: '',
      steps: [
        'Lie flat on the floor with knees bent (feet flat).',
        'Unrack or hold weights at chest, and press straight up to lockout.',
        'Lower until your triceps touch the floor flatly (do not slam), pause, and press back up.'
      ],
      commonMistakes: ['Bouncing elbows off floor', 'Lifting hips'],
      safetyTips: ['Ensure triceps rest fully before next press'],
      breathing: 'Inhale lowering, exhale pressing.',
      estimatedCaloriesPerMinute: 7.8,
      tags: ['Middle Chest', 'Barbell', 'Intermediate', 'Compound', 'Push', 'Upper Body'],
    ),

    // 20. High to Low Cable Fly
    Exercise(
      exerciseId: 'high_to_low_cable_fly',
      name: 'High to Low Cable Fly',
      aliases: ['Decline Cable Fly'],
      muscleGroup: 'Chest',
      targetRegions: ['Lower Chest', 'Inner Chest'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable'],
      difficulty: 'Intermediate',
      movementPattern: 'Fly',
      goalTags: ['Muscle Gain', 'Lower Chest Development'],
      isCompound: false,
      primaryMuscles: ['Lower Chest'],
      secondaryMuscles: ['Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['cable_fly', 'decline_dumbbell_fly'],
      progressions: ['heavy_high_to_low_cable_fly'],
      regressions: ['pec_deck'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Set pulley cables high (above head height).',
        'Hold handles, step forward, and lean slightly forward.',
        'Sweep hands down and together in front of your hips, squeezing lower chest.'
      ],
      commonMistakes: ['Bending elbows (pressing)', 'Shrugging shoulders'],
      safetyTips: ['Keep stance stable'],
      breathing: 'Exhale down, inhale returning up.',
      estimatedCaloriesPerMinute: 6.2,
      tags: ['Lower Chest', 'Inner Chest', 'Cable', 'Intermediate', 'Isolation', 'Push', 'Upper Body'],
    ),

    // 21. Hindu Push Up
    Exercise(
      exerciseId: 'hindu_push_up',
      name: 'Hindu Push Up',
      aliases: ['Dand', 'Judo Push Up'],
      muscleGroup: 'Chest',
      targetRegions: ['Middle Chest', 'Lower Chest', 'Shoulders'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Functional Fitness', 'Yoga'],
      categories: ['Calisthenics', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      goalTags: ['Strength', 'Shoulder Mobility', 'Flexibility'],
      isCompound: true,
      primaryMuscles: ['Chest', 'Shoulders'],
      secondaryMuscles: ['Triceps', 'Core', 'Lower Back'],
      mechanics: 'Compound',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['push_ups', 'plyometric_push_up'],
      progressions: ['one_arm_push_up'],
      regressions: ['push_ups', 'knee_push_up'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/hindu_push_up.gif',
      videoUrl: '',
      steps: [
        'Start in downward dog position (hips high in V-shape).',
        'Lower your body by bending elbows and swooping chest forward and down toward hands.',
        'Press your chest upward into upward dog stance, arching back slightly.',
        'Push hips back to V-shape start.'
      ],
      commonMistakes: ['Rounding back heavily', 'Rushing swoop phase'],
      safetyTips: ['Perform slowly to protect shoulders and spine'],
      breathing: 'Inhale swooping forward, exhale pushing back to V.',
      estimatedCaloriesPerMinute: 7.8,
      tags: ['Middle Chest', 'Lower Chest', 'Bodyweight', 'Intermediate', 'Compound', 'Calisthenics', 'Push', 'Upper Body'],
    ),

    // 22. Incline Barbell Bench Press
    Exercise(
      exerciseId: 'incline_barbell_bench_press',
      name: 'Incline Barbell Bench Press',
      aliases: ['Incline Bench Press', 'Incline Barbell Press'],
      muscleGroup: 'Chest',
      targetRegions: ['Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Powerlifting', 'Strength Training'],
      categories: ['Barbell', 'Bench', 'Compound'],
      equipment: ['Barbell', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      goalTags: ['Muscle Gain', 'Strength', 'Upper Chest Mass'],
      isCompound: true,
      primaryMuscles: ['Upper Chest'],
      secondaryMuscles: ['Triceps', 'Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['incline_db_press', 'bench_press'],
      progressions: ['heavy_incline_press'],
      regressions: ['incline_machine_press'],
      thumbnail: 'https://images.unsplash.com/photo-1534368786749-b63e05c4a4fb?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/incline_barbell_bench_press.gif',
      videoUrl: '',
      steps: [
        'Lie on bench inclined at 30-45 degrees, grip barbell wider than shoulder-width.',
        'Unrack bar, lower it slowly to upper chest, then press back to lockout.'
      ],
      commonMistakes: ['Bench too steep (loads front delts)', 'Bouncing bar off upper chest'],
      safetyTips: ['Maintain foot plant', 'Use a spotter'],
      breathing: 'Inhale lowering, exhale pressing.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Upper Chest', 'Barbell', 'Intermediate', 'Compound', 'Push', 'Upper Body'],
    ),

    // 23. Incline Chest Press Machine
    Exercise(
      exerciseId: 'incline_chest_press_machine',
      name: 'Incline Chest Press Machine',
      aliases: ['Incline Machine Chest Press'],
      muscleGroup: 'Chest',
      targetRegions: ['Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Machine', 'Compound'],
      equipment: ['Machine'],
      difficulty: 'Beginner',
      movementPattern: 'Push',
      goalTags: ['Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Upper Chest'],
      secondaryMuscles: ['Triceps', 'Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['incline_db_press', 'incline_machine_press'],
      progressions: ['incline_db_press'],
      regressions: ['incline_push_up'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/incline_chest_press_machine.gif',
      videoUrl: '',
      steps: [
        'Adjust machine seat so handles align with upper chest.',
        'Sit back and press handles upward/forward to lockout.',
        'Slowly return to starting position.'
      ],
      commonMistakes: ['Glutes lifting off seat', 'Locking elbows too hard'],
      safetyTips: ['Keep head and spine supported'],
      breathing: 'Exhale pressing, inhale returning.',
      estimatedCaloriesPerMinute: 6.8,
      tags: ['Upper Chest', 'Machine', 'Beginner', 'Compound', 'Push', 'Upper Body'],
    ),

    // 24. Incline Dumbbell Press
    Exercise(
      exerciseId: 'incline_db_press',
      name: 'Incline Dumbbell Press',
      aliases: ['Incline DB Press'],
      muscleGroup: 'Chest',
      targetRegions: ['Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'General Fitness', 'Strength Training'],
      categories: ['Strength', 'Bodybuilding', 'Compound'],
      equipment: ['Dumbbell', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      goalTags: ['Muscle Gain', 'Strength'],
      isCompound: true,
      primaryMuscles: ['Upper Chest'],
      secondaryMuscles: ['Front Delts', 'Triceps'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['bench_press', 'chest_press_machine', 'dumbbell_fly'],
      progressions: ['dumbbell_bench_press', 'incline_db_press'],
      regressions: ['machine_chest_press', 'incline_push_ups'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/incline_db_press.gif',
      videoUrl: '',
      steps: [
        'Set an incline bench to around 30 to 45 degrees. Sit with a dumbbell in each hand on your thighs.',
        'Lie back, bringing the weights to shoulder level with elbows bent at 90 degrees.',
        'Press the dumbbells straight up over your upper chest, locking your elbows at the top.',
        'Lower the weights slowly under control back to the sides of your chest.'
      ],
      commonMistakes: ['Setting the bench angle too steep', 'Clashing dumbbells at the top', 'Dropping weights too fast'],
      safetyTips: ['Keep your feet flat on the floor', 'Avoid over-extending at the bottom of the movement'],
      breathing: 'Inhale on the way down, exhale as you press.',
      estimatedCaloriesPerMinute: 7.8,
      tags: ['Upper Chest', 'Dumbbell', 'Intermediate', 'Compound', 'Strength', 'Push', 'Upper Body'],
    ),

    // 25. Incline Dumbbell Fly
    Exercise(
      exerciseId: 'incline_dumbbell_fly',
      name: 'Incline Dumbbell Fly',
      aliases: ['Incline DB Fly'],
      muscleGroup: 'Chest',
      targetRegions: ['Upper Chest', 'Inner Chest'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Dumbbell', 'Bench', 'Isolation'],
      equipment: ['Dumbbell', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Fly',
      goalTags: ['Muscle Gain', 'Upper Chest Width'],
      isCompound: false,
      primaryMuscles: ['Upper Chest'],
      secondaryMuscles: ['Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['incline_db_press', 'cable_fly'],
      progressions: ['incline_cable_fly'],
      regressions: ['pec_deck'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/incline_dumbbell_fly.gif',
      videoUrl: '',
      steps: [
        'Lie on a 30-45 degree incline bench holding dumbbells overhead.',
        'Lower weights out to sides in wide arc, keeping elbows bent slightly.',
        'Squeeze upper chest to return to top.'
      ],
      commonMistakes: ['Elbows bending too much', 'Bench angle too steep'],
      safetyTips: ['Control the bottom stretch phase carefully'],
      breathing: 'Inhale lowering, exhale squeezing.',
      estimatedCaloriesPerMinute: 5.8,
      tags: ['Upper Chest', 'Inner Chest', 'Dumbbell', 'Intermediate', 'Isolation', 'Push', 'Upper Body'],
    ),

    // 26. Incline Machine Press
    Exercise(
      exerciseId: 'incline_machine_press',
      name: 'Incline Machine Press',
      aliases: ['Leverage Incline Press'],
      muscleGroup: 'Chest',
      targetRegions: ['Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding'],
      categories: ['Machine', 'Compound'],
      equipment: ['Machine'],
      difficulty: 'Beginner',
      movementPattern: 'Push',
      goalTags: ['Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Upper Chest'],
      secondaryMuscles: ['Triceps', 'Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['incline_chest_press_machine', 'incline_db_press'],
      progressions: ['incline_barbell_bench_press'],
      regressions: ['incline_push_up'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/incline_machine_press.gif',
      videoUrl: '',
      steps: [
        'Sit and adjust seat on incline press machine.',
        'Push handles forward/upward, and slowly return to start.'
      ],
      commonMistakes: ['Glutes lifting off pad', 'Incorrect seat alignment'],
      safetyTips: ['Avoid locking elbows aggressively'],
      breathing: 'Exhale pressing, inhale returning.',
      estimatedCaloriesPerMinute: 6.8,
      tags: ['Upper Chest', 'Machine', 'Beginner', 'Compound', 'Push', 'Upper Body'],
    ),

    // 27. Incline Push Up
    Exercise(
      exerciseId: 'incline_push_up',
      name: 'Incline Push Up',
      aliases: ['Incline Push-ups'],
      muscleGroup: 'Chest',
      targetRegions: ['Lower Chest', 'Middle Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Calisthenics'],
      categories: ['Calisthenics', 'Compound'],
      equipment: ['Bench', 'Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Push',
      goalTags: ['Endurance', 'Conditioning'],
      isCompound: true,
      primaryMuscles: ['Lower Chest'],
      secondaryMuscles: ['Triceps', 'Shoulders', 'Core'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Beginner Friendly', 'Shoulder Friendly'],
      alternatives: ['push_ups', 'knee_push_up'],
      progressions: ['push_ups'],
      regressions: ['wall_push_up'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/incline_push_up.gif',
      videoUrl: '',
      steps: [
        'Place hands on a bench or elevated step slightly wider than shoulder-width, and extend feet back on floor.',
        'Keep body straight, lower chest to bench, and press back to lockout.'
      ],
      commonMistakes: ['Sagging hips', 'Head dropping'],
      safetyTips: ['Ensure bench is highly stable'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Lower Chest', 'Middle Chest', 'Bodyweight', 'Beginner', 'Compound', 'Calisthenics', 'Push', 'Upper Body'],
    ),

    // 28. Incline Smith Machine Press
    Exercise(
      exerciseId: 'incline_smith_machine_press',
      name: 'Incline Smith Machine Press',
      aliases: ['Smith Machine Incline Press'],
      muscleGroup: 'Chest',
      targetRegions: ['Upper Chest'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Machine', 'Compound'],
      equipment: ['Smith Machine', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      goalTags: ['Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Upper Chest'],
      secondaryMuscles: ['Triceps', 'Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['incline_barbell_bench_press', 'incline_chest_press_machine'],
      progressions: ['incline_barbell_bench_press'],
      regressions: ['incline_machine_press'],
      thumbnail: 'https://images.unsplash.com/photo-1534368786749-b63e05c4a4fb?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/incline_smith_machine_press.gif',
      videoUrl: '',
      steps: [
        'Position an incline bench inside the Smith machine.',
        'Align bar path to land on upper chest.',
        'Unlock bar, lower slowly to upper chest, and press up to lockout.'
      ],
      commonMistakes: ['Elbows flaring 90 degrees out', 'Improper bench placement'],
      safetyTips: ['Set safety stop clips on Smith columns'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Upper Chest', 'Machine', 'Intermediate', 'Compound', 'Push', 'Upper Body'],
    ),

    // 29. Knee Push Up
    Exercise(
      exerciseId: 'knee_push_up',
      name: 'Knee Push Up',
      aliases: ['Modified Pushup', 'Knee Pushups'],
      muscleGroup: 'Chest',
      targetRegions: ['Middle Chest', 'Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Calisthenics'],
      categories: ['Calisthenics', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Push',
      goalTags: ['Endurance', 'Conditioning'],
      isCompound: true,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Shoulders', 'Core'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Beginner Friendly', 'Shoulder Friendly'],
      alternatives: ['incline_push_up', 'wall_push_up'],
      progressions: ['push_ups'],
      regressions: ['wall_push_up'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/knee_push_up.gif',
      videoUrl: '',
      steps: [
        'Get on hands and knees, hands slightly wider than shoulders.',
        'Lower chest to floor, keeping body straight from head to knees.',
        'Press back up to starting position.'
      ],
      commonMistakes: ['Bending at hips (keeping glutes high)', 'Elbows flaring too wide'],
      safetyTips: ['Use a mat under knees for comfort'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Middle Chest', 'Upper Chest', 'Bodyweight', 'Beginner', 'Compound', 'Calisthenics', 'Push', 'Upper Body'],
    ),

    // 30. Low to High Cable Fly
    Exercise(
      exerciseId: 'low_to_high_cable_fly',
      name: 'Low to High Cable Fly',
      aliases: ['Incline Cable Fly'],
      muscleGroup: 'Chest',
      targetRegions: ['Upper Chest', 'Inner Chest'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable'],
      difficulty: 'Intermediate',
      movementPattern: 'Fly',
      goalTags: ['Muscle Gain', 'Upper Chest Development'],
      isCompound: false,
      primaryMuscles: ['Upper Chest'],
      secondaryMuscles: ['Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['incline_dumbbell_fly', 'cable_fly'],
      progressions: ['heavy_low_to_high_cable_fly'],
      regressions: ['pec_deck'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Set pulleys to lowest position.',
        'Hold handles, step forward, and sweep hands forward and upward in front of your face/upper chest.'
      ],
      commonMistakes: ['Bending elbows (pressing)', 'Using too much momentum'],
      safetyTips: ['Maintain stable stance'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 6.2,
      tags: ['Upper Chest', 'Inner Chest', 'Cable', 'Intermediate', 'Isolation', 'Push', 'Upper Body'],
    ),

    // 31. One Arm Push Up
    Exercise(
      exerciseId: 'one_arm_push_up',
      name: 'One Arm Push Up',
      aliases: ['Single Arm Pushup'],
      muscleGroup: 'Chest',
      targetRegions: ['Middle Chest', 'Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Advanced Strength'],
      categories: ['Calisthenics', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Advanced',
      movementPattern: 'Push',
      goalTags: ['Strength', 'Core Stability'],
      isCompound: true,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Shoulders', 'Core'],
      mechanics: 'Unilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['archer_push_ups', 'plyometric_push_up'],
      progressions: ['weighted_one_arm_push_up'],
      regressions: ['archer_push_ups', 'push_ups'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/one_arm_push_up.gif',
      videoUrl: '',
      steps: [
        'Set up in push-up plank, feet very wide apart.',
        'Place one hand behind your back, and lower your chest to floor using the supporting arm.',
        'Press back up to lockout under control.'
      ],
      commonMistakes: ['Hips twisting excessively', 'Rounding spine'],
      safetyTips: ['Keep core extremely tight', 'Avoid placing excessive strain on shoulder joint'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 9.0,
      tags: ['Middle Chest', 'Upper Chest', 'Bodyweight', 'Advanced', 'Compound', 'Calisthenics', 'Push', 'Upper Body'],
    ),

    // 32. Paused Bench Press
    Exercise(
      exerciseId: 'paused_bench_press',
      name: 'Paused Bench Press',
      aliases: ['Paused Barbell Bench Press'],
      muscleGroup: 'Chest',
      targetRegions: ['Middle Chest', 'Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Powerlifting', 'Strength Training'],
      categories: ['Powerlifting', 'Strength Training', 'Compound'],
      equipment: ['Barbell', 'Bench'],
      difficulty: 'Advanced',
      movementPattern: 'Push',
      goalTags: ['Strength', 'Explosive Power'],
      isCompound: true,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Shoulders'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['bench_press', 'spoto_press'],
      progressions: ['spoto_press'],
      regressions: ['bench_press'],
      thumbnail: 'https://images.unsplash.com/photo-1534368786749-b63e05c4a4fb?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Setup identically to a standard Bench Press.',
        'Lower the barbell to your chest under strict control.',
        'Pause the bar on your chest for a full 1 to 2 seconds (completely motionless).',
        'Press upward explosively to lockout.'
      ],
      commonMistakes: ['Resting bar too heavily on ribs (losing muscle tension)', 'Bouncing off chest anyway'],
      safetyTips: ['Ensure active spotter presence', 'Maintain full body tension during the pause'],
      breathing: 'Inhale lowering, hold pause, exhale aggressively on push.',
      estimatedCaloriesPerMinute: 8.8,
      tags: ['Middle Chest', 'Upper Chest', 'Barbell', 'Advanced', 'Compound', 'Powerlifting', 'Push', 'Upper Body'],
    ),

    // 33. Pec Deck
    Exercise(
      exerciseId: 'pec_deck',
      name: 'Pec Deck',
      aliases: ['Pec Deck Fly', 'Machine Fly'],
      muscleGroup: 'Chest',
      targetRegions: ['Inner Chest', 'Middle Chest'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Bodybuilding', 'General Fitness', 'Isolation'],
      equipment: ['Machine'],
      difficulty: 'Beginner',
      movementPattern: 'Fly',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Shoulder Friendly', 'Lower Back Safe'],
      alternatives: ['cable_fly', 'dumbbell_fly'],
      progressions: ['cable_fly', 'dumbbell_fly'],
      regressions: ['pec_deck_light'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/pec_deck.gif',
      videoUrl: '',
      steps: [
        'Sit on the machine with your back flat against the backrest.',
        'Grip the handles, placing your forearms against the padded rollers (if applicable).',
        'Squeeze the pads/handles together in front of your chest under control.',
        'Slowly return to the starting stretched position.'
      ],
      commonMistakes: ['Letting weight stack slam', 'Bending elbows forward out of posture'],
      safetyTips: ['Keep chest up and shoulders back', 'Do not overextend shoulders at the back'],
      breathing: 'Inhale opening up, exhale closing together.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Inner Chest', 'Middle Chest', 'Machine', 'Beginner', 'Isolation', 'Bodybuilding', 'Push', 'Upper Body'],
    ),

    // 34. Plyometric Push Up
    Exercise(
      exerciseId: 'plyometric_push_up',
      name: 'Plyometric Push Up',
      aliases: ['Plyo Pushup', 'Explosive Push Up'],
      muscleGroup: 'Chest',
      targetRegions: ['Middle Chest', 'Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Plyometrics', 'Calisthenics', 'Athletic Performance'],
      categories: ['Calisthenics', 'HIIT', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Advanced',
      movementPattern: 'Push',
      goalTags: ['Explosive Power', 'Strength'],
      isCompound: true,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Shoulders', 'Core'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['clap_push_up', 'push_ups'],
      progressions: ['clap_push_up'],
      regressions: ['push_ups'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/plyometric_push_up.gif',
      videoUrl: '',
      steps: [
        'Lower chest to floor in standard pushup.',
        'Explode upward so your hands lift completely off the ground.',
        'Land softly back into starting position, absorbing impact.'
      ],
      commonMistakes: ['Landing with locked elbows', 'Sagging hips'],
      safetyTips: ['Warm up wrists', 'Perform on soft or matted floor'],
      breathing: 'Inhale down, exhale exploding up.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Middle Chest', 'Upper Chest', 'Bodyweight', 'Advanced', 'Compound', 'Calisthenics', 'Push', 'Upper Body'],
    ),

    // 35. Push Up Plus
    Exercise(
      exerciseId: 'push_up_plus',
      name: 'Push Up Plus',
      aliases: ['Scapular Push Up Plus'],
      muscleGroup: 'Chest',
      targetRegions: ['Serratus Anterior', 'Middle Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Rehabilitation', 'General Fitness'],
      categories: ['Calisthenics', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Push',
      goalTags: ['Shoulder Health', 'Core Stability'],
      isCompound: true,
      primaryMuscles: ['Chest', 'Serratus Anterior'],
      secondaryMuscles: ['Triceps', 'Shoulder Stabilizers', 'Core'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['push_ups', 'scapular_push_up'],
      progressions: ['push_ups'],
      regressions: ['knee_push_up_plus'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/push_up_plus.gif',
      videoUrl: '',
      steps: [
        'Perform standard pushup.',
        'At the top of the pushup (arms locked), push through hands to protract shoulder blades (doming upper back).',
        'Hold plus position for 1 second, then lower back into next rep.'
      ],
      commonMistakes: ['Shrugging shoulders', 'Sagging hips'],
      safetyTips: ['Keep movement slow and focused'],
      breathing: 'Inhale down, exhale up and dome.',
      estimatedCaloriesPerMinute: 6.2,
      tags: ['Serratus Anterior', 'Middle Chest', 'Bodyweight', 'Beginner', 'Compound', 'Push', 'Upper Body'],
    ),

    // 36. Push Ups
    Exercise(
      exerciseId: 'push_ups',
      name: 'Push Ups',
      aliases: ['Push-ups', 'Classic Push Ups'],
      muscleGroup: 'Chest',
      targetRegions: ['Middle Chest', 'Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'CrossFit', 'General Fitness', 'Fat Loss'],
      categories: ['Calisthenics', 'General Fitness', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Push',
      goalTags: ['Endurance', 'Conditioning', 'Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Core', 'Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Office', 'Travel'],
      injuryFriendly: ['Lower Back Safe'],
      alternatives: ['decline_push_ups', 'bench_press', 'dips'],
      progressions: ['decline_push_ups', 'archer_push_ups', 'one_arm_push_ups'],
      regressions: ['incline_push_ups', 'knee_push_ups'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/push_ups.gif',
      videoUrl: '',
      steps: [
        'Place hands on the floor slightly wider than shoulder-width, extend legs back in a plank position.',
        'Keep your body in a straight line from head to heels, core engaged.',
        'Lower your chest toward the floor by bending your elbows back at a 45-degree angle.',
        'Push away from the floor back to the starting plank position.'
      ],
      commonMistakes: ['Sagging lower back', 'Flaring elbows 90 degrees out', 'Incomplete range of motion'],
      safetyTips: ['Keep core actively braced', 'Keep head neutral looking slightly forward'],
      breathing: 'Inhale while lowering, exhale while pushing up.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Middle Chest', 'Upper Chest', 'Bodyweight', 'Beginner', 'Compound', 'General Fitness', 'Push', 'Upper Body'],
    ),

    // 37. Resistance Band Fly
    Exercise(
      exerciseId: 'resistance_band_fly',
      name: 'Resistance Band Fly',
      aliases: ['Band Fly', 'Band Chest Fly'],
      muscleGroup: 'Chest',
      targetRegions: ['Inner Chest', 'Middle Chest'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['General Fitness', 'Calisthenics', 'Travel Fitness'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Resistance Band'],
      difficulty: 'Beginner',
      movementPattern: 'Fly',
      goalTags: ['Muscle Gain', 'Endurance'],
      isCompound: false,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Joint Friendly'],
      alternatives: ['cable_fly', 'dumbbell_fly'],
      progressions: ['cable_fly'],
      regressions: ['lighter_band_fly'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/resistance_band_fly.gif',
      videoUrl: '',
      steps: [
        'Anchor band behind you at shoulder height.',
        'Hold handles, stand facing away, and step forward to create tension.',
        'Perform wide hugging fly motion meeting in front of chest.'
      ],
      commonMistakes: ['Elbows flaring', 'Hunched back'],
      safetyTips: ['Ensure band is securely anchored'],
      breathing: 'Exhale squeezing forward, inhale returning.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Inner Chest', 'Middle Chest', 'Resistance Band', 'Beginner', 'Isolation', 'Push', 'Upper Body'],
    ),

    // 38. Ring Dip
    Exercise(
      exerciseId: 'ring_dip',
      name: 'Ring Dip',
      aliases: ['Gymnastic Ring Dip'],
      muscleGroup: 'Chest',
      targetRegions: ['Lower Chest', 'Middle Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Gymnastics', 'CrossFit'],
      categories: ['Calisthenics', 'Compound'],
      equipment: ['Gymnastic Rings'],
      difficulty: 'Advanced',
      movementPattern: 'Push',
      goalTags: ['Strength', 'Shoulder Stability'],
      isCompound: true,
      primaryMuscles: ['Lower Chest', 'Triceps'],
      secondaryMuscles: ['Front Delts', 'Shoulder Stabilizers', 'Core'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['chest_dip', 'dips'],
      progressions: ['weighted_ring_dip'],
      regressions: ['dips', 'assisted_dip'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/ring_dip.gif',
      videoUrl: '',
      steps: [
        'Support your weight on gymnastic rings with arms locked out straight.',
        'Lower body slowly, leaning forward slightly, until shoulders are below elbows.',
        'Press back to lockout, turning rings slightly out at the top.'
      ],
      commonMistakes: ['Rings drifting away from body', 'Shrugging shoulders'],
      safetyTips: ['Keep rings tight to your sides', 'Ensure shoulder girdle is highly stable'],
      breathing: 'Inhale down, exhale pressing up.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Lower Chest', 'Middle Chest', 'Gymnastic Rings', 'Advanced', 'Compound', 'Push', 'Upper Body'],
    ),

    // 39. Ring Push Ups
    Exercise(
      exerciseId: 'ring_push_ups',
      name: 'Ring Push Ups',
      aliases: ['Gymnastic Ring Pushups'],
      muscleGroup: 'Chest',
      targetRegions: ['Inner Chest', 'Middle Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'CrossFit', 'Athletic Performance'],
      categories: ['Calisthenics', 'Stability', 'Compound'],
      equipment: ['Suspension Trainer (TRX)'],
      difficulty: 'Advanced',
      movementPattern: 'Push',
      goalTags: ['Strength', 'Balance', 'Core Stability'],
      isCompound: true,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Core', 'Shoulder Stabilizers', 'Triceps'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['push_ups', 'dips'],
      progressions: ['archer_push_ups', 'weighted_ring_push_ups'],
      regressions: ['push_ups', 'incline_ring_push_ups'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/ring_push_ups.gif',
      videoUrl: '',
      steps: [
        'Grip gymnastic rings suspended slightly above the floor and extend your feet back into a plank.',
        'Keep your body rigid and slowly lower your chest between the rings.',
        'Turn your hands slightly outward at the bottom for chest stretch.',
        'Push back up, bringing the rings close together at the top.'
      ],
      commonMistakes: ['Allowing rings to drift too far outward', 'Shrugging shoulders upward'],
      safetyTips: ['Start with rings higher off the ground to reduce difficulty if needed', 'Maintain active shoulder stability'],
      breathing: 'Inhale on descent, exhale on execution.',
      estimatedCaloriesPerMinute: 7.0,
      tags: ['Inner Chest', 'Middle Chest', 'Bodyweight', 'Advanced', 'Compound', 'Calisthenics', 'Push', 'Upper Body'],
    ),

    // 40. Single Arm Cable Fly
    Exercise(
      exerciseId: 'single_arm_cable_fly',
      name: 'Single Arm Cable Fly',
      aliases: ['One Arm Cable Fly'],
      muscleGroup: 'Chest',
      targetRegions: ['Inner Chest', 'Middle Chest'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable'],
      difficulty: 'Intermediate',
      movementPattern: 'Fly',
      goalTags: ['Muscle Gain', 'Muscle Balance'],
      isCompound: false,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Front Delts', 'Core'],
      mechanics: 'Unilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['cable_fly', 'pec_deck'],
      progressions: ['heavy_single_arm_cable_fly'],
      regressions: ['cable_fly'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/single_arm_cable_fly.gif',
      videoUrl: '',
      steps: [
        'Stand next to cable crossover machine, holding single pulley handle at shoulder height.',
        'Sweep hand forward across chest in wide arc to center, resisting rotation in torso.',
        'Slowly return to start.'
      ],
      commonMistakes: ['Twisting torso', 'Bending elbow (pressing)'],
      safetyTips: ['Engage core to prevent torso rotation'],
      breathing: 'Exhale forward, inhale returning.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Inner Chest', 'Middle Chest', 'Cable', 'Intermediate', 'Isolation', 'Push', 'Upper Body'],
    ),

    // 41. Smith Machine Bench Press
    Exercise(
      exerciseId: 'smith_machine_bench_press',
      name: 'Smith Machine Bench Press',
      aliases: ['Smith Machine Flat Bench Press'],
      muscleGroup: 'Chest',
      targetRegions: ['Middle Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Strength Training'],
      categories: ['Smith Machine', 'Compound'],
      equipment: ['Smith Machine', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      goalTags: ['Muscle Gain', 'Lockout Power'],
      isCompound: true,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['bench_press', 'dumbbell_bench_press'],
      progressions: ['bench_press'],
      regressions: ['chest_press_machine'],
      thumbnail: 'https://images.unsplash.com/photo-1534368786749-b63e05c4a4fb?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/smith_machine_bench_press.gif',
      videoUrl: '',
      steps: [
        'Set flat bench inside Smith machine.',
        'Unlock bar, lower slowly to chest, then press back to lockout.'
      ],
      commonMistakes: ['Wrong bar path landing point', 'Elbows flared too wide'],
      safetyTips: ['Set safety stop locks correctly'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Middle Chest', 'Machine', 'Intermediate', 'Compound', 'Push', 'Upper Body'],
    ),

    // 42. Spoto Press
    Exercise(
      exerciseId: 'spoto_press',
      name: 'Spoto Press',
      aliases: ['Spoto Bench Press'],
      muscleGroup: 'Chest',
      targetRegions: ['Middle Chest', 'Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Powerlifting', 'Strength Training'],
      categories: ['Powerlifting', 'Strength Training', 'Compound'],
      equipment: ['Barbell', 'Bench'],
      difficulty: 'Advanced',
      movementPattern: 'Push',
      goalTags: ['Strength', 'Explosive Power'],
      isCompound: true,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Shoulders'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['bench_press', 'paused_bench_press'],
      progressions: ['spoto_press_heavy'],
      regressions: ['paused_bench_press', 'bench_press'],
      thumbnail: 'https://images.unsplash.com/photo-1534368786749-b63e05c4a4fb?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Setup like a normal bench press.',
        'Lower the bar to about 1 to 2 inches off your chest and pause.',
        'Hold the bar motionless in the air for 1 to 2 seconds, maintaining maximum tightness.',
        'Press the bar explosively back to the starting locked position.'
      ],
      commonMistakes: ['Allowing the bar to drift or shake', 'Pausing too close/touching chest'],
      safetyTips: ['Keep shoulder blades retracted and stable', 'Use a rack with safety pins'],
      breathing: 'Inhale as bar descends, hold breath during hover-pause, exhale on press.',
      estimatedCaloriesPerMinute: 8.7,
      tags: ['Middle Chest', 'Upper Chest', 'Barbell', 'Advanced', 'Compound', 'Powerlifting', 'Push', 'Upper Body'],
    ),

    // 43. Standing Cable Fly
    Exercise(
      exerciseId: 'standing_cable_fly',
      name: 'Standing Cable Fly',
      aliases: ['Standing Cable Chest Fly'],
      muscleGroup: 'Chest',
      targetRegions: ['Inner Chest', 'Middle Chest'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable'],
      difficulty: 'Intermediate',
      movementPattern: 'Fly',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Front Delts', 'Core'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['cable_fly', 'pec_deck'],
      progressions: ['heavy_standing_cable_fly'],
      regressions: ['cable_fly'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/standing_cable_fly.gif',
      videoUrl: '',
      steps: [
        'Stand tall between pulleys set at shoulder height.',
        'Grip handles, step forward, and perform hugging fly motion, meeting in center.'
      ],
      commonMistakes: ['Torso leaning too far forward (turning it into a decline press)', 'Bending elbows'],
      safetyTips: ['Maintain core stability'],
      breathing: 'Exhale forward, inhale returning.',
      estimatedCaloriesPerMinute: 6.2,
      tags: ['Inner Chest', 'Middle Chest', 'Cable', 'Intermediate', 'Isolation', 'Push', 'Upper Body'],
    ),

    // 44. Weighted Dip
    Exercise(
      exerciseId: 'weighted_dip',
      name: 'Weighted Dip',
      aliases: ['Weighted Parallel Bar Dips'],
      muscleGroup: 'Chest',
      targetRegions: ['Lower Chest', 'Middle Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Strength Training', 'CrossFit'],
      categories: ['Compound', 'Strength'],
      equipment: ['Dip Station', 'Dip Belt'],
      difficulty: 'Advanced',
      movementPattern: 'Push',
      goalTags: ['Strength', 'Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Lower Chest', 'Triceps'],
      secondaryMuscles: ['Front Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['chest_dip', 'bench_press'],
      progressions: ['heavy_weighted_dips'],
      regressions: ['chest_dip'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Secure weight plate around waist using a dip belt.',
        'Hoist yourself up on parallel bars and perform dip under strict control, leaning forward slightly.',
        'Push back up to starting lockout.'
      ],
      commonMistakes: ['Shrugging shoulders', 'Swinging weight plates', 'Dropping too quickly'],
      safetyTips: ['Maintain active shoulder stability', 'Ensure belt is fully secured'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 9.0,
      tags: ['Lower Chest', 'Middle Chest', 'Dip Belt', 'Advanced', 'Compound', 'Push', 'Upper Body'],
    ),

    // 45. Weighted Push Up
    Exercise(
      exerciseId: 'weighted_push_up',
      name: 'Weighted Push Up',
      aliases: ['Weighted Pushups'],
      muscleGroup: 'Chest',
      targetRegions: ['Middle Chest', 'Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Strength Training'],
      categories: ['Calisthenics', 'Compound'],
      equipment: ['Bodyweight', 'Weight Plate'],
      difficulty: 'Advanced',
      movementPattern: 'Push',
      goalTags: ['Strength', 'Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Shoulders', 'Core'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['bench_press', 'push_ups'],
      progressions: ['one_arm_push_up'],
      regressions: ['push_ups'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/weighted_push_up.gif',
      videoUrl: '',
      steps: [
        'Position a weight plate flat on your upper back.',
        'Assume high plank stance, and perform push-up under strict control, keeping body straight.'
      ],
      commonMistakes: ['Plate sliding', 'Sagging hips'],
      safetyTips: ['Have a partner place plate on back safely'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 7.5,
      tags: ['Middle Chest', 'Upper Chest', 'Bodyweight', 'Advanced', 'Compound', 'Calisthenics', 'Push', 'Upper Body'],
    ),

    // 46. Wide Push Up
    Exercise(
      exerciseId: 'wide_push_up',
      name: 'Wide Push Up',
      aliases: ['Wide Grip Pushups'],
      muscleGroup: 'Chest',
      targetRegions: ['Middle Chest', 'Outer Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'General Fitness'],
      categories: ['Calisthenics', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Push',
      goalTags: ['Muscle Gain', 'Endurance'],
      isCompound: true,
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Shoulders', 'Core'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['push_ups', 'incline_push_up'],
      progressions: ['decline_push_ups'],
      regressions: ['knee_push_up', 'incline_push_up'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/wide_push_up.gif',
      videoUrl: '',
      steps: [
        'Get in plank position with hands placed much wider than shoulder-width.',
        'Lower chest slowly toward floor, then press back up to start.'
      ],
      commonMistakes: ['Sagging hips', 'Flaring elbows excessively'],
      safetyTips: ['Keep core tight'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 6.2,
      tags: ['Middle Chest', 'Outer Chest', 'Bodyweight', 'Beginner', 'Compound', 'Calisthenics', 'Push', 'Upper Body'],
    ),
  ];
}
