import '../../models/models.dart';

class ForearmsExercises {
  static final List<Exercise> exercises = [
    // 1. Barbell Finger Curl
    Exercise(
      exerciseId: 'barbell_finger_curl',
      name: 'Barbell Finger Curl',
      aliases: ['Barbell Finger Curls'],
      muscleGroup: 'Forearms',
      targetRegions: ['Wrist Flexors', 'Grip Strength'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'Strength Training'],
      categories: ['Barbell', 'Isolation'],
      equipment: ['Barbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Curl',
      goalTags: ['Forearm Mass', 'Grip Strength'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['finger_curl', 'barbell_wrist_curl'],
      progressions: ['heavy_barbell_finger_curl'],
      regressions: ['dumbbell_wrist_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding a barbell behind your back (or sit on a bench with forearms on thighs, holding bar underhand).',
        'Slowly open your hands, letting the barbell roll down to the tips of your fingers.',
        'Close your hands, curling the bar back into your palms, and flex your wrists slightly at the top.'
      ],
      commonMistakes: ['Using too much weight', 'Losing control of the bar at fingertips'],
      safetyTips: ['Do not drop the bar'],
      breathing: 'Inhale rolling down, exhale curling up.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Wrist Flexors', 'Grip Strength', 'Barbell', 'Intermediate', 'Isolation', 'Forearms'],
    ),

    // 2. Barbell Reverse Wrist Curl
    Exercise(
      exerciseId: 'barbell_reverse_wrist_curl',
      name: 'Barbell Reverse Wrist Curl',
      aliases: ['Barbell Reverse Wrist Curls'],
      muscleGroup: 'Forearms',
      targetRegions: ['Wrist Extensors'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Barbell', 'Isolation'],
      equipment: ['Barbell', 'Bench'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Forearm Mass', 'Wrist Strength'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['dumbbell_reverse_wrist_curl', 'cable_reverse_wrist_curl'],
      progressions: ['heavy_barbell_reverse_wrist_curl'],
      regressions: ['resistance_band_reverse_wrist_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit on a bench, resting your forearms flat on your thighs with wrists hanging over your knees.',
        'Grip a barbell overhand (palms facing down).',
        'Raise the bar by extending your wrists upward as far as possible.',
        'Slowly lower the bar back to starting position.'
      ],
      commonMistakes: ['Lifting forearms off thighs', 'Using thumb grip incorrectly'],
      safetyTips: ['Keep movement slow and controlled to protect wrist joints'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Wrist Extensors', 'Barbell', 'Beginner', 'Isolation', 'Forearms'],
    ),

    // 3. Barbell Wrist Curl
    Exercise(
      exerciseId: 'barbell_wrist_curl',
      name: 'Barbell Wrist Curl',
      aliases: ['Barbell Wrist Curls'],
      muscleGroup: 'Forearms',
      targetRegions: ['Wrist Flexors'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Barbell', 'Isolation'],
      equipment: ['Barbell', 'Bench'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Forearm Mass', 'Wrist Strength'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['dumbbell_wrist_curl', 'cable_wrist_curl'],
      progressions: ['heavy_barbell_wrist_curl'],
      regressions: ['resistance_band_wrist_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit on a bench, resting your forearms flat on your thighs with wrists hanging over knees.',
        'Grip a barbell underhand (palms facing up).',
        'Curl the bar upward by flexing your wrists as far as possible, keeping forearms pinned.',
        'Slowly lower the bar back down.'
      ],
      commonMistakes: ['Lifting elbows or forearms off thighs', 'Using too much momentum'],
      safetyTips: ['Do not let the bar slip out of grip'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Wrist Flexors', 'Barbell', 'Beginner', 'Isolation', 'Forearms'],
    ),

    // 4. Behind the Back Wrist Curl
    Exercise(
      exerciseId: 'behind_the_back_wrist_curl',
      name: 'Behind The Back Wrist Curl',
      aliases: ['Standing Behind Back Wrist Curl'],
      muscleGroup: 'Forearms',
      targetRegions: ['Wrist Flexors'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Barbell', 'Isolation'],
      equipment: ['Barbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Curl',
      goalTags: ['Forearm Mass'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['barbell_wrist_curl', 'cable_wrist_curl'],
      progressions: ['heavy_behind_back_wrist_curl'],
      regressions: ['dumbbell_wrist_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand tall and hold a barbell behind your back with an underhand grip (palms facing away from your body).',
        'Flex your wrists upward to curl the bar, squeezing your forearms at the top.',
        'Slowly lower the bar back to full stretch.'
      ],
      commonMistakes: ['Using shoulder movement', 'Bending elbows'],
      safetyTips: ['Keep posture upright; do not lean forward'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Wrist Flexors', 'Barbell', 'Intermediate', 'Isolation', 'Forearms'],
    ),

    // 5. Cable Reverse Wrist Curl
    Exercise(
      exerciseId: 'cable_reverse_wrist_curl',
      name: 'Cable Reverse Wrist Curl',
      aliases: ['Cable Reverse Wrist Curls'],
      muscleGroup: 'Forearms',
      targetRegions: ['Wrist Extensors'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable', 'Bench'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Forearm Mass', 'Wrist Strength'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['barbell_reverse_wrist_curl', 'dumbbell_reverse_wrist_curl'],
      progressions: ['heavy_cable_reverse_wrist_curl'],
      regressions: ['resistance_band_reverse_wrist_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Place a bench in front of a low cable pulley.',
        'Kneel or sit next to bench, resting forearms on pad with wrists hanging over edge.',
        'Grip straight bar attachment overhand (facing down).',
        'Extend wrists upward to lift the stack, then slowly lower.'
      ],
      commonMistakes: ['Rounding wrists inward', 'Flaring elbows'],
      safetyTips: ['Adjust weight conservatively'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Wrist Extensors', 'Cable', 'Beginner', 'Isolation', 'Forearms'],
    ),

    // 6. Cable Wrist Curl
    Exercise(
      exerciseId: 'cable_wrist_curl',
      name: 'Cable Wrist Curl',
      aliases: ['Cable Wrist Curls'],
      muscleGroup: 'Forearms',
      targetRegions: ['Wrist Flexors'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable', 'Bench'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Forearm Mass', 'Wrist Strength'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['barbell_wrist_curl', 'dumbbell_wrist_curl'],
      progressions: ['heavy_cable_wrist_curl'],
      regressions: ['resistance_band_wrist_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Place a bench in front of a low cable pulley.',
        'Rest forearms flat on bench pad, wrists hanging over edge.',
        'Grip straight bar underhand (facing up).',
        'Curl wrists upward, squeeze, and slowly lower.'
      ],
      commonMistakes: ['Elbows lifting off bench', 'Incomplete range of motion'],
      safetyTips: ['Keep forearm bone pinned flat'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Wrist Flexors', 'Cable', 'Beginner', 'Isolation', 'Forearms'],
    ),

    // 7. Captains of Crush Gripper
    Exercise(
      exerciseId: 'captains_of_crush_gripper',
      name: 'Captains of Crush Gripper',
      aliases: ['Heavy Gripper', 'Hand Gripper'],
      muscleGroup: 'Forearms',
      targetRegions: ['Grip Strength'],
      exerciseType: 'Strength',
      trainingStyles: ['Strength Training', 'Strongman', 'Grip Sport'],
      categories: ['Isolation', 'Functional'],
      equipment: ['Hand Gripper'],
      difficulty: 'Intermediate',
      movementPattern: 'Squeeze',
      goalTags: ['Crush Grip', 'Hand Strength'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: [],
      mechanics: 'Unilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Office', 'Travel'],
      injuryFriendly: [],
      alternatives: ['dead_hang', 'plate_pinch_hold'],
      progressions: ['heavier_gripper_level'],
      regressions: ['lighter_hand_gripper'],
      thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Place one handle of the gripper in the palm of your hand, and wrap fingers around opposite handle.',
        'Squeeze handles together until they touch completely.',
        'Release slowly under control.'
      ],
      commonMistakes: ['Not touching handles at lockout', 'Using opposite hand to close gripper (unless setting)'],
      safetyTips: ['Warm up fingers before heavy gripper attempts'],
      breathing: 'Exhale squeezing, inhale releasing.',
      estimatedCaloriesPerMinute: 3.5,
      tags: ['Grip Strength', 'Hand Gripper', 'Intermediate', 'Isolation', 'Forearms'],
    ),

    // 8. Dead Hang
    Exercise(
      exerciseId: 'dead_hang',
      name: 'Dead Hang',
      aliases: ['Bar Hang', 'Passive Hang'],
      muscleGroup: 'Forearms',
      targetRegions: ['Grip Strength'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'General Fitness', 'Rehabilitation'],
      categories: ['Bodyweight', 'Static Hold'],
      equipment: ['Pull-up Bar'],
      difficulty: 'Beginner',
      movementPattern: 'Passive Hang',
      goalTags: ['Grip Strength', 'Shoulder Decompression', 'Spine Decompression'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: ['Shoulders', 'Lats'],
      mechanics: 'Static',
      forceType: 'Isometric',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['towel_dead_hang', 'thick_bar_hold'],
      progressions: ['single_arm_dead_hang', 'towel_dead_hang'],
      regressions: ['feet_supported_dead_hang'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-a6f9d1f6b1b8?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Grip a pull-up bar with an overhand grip, shoulder-width apart.',
        'Hang freely with straight arms, relaxing your shoulders and spine.',
        'Hold for as long as possible, keeping your grip solid.'
      ],
      commonMistakes: ['Bending elbows', 'Holding breath'],
      safetyTips: ['Wear active chalk if slipping'],
      breathing: 'Maintain slow, deep, diaphragmatic breathing.',
      estimatedCaloriesPerMinute: 4.0,
      tags: ['Grip Strength', 'Pull-up Bar', 'Beginner', 'Static Hold', 'Forearms'],
    ),

    // 9. Dumbbell Pronation
    Exercise(
      exerciseId: 'dumbbell_pronation',
      name: 'Dumbbell Pronation',
      aliases: ['DB Forearm Pronation'],
      muscleGroup: 'Forearms',
      targetRegions: ['Pronator Teres'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'Rehabilitation', 'Arm Wrestling Training'],
      categories: ['Dumbbell', 'Isolation'],
      equipment: ['Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Rotation',
      goalTags: ['Pronation Strength', 'Elbow Stability'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: [],
      mechanics: 'Unilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Travel'],
      injuryFriendly: [],
      alternatives: ['dumbbell_supination', 'lever_bar_rotation'],
      progressions: ['heavy_dumbbell_pronation'],
      regressions: ['light_dumbbell_pronation'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Rest forearm on a bench or thigh, holding dumbbell by one end of handle (off-center grip).',
        'Start with palm facing upward.',
        'Rotate wrist inward (pronating) until palm faces down.',
        'Slowly return to start.'
      ],
      commonMistakes: ['Using shoulder rotation', 'Moving elbow off bench'],
      safetyTips: ['Start light; wrist rotation is delicate'],
      breathing: 'Exhale rotating, inhale returning.',
      estimatedCaloriesPerMinute: 3.5,
      tags: ['Pronator Teres', 'Dumbbell', 'Beginner', 'Isolation', 'Forearms'],
    ),

    // 10. Dumbbell Reverse Wrist Curl
    Exercise(
      exerciseId: 'dumbbell_reverse_wrist_curl',
      name: 'Dumbbell Reverse Wrist Curl',
      aliases: ['DB Reverse Wrist Curls'],
      muscleGroup: 'Forearms',
      targetRegions: ['Wrist Extensors'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Dumbbell', 'Isolation'],
      equipment: ['Dumbbell', 'Bench'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Forearm Mass', 'Wrist Strength'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['barbell_reverse_wrist_curl', 'cable_reverse_wrist_curl'],
      progressions: ['heavy_dumbbell_reverse_wrist_curl'],
      regressions: ['resistance_band_reverse_wrist_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit on a bench holding dumbbells overhand, resting forearms on thighs with wrists hanging over knees.',
        'Extend wrists upward to raise dumbbells, then slowly lower.'
      ],
      commonMistakes: ['Forearms lifting off thighs', 'Using momentum'],
      safetyTips: ['Avoid wrist hyperextension'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Wrist Extensors', 'Dumbbell', 'Beginner', 'Isolation', 'Forearms'],
    ),

    // 11. Dumbbell Supination
    Exercise(
      exerciseId: 'dumbbell_supination',
      name: 'Dumbbell Supination',
      aliases: ['DB Forearm Supination'],
      muscleGroup: 'Forearms',
      targetRegions: ['Supinator'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'Rehabilitation', 'Arm Wrestling Training'],
      categories: ['Dumbbell', 'Isolation'],
      equipment: ['Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Rotation',
      goalTags: ['Supination Strength', 'Bicep Peak Activation'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: ['Biceps'],
      mechanics: 'Unilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Travel'],
      injuryFriendly: [],
      alternatives: ['dumbbell_pronation', 'lever_bar_rotation'],
      progressions: ['heavy_dumbbell_supination'],
      regressions: ['light_dumbbell_supination'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Rest forearm on a bench or thigh, holding dumbbell by one end of handle (off-center grip).',
        'Start with palm facing downward.',
        'Rotate wrist outward (supinating) until palm faces up.',
        'Slowly return to start.'
      ],
      commonMistakes: ['Using shoulder movement', 'Lifting elbow'],
      safetyTips: ['Move in slow, controlled manner'],
      breathing: 'Exhale rotating, inhale returning.',
      estimatedCaloriesPerMinute: 3.5,
      tags: ['Supinator', 'Dumbbell', 'Beginner', 'Isolation', 'Forearms'],
    ),

    // 12. Dumbbell Wrist Curl
    Exercise(
      exerciseId: 'dumbbell_wrist_curl',
      name: 'Dumbbell Wrist Curl',
      aliases: ['DB Wrist Curls'],
      muscleGroup: 'Forearms',
      targetRegions: ['Wrist Flexors'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Dumbbell', 'Isolation'],
      equipment: ['Dumbbell', 'Bench'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Forearm Mass', 'Wrist Strength'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['barbell_wrist_curl', 'cable_wrist_curl'],
      progressions: ['heavy_dumbbell_wrist_curl'],
      regressions: ['resistance_band_wrist_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit on a bench holding dumbbells underhand, resting forearms on thighs with wrists hanging over knees.',
        'Flex wrists upward to curl dumbbells, then slowly lower.'
      ],
      commonMistakes: ['Using biceps to lift', 'Lifting elbows off thighs'],
      safetyTips: ['Maintain neutral, straight wrist line during descent'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Wrist Flexors', 'Dumbbell', 'Beginner', 'Isolation', 'Forearms'],
    ),

    // 13. Finger Curl
    Exercise(
      exerciseId: 'finger_curl',
      name: 'Finger Curl',
      aliases: ['Dumbbell Finger Curls'],
      muscleGroup: 'Forearms',
      targetRegions: ['Grip Strength', 'Wrist Flexors'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'Grip Sport'],
      categories: ['Dumbbell', 'Isolation'],
      equipment: ['Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Grip Strength', 'Forearm Mass'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Travel'],
      injuryFriendly: [],
      alternatives: ['barbell_finger_curl', 'dumbbell_wrist_curl'],
      progressions: ['heavy_finger_curl'],
      regressions: ['light_wrist_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit and rest forearms on thighs, holding dumbbells underhand.',
        'Open hands, letting dumbbells roll down to fingertips.',
        'Curl fingers back to closed palms, and flex wrists slightly.'
      ],
      commonMistakes: ['Dropping weights', 'Rushing reps'],
      safetyTips: ['Ensure firm control at fingertips'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 4.0,
      tags: ['Grip Strength', 'Wrist Flexors', 'Dumbbell', 'Beginner', 'Isolation', 'Forearms'],
    ),

    // 14. Lever Bar Rotation
    Exercise(
      exerciseId: 'lever_bar_rotation',
      name: 'Lever Bar Rotation',
      aliases: ['Leverage Rotation', 'Sledgehammer Pronation/Supination'],
      muscleGroup: 'Forearms',
      targetRegions: ['Pronator Teres', 'Supinator'],
      exerciseType: 'Strength',
      trainingStyles: ['Strength Training', 'Arm Wrestling Training', 'Grip Sport'],
      categories: ['Isolation', 'Functional'],
      equipment: ['Lever Bar', 'Sledgehammer'],
      difficulty: 'Intermediate',
      movementPattern: 'Rotation',
      goalTags: ['Pronation Strength', 'Supination Strength', 'Wrist Stability'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: [],
      mechanics: 'Unilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['dumbbell_pronation', 'dumbbell_supination'],
      progressions: ['heavy_lever_bar_rotation'],
      regressions: ['light_dumbbell_rotation'],
      thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Hold a lever bar or sledgehammer at one end with your elbow bent at 90 degrees at your side.',
        'Slowly rotate the bar to the left (pronation/supination) under control until it is parallel to floor.',
        'Return to upright, then rotate to the right side.'
      ],
      commonMistakes: ['Flaring elbow away from torso', 'Using shoulder to swing'],
      safetyTips: ['Start with grip closer to weighted end to reduce leverage difficulty'],
      breathing: 'Inhale lowering, exhale returning upright.',
      estimatedCaloriesPerMinute: 4.0,
      tags: ['Pronator Teres', 'Supinator', 'Lever Bar', 'Intermediate', 'Isolation', 'Forearms'],
    ),

    // 15. Plate Pinch Hold
    Exercise(
      exerciseId: 'plate_pinch_hold',
      name: 'Plate Pinch Hold',
      aliases: ['Pinch Grip Hold', 'Weight Plate Pinch'],
      muscleGroup: 'Forearms',
      targetRegions: ['Grip Strength'],
      exerciseType: 'Strength',
      trainingStyles: ['Strongman', 'Grip Sport', 'Strength Training'],
      categories: ['Isolation', 'Functional', 'Static Hold'],
      equipment: ['Weight Plate'],
      difficulty: 'Intermediate',
      movementPattern: 'Pinch',
      goalTags: ['Pinch Grip Strength', 'Forearm Mass'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Isometric',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['dead_hang', 'captains_of_crush_gripper'],
      progressions: ['heavy_plate_pinch_hold', 'two_plate_pinch_hold'],
      regressions: ['lighter_plate_pinch_hold'],
      thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand up and pinch two smooth metal plates together (smooth sides facing outward) using only your fingers and thumb.',
        'Lift them off the floor and hold for maximum time.'
      ],
      commonMistakes: ['Resting plates against thighs', 'Curling fingers under plate lip'],
      safetyTips: ['Keep toes clear in case plates drop'],
      breathing: 'Maintain steady diaphragmatic breathing.',
      estimatedCaloriesPerMinute: 4.0,
      tags: ['Grip Strength', 'Weight Plate', 'Intermediate', 'Static Hold', 'Forearms'],
    ),

    // 16. Resistance Band Reverse Wrist Curl
    Exercise(
      exerciseId: 'resistance_band_reverse_wrist_curl',
      name: 'Resistance Band Reverse Wrist Curl',
      aliases: ['Band Reverse Wrist Curl'],
      muscleGroup: 'Forearms',
      targetRegions: ['Wrist Extensors'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['General Fitness', 'Rehabilitation', 'Travel Fitness'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Resistance Band'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Wrist Strength', 'Rehab'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Joint Friendly'],
      alternatives: ['dumbbell_reverse_wrist_curl', 'cable_reverse_wrist_curl'],
      progressions: ['heavy_band_reverse_wrist_curl'],
      regressions: ['lighter_band_reverse_wrist_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Step on resistance band and grip handles/ends overhand.',
        'Rest forearms on thighs, and extend wrists upward against band resistance.'
      ],
      commonMistakes: ['Wrist bending', 'Flaring elbows'],
      safetyTips: ['Secure band tightly under feet'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.0,
      tags: ['Wrist Extensors', 'Resistance Band', 'Beginner', 'Isolation', 'Forearms'],
    ),

    // 17. Resistance Band Wrist Curl
    Exercise(
      exerciseId: 'resistance_band_wrist_curl',
      name: 'Resistance Band Wrist Curl',
      aliases: ['Band Wrist Curl'],
      muscleGroup: 'Forearms',
      targetRegions: ['Wrist Flexors'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['General Fitness', 'Rehabilitation', 'Travel Fitness'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Resistance Band'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Wrist Strength', 'Rehab'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Joint Friendly'],
      alternatives: ['dumbbell_wrist_curl', 'cable_wrist_curl'],
      progressions: ['heavy_band_wrist_curl'],
      regressions: ['lighter_band_wrist_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Step on resistance band and grip handles/ends underhand.',
        'Rest forearms on thighs, and flex wrists upward against band resistance.'
      ],
      commonMistakes: ['Elbows lifting off thighs'],
      safetyTips: ['Check band for tears before use'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.0,
      tags: ['Wrist Flexors', 'Resistance Band', 'Beginner', 'Isolation', 'Forearms'],
    ),

    // 18. Reverse EZ Bar Curl
    Exercise(
      exerciseId: 'reverse_ez_bar_curl',
      name: 'Reverse EZ Bar Curl',
      aliases: ['Reverse EZ Bar Curls'],
      muscleGroup: 'Forearms',
      targetRegions: ['Brachioradialis', 'Brachialis'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'Strength Training'],
      categories: ['Barbell', 'Isolation'],
      equipment: ['EZ Bar'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Forearm Mass', 'Grip Strength'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Brachioradialis'],
      secondaryMuscles: ['Brachialis'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Wrist Friendly'],
      alternatives: ['reverse_barbell_curl', 'reverse_dumbbell_curl'],
      progressions: ['heavy_reverse_ez_bar_curl'],
      regressions: ['resistance_band_reverse_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding an EZ-bar overhand on knurled angled grips.',
        'Keep elbows tucked to sides, and curl bar upward.',
        'Slowly lower to full extension.'
      ],
      commonMistakes: ['Flaring elbows out', 'Wrist bending'],
      safetyTips: ['Keep wrists locked and firm'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 5.2,
      tags: ['Brachioradialis', 'Brachialis', 'EZ Bar', 'Beginner', 'Isolation', 'Forearms'],
    ),

    // 19. Reverse Wrist Curl
    Exercise(
      exerciseId: 'reverse_wrist_curl',
      name: 'Reverse Wrist Curl',
      aliases: ['Reverse Wrist Curls'],
      muscleGroup: 'Forearms',
      targetRegions: ['Wrist Extensors'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Barbell', 'Bench'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Wrist Strength', 'Forearm Mass'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['barbell_reverse_wrist_curl', 'dumbbell_reverse_wrist_curl'],
      progressions: ['barbell_reverse_wrist_curl'],
      regressions: ['resistance_band_reverse_wrist_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit and rest forearms on thighs with wrists hanging over knees overhand.',
        'Extend wrists upward to raise the weight, and slowly lower back down.'
      ],
      commonMistakes: ['Lifting elbows', 'Using too much weight'],
      safetyTips: ['Move strictly in pain-free range'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Wrist Extensors', 'Barbell', 'Beginner', 'Isolation', 'Forearms'],
    ),

    // 20. Seated Wrist Curl
    Exercise(
      exerciseId: 'seated_wrist_curl',
      name: 'Seated Wrist Curl',
      aliases: ['Seated Dumbbell Wrist Curl'],
      muscleGroup: 'Forearms',
      targetRegions: ['Wrist Flexors'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Dumbbell', 'Isolation'],
      equipment: ['Dumbbell', 'Bench'],
      difficulty: 'Beginner',
      movementPattern: 'Curl',
      goalTags: ['Forearm Mass', 'Wrist Strength'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['barbell_wrist_curl', 'cable_wrist_curl'],
      progressions: ['heavy_seated_wrist_curl'],
      regressions: ['resistance_band_wrist_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit on flat bench, rest forearms on thighs, and curl wrists upward underhand.'
      ],
      commonMistakes: ['Lifting elbows off thighs'],
      safetyTips: ['Keep movement slow'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Wrist Flexors', 'Dumbbell', 'Beginner', 'Isolation', 'Forearms'],
    ),

    // 21. Thick Bar Hold
    Exercise(
      exerciseId: 'thick_bar_hold',
      name: 'Thick Bar Hold',
      aliases: ['Axle Bar Hold', 'Fat Grip Hold'],
      muscleGroup: 'Forearms',
      targetRegions: ['Grip Strength'],
      exerciseType: 'Strength',
      trainingStyles: ['Strongman', 'Grip Sport', 'Strength Training'],
      categories: ['Isolation', 'Functional', 'Static Hold'],
      equipment: ['Fat Grips', 'Barbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Squeeze',
      goalTags: ['Grip Strength', 'Forearm Mass'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Isometric',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['dead_hang', 'plate_pinch_hold'],
      progressions: ['heavy_thick_bar_hold'],
      regressions: ['standard_barbell_hold'],
      thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Attach Fat Grips to a barbell (or use an Axle bar) loaded with weight.',
        'Deadlift the bar to standing lockout, and hold for maximum time, squeezing the thick bar tightly.'
      ],
      commonMistakes: ['Not locking hips', 'Allowing wrists to bend backward'],
      safetyTips: ['Keep shins clear of bar during lift'],
      breathing: 'Maintain slow, steady breathing.',
      estimatedCaloriesPerMinute: 4.0,
      tags: ['Grip Strength', 'Fat Grips', 'Intermediate', 'Static Hold', 'Forearms'],
    ),

    // 22. Towel Dead Hang
    Exercise(
      exerciseId: 'towel_dead_hang',
      name: 'Towel Dead Hang',
      aliases: ['Towel Grip Dead Hang'],
      muscleGroup: 'Forearms',
      targetRegions: ['Grip Strength'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Strongman', 'Grip Sport'],
      categories: ['Bodyweight', 'Static Hold', 'Functional'],
      equipment: ['Pull-up Bar', 'Towels'],
      difficulty: 'Advanced',
      movementPattern: 'Passive Hang',
      goalTags: ['Grip Strength', 'Shoulder Stability'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: ['Shoulders', 'Lats'],
      mechanics: 'Bilateral',
      forceType: 'Isometric',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['dead_hang', 'plate_pinch_hold'],
      progressions: ['one_arm_towel_dead_hang'],
      regressions: ['dead_hang'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-a6f9d1f6b1b8?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Drape two towels over a pull-up bar, shoulder-width apart.',
        'Grip the towels firmly near the top/middle.',
        'Hang with straight arms, holding for maximum time.'
      ],
      commonMistakes: ['Grip slipping', 'Bending elbows'],
      safetyTips: ['Ensure towels are heavy-duty and secure'],
      breathing: 'Deep, steady breathing.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Grip Strength', 'Towels', 'Advanced', 'Static Hold', 'Forearms'],
    ),

    // 23. Wrist Roller
    Exercise(
      exerciseId: 'wrist_roller',
      name: 'Wrist Roller',
      aliases: ['Wrist Roller Extension/Flexion'],
      muscleGroup: 'Forearms',
      targetRegions: ['Wrist Flexors', 'Wrist Extensors'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'Strength Training'],
      categories: ['Isolation', 'Functional'],
      equipment: ['Wrist Roller', 'Weight Plate'],
      difficulty: 'Intermediate',
      movementPattern: 'Rotation',
      goalTags: ['Forearm Mass', 'Wrist Endurance'],
      isCompound: false,
      primaryMuscles: ['Forearms'],
      secondaryMuscles: ['Shoulders'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['barbell_wrist_curl', 'barbell_reverse_wrist_curl'],
      progressions: ['heavy_wrist_roller'],
      regressions: ['dumbbell_wrist_curl'],
      thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding a wrist roller in front of you with straight or bent arms, weight suspended at bottom.',
        'Rotate the roller handle forward using alternating wrists to roll the rope and weight all the way to top.',
        'Slowly reverse the rotation to lower the weight back down under control.'
      ],
      commonMistakes: ['Using fast, uncontrolled descent', 'Letting arms sag'],
      safetyTips: ['Hold roller firmly to prevent weight dropping suddenly'],
      breathing: 'Breathe continuously in rhythm with wrist movements.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Wrist Flexors', 'Wrist Extensors', 'Wrist Roller', 'Intermediate', 'Isolation', 'Forearms'],
    ),
  ];
}
