import '../../models/models.dart';

class ForearmsExercises {
  static final List<Exercise> exercises = [
    // 1. Barbell Finger Curl
    Exercise(
      exerciseId: 'barbell_finger_curl',
      name: 'Barbell Finger Curl',
      aliases: ['Barbell Finger Curl'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Barbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/barbell_finger_curl.gif',
      videoUrl: '',
      steps: ['Set up properly for Barbell Finger Curl with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Forearms', 'Wrist Flexors', 'Barbell', 'Grip', 'Intermediate'],
    ),
    // 2. Barbell Reverse Curl
    Exercise(
      exerciseId: 'barbell_reverse_curl',
      name: 'Barbell Reverse Curl',
      aliases: ['Barbell Reverse Curl'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Barbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/barbell_reverse_curl.gif',
      videoUrl: '',
      steps: ['Set up properly for Barbell Reverse Curl with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Forearms', 'Wrist Flexors', 'Barbell', 'Grip', 'Intermediate'],
    ),
    // 3. Barbell Reverse Wrist Curl
    Exercise(
      exerciseId: 'barbell_reverse_wrist_curl',
      name: 'Barbell Reverse Wrist Curl',
      aliases: ['Barbell Reverse Wrist Curl'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Barbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/barbell_reverse_wrist_curl.gif',
      videoUrl: '',
      steps: ['Set up properly for Barbell Reverse Wrist Curl with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Forearms', 'Wrist Flexors', 'Barbell', 'Grip', 'Intermediate'],
    ),
    // 4. Barbell Reverse Wrist Curl Over A Bench
    Exercise(
      exerciseId: 'barbell_reverse_wrist_curl_over_a_bench',
      name: 'Barbell Reverse Wrist Curl Over A Bench',
      aliases: ['Barbell Reverse Wrist Curl Over A Bench'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Barbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/barbell_reverse_wrist_curl_over_a_bench.gif',
      videoUrl: '',
      steps: ['Set up properly for Barbell Reverse Wrist Curl Over A Bench with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Forearms', 'Wrist Flexors', 'Barbell', 'Grip', 'Intermediate'],
    ),
    // 5. Behind The Back Barbell Wrist Curl
    Exercise(
      exerciseId: 'behind_the_back_barbell_wrist_curl',
      name: 'Behind The Back Barbell Wrist Curl',
      aliases: ['Behind The Back Barbell Wrist Curl'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Barbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/behind_the_back_barbell_wrist_curl.gif',
      videoUrl: '',
      steps: ['Set up properly for Behind The Back Barbell Wrist Curl with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Forearms', 'Wrist Flexors', 'Barbell', 'Grip', 'Intermediate'],
    ),
    // 6. Cable One Arm Wrist Curl On Floor
    Exercise(
      exerciseId: 'cable_one_arm_wrist_curl_on_floor',
      name: 'Cable One Arm Wrist Curl On Floor',
      aliases: ['Cable One Arm Wrist Curl On Floor'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Cable'],
      difficulty: 'Advanced',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/cable_one_arm_wrist_curl_on_floor.gif',
      videoUrl: '',
      steps: ['Set up properly for Cable One Arm Wrist Curl On Floor with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Forearms', 'Cable', 'Wrist Flexors', 'Advanced', 'Grip'],
    ),
    // 7. Cable Single Arm Hammer Curl
    Exercise(
      exerciseId: 'cable_single_arm_hammer_curl',
      name: 'Cable Single Arm Hammer Curl',
      aliases: ['Cable Single Arm Hammer Curl'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Cable'],
      difficulty: 'Advanced',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/cable_single_arm_hammer_curl.gif',
      videoUrl: '',
      steps: ['Set up properly for Cable Single Arm Hammer Curl with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Forearms', 'Cable', 'Wrist Flexors', 'Advanced', 'Grip'],
    ),
    // 8. Dumbbell Seated Neutral Wrist Curl
    Exercise(
      exerciseId: 'dumbbell_seated_neutral_wrist_curl',
      name: 'Dumbbell Seated Neutral Wrist Curl',
      aliases: ['Dumbbell Seated Neutral Wrist Curl'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Dumbbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/dumbbell_seated_neutral_wrist_curl.gif',
      videoUrl: '',
      steps: ['Set up properly for Dumbbell Seated Neutral Wrist Curl with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Forearms', 'Wrist Flexors', 'Dumbbell', 'Grip', 'Intermediate'],
    ),
    // 9. Dumbbell Wrist Curl
    Exercise(
      exerciseId: 'dumbbell_wrist_curl',
      name: 'Dumbbell Wrist Curl',
      aliases: ['Dumbbell Wrist Curl'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Dumbbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/dumbbell_wrist_curl.gif',
      videoUrl: '',
      steps: ['Set up properly for Dumbbell Wrist Curl with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Forearms', 'Wrist Flexors', 'Dumbbell', 'Grip', 'Intermediate'],
    ),
    // 10. Hand Gripper
    Exercise(
      exerciseId: 'hand_gripper',
      name: 'Hand Gripper',
      aliases: ['Hand Gripper'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/hand_gripper.gif',
      videoUrl: '',
      steps: ['Set up properly for Hand Gripper with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Bodyweight', 'Forearms', 'Wrist Flexors', 'Grip', 'Intermediate'],
    ),
    // 11. Reverse Wrist Curl
    Exercise(
      exerciseId: 'reverse_wrist_curl',
      name: 'Reverse Wrist Curl',
      aliases: ['Reverse Wrist Curl'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/reverse_wrist_curl.gif',
      videoUrl: '',
      steps: ['Set up properly for Reverse Wrist Curl with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Bodyweight', 'Forearms', 'Wrist Flexors', 'Grip', 'Intermediate'],
    ),
    // 12. Reverse Wrist Stretch
    Exercise(
      exerciseId: 'reverse_wrist_stretch',
      name: 'Reverse Wrist Stretch',
      aliases: ['Reverse Wrist Stretch'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/reverse_wrist_stretch.gif',
      videoUrl: '',
      steps: ['Set up properly for Reverse Wrist Stretch with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Bodyweight', 'Forearms', 'Wrist Flexors', 'Grip', 'Intermediate'],
    ),
    // 13. Seated Barbell Finger Curl
    Exercise(
      exerciseId: 'seated_barbell_finger_curl',
      name: 'Seated Barbell Finger Curl',
      aliases: ['Seated Barbell Finger Curl'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Barbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/seated_barbell_finger_curl.gif',
      videoUrl: '',
      steps: ['Set up properly for Seated Barbell Finger Curl with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Forearms', 'Wrist Flexors', 'Barbell', 'Grip', 'Intermediate'],
    ),
    // 14. Seated Zottman Curl
    Exercise(
      exerciseId: 'seated_zottman_curl',
      name: 'Seated Zottman Curl',
      aliases: ['Seated Zottman Curl'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/seated_zottman_curl.gif',
      videoUrl: '',
      steps: ['Set up properly for Seated Zottman Curl with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Bodyweight', 'Forearms', 'Wrist Flexors', 'Grip', 'Intermediate'],
    ),
    // 15. Weighted Neutral Wrist Curl
    Exercise(
      exerciseId: 'weighted_neutral_wrist_curl',
      name: 'Weighted Neutral Wrist Curl',
      aliases: ['Weighted Neutral Wrist Curl'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/weighted_neutral_wrist_curl.gif',
      videoUrl: '',
      steps: ['Set up properly for Weighted Neutral Wrist Curl with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Bodyweight', 'Forearms', 'Wrist Flexors', 'Grip', 'Intermediate'],
    ),
    // 16. Wrist Circles Stretch
    Exercise(
      exerciseId: 'wrist_circles_stretch',
      name: 'Wrist Circles Stretch',
      aliases: ['Wrist Circles Stretch'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/wrist_circles_stretch.gif',
      videoUrl: '',
      steps: ['Set up properly for Wrist Circles Stretch with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Bodyweight', 'Forearms', 'Wrist Flexors', 'Grip', 'Intermediate'],
    ),
    // 17. Wrist Curl
    Exercise(
      exerciseId: 'wrist_curl',
      name: 'Wrist Curl',
      aliases: ['Wrist Curl'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/wrist_curl.gif',
      videoUrl: '',
      steps: ['Set up properly for Wrist Curl with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Bodyweight', 'Forearms', 'Wrist Flexors', 'Grip', 'Intermediate'],
    ),
    // 18. Wrist Roller
    Exercise(
      exerciseId: 'wrist_roller',
      name: 'Wrist Roller',
      aliases: ['Wrist Roller'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/wrist_roller.gif',
      videoUrl: '',
      steps: ['Set up properly for Wrist Roller with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Bodyweight', 'Forearms', 'Wrist Flexors', 'Grip', 'Intermediate'],
    ),
    // 19. Wrist Rotations
    Exercise(
      exerciseId: 'wrist_rotations',
      name: 'Wrist Rotations',
      aliases: ['Wrist Rotations'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/wrist_rotations.gif',
      videoUrl: '',
      steps: ['Set up properly for Wrist Rotations with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Bodyweight', 'Forearms', 'Wrist Flexors', 'Grip', 'Intermediate'],
    ),
    // 20. Wrist Stretch
    Exercise(
      exerciseId: 'wrist_stretch',
      name: 'Wrist Stretch',
      aliases: ['Wrist Stretch'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/wrist_stretch.gif',
      videoUrl: '',
      steps: ['Set up properly for Wrist Stretch with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Bodyweight', 'Forearms', 'Wrist Flexors', 'Grip', 'Intermediate'],
    ),
    // 21. Wrist Ulnar Deviator And Extensor Stretch
    Exercise(
      exerciseId: 'wrist_ulnar_deviator_and_extensor_stretch',
      name: 'Wrist Ulnar Deviator And Extensor Stretch',
      aliases: ['Wrist Ulnar Deviator And Extensor Stretch'],
      muscleGroup: 'Forearms',
      targetRegions: ['Forearms', 'Wrist Flexors'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Strength Training'],
      categories: ['Isolation'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Isolation Movement',
      goalTags: ['Core Strength', 'Muscle Gain', 'Fitness'],
      isCompound: false,
      primaryMuscles: ['Forearms', 'Wrist Flexors'],
      secondaryMuscles: ['Grip'],
      mechanics: 'Isolation',
      forceType: 'Pull',
      bodyRegion: 'Forearms',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: [],
      progressions: [],
      regressions: [],
      thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/wrist_ulnar_deviator_and_extensor_stretch.gif',
      videoUrl: '',
      steps: ['Set up properly for Wrist Ulnar Deviator And Extensor Stretch with controlled posture.', 'Engage core and execute movement through full range of motion.', 'Return steadily to starting position.'],
      commonMistakes: ['Using momentum instead of controlled muscle contraction', 'Incomplete range of motion'],
      safetyTips: ['Maintain neutral spine', 'Breathe steadily during rep execution'],
      breathing: 'Exhale during exertion, inhale during release.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Bodyweight', 'Forearms', 'Wrist Flexors', 'Grip', 'Intermediate'],
    )
  ];
}
