import '../../models/models.dart';

class ShouldersExercises {
  static final List<Exercise> exercises = [
    // 1. Alternating Front Raise
    Exercise(
      exerciseId: 'alternating_front_raise',
      name: 'Alternating Front Raise',
      aliases: ['Alternating DB Front Raise'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Dumbbell', 'Isolation'],
      equipment: ['Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Raise',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Front Delts'],
      secondaryMuscles: ['Side Delts'],
      mechanics: 'Unilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Travel'],
      injuryFriendly: [],
      alternatives: ['dumbbell_front_raise', 'cable_front_raise'],
      progressions: ['barbell_front_raise'],
      regressions: ['resistance_band_front_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand tall holding a dumbbell in each hand at your thighs, palms facing backward.',
        'Raise one dumbbell straight forward to shoulder height, keeping elbow straight.',
        'Slowly lower, then repeat with the opposite arm.'
      ],
      commonMistakes: ['Swinging torso', 'Bending elbows'],
      safetyTips: ['Keep core tight to prevent torso sway'],
      breathing: 'Exhale raising, inhale lowering.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Front Delts', 'Dumbbell', 'Beginner', 'Isolation', 'Shoulders'],
    ),

    // 2. Arnold Press
    Exercise(
      exerciseId: 'arnold_press',
      name: 'Arnold Press',
      aliases: ['Arnold Shoulder Press'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts', 'Side Delts'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Strength Training'],
      categories: ['Dumbbell', 'Compound'],
      equipment: ['Dumbbell', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Press',
      goalTags: ['Muscle Gain', 'Shoulder Mass'],
      isCompound: true,
      primaryMuscles: ['Front Delts', 'Side Delts'],
      secondaryMuscles: ['Triceps', 'Upper Chest'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['dumbbell_shoulder_press', 'machine_shoulder_press'],
      progressions: ['heavy_dumbbell_shoulder_press'],
      regressions: ['dumbbell_lateral_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit on a bench with back support, holding dumbbells at chest height with palms facing your body (like the top of a bicep curl).',
        'Press weights overhead while rotating wrists so your palms face forward at the top lockout.',
        'Slowly lower while rotating palms back to starting position.'
      ],
      commonMistakes: ['Rushing the rotation', 'Arching lower back'],
      safetyTips: ['Perform rotation smoothly throughout press phase'],
      breathing: 'Inhale lowering, exhale pressing overhead.',
      estimatedCaloriesPerMinute: 7.8,
      tags: ['Front Delts', 'Side Delts', 'Dumbbell', 'Intermediate', 'Compound', 'Shoulders'],
    ),

    // 3. Barbell Front Raise
    Exercise(
      exerciseId: 'barbell_front_raise',
      name: 'Barbell Front Raise',
      aliases: ['Barbell Front Raises'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Barbell', 'Isolation'],
      equipment: ['Barbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Raise',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Front Delts'],
      secondaryMuscles: ['Side Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['dumbbell_front_raise', 'plate_front_raise'],
      progressions: ['heavy_barbell_front_raise'],
      regressions: ['resistance_band_front_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand tall holding a barbell overhand at your thighs.',
        'Raise the bar straight forward to shoulder height, keeping elbows locked.',
        'Slowly lower back down.'
      ],
      commonMistakes: ['Swinging torso', 'Grip too wide'],
      safetyTips: ['Do not lift bar higher than shoulder level to avoid impingement'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Front Delts', 'Barbell', 'Intermediate', 'Isolation', 'Shoulders'],
    ),

    // 4. Barbell Overhead Press
    Exercise(
      exerciseId: 'barbell_overhead_press',
      name: 'Barbell Overhead Press',
      aliases: ['Military Press', 'OHP', 'Overhead Press'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts', 'Side Delts'],
      exerciseType: 'Strength',
      trainingStyles: ['Powerlifting', 'Weightlifting', 'CrossFit', 'General Fitness', 'Strength Training'],
      categories: ['Powerlifting', 'Weightlifting', 'Compound'],
      equipment: ['Barbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Press',
      goalTags: ['Strength', 'Explosive Power', 'Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Shoulders', 'Triceps'],
      secondaryMuscles: ['Upper Chest', 'Core', 'Traps'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['dumbbell_shoulder_press', 'machine_shoulder_press'],
      progressions: ['heavy_overhead_press', 'push_press'],
      regressions: ['dumbbell_shoulder_press', 'kettlebell_overhead_press'],
      thumbnail: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand with feet shoulder-width apart, barbell resting on your upper chest.',
        'Grip the bar slightly wider than shoulders, squeeze core and glutes.',
        'Press the bar straight up over your head, moving your face back to let the bar pass.',
        'Lock elbows at the top, pushing your head forward slightly for lockout stability.'
      ],
      commonMistakes: ['Arching lower back excessively', 'Not pushing bar in a straight line', 'Incomplete lockout'],
      safetyTips: ['Keep glutes tightly squeezed to stabilize lower back', 'Keep elbows under the bar'],
      breathing: 'Inhale at bottom, hold brace, exhale at top.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Front Delts', 'Side Delts', 'Barbell', 'Intermediate', 'Compound', 'Powerlifting', 'Push', 'Upper Body'],
    ),

    // 5. Barbell Shrug
    Exercise(
      exerciseId: 'barbell_shrug',
      name: 'Barbell Shrug',
      aliases: ['Barbell Shrugs'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Traps'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'Powerlifting', 'Strength Training'],
      categories: ['Barbell', 'Isolation'],
      equipment: ['Barbell'],
      difficulty: 'Beginner',
      movementPattern: 'Shrug',
      goalTags: ['Trap Mass', 'Upper Back Strength'],
      isCompound: false,
      primaryMuscles: ['Traps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['dumbbell_shrug', 'upright_row'],
      progressions: ['heavy_barbell_shrug'],
      regressions: ['light_dumbbell_shrug'],
      thumbnail: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand tall holding a barbell at thighs with overhand grip.',
        'Raise your shoulders straight up toward ears as high as possible, squeezing traps at top.',
        'Slowly lower back down.'
      ],
      commonMistakes: ['Rolling shoulders in circle', 'Bending elbows to lift'],
      safetyTips: ['Move shoulders strictly straight up and down to protect joints'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Traps', 'Barbell', 'Beginner', 'Isolation', 'Shoulders'],
    ),

    // 6. Behind the Back Cable Lateral Raise
    Exercise(
      exerciseId: 'behind_the_back_cable_lateral_raise',
      name: 'Behind The Back Cable Lateral Raise',
      aliases: ['Behind Back Cable Lateral Raise'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Side Delts'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable'],
      difficulty: 'Intermediate',
      movementPattern: 'Raise',
      goalTags: ['Side Delts Development', 'Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Side Delts'],
      secondaryMuscles: ['Traps'],
      mechanics: 'Unilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['cable_lateral_raise', 'leaning_cable_lateral_raise'],
      progressions: ['heavy_cable_lateral_raise'],
      regressions: ['dumbbell_lateral_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand facing away from low pulley stack, cable running behind your back.',
        'Grip D-handle with outer hand.',
        'Sweep arm outward and upward to shoulder height, keeping elbow soft.',
        'Slowly return to starting stretch.'
      ],
      commonMistakes: ['Using momentum', 'Leaning sideways excessively'],
      safetyTips: ['Maintain neutral spine posture'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Side Delts', 'Cable', 'Intermediate', 'Isolation', 'Shoulders'],
    ),

    // 7. Bradford Press
    Exercise(
      exerciseId: 'bradford_press',
      name: 'Bradford Press',
      aliases: ['Bradford Press Squat Rack'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts', 'Side Delts', 'Rear Delts'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Strongman', 'Bodybuilding'],
      categories: ['Barbell', 'Compound'],
      equipment: ['Barbell'],
      difficulty: 'Advanced',
      movementPattern: 'Press',
      goalTags: ['Shoulder Endurance', 'Time Under Tension'],
      isCompound: true,
      primaryMuscles: ['Front Delts', 'Side Delts'],
      secondaryMuscles: ['Triceps', 'Upper Back'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['barbell_overhead_press', 'arnold_press'],
      progressions: ['heavy_overhead_press'],
      regressions: ['dumbbell_shoulder_press'],
      thumbnail: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Start with barbell resting on front shoulders.',
        'Press bar up just enough to clear your head, then move it backward and lower it behind neck.',
        'Press back up just over head height and return to front collarbone.'
      ],
      commonMistakes: ['Hitting head with bar', 'Using too much weight', 'Arching lower back'],
      safetyTips: ['Requires high shoulder mobility; keep weight light and reps controlled'],
      breathing: 'Breathe rhythmically.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Front Delts', 'Side Delts', 'Barbell', 'Advanced', 'Compound', 'Shoulders'],
    ),

    // 8. Cable Front Raise
    Exercise(
      exerciseId: 'cable_front_raise',
      name: 'Cable Front Raise',
      aliases: ['Low Pulley Front Raise'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable'],
      difficulty: 'Beginner',
      movementPattern: 'Raise',
      goalTags: ['Muscle Gain', 'Constant Tension'],
      isCompound: false,
      primaryMuscles: ['Front Delts'],
      secondaryMuscles: ['Side Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['dumbbell_front_raise', 'plate_front_raise'],
      progressions: ['barbell_front_raise'],
      regressions: ['resistance_band_front_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand facing away from low pulley stack, holding straight bar attachment overhand.',
        'Raise arms straight forward to shoulder height.',
        'Slowly lower against cable tension.'
      ],
      commonMistakes: ['Hunching back', 'Slamming weights'],
      safetyTips: ['Keep spine vertical'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Front Delts', 'Cable', 'Beginner', 'Isolation', 'Shoulders'],
    ),

    // 9. Cable Lateral Raise
    Exercise(
      exerciseId: 'cable_lateral_raise',
      name: 'Cable Lateral Raise',
      aliases: ['Cable Side Raise'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Side Delts'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable'],
      difficulty: 'Beginner',
      movementPattern: 'Raise',
      goalTags: ['Muscle Gain', 'Constant Tension'],
      isCompound: false,
      primaryMuscles: ['Side Delts'],
      secondaryMuscles: ['Traps'],
      mechanics: 'Unilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['dumbbell_lateral_raise', 'machine_lateral_raise'],
      progressions: ['leaning_cable_lateral_raise'],
      regressions: ['dumbbell_lateral_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand next to low pulley stack.',
        'Reach across body to grip D-handle with outer hand.',
        'Raise arm out to side to shoulder height under control.',
        'Slowly lower back down.'
      ],
      commonMistakes: ['Shrugging shoulders', 'Using too much weight'],
      safetyTips: ['Keep elbow slightly bent to protect joint'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Side Delts', 'Cable', 'Beginner', 'Isolation', 'Shoulders'],
    ),

    // 10. Cuban Press
    Exercise(
      exerciseId: 'cuban_press',
      name: 'Cuban Press',
      aliases: ['Dumbbell Cuban Press'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Rotator Cuff', 'Rear Delts', 'Side Delts'],
      exerciseType: 'Strength',
      trainingStyles: ['Strength Training', 'Injury Prevention', 'Athletic Performance'],
      categories: ['Dumbbell', 'Compound'],
      equipment: ['Dumbbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Rotation',
      goalTags: ['Shoulder Health', 'Rotator Cuff Strength'],
      isCompound: true,
      primaryMuscles: ['Rotator Cuff', 'Shoulders'],
      secondaryMuscles: ['Traps', 'Rear Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['external_rotation', 'scaption_raise'],
      progressions: ['heavy_cuban_press'],
      regressions: ['external_rotation'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding dumbbells at thighs.',
        'Perform upright row until upper arms are parallel to floor.',
        'Rotate dumbbells upward (external rotation) until palms face forward.',
        'Press weights overhead to lockout, then reverse all steps to return.'
      ],
      commonMistakes: ['Using heavy weights (strains rotators)', 'Rushing the rotation phase'],
      safetyTips: ['Cuban presses require strict form; keep weights very light'],
      breathing: 'Breathe in rhythm with phases.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Rotator Cuff', 'Shoulders', 'Dumbbell', 'Intermediate', 'Compound', 'Shoulders'],
    ),

    // 11. Dumbbell Front Raise
    Exercise(
      exerciseId: 'dumbbell_front_raise',
      name: 'Dumbbell Front Raise',
      aliases: ['DB Front Raise', 'Dumbbell Front Raises'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Dumbbell', 'Isolation'],
      equipment: ['Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Raise',
      goalTags: ['Muscle Gain', 'Front Delts Shaping'],
      isCompound: false,
      primaryMuscles: ['Front Delts'],
      secondaryMuscles: ['Side Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Travel'],
      injuryFriendly: [],
      alternatives: ['barbell_front_raise', 'cable_front_raise'],
      progressions: ['barbell_front_raise'],
      regressions: ['resistance_band_front_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand tall holding dumbbells at thighs overhand.',
        'Raise weights straight forward to shoulder height.',
        'Slowly lower weights back to thighs.'
      ],
      commonMistakes: ['Swinging torso', 'Bending elbows too much'],
      safetyTips: ['Do not shrug shoulders while raising weights'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Front Delts', 'Dumbbell', 'Beginner', 'Isolation', 'Shoulders'],
    ),

    // 12. Dumbbell Lateral Raise
    Exercise(
      exerciseId: 'dumbbell_lateral_raise',
      name: 'Dumbbell Lateral Raise',
      aliases: ['Lateral Raises', 'DB Lateral Raise', 'Dumbbell Side Raises'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Side Delts'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Bodybuilding', 'General Fitness', 'Isolation'],
      equipment: ['Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Raise',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Side Delts'],
      secondaryMuscles: ['Traps'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: ['Lower Back Safe'],
      alternatives: ['overhead_press', 'cable_lateral_raise'],
      progressions: ['cable_lateral_raise', 'dumbbell_lateral_raise_heavy'],
      regressions: ['resistance_band_lateral_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand tall with dumbbells at your sides, palms facing inward.',
        'Keep a slight bend in your elbows and lift the weights out to your sides.',
        'Raise arms until they are parallel to the floor (pinky fingers slightly rotated up).',
        'Slowly lower the dumbbells back to starting position.'
      ],
      commonMistakes: ['Shrugging with traps instead of side delts', 'Swinging torso for momentum', 'Using too much weight'],
      safetyTips: ['Maintain a slight elbow bend', 'Control weights throughout descent'],
      breathing: 'Exhale raising, inhale lowering.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Side Delts', 'Dumbbell', 'Beginner', 'Isolation', 'Bodybuilding', 'Push', 'Upper Body'],
    ),

    // 13. Dumbbell Shoulder Press
    Exercise(
      exerciseId: 'dumbbell_shoulder_press',
      name: 'Dumbbell Shoulder Press',
      aliases: ['DB Shoulder Press', 'Dumbbell Overhead Press'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts', 'Side Delts'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Strength Training', 'General Fitness'],
      categories: ['Dumbbell', 'Bench', 'Compound'],
      equipment: ['Dumbbell', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Press',
      goalTags: ['Muscle Gain', 'Shoulder Mass', 'Muscle Balance'],
      isCompound: true,
      primaryMuscles: ['Front Delts', 'Side Delts'],
      secondaryMuscles: ['Triceps', 'Upper Chest'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['barbell_overhead_press', 'machine_shoulder_press'],
      progressions: ['heavy_dumbbell_shoulder_press'],
      regressions: ['dumbbell_lateral_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit on a bench with back support, holding dumbbells at shoulder height with palms facing forward.',
        'Press weights straight overhead to lockout, then lower under control.'
      ],
      commonMistakes: ['Arching lower back', 'Clashing weights at top'],
      safetyTips: ['Keep elbows slightly forward of body plane (not flared 90 degrees) to protect shoulders'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 7.5,
      tags: ['Front Delts', 'Side Delts', 'Dumbbell', 'Intermediate', 'Compound', 'Shoulders'],
    ),

    // 14. Dumbbell Shrug
    Exercise(
      exerciseId: 'dumbbell_shrug',
      name: 'Dumbbell Shrug',
      aliases: ['DB Shrugs'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Traps'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Dumbbell', 'Isolation'],
      equipment: ['Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Shrug',
      goalTags: ['Trap Mass'],
      isCompound: false,
      primaryMuscles: ['Traps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Travel'],
      injuryFriendly: [],
      alternatives: ['barbell_shrug', 'upright_row'],
      progressions: ['heavy_dumbbell_shrug'],
      regressions: ['light_dumbbell_shrug'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding dumbbells at your sides.',
        'Raise shoulders straight up toward ears, squeeze traps, and lower.'
      ],
      commonMistakes: ['Rolling shoulders', 'Bending elbows'],
      safetyTips: ['Keep head neutral; do not crane neck forward'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Traps', 'Dumbbell', 'Beginner', 'Isolation', 'Shoulders'],
    ),

    // 15. External Rotation
    Exercise(
      exerciseId: 'external_rotation',
      name: 'External Rotation',
      aliases: ['Dumbbell External Rotation', 'Band External Rotation'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Rotator Cuff'],
      exerciseType: 'Strength',
      trainingStyles: ['Rehabilitation', 'Injury Prevention', 'Warm-up'],
      categories: ['Isolation'],
      equipment: ['Dumbbell', 'Resistance Band'],
      difficulty: 'Beginner',
      movementPattern: 'Rotation',
      goalTags: ['Shoulder Health', 'Rotator Cuff Strength'],
      isCompound: false,
      primaryMuscles: ['Rotator Cuff'],
      secondaryMuscles: [],
      mechanics: 'Unilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Travel'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['internal_rotation', 'cuban_press'],
      progressions: ['cuban_press'],
      regressions: ['light_band_rotation'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding a light dumbbell (or loop band anchored to a post).',
        'Keep elbow bent at 90 degrees and pinned to your side (place towel roll under elbow).',
        'Rotate forearm outward away from your stomach as far as comfortable.',
        'Slowly return to starting position.'
      ],
      commonMistakes: ['Elbow drifting away from torso', 'Using too much weight'],
      safetyTips: ['Rotator cuff muscles are small; load should be very light'],
      breathing: 'Exhale rotating out, inhale returning.',
      estimatedCaloriesPerMinute: 3.0,
      tags: ['Rotator Cuff', 'Dumbbell', 'Beginner', 'Isolation', 'Shoulders'],
    ),

    // 16. Handstand Push Up
    Exercise(
      exerciseId: 'handstand_push_up',
      name: 'Handstand Push Up',
      aliases: ['HSPU', 'Wall Handstand Push Up'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts', 'Side Delts', 'Triceps'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Gymnastics', 'CrossFit'],
      categories: ['Calisthenics', 'Compound', 'Bodyweight'],
      equipment: ['Bodyweight', 'Wall'],
      difficulty: 'Advanced',
      movementPattern: 'Press',
      goalTags: ['Shoulder Power', 'Core Stability'],
      isCompound: true,
      primaryMuscles: ['Shoulders', 'Triceps'],
      secondaryMuscles: ['Core', 'Traps'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['pike_push_up', 'barbell_overhead_press'],
      progressions: ['freestanding_hspu'],
      regressions: ['pike_push_up'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Kick up into a handstand against a wall, hands shoulder-width apart.',
        'Slowly lower your head to the floor by bending elbows.',
        'Press away from floor powerfully to return to full lockout.'
      ],
      commonMistakes: ['Arching back like banana', 'Flaring elbows outward excessively', 'Losing core tightness'],
      safetyTips: ['Use a mat under head for protection', 'Do not perform if you have neck pain'],
      breathing: 'Inhale lowering down, exhale pressing up.',
      estimatedCaloriesPerMinute: 9.0,
      tags: ['Front Delts', 'Side Delts', 'Bodyweight', 'Advanced', 'Compound', 'Calisthenics', 'Push', 'Upper Body'],
    ),

    // 17. High Pull
    Exercise(
      exerciseId: 'high_pull',
      name: 'High Pull',
      aliases: ['Barbell High Pull', 'Snatch High Pull'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Traps', 'Rear Delts', 'Side Delts'],
      exerciseType: 'Strength',
      trainingStyles: ['Weightlifting', 'Athletic Performance', 'Strongman'],
      categories: ['Barbell', 'Compound', 'Weightlifting'],
      equipment: ['Barbell'],
      difficulty: 'Advanced',
      movementPattern: 'Pull',
      goalTags: ['Explosive Power', 'Trap Mass'],
      isCompound: true,
      primaryMuscles: ['Traps', 'Shoulders'],
      secondaryMuscles: ['Hamstrings', 'Glutes', 'Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Full Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['upright_row', 'power_clean'],
      progressions: ['power_snatch'],
      regressions: ['upright_row'],
      thumbnail: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding barbell with wide grip (snatch grip).',
        'Hinge hips and bend knees to place bar just above knees.',
        'Extend hips and knees explosively, shrugging shoulders and pulling elbows high to lift the bar to chest height.'
      ],
      commonMistakes: ['Pulling purely with arms', 'Rounding lower back', 'Not completing hip extension'],
      safetyTips: ['Ensure bar paths remain vertical close to torso'],
      breathing: 'Inhale down, exhale aggressively on explosive pull.',
      estimatedCaloriesPerMinute: 9.5,
      tags: ['Traps', 'Shoulders', 'Barbell', 'Advanced', 'Compound', 'Shoulders'],
    ),

    // 18. Incline Lateral Raise
    Exercise(
      exerciseId: 'incline_lateral_raise',
      name: 'Incline Lateral Raise',
      aliases: ['Incline DB Lateral Raise'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Side Delts'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Dumbbell', 'Bench', 'Isolation'],
      equipment: ['Dumbbell', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Raise',
      goalTags: ['Side Delts Development', 'Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Side Delts'],
      secondaryMuscles: ['Traps'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['dumbbell_lateral_raise', 'cable_lateral_raise'],
      progressions: ['leaning_cable_lateral_raise'],
      regressions: ['dumbbell_lateral_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Lie chest-down on an incline bench (set to 30-45 degrees).',
        'Hold dumbbells hanging down, then raise them out to the sides to shoulder height.'
      ],
      commonMistakes: ['Using momentum', 'Lifting chest off pad'],
      safetyTips: ['Avoid jerking weights at bottom'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 5.2,
      tags: ['Side Delts', 'Dumbbell', 'Intermediate', 'Isolation', 'Shoulders'],
    ),

    // 19. Internal Rotation
    Exercise(
      exerciseId: 'internal_rotation',
      name: 'Internal Rotation',
      aliases: ['Dumbbell Internal Rotation', 'Band Internal Rotation'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Rotator Cuff'],
      exerciseType: 'Strength',
      trainingStyles: ['Rehabilitation', 'Injury Prevention', 'Warm-up'],
      categories: ['Isolation'],
      equipment: ['Dumbbell', 'Resistance Band'],
      difficulty: 'Beginner',
      movementPattern: 'Rotation',
      goalTags: ['Shoulder Health', 'Rotator Cuff Strength'],
      isCompound: false,
      primaryMuscles: ['Rotator Cuff'],
      secondaryMuscles: [],
      mechanics: 'Unilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Travel'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['external_rotation', 'cuban_press'],
      progressions: ['cuban_press'],
      regressions: ['light_band_rotation'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding light dumbbell (or loop band anchored laterally).',
        'Elbow bent at 90 degrees at side.',
        'Rotate forearm inward across stomach.',
        'Slowly return.'
      ],
      commonMistakes: ['Elbow lifting', 'Twisting torso'],
      safetyTips: ['Use very conservative resistance'],
      breathing: 'Exhale rotating in, inhale out.',
      estimatedCaloriesPerMinute: 3.0,
      tags: ['Rotator Cuff', 'Dumbbell', 'Beginner', 'Isolation', 'Shoulders'],
    ),

    // 20. Kettlebell Overhead Press
    Exercise(
      exerciseId: 'kettlebell_overhead_press',
      name: 'Kettlebell Overhead Press',
      aliases: ['KB Press', 'KB Shoulder Press'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts', 'Side Delts'],
      exerciseType: 'Strength',
      trainingStyles: ['Kettlebell Training', 'Strength Training', 'Functional Fitness'],
      categories: ['Kettlebell', 'Compound'],
      equipment: ['Kettlebell'],
      difficulty: 'Intermediate',
      movementPattern: 'Press',
      goalTags: ['Shoulder Strength', 'Core Stability', 'Unilateral Balance'],
      isCompound: true,
      primaryMuscles: ['Front Delts', 'Side Delts'],
      secondaryMuscles: ['Triceps', 'Core'],
      mechanics: 'Unilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['dumbbell_shoulder_press', 'barbell_overhead_press'],
      progressions: ['heavy_kettlebell_overhead_press'],
      regressions: ['light_dumbbell_press'],
      thumbnail: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Hold kettlebell in front rack position (resting in crook of arm/chest).',
        'Press kettlebell straight overhead, letting the bell rotate naturally behind shoulder.',
        'Lower back to rack position.'
      ],
      commonMistakes: ['Letting wrist bend backward', 'Flaring ribs'],
      safetyTips: ['Keep wrist locked straight throughout lift'],
      breathing: 'Inhale at rack, exhale pressing up.',
      estimatedCaloriesPerMinute: 7.8,
      tags: ['Front Delts', 'Side Delts', 'Kettlebell', 'Intermediate', 'Compound', 'Shoulders'],
    ),

    // 21. Landmine Press
    Exercise(
      exerciseId: 'landmine_press',
      name: 'Landmine Press',
      aliases: ['Barbell Landmine Press'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts', 'Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Functional Fitness', 'Strength Training'],
      categories: ['Barbell', 'Compound'],
      equipment: ['Barbell', 'Landmine Attachment'],
      difficulty: 'Beginner',
      movementPattern: 'Press',
      goalTags: ['Shoulder Strength', 'Lower Back Safe Pressing'],
      isCompound: true,
      primaryMuscles: ['Front Delts', 'Upper Chest'],
      secondaryMuscles: ['Triceps'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Shoulder Friendly', 'Lower Back Friendly'],
      alternatives: ['dumbbell_shoulder_press', 'single_arm_landmine_press'],
      progressions: ['single_arm_landmine_press'],
      regressions: ['push_ups'],
      thumbnail: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding the sleeve of a barbell set in landmine attachment at chest height with both hands.',
        'Lean slightly forward and press the bar upward and forward to lockout.',
        'Slowly return to chest.'
      ],
      commonMistakes: ['Leaning backward', 'Not bracing core'],
      safetyTips: ['Keep stance stable and core braced'],
      breathing: 'Inhale down, exhale pressing.',
      estimatedCaloriesPerMinute: 6.8,
      tags: ['Front Delts', 'Upper Chest', 'Barbell', 'Beginner', 'Compound', 'Shoulders'],
    ),

    // 22. Leaning Cable Lateral Raise
    Exercise(
      exerciseId: 'leaning_cable_lateral_raise',
      name: 'Leaning Cable Lateral Raise',
      aliases: ['Leaning Side Raise'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Side Delts'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable'],
      difficulty: 'Intermediate',
      movementPattern: 'Raise',
      goalTags: ['Side Delts Development', 'Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Side Delts'],
      secondaryMuscles: ['Traps'],
      mechanics: 'Unilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['cable_lateral_raise', 'dumbbell_lateral_raise'],
      progressions: ['heavy_leaning_cable_raise'],
      regressions: ['dumbbell_lateral_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand next to pulley stack, holding column with inner hand and leaning torso outward at an angle.',
        'Grip cable handle with outer hand and raise arm out to side to shoulder height.'
      ],
      commonMistakes: ['Torso swinging', 'Wrist bending'],
      safetyTips: ['Ensure column grip is completely secure before leaning'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Side Delts', 'Cable', 'Intermediate', 'Isolation', 'Shoulders'],
    ),

    // 23. Machine Lateral Raise
    Exercise(
      exerciseId: 'machine_lateral_raise',
      name: 'Machine Lateral Raise',
      aliases: ['Machine Side Raise', 'Lateral Raise Machine'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Side Delts'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Machine', 'Isolation'],
      equipment: ['Machine'],
      difficulty: 'Beginner',
      movementPattern: 'Raise',
      goalTags: ['Muscle Gain', 'Side Delts Isolation'],
      isCompound: false,
      primaryMuscles: ['Side Delts'],
      secondaryMuscles: ['Traps'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['dumbbell_lateral_raise', 'cable_lateral_raise'],
      progressions: ['heavy_machine_lateral_raise'],
      regressions: ['dumbbell_lateral_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit in machine, adjusting seat so elbows align with pads.',
        'Grip handles and raise elbows outward against pads to shoulder level.',
        'Slowly return to start.'
      ],
      commonMistakes: ['Shrugging shoulders', 'Letting weights slam'],
      safetyTips: ['Keep neck relaxed'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Side Delts', 'Machine', 'Beginner', 'Isolation', 'Shoulders'],
    ),

    // 24. Machine Shoulder Press
    Exercise(
      exerciseId: 'machine_shoulder_press',
      name: 'Machine Shoulder Press',
      aliases: ['Machine Overhead Press', 'Shoulder Press Machine'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts', 'Side Delts'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Machine', 'Compound'],
      equipment: ['Machine'],
      difficulty: 'Beginner',
      movementPattern: 'Press',
      goalTags: ['Muscle Gain', 'Shoulder Strength'],
      isCompound: true,
      primaryMuscles: ['Front Delts', 'Side Delts'],
      secondaryMuscles: ['Triceps'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['dumbbell_shoulder_press', 'barbell_overhead_press'],
      progressions: ['dumbbell_shoulder_press'],
      regressions: ['dumbbell_lateral_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Adjust seat height so handles are at shoulder level.',
        'Sit back flat against pad, grip handles, and press upward to lockout.',
        'Slowly lower back to shoulders.'
      ],
      commonMistakes: ['Arching lower back off pad', 'Locking elbows too aggressively'],
      safetyTips: ['Keep head supported on pad'],
      breathing: 'Exhale pressing, inhale lowering.',
      estimatedCaloriesPerMinute: 6.8,
      tags: ['Front Delts', 'Side Delts', 'Machine', 'Beginner', 'Compound', 'Shoulders'],
    ),

    // 25. Overhead Carry
    Exercise(
      exerciseId: 'overhead_carry',
      name: 'Overhead Carry',
      aliases: ['Waiter Carry', 'Barbell Overhead Carry'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Shoulder Stabilizers', 'Core'],
      exerciseType: 'Strength',
      trainingStyles: ['Strongman', 'Functional Fitness', 'Athletic Performance'],
      categories: ['Compound', 'Functional'],
      equipment: ['Dumbbell', 'Kettlebell', 'Barbell'],
      difficulty: 'Advanced',
      movementPattern: 'Carry',
      goalTags: ['Shoulder Stability', 'Core Strength', 'Postures'],
      isCompound: true,
      primaryMuscles: ['Shoulder Stabilizers', 'Core'],
      secondaryMuscles: ['Shoulders', 'Traps'],
      mechanics: 'Bilateral',
      forceType: 'Isometric',
      bodyRegion: 'Full Body',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['farmers_carry', 'suitcase_carry'],
      progressions: ['heavy_overhead_carry'],
      regressions: ['farmers_carry'],
      thumbnail: 'https://images.unsplash.com/photo-1627483297886-49710ae1fc22?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Press weights overhead to full lockout.',
        'Keeping arms locked and core braced, walk forward taking slow, controlled strides.',
        'Maintain upright spine posture.'
      ],
      commonMistakes: ['Flaring ribs', 'Arching lower back', 'Soft elbows'],
      safetyTips: ['Drop weights safely to sides if stability is lost'],
      breathing: 'Maintain steady, braced breathing.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Shoulder Stabilizers', 'Core', 'Dumbbell', 'Advanced', 'Compound', 'Shoulders'],
    ),

    // 26. Pike Push Up
    Exercise(
      exerciseId: 'pike_push_up',
      name: 'Pike Push Up',
      aliases: ['Pike Pushup', 'Pike Pushups'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts', 'Side Delts', 'Triceps'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'General Fitness'],
      categories: ['Calisthenics', 'Compound', 'Bodyweight'],
      equipment: ['Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Press',
      goalTags: ['Shoulder Strength', 'Triceps strength'],
      isCompound: true,
      primaryMuscles: ['Shoulders', 'Triceps'],
      secondaryMuscles: ['Traps', 'Core'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['push_ups', 'handstand_push_up'],
      progressions: ['handstand_push_up'],
      regressions: ['incline_push_up'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Start in standard push-up plank, then walk feet forward while lifting hips high into an inverted V-shape (pike stance).',
        'Lower head diagonally forward toward floor between hands.',
        'Press back up to lock arms.'
      ],
      commonMistakes: ['Flaring elbows wide', 'Sagging hips', 'Looking straight down'],
      safetyTips: ['Keep head path slightly in front of hands to form a tripod stance at bottom'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 7.0,
      tags: ['Front Delts', 'Side Delts', 'Bodyweight', 'Intermediate', 'Compound', 'Calisthenics', 'Push', 'Upper Body'],
    ),

    // 27. Plate Front Raise
    Exercise(
      exerciseId: 'plate_front_raise',
      name: 'Plate Front Raise',
      aliases: ['Weight Plate Front Raise'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Isolation'],
      equipment: ['Weight Plate'],
      difficulty: 'Beginner',
      movementPattern: 'Raise',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Front Delts'],
      secondaryMuscles: ['Side Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['dumbbell_front_raise', 'barbell_front_raise'],
      progressions: ['heavy_plate_front_raise'],
      regressions: ['resistance_band_front_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding weight plate on sides (3 and 9 o\'clock).',
        'Raise plate straight forward to shoulder height.',
        'Slowly lower.'
      ],
      commonMistakes: ['Swinging torso', 'Hunching shoulders'],
      safetyTips: ['Keep core braced'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Front Delts', 'Weight Plate', 'Beginner', 'Isolation', 'Shoulders'],
    ),

    // 28. Push Press
    Exercise(
      exerciseId: 'push_press',
      name: 'Push Press',
      aliases: ['Barbell Push Press'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts', 'Side Delts', 'Triceps'],
      exerciseType: 'Strength',
      trainingStyles: ['Weightlifting', 'CrossFit', 'Athletic Performance'],
      categories: ['Compound', 'Weightlifting'],
      equipment: ['Barbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Press',
      goalTags: ['Explosive Power', 'Strength'],
      isCompound: true,
      primaryMuscles: ['Shoulders', 'Triceps'],
      secondaryMuscles: ['Quads', 'Glutes', 'Core', 'Traps'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Full Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['barbell_overhead_press', 'dumbbell_shoulder_press'],
      progressions: ['jerk'],
      regressions: ['barbell_overhead_press'],
      thumbnail: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand with barbell on shoulders in front rack stance.',
        'Perform quick, shallow knee dip (4-6 inches).',
        'Drive legs straight explosively, transferring leg power to press bar overhead to lockout.'
      ],
      commonMistakes: ['Squatting too deep (slows transition)', 'Not using leg drive', 'Ribs flaring'],
      safetyTips: ['Keep spine neutral; do not lean back during leg drive'],
      breathing: 'Inhale/brace on dip, exhale powerfully on drive.',
      estimatedCaloriesPerMinute: 9.0,
      tags: ['Front Delts', 'Side Delts', 'Barbell', 'Intermediate', 'Compound', 'Shoulders'],
    ),

    // 29. Resistance Band Front Raise
    Exercise(
      exerciseId: 'resistance_band_front_raise',
      name: 'Resistance Band Front Raise',
      aliases: ['Band Front Raise'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['General Fitness', 'Travel Fitness'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Resistance Band'],
      difficulty: 'Beginner',
      movementPattern: 'Raise',
      goalTags: ['Muscle Gain', 'Conditioning'],
      isCompound: false,
      primaryMuscles: ['Front Delts'],
      secondaryMuscles: ['Side Delts'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Joint Friendly'],
      alternatives: ['dumbbell_front_raise', 'cable_front_raise'],
      progressions: ['dumbbell_front_raise'],
      regressions: ['lighter_band_front_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Step on band, grip handles overhand.',
        'Raise arms straight forward to shoulder height against band resistance.',
        'Slowly lower.'
      ],
      commonMistakes: ['Rounding back', 'Swinging torso'],
      safetyTips: ['Ensure band is secured under feet'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.0,
      tags: ['Front Delts', 'Resistance Band', 'Beginner', 'Isolation', 'Shoulders'],
    ),

    // 30. Resistance Band Lateral Raise
    Exercise(
      exerciseId: 'resistance_band_lateral_raise',
      name: 'Resistance Band Lateral Raise',
      aliases: ['Band Side Raise'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Side Delts'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['General Fitness', 'Travel Fitness'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Resistance Band'],
      difficulty: 'Beginner',
      movementPattern: 'Raise',
      goalTags: ['Muscle Gain', 'Conditioning'],
      isCompound: false,
      primaryMuscles: ['Side Delts'],
      secondaryMuscles: ['Traps'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Joint Friendly'],
      alternatives: ['dumbbell_lateral_raise', 'cable_lateral_raise'],
      progressions: ['dumbbell_lateral_raise'],
      regressions: ['lighter_band_lateral_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Step on band, grip handles at sides.',
        'Raise arms straight out to sides to shoulder height against band resistance.',
        'Slowly lower.'
      ],
      commonMistakes: ['Shrugging shoulders', 'Rushing reps'],
      safetyTips: ['Check band for cracks before standing on it'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.0,
      tags: ['Side Delts', 'Resistance Band', 'Beginner', 'Isolation', 'Shoulders'],
    ),

    // 31. Reverse Cable Fly
    Exercise(
      exerciseId: 'reverse_cable_fly',
      name: 'Reverse Cable Fly',
      aliases: ['Rear Delt Cable Fly Cross'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Rear Delts'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable'],
      difficulty: 'Intermediate',
      movementPattern: 'Fly',
      goalTags: ['Rear Delts Isolation', 'Posture'],
      isCompound: false,
      primaryMuscles: ['Rear Delts'],
      secondaryMuscles: ['Rhomboids', 'Traps'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['rear_delt_cable_fly', 'reverse_pec_deck'],
      progressions: ['heavy_reverse_cable_fly'],
      regressions: ['dumbbell_rear_delt_fly'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand facing cable crossover pulleys set to shoulder height.',
        'Grip left cable with right hand, right cable with left hand (crossover).',
        'Pull arms horizontally back and wide, squeezing rear delts.'
      ],
      commonMistakes: ['Shrugging shoulders', 'Bending elbows'],
      safetyTips: ['Keep torso steady'],
      breathing: 'Exhale pulling back, inhale returning forward.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Rear Delts', 'Cable', 'Intermediate', 'Isolation', 'Shoulders'],
    ),

    // 32. Scaption Raise
    Exercise(
      exerciseId: 'scaption_raise',
      name: 'Scaption Raise',
      aliases: ['Dumbbell Scaption'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Lower Traps', 'Side Delts', 'Rotator Cuff'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['General Fitness', 'Rehabilitation', 'Warm-up'],
      categories: ['Dumbbell', 'Isolation'],
      equipment: ['Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Raise',
      goalTags: ['Shoulder Health', 'Shoulder Stability'],
      isCompound: false,
      primaryMuscles: ['Shoulders', 'Rotator Cuff'],
      secondaryMuscles: ['Traps'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Travel'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['dumbbell_lateral_raise', 'external_rotation'],
      progressions: ['dumbbell_lateral_raise'],
      regressions: ['light_band_raises'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand tall holding light dumbbells at your sides, thumbs pointing upward.',
        'Raise arms diagonally forward (at 30-degree angle from front, plane of scapula) to shoulder height.',
        'Slowly lower.'
      ],
      commonMistakes: ['Lifting straight out to side', 'Shrugging'],
      safetyTips: ['Scaption is the most natural shoulder movement plane for joint sockets'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Rotator Cuff', 'Shoulders', 'Dumbbell', 'Beginner', 'Isolation', 'Shoulders'],
    ),

    // 33. Seated Barbell Shoulder Press
    Exercise(
      exerciseId: 'seated_barbell_shoulder_press',
      name: 'Seated Barbell Shoulder Press',
      aliases: ['Seated Military Press'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts', 'Side Delts'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Strength Training'],
      categories: ['Barbell', 'Bench', 'Compound'],
      equipment: ['Barbell', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Press',
      goalTags: ['Shoulder Mass', 'Strength'],
      isCompound: true,
      primaryMuscles: ['Front Delts', 'Side Delts'],
      secondaryMuscles: ['Triceps'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['barbell_overhead_press', 'dumbbell_shoulder_press'],
      progressions: ['barbell_overhead_press'],
      regressions: ['machine_shoulder_press'],
      thumbnail: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit on bench with back support, rack barbell at chest.',
        'Unrack bar, press straight overhead to lockout, and lower slowly.'
      ],
      commonMistakes: ['Arching back off pad', 'Hitting face with bar'],
      safetyTips: ['Ensure bench backing is locked secure'],
      breathing: 'Inhale down, exhale pressing.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Front Delts', 'Side Delts', 'Barbell', 'Intermediate', 'Compound', 'Shoulders'],
    ),

    // 34. Seated Lateral Raise
    Exercise(
      exerciseId: 'seated_lateral_raise',
      name: 'Seated Lateral Raise',
      aliases: ['Seated DB Lateral Raise'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Side Delts'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Dumbbell', 'Bench', 'Isolation'],
      equipment: ['Dumbbell', 'Bench'],
      difficulty: 'Beginner',
      movementPattern: 'Raise',
      goalTags: ['Side Delts Isolation'],
      isCompound: false,
      primaryMuscles: ['Side Delts'],
      secondaryMuscles: ['Traps'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['dumbbell_lateral_raise', 'machine_lateral_raise'],
      progressions: ['incline_lateral_raise'],
      regressions: ['dumbbell_lateral_raise_light'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit on flat bench, holding dumbbells at sides.',
        'Raise weights out to sides to shoulder level, then lower slowly.'
      ],
      commonMistakes: ['Swinging torso (seated posture minimizes this cheating)', 'Elbows locked straight'],
      safetyTips: ['Keep elbows slightly soft'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Side Delts', 'Dumbbell', 'Beginner', 'Isolation', 'Shoulders'],
    ),

    // 35. Single Arm Landmine Press
    Exercise(
      exerciseId: 'single_arm_landmine_press',
      name: 'Single Arm Landmine Press',
      aliases: ['One Arm Landmine Press'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts', 'Upper Chest'],
      exerciseType: 'Strength',
      trainingStyles: ['Functional Fitness', 'Strength Training', 'Athletic Performance'],
      categories: ['Barbell', 'Compound'],
      equipment: ['Barbell', 'Landmine Attachment'],
      difficulty: 'Intermediate',
      movementPattern: 'Press',
      goalTags: ['Unilateral Shoulder Strength', 'Core Stability'],
      isCompound: true,
      primaryMuscles: ['Front Delts', 'Upper Chest'],
      secondaryMuscles: ['Triceps', 'Core'],
      mechanics: 'Unilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Shoulder Friendly', 'Lower Back Friendly'],
      alternatives: ['landmine_press', 'dumbbell_shoulder_press'],
      progressions: ['heavy_single_arm_landmine_press'],
      regressions: ['landmine_press'],
      thumbnail: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Hold sleeve of barbell set in landmine with one hand at shoulder level.',
        'Stand in split stance (opposite foot forward).',
        'Press bar up and forward, extending arm fully.',
        'Slowly return to start.'
      ],
      commonMistakes: ['Torso twisting', 'Ribs flaring'],
      safetyTips: ['Maintain tight core brace to prevent spinal twist'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 7.0,
      tags: ['Front Delts', 'Upper Chest', 'Barbell', 'Intermediate', 'Compound', 'Shoulders'],
    ),

    // 36. Smith Machine Shoulder Press
    Exercise(
      exerciseId: 'smith_machine_shoulder_press',
      name: 'Smith Machine Shoulder Press',
      aliases: ['Smith Machine Overhead Press'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts', 'Side Delts'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Machine', 'Compound'],
      equipment: ['Smith Machine', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Press',
      goalTags: ['Shoulder Mass', 'Lockout Strength'],
      isCompound: true,
      primaryMuscles: ['Front Delts', 'Side Delts'],
      secondaryMuscles: ['Triceps'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['seated_barbell_shoulder_press', 'machine_shoulder_press'],
      progressions: ['seated_barbell_shoulder_press'],
      regressions: ['machine_shoulder_press'],
      thumbnail: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Position seat inside Smith machine, bar path in front of face.',
        'Unlock bar, lower slowly to chin level, and press up to lockout.'
      ],
      commonMistakes: ['Wrong seat placement', 'Elbows flared too wide'],
      safetyTips: ['Set safety stop locks on track columns'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Front Delts', 'Side Delts', 'Machine', 'Intermediate', 'Compound', 'Shoulders'],
    ),

    // 37. TRX Rear Delt Fly
    Exercise(
      exerciseId: 'trx_rear_delt_fly',
      name: 'TRX Rear Delt Fly',
      aliases: ['Suspension Rear Delt Fly'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Rear Delts'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Calisthenics', 'Functional Fitness'],
      categories: ['Calisthenics', 'Stability', 'Isolation'],
      equipment: ['Suspension Trainer (TRX)'],
      difficulty: 'Intermediate',
      movementPattern: 'Fly',
      goalTags: ['Rear Delts Strength', 'Shoulder Health'],
      isCompound: false,
      primaryMuscles: ['Rear Delts'],
      secondaryMuscles: ['Rhomboids', 'Traps', 'Core'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['dumbbell_rear_delt_fly', 'reverse_cable_fly'],
      progressions: ['weighted_trx_rear_delt_fly'],
      regressions: ['band_pull_aparts'],
      thumbnail: 'https://images.unsplash.com/photo-1544033527-b192daee1f5b?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Grip TRX handles facing anchor point, leaning back at an angle with straight body and arms extended forward.',
        'Pull your body up by opening arms wide into a T-shape, keeping elbows straight.',
        'Slowly lower back down.'
      ],
      commonMistakes: ['Slipping hips', 'Bending elbows to pull (turns into row)'],
      safetyTips: ['Brace core to keep body in perfect plank throughout movement'],
      breathing: 'Exhale rising, inhale lowering.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Rear Delts', 'Suspension Trainer (TRX)', 'Intermediate', 'Isolation', 'Shoulders'],
    ),

    // 38. Upright Row
    Exercise(
      exerciseId: 'upright_row',
      name: 'Upright Row',
      aliases: ['Barbell Upright Row', 'Cable Upright Row'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Side Delts', 'Traps'],
      exerciseType: 'Strength',
      trainingStyles: ['Bodybuilding', 'Strength Training'],
      categories: ['Barbell', 'Compound'],
      equipment: ['Barbell', 'Cable'],
      difficulty: 'Intermediate',
      movementPattern: 'Pull',
      goalTags: ['Shoulder Mass', 'Trap Mass'],
      isCompound: true,
      primaryMuscles: ['Shoulders', 'Traps'],
      secondaryMuscles: ['Biceps', 'Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Pull',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['dumbbell_lateral_raise', 'high_pull'],
      progressions: ['high_pull'],
      regressions: ['dumbbell_lateral_raise'],
      thumbnail: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding barbell overhand at thighs, shoulder-width grip.',
        'Pull bar straight up along torso toward collarbone, letting elbows flare high and wide.',
        'Slowly lower bar to starting position.'
      ],
      commonMistakes: ['Grip too narrow (damages shoulder joint rotators)', 'Pulling bar too high (above chest)'],
      safetyTips: ['Keep bar close to body', 'Do not pull above mid-chest level to avoid joint impingement'],
      breathing: 'Exhale up, inhale down.',
      estimatedCaloriesPerMinute: 6.8,
      tags: ['Side Delts', 'Traps', 'Barbell', 'Intermediate', 'Compound', 'Shoulders'],
    ),

    // 39. Z Press
    Exercise(
      exerciseId: 'z_press',
      name: 'Z Press',
      aliases: ['Barbell Z Press', 'Dumbbell Z Press'],
      muscleGroup: 'Shoulders',
      targetRegions: ['Front Delts', 'Side Delts', 'Core'],
      exerciseType: 'Strength',
      trainingStyles: ['Strongman', 'Powerlifting', 'Strength Training'],
      categories: ['Barbell', 'Compound'],
      equipment: ['Barbell', 'Dumbbell'],
      difficulty: 'Advanced',
      movementPattern: 'Press',
      goalTags: ['Core Stability', 'Shoulder Power'],
      isCompound: true,
      primaryMuscles: ['Front Delts', 'Side Delts', 'Core'],
      secondaryMuscles: ['Triceps', 'Upper Back'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['barbell_overhead_press', 'dumbbell_shoulder_press'],
      progressions: ['heavy_z_press'],
      regressions: ['barbell_overhead_press'],
      thumbnail: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Sit flat on the floor with legs extended straight out in front of you (V-shape).',
        'Hold barbell or dumbbells at shoulder rack height (no back support).',
        'Press weights straight overhead, bracing core intensely to stay upright.',
        'Lower weights back to shoulders.'
      ],
      commonMistakes: ['Leaning backward (loses core target)', 'Bending knees', 'Slouching spine'],
      safetyTips: ['Requires high hamstring flexibility and core strength to hold posture'],
      breathing: 'Inhale/brace at rack, exhale pressing overhead.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Front Delts', 'Side Delts', 'Core', 'Barbell', 'Advanced', 'Compound', 'Shoulders'],
    ),
  ];
}
