import '../../models/models.dart';

class TricepsExercises {
  static final List<Exercise> exercises = [
    // 1. Assisted Dip Machine
    Exercise(
      exerciseId: 'assisted_dip_machine',
      name: 'Assisted Dip Machine',
      aliases: ['Machine Assisted Tricep Dip'],
      muscleGroup: 'Triceps',
      targetRegions: ['Lateral Head', 'Medial Head'],
      exerciseType: 'Strength',
      trainingStyles: ['General Fitness', 'Bodybuilding'],
      categories: ['Compound', 'Machine'],
      equipment: ['Assisted Pull-Up Machine'],
      difficulty: 'Beginner',
      movementPattern: 'Push',
      goalTags: ['Strength', 'Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: ['Shoulders', 'Chest'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['bench_dip', 'tricep_pushdown'],
      progressions: ['tricep_dip'],
      regressions: ['bench_dip'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/assisted_dip_machine.gif',
      videoUrl: '',
      steps: [
        'Set weight assistance on machine and place knees/feet on pad.',
        'Grip parallel handles, keep elbows tucked close to ribs to target triceps.',
        'Lower your body by bending elbows, then press back up to starting lockout.'
      ],
      commonMistakes: ['Shrugging shoulders', 'Lowering too deep', 'Elbows flaring out'],
      safetyTips: ['Keep shoulders back and chest up'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Lateral Head', 'Medial Head', 'Machine', 'Beginner', 'Compound', 'Push', 'Upper Body'],
    ),

    // 2. Barbell Overhead Tricep Extension
    Exercise(
      exerciseId: 'barbell_overhead_tricep_extension',
      name: 'Barbell Overhead Tricep Extension',
      aliases: ['Barbell Overhead Extension', 'Standing Barbell Extension'],
      muscleGroup: 'Triceps',
      targetRegions: ['Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'Strength Training'],
      categories: ['Barbell', 'Isolation'],
      equipment: ['Barbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Extension',
      goalTags: ['Long Head Development', 'Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['dumbbell_overhead_extension', 'ez_bar_overhead_extension'],
      progressions: ['heavy_barbell_overhead_extension'],
      regressions: ['resistance_band_overhead_tricep_extension'],
      thumbnail: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand holding barbell overhead with shoulder-width grip.',
        'Lower bar behind your head by bending elbows, keeping upper arms vertical next to head.',
        'Extend elbows to press bar back overhead.'
      ],
      commonMistakes: ['Elbows flaring out', 'Arching lower back', 'Wrong neck alignment'],
      safetyTips: ['Keep core tight to protect lower back'],
      breathing: 'Inhale down, exhale pressing up.',
      estimatedCaloriesPerMinute: 5.8,
      tags: ['Long Head', 'Barbell', 'Intermediate', 'Isolation', 'Triceps'],
    ),

    // 3. Bench Dip
    Exercise(
      exerciseId: 'bench_dip',
      name: 'Bench Dip',
      aliases: ['Bench Dips', 'Weighted Bench Dip'],
      muscleGroup: 'Triceps',
      targetRegions: ['Lateral Head', 'Medial Head'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'General Fitness', 'Bodybuilding'],
      categories: ['Calisthenics', 'Compound'],
      equipment: ['Bench'],
      difficulty: 'Beginner',
      movementPattern: 'Push',
      goalTags: ['Muscle Gain', 'Endurance'],
      isCompound: true,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: ['Front Delts', 'Chest'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Lower Back Safe'],
      alternatives: ['tricep_pushdown', 'assisted_dip_machine'],
      progressions: ['weighted_bench_dip', 'tricep_dip'],
      regressions: ['bench_dip_knees_bent'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/bench_dip.gif',
      videoUrl: '',
      steps: [
        'Place hands on edge of bench behind you, feet flat on floor (knees bent or straight).',
        'Lower hips by bending elbows, keeping back close to bench.',
        'Press through hands to return to starting lockout.'
      ],
      commonMistakes: ['Elbows flaring', 'Moving too far forward away from bench'],
      safetyTips: ['Do not lower hips past shoulder line to protect rotators'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Lateral Head', 'Medial Head', 'Bodyweight', 'Beginner', 'Compound', 'Push', 'Upper Body'],
    ),

    // 4. Bodyweight Tricep Extension
    Exercise(
      exerciseId: 'bodyweight_tricep_extension',
      name: 'Bodyweight Tricep Extension',
      aliases: ['Bench Bodyweight Extension', 'Tiger Bend Push Up'],
      muscleGroup: 'Triceps',
      targetRegions: ['Long Head', 'Lateral Head'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics'],
      categories: ['Calisthenics', 'Compound'],
      equipment: ['Bench', 'Bodyweight'],
      difficulty: 'Intermediate',
      movementPattern: 'Extension',
      goalTags: ['Strength', 'Core Stability'],
      isCompound: true,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: ['Core'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['skull_crusher', 'tricep_pushdown'],
      progressions: ['floor_bodyweight_tricep_extension'],
      regressions: ['incline_bodyweight_tricep_extension'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Place hands on a bench or bar at chest height, extend feet back in high plank.',
        'Lower head under hands by bending elbows, keeping elbows tucked close.',
        'Press through palms to extend elbows back to plank.'
      ],
      commonMistakes: ['Sagging hips', 'Elbows flaring'],
      safetyTips: ['Brace core intensely'],
      breathing: 'Inhale down, exhale pressing up.',
      estimatedCaloriesPerMinute: 6.2,
      tags: ['Long Head', 'Lateral Head', 'Bodyweight', 'Intermediate', 'Compound', 'Push', 'Upper Body'],
    ),

    // 5. Cable Tricep Kickback
    Exercise(
      exerciseId: 'cable_tricep_kickback',
      name: 'Cable Tricep Kickback',
      aliases: ['Cable Kickbacks', 'Single Arm Cable Kickback'],
      muscleGroup: 'Triceps',
      targetRegions: ['Lateral Head', 'Medial Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable'],
      difficulty: 'Beginner',
      movementPattern: 'Extension',
      goalTags: ['Muscle Gain', 'Constant Tension'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Unilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['dumbbell_kickback', 'tricep_pushdown'],
      progressions: ['heavy_cable_kickback_tricep'],
      regressions: ['resistance_band_kickback'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/cable_tricep_kickback.gif',
      videoUrl: '',
      steps: [
        'Stand facing low cable pulley, holding cable sleeve with one hand.',
        'Hinge at hips, bend elbow at 90 degrees next to ribs.',
        'Extend arm straight back, squeezing tricep at extension.',
        'Slowly return to start.'
      ],
      commonMistakes: ['Elbow dropping', 'Using torso swing'],
      safetyTips: ['Keep shoulder locked completely still'],
      breathing: 'Exhale extending, inhale returning.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Lateral Head', 'Medial Head', 'Cable', 'Beginner', 'Isolation', 'Triceps'],
    ),

    // 6. Cable Skull Crusher
    Exercise(
      exerciseId: 'cable_skull_crusher',
      name: 'Cable Skull Crusher',
      aliases: ['Cable Lying Tricep Extension'],
      muscleGroup: 'Triceps',
      targetRegions: ['Long Head', 'Lateral Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation', 'Bench'],
      equipment: ['Cable', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Extension',
      goalTags: ['Muscle Gain', 'Constant Tension'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['skull_crusher', 'overhead_cable_tricep_extension'],
      progressions: ['heavy_cable_skull_crusher'],
      regressions: ['tricep_pushdown'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/cable_skull_crusher.gif',
      videoUrl: '',
      steps: [
        'Place flat bench in front of low cable stack.',
        'Lie back holding straight bar attachment overhead, arms angled slightly back toward cable.',
        'Bend elbows to lower bar to forehead, then extend back to starting angle.'
      ],
      commonMistakes: ['Elbows flaring', 'Arm angle drifting vertical (loses tension)'],
      safetyTips: ['Start with light weight to coordinate the cable pull angle'],
      breathing: 'Inhale down, exhale extending up.',
      estimatedCaloriesPerMinute: 5.2,
      tags: ['Long Head', 'Lateral Head', 'Cable', 'Intermediate', 'Isolation', 'Triceps'],
    ),

    // 7. Close Grip Push Up
    Exercise(
      exerciseId: 'close_grip_push_up',
      name: 'Close Grip Push Up',
      aliases: ['Close Grip Push-ups', 'Tricep Pushup'],
      muscleGroup: 'Triceps',
      targetRegions: ['Lateral Head', 'Medial Head'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'General Fitness'],
      categories: ['Calisthenics', 'Compound'],
      equipment: ['Bodyweight'],
      difficulty: 'Beginner',
      movementPattern: 'Push',
      goalTags: ['Strength', 'Muscle Gain'],
      isCompound: true,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: ['Chest', 'Shoulders', 'Core'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: [],
      alternatives: ['bench_dip', 'tricep_pushdown'],
      progressions: ['diamond_push_up'],
      regressions: ['knee_push_up'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/close_grip_push_up.gif',
      videoUrl: '',
      steps: [
        'Set up in high plank, hands slightly narrower than shoulder-width.',
        'Lower chest to floor, keeping elbows tucked tightly to ribs.',
        'Press back to plank.'
      ],
      commonMistakes: ['Elbows flaring', 'Hips sagging'],
      safetyTips: ['Keep core actively braced'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Lateral Head', 'Medial Head', 'Bodyweight', 'Beginner', 'Compound', 'Push', 'Upper Body'],
    ),

    // 8. Cross Body Cable Pushdown
    Exercise(
      exerciseId: 'cross_body_cable_pushdown',
      name: 'Cross Body Cable Pushdown',
      aliases: ['Cross-Body Pushdowns'],
      muscleGroup: 'Triceps',
      targetRegions: ['Lateral Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable'],
      difficulty: 'Intermediate',
      movementPattern: 'Extension',
      goalTags: ['Lateral Head Isolation', 'Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['tricep_pushdown', 'rope_pushdown'],
      progressions: ['heavy_cross_body_pushdown'],
      regressions: ['single_arm_cable_pushdown'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/cross_body_cable_pushdown.gif',
      videoUrl: '',
      steps: [
        'Stand facing dual cable machine pulleys set high.',
        'Grip left cable with right hand, right cable with left hand (crossover).',
        'Extend elbows down and out to sides, keeping arms close to body.'
      ],
      commonMistakes: ['Elbows drifting', 'Hunching shoulders forward'],
      safetyTips: ['Do not use excessively heavy weights to maintain form'],
      breathing: 'Exhale down, inhale up.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Lateral Head', 'Cable', 'Intermediate', 'Isolation', 'Triceps'],
    ),

    // 9. Decline Skull Crusher
    Exercise(
      exerciseId: 'decline_skull_crusher',
      name: 'Decline Skull Crusher',
      aliases: ['Decline Lying Tricep Extension'],
      muscleGroup: 'Triceps',
      targetRegions: ['Long Head', 'Lateral Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Dumbbell', 'EZ Bar', 'Bench', 'Isolation'],
      equipment: ['EZ Bar', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Extension',
      goalTags: ['Long Head Development', 'Triceps Mass'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['skull_crusher', 'incline_skull_crusher'],
      progressions: ['heavy_decline_skull_crusher'],
      regressions: ['tricep_pushdown'],
      thumbnail: 'https://images.unsplash.com/photo-1534368786749-b63e05c4a4fb?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/decline_skull_crusher.gif',
      videoUrl: '',
      steps: [
        'Lie back on decline bench holding barbell/EZ-bar overhead, arms angled slightly back toward head.',
        'Bend elbows to lower bar to forehead/top of head.',
        'Extend elbows to press back up.'
      ],
      commonMistakes: ['Elbows flaring', 'Moving shoulders'],
      safetyTips: ['Use a spotter or start very light on decline'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 5.8,
      tags: ['Long Head', 'Lateral Head', 'EZ Bar', 'Intermediate', 'Isolation', 'Triceps'],
    ),

    // 10. Dumbbell Kickback
    Exercise(
      exerciseId: 'dumbbell_kickback',
      name: 'Dumbbell Kickback',
      aliases: ['DB Tricep Kickback', 'Dumbbell Kickbacks'],
      muscleGroup: 'Triceps',
      targetRegions: ['Lateral Head', 'Medial Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Dumbbell', 'Isolation'],
      equipment: ['Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Extension',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Travel'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['cable_tricep_kickback', 'tricep_pushdown'],
      progressions: ['cable_tricep_kickback'],
      regressions: ['resistance_band_kickback'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/dumbbell_kickback.gif',
      videoUrl: '',
      steps: [
        'Hinge forward holding dumbbells, elbows bent at 90 degrees next to ribs.',
        'Extend elbows to push dumbbells straight back, squeezing triceps.',
        'Slowly return to start.'
      ],
      commonMistakes: ['Elbow dropping', 'Using momentum', 'Rounding back'],
      safetyTips: ['Keep back flat and neck neutral'],
      breathing: 'Exhale back, inhale forward.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Lateral Head', 'Medial Head', 'Dumbbell', 'Beginner', 'Isolation', 'Triceps'],
    ),

    // 11. Dumbbell Overhead Tricep Extension
    Exercise(
      exerciseId: 'dumbbell_overhead_tricep_extension',
      name: 'Dumbbell Overhead Tricep Extension',
      aliases: ['DB Overhead Extension', 'Standing Dumbbell Extension'],
      muscleGroup: 'Triceps',
      targetRegions: ['Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Dumbbell', 'Isolation'],
      equipment: ['Dumbbell'],
      difficulty: 'Beginner',
      movementPattern: 'Extension',
      goalTags: ['Long Head Growth', 'Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Travel'],
      injuryFriendly: [],
      alternatives: ['barbell_overhead_tricep_extension', 'ez_bar_overhead_tricep_extension'],
      progressions: ['heavy_dumbbell_overhead_extension'],
      regressions: ['resistance_band_overhead_tricep_extension'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Stand or sit holding one dumbbell overhead with both hands (diamond grip).',
        'Lower weight behind head by bending elbows.',
        'Extend elbows to press weight back overhead.'
      ],
      commonMistakes: ['Elbows flaring', 'Arching lower back'],
      safetyTips: ['Keep core braced to protect lower spine'],
      breathing: 'Inhale down, exhale pressing up.',
      estimatedCaloriesPerMinute: 5.0,
      tags: ['Long Head', 'Dumbbell', 'Beginner', 'Isolation', 'Triceps'],
    ),

    // 12. Dumbbell Skull Crusher
    Exercise(
      exerciseId: 'dumbbell_skull_crusher',
      name: 'Dumbbell Skull Crusher',
      aliases: ['DB Skull Crushers', 'Dumbbell Lying Tricep Extension'],
      muscleGroup: 'Triceps',
      targetRegions: ['Long Head', 'Lateral Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Dumbbell', 'Bench', 'Isolation'],
      equipment: ['Dumbbell', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Extension',
      goalTags: ['Muscle Gain', 'Triceps Mass'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['skull_crusher', 'cable_skull_crusher'],
      progressions: ['heavy_dumbbell_skull_crusher'],
      regressions: ['tricep_pushdown'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/dumbbell_skull_crusher.gif',
      videoUrl: '',
      steps: [
        'Lie flat on bench holding dumbbells overhead, palms facing each other.',
        'Lower weights toward ears by bending elbows, keeping upper arms stationary.',
        'Extend elbows back to start.'
      ],
      commonMistakes: ['Elbows flaring', 'Moving shoulder joints'],
      safetyTips: ['Keep dumbbells balanced securely to avoid dropping'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Long Head', 'Lateral Head', 'Dumbbell', 'Intermediate', 'Isolation', 'Triceps'],
    ),

    // 13. EZ Bar Overhead Tricep Extension
    Exercise(
      exerciseId: 'ez_bar_overhead_tricep_extension',
      name: 'EZ Bar Overhead Tricep Extension',
      aliases: ['EZ Bar Overhead Extension'],
      muscleGroup: 'Triceps',
      targetRegions: ['Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Barbell', 'Isolation'],
      equipment: ['EZ Bar'],
      difficulty: 'Intermediate',
      movementPattern: 'Extension',
      goalTags: ['Long Head Growth'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Wrist Friendly'],
      alternatives: ['barbell_overhead_tricep_extension', 'dumbbell_overhead_tricep_extension'],
      progressions: ['heavy_ez_bar_overhead_extension'],
      regressions: ['resistance_band_overhead_tricep_extension'],
      thumbnail: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/ez_bar_overhead_tricep_extension.gif',
      videoUrl: '',
      steps: [
        'Stand holding EZ-bar overhead on angled grips.',
        'Lower bar behind head by bending elbows, keeping upper arms vertical.',
        'Extend elbows to press bar back overhead.'
      ],
      commonMistakes: ['Elbows flaring', 'Arching back'],
      safetyTips: ['Angled bar grips reduce wrist strain compared to straight barbell'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Long Head', 'EZ Bar', 'Intermediate', 'Isolation', 'Triceps'],
    ),

    // 14. EZ Bar Skull Crusher
    Exercise(
      exerciseId: 'ez_bar_skull_crusher',
      name: 'EZ Bar Skull Crusher',
      aliases: ['EZ-Bar Lying Tricep Extension'],
      muscleGroup: 'Triceps',
      targetRegions: ['Long Head', 'Lateral Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Barbell', 'Bench', 'Isolation'],
      equipment: ['EZ Bar', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Extension',
      goalTags: ['Muscle Gain', 'Triceps Mass'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Wrist Friendly'],
      alternatives: ['skull_crusher', 'dumbbell_skull_crusher'],
      progressions: ['heavy_ez_bar_skull_crusher'],
      regressions: ['tricep_pushdown'],
      thumbnail: 'https://images.unsplash.com/photo-1534368786749-b63e05c4a4fb?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Lie flat on bench holding EZ-bar overhead, arms angled slightly back toward head.',
        'Lower bar toward forehead by bending elbows.',
        'Extend elbows to press bar back up.'
      ],
      commonMistakes: ['Elbows flaring', 'Spine arching'],
      safetyTips: ['Keep upper arms stationary'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Long Head', 'Lateral Head', 'EZ Bar', 'Intermediate', 'Isolation', 'Triceps'],
    ),

    // 15. Floor Skull Crusher
    Exercise(
      exerciseId: 'floor_skull_crusher',
      name: 'Floor Skull Crusher',
      aliases: ['Barbell Floor Skull Crusher'],
      muscleGroup: 'Triceps',
      targetRegions: ['Long Head', 'Lateral Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'Powerlifting'],
      categories: ['Barbell', 'Isolation'],
      equipment: ['Barbell', 'EZ Bar'],
      difficulty: 'Intermediate',
      movementPattern: 'Extension',
      goalTags: ['Triceps Mass', 'Lockout Power'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: ['Shoulder Friendly'],
      alternatives: ['skull_crusher', 'floor_press'],
      progressions: ['heavy_floor_skull_crusher'],
      regressions: ['tricep_pushdown'],
      thumbnail: 'https://images.unsplash.com/photo-1534368786749-b63e05c4a4fb?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/floor_skull_crusher.gif',
      videoUrl: '',
      steps: [
        'Lie flat on floor with knees bent (feet flat).',
        'Hold EZ-bar overhead, arms angled slightly back toward head.',
        'Lower bar toward floor behind head by bending elbows, then extend back to start.'
      ],
      commonMistakes: ['Bouncing bar off floor', 'Rounding back'],
      safetyTips: ['Allows shoulder safety since range is blocked by floor'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Long Head', 'Lateral Head', 'EZ Bar', 'Intermediate', 'Isolation', 'Triceps'],
    ),

    // 16. Heavy Rope Pushdown
    Exercise(
      exerciseId: 'heavy_rope_pushdown',
      name: 'Heavy Rope Pushdown',
      aliases: ['Heavy Rope Cable Pushdown'],
      muscleGroup: 'Triceps',
      targetRegions: ['Lateral Head', 'Medial Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'Strength Training'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable', 'Heavy Rope'],
      difficulty: 'Intermediate',
      movementPattern: 'Extension',
      goalTags: ['Muscle Gain', 'Grip Endurance'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['rope_pushdown', 'v_bar_pushdown'],
      progressions: ['heavy_rope_pushdown_max'],
      regressions: ['rope_pushdown'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Setup identically to Rope Pushdown but using a thick, heavy-duty rope.',
        'Press down and flare ends out.'
      ],
      commonMistakes: ['Using torso momentum', 'Shrugging shoulders'],
      safetyTips: ['Maintain wrist stability'],
      breathing: 'Exhale down, inhale up.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Lateral Head', 'Medial Head', 'Cable', 'Intermediate', 'Isolation', 'Triceps'],
    ),

    // 17. Incline Skull Crusher
    Exercise(
      exerciseId: 'incline_skull_crusher',
      name: 'Incline Skull Crusher',
      aliases: ['Incline Lying Tricep Extension'],
      muscleGroup: 'Triceps',
      targetRegions: ['Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Dumbbell', 'EZ Bar', 'Bench', 'Isolation'],
      equipment: ['EZ Bar', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Extension',
      goalTags: ['Long Head Stretch', 'Triceps Mass'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['skull_crusher', 'decline_skull_crusher'],
      progressions: ['heavy_incline_skull_crusher'],
      regressions: ['tricep_pushdown'],
      thumbnail: 'https://images.unsplash.com/photo-1534368786749-b63e05c4a4fb?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/incline_skull_crusher.gif',
      videoUrl: '',
      steps: [
        'Lie back on incline bench (set to 30-45 degrees) holding barbell/EZ-bar overhead, arms angled slightly back toward head.',
        'Lower bar toward forehead/top of head by bending elbows, achieving deep stretch in long head.',
        'Extend elbows to press bar back up.'
      ],
      commonMistakes: ['Elbows flaring', 'Drifting arms vertical'],
      safetyTips: ['Keep elbows tucked'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 5.8,
      tags: ['Long Head', 'EZ Bar', 'Intermediate', 'Isolation', 'Triceps'],
    ),

    // 18. JM Press
    Exercise(
      exerciseId: 'jm_press',
      name: 'JM Press',
      aliases: ['Barbell JM Press'],
      muscleGroup: 'Triceps',
      targetRegions: ['Lateral Head', 'Medial Head'],
      exerciseType: 'Strength',
      trainingStyles: ['Powerlifting', 'Strength Training'],
      categories: ['Barbell', 'Bench', 'Compound'],
      equipment: ['Barbell', 'Bench'],
      difficulty: 'Advanced',
      movementPattern: 'Push',
      goalTags: ['Lockout Strength', 'Triceps Mass'],
      isCompound: true,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: ['Chest', 'Shoulders'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['close_grip_bench_press', 'skull_crusher'],
      progressions: ['heavy_jm_press'],
      regressions: ['close_grip_bench_press'],
      thumbnail: 'https://images.unsplash.com/photo-1534368786749-b63e05c4a4fb?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/jm_press.gif',
      videoUrl: '',
      steps: [
        'Lie flat on bench, grip bar with narrow grip (close-grip bench style).',
        'Lower barbell by bending elbows while aiming bar toward throat/chin (elbows flare slightly forward, not tucked like normal close-grip bench).',
        'Pause briefly, then press barbell back to lockout.'
      ],
      commonMistakes: ['Turning it into a standard bench press', 'Bar paths hitting neck', 'Going too heavy too fast'],
      safetyTips: ['Always use safety pins or active spotter on JM Press; it is highly demanding on elbows'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 8.5,
      tags: ['Lateral Head', 'Medial Head', 'Barbell', 'Advanced', 'Compound', 'Triceps'],
    ),

    // 19. Machine Tricep Extension
    Exercise(
      exerciseId: 'machine_tricep_extension',
      name: 'Machine Tricep Extension',
      aliases: ['Seated Tricep Extension Machine'],
      muscleGroup: 'Triceps',
      targetRegions: ['Lateral Head', 'Medial Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Machine', 'Isolation'],
      equipment: ['Machine'],
      difficulty: 'Beginner',
      movementPattern: 'Extension',
      goalTags: ['Muscle Gain', 'Triceps Isolation'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['tricep_pushdown', 'bench_dip'],
      progressions: ['heavy_machine_tricep_extension'],
      regressions: ['resistance_band_pushdown'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/machine_tricep_extension.gif',
      videoUrl: '',
      steps: [
        'Adjust machine seat so elbows align with pivot point.',
        'Sit back, grip handles, and press downward/forward to full elbow extension.',
        'Slowly return to start.'
      ],
      commonMistakes: ['Glutes lifting off seat', 'Letting weights slam'],
      safetyTips: ['Keep elbows supported on pad throughout range'],
      breathing: 'Exhale extending, inhale returning.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Lateral Head', 'Medial Head', 'Machine', 'Beginner', 'Isolation', 'Triceps'],
    ),

    // 20. Overhead Cable Tricep Extension
    Exercise(
      exerciseId: 'overhead_cable_tricep_extension',
      name: 'Overhead Cable Tricep Extension',
      aliases: ['Overhead Cable Extension', 'High Pulley Overhead Extension'],
      muscleGroup: 'Triceps',
      targetRegions: ['Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable'],
      difficulty: 'Intermediate',
      movementPattern: 'Extension',
      goalTags: ['Long Head Development', 'Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['dumbbell_overhead_tricep_extension', 'overhead_rope_tricep_extension'],
      progressions: ['heavy_overhead_cable_extension'],
      regressions: ['resistance_band_overhead_tricep_extension'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Attach rope/straight bar to high cable pulley.',
        'Hold handles, stand facing away, step forward into split stance, and lean torso forward.',
        'Hold upper arms next to head, elbows bent.',
        'Extend elbows forward to push weights out, then slowly return.'
      ],
      commonMistakes: ['Elbows flaring wide', 'Torso rocking (using momentum)'],
      safetyTips: ['Step forward with one foot for stable stance support'],
      breathing: 'Exhale extending, inhale returning.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Long Head', 'Cable', 'Intermediate', 'Isolation', 'Triceps'],
    ),

    // 21. Overhead Rope Tricep Extension
    Exercise(
      exerciseId: 'overhead_rope_tricep_extension',
      name: 'Overhead Rope Tricep Extension',
      aliases: ['Overhead Rope Extension'],
      muscleGroup: 'Triceps',
      targetRegions: ['Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable', 'Rope Attachment'],
      difficulty: 'Intermediate',
      movementPattern: 'Extension',
      goalTags: ['Long Head Growth'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['overhead_cable_tricep_extension', 'dumbbell_overhead_tricep_extension'],
      progressions: ['heavy_overhead_rope_extension'],
      regressions: ['resistance_band_overhead_tricep_extension'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Perform overhead cable extension using rope attachment.',
        'Separate rope ends at peak extension to maximize tricep contraction.'
      ],
      commonMistakes: ['Elbows flaring', 'Short range of motion'],
      safetyTips: ['Maintain stable split stance'],
      breathing: 'Exhale extending, inhale returning.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Long Head', 'Cable', 'Intermediate', 'Isolation', 'Triceps'],
    ),

    // 22. Resistance Band Kickback
    Exercise(
      exerciseId: 'resistance_band_kickback',
      name: 'Resistance Band Kickback',
      aliases: ['Band Tricep Kickback'],
      muscleGroup: 'Triceps',
      targetRegions: ['Lateral Head', 'Medial Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['General Fitness', 'Travel Fitness'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Resistance Band'],
      difficulty: 'Beginner',
      movementPattern: 'Extension',
      goalTags: ['Conditioning', 'Rehab'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Joint Friendly'],
      alternatives: ['dumbbell_kickback', 'cable_tricep_kickback'],
      progressions: ['dumbbell_kickback'],
      regressions: ['lighter_band_kickback'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/resistance_band_kickback.gif',
      videoUrl: '',
      steps: [
        'Anchor band in front of you at chest height.',
        'Hinge at hips, bend elbow at 90 degrees next to ribs.',
        'Extend arm straight back against band resistance.'
      ],
      commonMistakes: ['Elbow dropping', 'Band slipping'],
      safetyTips: ['Ensure anchor point is highly secure'],
      breathing: 'Exhale back, inhale forward.',
      estimatedCaloriesPerMinute: 4.0,
      tags: ['Lateral Head', 'Medial Head', 'Resistance Band', 'Beginner', 'Isolation', 'Triceps'],
    ),

    // 23. Resistance Band Overhead Tricep Extension
    Exercise(
      exerciseId: 'resistance_band_overhead_tricep_extension',
      name: 'Resistance Band Overhead Tricep Extension',
      aliases: ['Band Overhead Extension'],
      muscleGroup: 'Triceps',
      targetRegions: ['Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['General Fitness', 'Travel Fitness'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Resistance Band'],
      difficulty: 'Beginner',
      movementPattern: 'Extension',
      goalTags: ['Long Head Growth', 'Conditioning'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Joint Friendly'],
      alternatives: ['dumbbell_overhead_tricep_extension', 'barbell_overhead_tricep_extension'],
      progressions: ['dumbbell_overhead_tricep_extension'],
      regressions: ['lighter_band_overhead_extension'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Step on band, pull handle behind back and hold overhead with elbows bent.',
        'Extend arms straight overhead against band resistance.'
      ],
      commonMistakes: ['Arching back', 'Flaring elbows'],
      safetyTips: ['Check band for tears before standing on it'],
      breathing: 'Exhale pressing, inhale down.',
      estimatedCaloriesPerMinute: 4.0,
      tags: ['Long Head', 'Resistance Band', 'Beginner', 'Isolation', 'Triceps'],
    ),

    // 24. Resistance Band Pushdown
    Exercise(
      exerciseId: 'resistance_band_pushdown',
      name: 'Resistance Band Pushdown',
      aliases: ['Band Tricep Pushdown'],
      muscleGroup: 'Triceps',
      targetRegions: ['Lateral Head', 'Medial Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['General Fitness', 'Travel Fitness'],
      categories: ['Isolation', 'Bodyweight'],
      equipment: ['Resistance Band'],
      difficulty: 'Beginner',
      movementPattern: 'Extension',
      goalTags: ['Conditioning', 'Rehab'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor', 'Travel'],
      injuryFriendly: ['Joint Friendly'],
      alternatives: ['tricep_pushdown', 'rope_pushdown'],
      progressions: ['tricep_pushdown'],
      regressions: ['lighter_band_pushdown'],
      thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/resistance_band_pushdown.gif',
      videoUrl: '',
      steps: [
        'Anchor band high overhead.',
        'Grip ends of band and tuck elbows to sides.',
        'Extend elbows down to hips against band resistance.'
      ],
      commonMistakes: ['Elbows flaring', 'Standing too close to anchor'],
      safetyTips: ['Verify anchor security'],
      breathing: 'Exhale down, inhale up.',
      estimatedCaloriesPerMinute: 4.0,
      tags: ['Lateral Head', 'Medial Head', 'Resistance Band', 'Beginner', 'Isolation', 'Triceps'],
    ),

    // 25. Reverse Grip Pushdown
    Exercise(
      exerciseId: 'reverse_grip_pushdown',
      name: 'Reverse Grip Pushdown',
      aliases: ['Underhand Cable Pushdown'],
      muscleGroup: 'Triceps',
      targetRegions: ['Medial Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable'],
      difficulty: 'Beginner',
      movementPattern: 'Extension',
      goalTags: ['Medial Head Isolation', 'Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: ['Forearms'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['tricep_pushdown', 'straight_bar_pushdown'],
      progressions: ['heavy_reverse_grip_pushdown'],
      regressions: ['rope_pushdown'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/reverse_grip_pushdown.gif',
      videoUrl: '',
      steps: [
        'Grip straight bar on high pulley underhand (palms facing up).',
        'Tuck elbows to ribs and press bar down to hips by extending elbows.'
      ],
      commonMistakes: ['Elbows drifting', 'Wrist bending under pressure'],
      safetyTips: ['Keep wrist joints locked and firm'],
      breathing: 'Exhale down, inhale up.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Medial Head', 'Cable', 'Beginner', 'Isolation', 'Triceps'],
    ),

    // 26. Ring Tricep Extension
    Exercise(
      exerciseId: 'ring_tricep_extension',
      name: 'Ring Tricep Extension',
      aliases: ['Gymnastic Ring Tricep Extension'],
      muscleGroup: 'Triceps',
      targetRegions: ['Long Head', 'Lateral Head'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Gymnastics'],
      categories: ['Calisthenics', 'Compound'],
      equipment: ['Gymnastic Rings'],
      difficulty: 'Advanced',
      movementPattern: 'Extension',
      goalTags: ['Shoulder Stability', 'Triceps Strength'],
      isCompound: true,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: ['Core', 'Shoulder Stabilizers'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['bodyweight_tricep_extension', 'trx_tricep_extension'],
      progressions: ['single_arm_ring_extension'],
      regressions: ['bodyweight_tricep_extension'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Grip gymnastic rings suspended slightly above floor, feet back in plank.',
        'Lower head under hands by bending elbows, keeping elbows tucked close.',
        'Press through palms to extend elbows back to plank.'
      ],
      commonMistakes: ['Rings drifting outward', 'Hips sagging'],
      safetyTips: ['Keep core tightly braced; start with rings higher to reduce load'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 7.0,
      tags: ['Long Head', 'Lateral Head', 'Gymnastic Rings', 'Advanced', 'Compound', 'Push', 'Upper Body'],
    ),

    // 27. Rope Pushdown
    Exercise(
      exerciseId: 'rope_pushdown',
      name: 'Rope Pushdown',
      aliases: ['Cable Rope Pushdowns'],
      muscleGroup: 'Triceps',
      targetRegions: ['Lateral Head', 'Medial Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable', 'Rope Attachment'],
      difficulty: 'Beginner',
      movementPattern: 'Extension',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['tricep_pushdown', 'straight_bar_pushdown'],
      progressions: ['heavy_rope_pushdown'],
      regressions: ['resistance_band_pushdown'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/rope_pushdown.gif',
      videoUrl: '',
      steps: [
        'Attach rope to high pulley stack.',
        'Grip rope ends, tuck elbows to ribs.',
        'Press down and flare rope ends out at bottom.'
      ],
      commonMistakes: ['Elbows drifting', 'Hunched back'],
      safetyTips: ['Maintain neutral spine'],
      breathing: 'Exhale down, inhale up.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Lateral Head', 'Medial Head', 'Cable', 'Beginner', 'Isolation', 'Triceps'],
    ),

    // 28. Seated Dip Machine
    Exercise(
      exerciseId: 'seated_dip_machine',
      name: 'Seated Dip Machine',
      aliases: ['Seated Machine Dip'],
      muscleGroup: 'Triceps',
      targetRegions: ['Lateral Head', 'Medial Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Machine', 'Compound'],
      equipment: ['Machine'],
      difficulty: 'Beginner',
      movementPattern: 'Push',
      goalTags: ['Muscle Gain', 'Triceps Power'],
      isCompound: true,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: ['Chest', 'Shoulders'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Friendly'],
      alternatives: ['assisted_dip_machine', 'bench_dip'],
      progressions: ['tricep_dip'],
      regressions: ['bench_dip'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/seated_dip_machine.gif',
      videoUrl: '',
      steps: [
        'Sit on dip machine, secure thigh pad.',
        'Grip handles at sides, press downward to lockout.',
        'Slowly return to start.'
      ],
      commonMistakes: ['Shoulders shrugging', 'Thighs lifting off pad'],
      safetyTips: ['Ensure proper seat pad height settings'],
      breathing: 'Exhale pressing, inhale returning.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Lateral Head', 'Medial Head', 'Machine', 'Beginner', 'Compound', 'Push', 'Upper Body'],
    ),

    // 29. Single Arm Cable Pushdown
    Exercise(
      exerciseId: 'single_arm_cable_pushdown',
      name: 'Single Arm Cable Pushdown',
      aliases: ['One Arm Cable Pushdown'],
      muscleGroup: 'Triceps',
      targetRegions: ['Lateral Head', 'Medial Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable'],
      difficulty: 'Beginner',
      movementPattern: 'Extension',
      goalTags: ['Muscle Balance', 'Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Unilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['tricep_pushdown', 'dumbbell_kickback'],
      progressions: ['heavy_single_arm_pushdown'],
      regressions: ['resistance_band_pushdown'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/single_arm_cable_pushdown.gif',
      videoUrl: '',
      steps: [
        'Grip single pulley handle with one hand.',
        'Tuck elbow to ribs and press down to hip.'
      ],
      commonMistakes: ['Elbow drifting', 'Torso twisting'],
      safetyTips: ['Keep shoulders square'],
      breathing: 'Exhale down, inhale up.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Lateral Head', 'Medial Head', 'Cable', 'Beginner', 'Isolation', 'Triceps'],
    ),

    // 30. Single Arm Dumbbell Overhead Tricep Extension
    Exercise(
      exerciseId: 'single_arm_dumbbell_overhead_tricep_extension',
      name: 'Single Arm Dumbbell Overhead Tricep Extension',
      aliases: ['One Arm DB Overhead Extension'],
      muscleGroup: 'Triceps',
      targetRegions: ['Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Dumbbell', 'Isolation'],
      equipment: ['Dumbbell'],
      difficulty: 'Intermediate',
      movementPattern: 'Extension',
      goalTags: ['Long Head Growth', 'Muscle Balance'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Unilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Travel'],
      injuryFriendly: [],
      alternatives: ['dumbbell_overhead_tricep_extension', 'barbell_overhead_tricep_extension'],
      progressions: ['heavy_single_arm_overhead_extension'],
      regressions: ['resistance_band_overhead_tricep_extension'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Hold dumbbell in one hand straight overhead.',
        'Lower weight behind head by bending elbow, keeping upper arm vertical next to ear.',
        'Extend elbow to press back upright.'
      ],
      commonMistakes: ['Elbow flaring out wide', 'Torso leaning'],
      safetyTips: ['Use non-working hand to support active elbow if needed'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 4.5,
      tags: ['Long Head', 'Dumbbell', 'Intermediate', 'Isolation', 'Triceps'],
    ),

    // 31. Skull Crusher
    Exercise(
      exerciseId: 'skull_crusher',
      name: 'Skull Crusher',
      aliases: ['Lying Tricep Extension', 'Barbell Skull Crusher'],
      muscleGroup: 'Triceps',
      targetRegions: ['Long Head', 'Lateral Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'Powerlifting', 'Strength Training'],
      categories: ['Barbell', 'Bench', 'Isolation'],
      equipment: ['Barbell', 'Bench'],
      difficulty: 'Intermediate',
      movementPattern: 'Extension',
      goalTags: ['Triceps Mass', 'Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['ez_bar_skull_crusher', 'dumbbell_skull_crusher'],
      progressions: ['heavy_skull_crushers'],
      regressions: ['tricep_pushdown'],
      thumbnail: 'https://images.unsplash.com/photo-1534368786749-b63e05c4a4fb?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/skull_crusher.gif',
      videoUrl: '',
      steps: [
        'Lie flat on a bench holding a barbell straight above your chest.',
        'Bend your elbows to lower the bar slowly toward your forehead, keeping your upper arms vertical and stationary.',
        'Press the bar back up to the starting position by extending your elbows.'
      ],
      commonMistakes: ['Elbows flaring outward', 'Moving the shoulder joints instead of only elbows', 'Lowering bar too quickly'],
      safetyTips: ['Keep elbows tucked', 'Start with a light weight', 'Always use collar clips'],
      breathing: 'Inhale while lowering the bar, exhale as you press up.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Long Head', 'Lateral Head', 'Barbell', 'Intermediate', 'Isolation', 'Bodybuilding', 'Push', 'Upper Body'],
    ),

    // 32. Straight Bar Pushdown
    Exercise(
      exerciseId: 'straight_bar_pushdown',
      name: 'Straight Bar Pushdown',
      aliases: ['Straight Bar Cable Pushdown'],
      muscleGroup: 'Triceps',
      targetRegions: ['Lateral Head', 'Medial Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable', 'Straight Bar'],
      difficulty: 'Beginner',
      movementPattern: 'Extension',
      goalTags: ['Triceps Mass'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['tricep_pushdown', 'v_bar_pushdown'],
      progressions: ['heavy_straight_bar_pushdown'],
      regressions: ['rope_pushdown'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/straight_bar_pushdown.gif',
      videoUrl: '',
      steps: [
        'Perform pushdown using straight bar attachment on high pulley.',
        'Press bar down to thighs and squeeze.'
      ],
      commonMistakes: ['Elbows flaring', 'Wrist strain'],
      safetyTips: ['Do not lock wrist joint under heavy loads'],
      breathing: 'Exhale down, inhale up.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Lateral Head', 'Medial Head', 'Cable', 'Beginner', 'Isolation', 'Triceps'],
    ),

    // 33. Tate Press
    Exercise(
      exerciseId: 'tate_press',
      name: 'Tate Press',
      aliases: ['Dumbbell Tate Press', 'Elbows-Out Extension'],
      muscleGroup: 'Triceps',
      targetRegions: ['Long Head', 'Lateral Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Powerlifting', 'Bodybuilding'],
      categories: ['Dumbbell', 'Bench', 'Isolation'],
      equipment: ['Dumbbell', 'Bench'],
      difficulty: 'Advanced',
      movementPattern: 'Extension',
      goalTags: ['Lockout Strength', 'Triceps Mass'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home'],
      injuryFriendly: [],
      alternatives: ['dumbbell_skull_crusher', 'jm_press'],
      progressions: ['heavy_tate_press'],
      regressions: ['dumbbell_skull_crusher'],
      thumbnail: 'https://images.unsplash.com/photo-1534368786749-b63e05c4a4fb?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/tate_press.gif',
      videoUrl: '',
      steps: [
        'Lie flat on bench holding dumbbells overhead, palms facing feet.',
        'Lower weights inward toward chest, pointing elbows high and wide to sides.',
        'Press dumbbells back up to lockout, keeping elbows flared out.'
      ],
      commonMistakes: ['Wrong bar/dumbbell path (hitting chest)', 'Locking elbows too hard'],
      safetyTips: ['Move dumbbells carefully in center of chest'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 5.5,
      tags: ['Long Head', 'Lateral Head', 'Dumbbell', 'Advanced', 'Isolation', 'Triceps'],
    ),

    // 34. Tricep Dip
    Exercise(
      exerciseId: 'tricep_dip',
      name: 'Tricep Dip',
      aliases: ['Dips', 'Parallel Bar Tricep Dips'],
      muscleGroup: 'Triceps',
      targetRegions: ['Lateral Head', 'Medial Head'],
      exerciseType: 'Strength',
      trainingStyles: ['Calisthenics', 'Bodybuilding', 'CrossFit'],
      categories: ['Calisthenics', 'Strength', 'Compound'],
      equipment: ['Dip Station'],
      difficulty: 'Intermediate',
      movementPattern: 'Push',
      goalTags: ['Strength', 'Triceps Mass'],
      isCompound: true,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: ['Front Delts', 'Lower Chest'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['chest_dip', 'bench_dip'],
      progressions: ['weighted_dip'],
      regressions: ['assisted_dip_machine'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a87?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Hoist yourself up on parallel bars, arms locked out.',
        'Keep torso upright (do not lean forward like in chest dips).',
        'Lower body by bending elbows, keeping them tucked close to ribs.',
        'Press back up to lockout.'
      ],
      commonMistakes: ['Leaning forward (targets chest)', 'Elbows flaring out wide'],
      safetyTips: ['Avoid shrugging shoulders during descent'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 8.0,
      tags: ['Lateral Head', 'Medial Head', 'Bodyweight', 'Intermediate', 'Compound', 'Push', 'Upper Body'],
    ),

    // 35. Tricep Pushdown
    Exercise(
      exerciseId: 'tricep_pushdown',
      name: 'Tricep Pushdown',
      aliases: ['Cable Tricep Pushdown', 'Tricep Pushdowns'],
      muscleGroup: 'Triceps',
      targetRegions: ['Lateral Head', 'Medial Head', 'Long Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding', 'General Fitness'],
      categories: ['Bodybuilding', 'General Fitness', 'Isolation'],
      equipment: ['Cable'],
      difficulty: 'Beginner',
      movementPattern: 'Extension',
      goalTags: ['Muscle Gain'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: ['Lower Back Safe'],
      alternatives: ['close_grip_bench_press', 'dips', 'overhead_tricep_extension'],
      progressions: ['heavy_tricep_pushdowns', 'weighted_dips'],
      regressions: ['resistance_band_pushdowns'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Attach a rope or bar to a high pulley cable station.',
        'Grip the attachment and tuck your elbows firmly against your ribs.',
        'Push the rope/bar straight down by extending your elbows, separating the rope ends at the bottom.',
        'Slowly return the hands back up to elbow level.'
      ],
      commonMistakes: ['Elbows drifting forward and back', 'Leaning too far over the cable', 'Wrist extension'],
      safetyTips: ['Keep shoulders back and locked', 'Maintain a firm, neutral grip'],
      breathing: 'Exhale pushing down, inhale returning to top.',
      estimatedCaloriesPerMinute: 5.8,
      tags: ['Lateral Head', 'Medial Head', 'Long Head', 'Cable', 'Beginner', 'Isolation', 'Bodybuilding', 'Push', 'Upper Body'],
    ),

    // 36. TRX Tricep Extension
    Exercise(
      exerciseId: 'trx_tricep_extension',
      name: 'TRX Tricep Extension',
      aliases: ['Suspension Tricep Extension'],
      muscleGroup: 'Triceps',
      targetRegions: ['Long Head', 'Lateral Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Calisthenics', 'Functional Fitness'],
      categories: ['Calisthenics', 'Isolation', 'Stability'],
      equipment: ['Suspension Trainer (TRX)'],
      difficulty: 'Intermediate',
      movementPattern: 'Extension',
      goalTags: ['Triceps Strength', 'Core Stability'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: ['Core', 'Shoulder Stabilizers'],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym', 'Home', 'Outdoor'],
      injuryFriendly: [],
      alternatives: ['bodyweight_tricep_extension', 'ring_tricep_extension'],
      progressions: ['weighted_trx_extension'],
      regressions: ['incline_trx_extension'],
      thumbnail: 'https://images.unsplash.com/photo-1544033527-b192daee1f5b?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      videoUrl: '',
      steps: [
        'Hold TRX handles facing away from anchor, leaning forward in plank with arms straight forward.',
        'Bend elbows to lower head toward hands, keeping elbows pointing forward.',
        'Press through hands to return to starting plank.'
      ],
      commonMistakes: ['Elbows flaring out', 'Sagging hips'],
      safetyTips: ['Keep core braced to prevent spinal sway'],
      breathing: 'Inhale down, exhale up.',
      estimatedCaloriesPerMinute: 6.0,
      tags: ['Long Head', 'Lateral Head', 'Suspension Trainer (TRX)', 'Intermediate', 'Isolation', 'Shoulders'],
    ),

    // 37. V-Bar Pushdown
    Exercise(
      exerciseId: 'v_bar_pushdown',
      name: 'V-Bar Pushdown',
      aliases: ['V-Bar Cable Pushdown'],
      muscleGroup: 'Triceps',
      targetRegions: ['Lateral Head', 'Medial Head'],
      exerciseType: 'Hypertrophy',
      trainingStyles: ['Bodybuilding'],
      categories: ['Cable', 'Isolation'],
      equipment: ['Cable', 'V-Bar'],
      difficulty: 'Beginner',
      movementPattern: 'Extension',
      goalTags: ['Triceps Mass'],
      isCompound: false,
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      mechanics: 'Bilateral',
      forceType: 'Push',
      bodyRegion: 'Upper Body',
      environment: ['Gym'],
      injuryFriendly: [],
      alternatives: ['tricep_pushdown', 'straight_bar_pushdown'],
      progressions: ['heavy_v_bar_pushdown'],
      regressions: ['rope_pushdown'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'assets/gif/male/v_bar_pushdown.gif',
      videoUrl: '',
      steps: [
        'Perform pushdown using V-bar attachment on high pulley.',
        'Press down and squeeze.'
      ],
      commonMistakes: ['Elbows flaring', 'Wrist strain'],
      safetyTips: ['V-bar angled shape reduces wrist strain'],
      breathing: 'Exhale down, inhale up.',
      estimatedCaloriesPerMinute: 4.8,
      tags: ['Lateral Head', 'Medial Head', 'Cable', 'Beginner', 'Isolation', 'Triceps'],
    ),
  ];
}
