import '../models/models.dart';

class ExercisesData {
  static final List<Exercise> masterExercises = [
    // ───────── CHEST ─────────
    Exercise(
      exerciseId: 'bench_press',
      name: 'Bench Press',
      muscleGroup: 'Chest',
      equipmentType: 'Barbell',
      difficulty: 'Intermediate',
      categories: ['Bodybuilding', 'Powerlifting', 'General Fitness'],
      goalTags: ['Muscle Building', 'Strength'],
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Front Delts'],
      thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&auto=format&fit=crop&q=80',
      gifUrl: 'https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExM3pjdWoxMTRmMnFmOXJ5bjVtcnd2ZDh3ZnA0ajR3azhpc3g4bDNxMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o7TKLzBYFrrwRpuJW/giphy.gif',
      steps: [
        'Lie flat on the bench, feet flat on the floor. Grip the barbell slightly wider than shoulder-width.',
        'Unrack the bar and hold it directly over your chest with elbows locked.',
        'Lower the bar slowly to your mid-chest while keeping your elbows at a 45-degree angle.',
        'Push the bar back up powerfully to the starting position, extending your arms fully.'
      ],
      alternatives: ['incline_db_press', 'chest_press_machine', 'push_ups'],
      isCompound: true,
    ),
    Exercise(
      exerciseId: 'incline_db_press',
      name: 'Incline Dumbbell Press',
      muscleGroup: 'Chest',
      equipmentType: 'Dumbbell',
      difficulty: 'Intermediate',
      categories: ['Bodybuilding', 'General Fitness'],
      goalTags: ['Muscle Building', 'Strength'],
      primaryMuscles: ['Upper Chest'],
      secondaryMuscles: ['Front Delts', 'Triceps'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Set an incline bench to around 30 to 45 degrees. Sit with a dumbbell in each hand on your thighs.',
        'Lie back, bringing the weights to shoulder level with elbows bent at 90 degrees.',
        'Press the dumbbells straight up over your upper chest, locking your elbows at the top.',
        'Lower the weights slowly under control back to the sides of your chest.'
      ],
      alternatives: ['bench_press', 'chest_press_machine', 'dumbbell_fly'],
      isCompound: true,
    ),
    Exercise(
      exerciseId: 'push_ups',
      name: 'Push Ups',
      muscleGroup: 'Chest',
      equipmentType: 'Bodyweight',
      difficulty: 'Beginner',
      categories: ['Calisthenics', 'CrossFit', 'General Fitness', 'Fat Loss'],
      goalTags: ['Endurance', 'Conditioning'],
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Core', 'Front Delts'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Place hands on the floor slightly wider than shoulder-width, extend legs back in a plank position.',
        'Keep your body in a straight line from head to heels, core engaged.',
        'Lower your chest toward the floor by bending your elbows back at a 45-degree angle.',
        'Push away from the floor back to the starting plank position.'
      ],
      alternatives: ['decline_push_ups', 'bench_press', 'dips'],
      isCompound: true,
    ),
    Exercise(
      exerciseId: 'archer_push_ups',
      name: 'Archer Push Ups',
      muscleGroup: 'Chest',
      equipmentType: 'Bodyweight',
      difficulty: 'Advanced',
      categories: ['Calisthenics'],
      goalTags: ['Strength', 'Muscle Building'],
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Shoulders', 'Core'],
      thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Get into a pushup position but with your hands placed much wider than normal, fingers pointing outward.',
        'Lower yourself to one side, keeping that arm close to your body while extending the opposite arm straight out.',
        'Push yourself back up to the center using the bent arm.',
        'Repeat on the opposite side to complete one rep.'
      ],
      alternatives: ['push_ups', 'ring_push_ups'],
      isCompound: true,
    ),
    Exercise(
      exerciseId: 'decline_push_ups',
      name: 'Decline Push Ups',
      muscleGroup: 'Chest',
      equipmentType: 'Bodyweight',
      difficulty: 'Intermediate',
      categories: ['Calisthenics', 'General Fitness'],
      goalTags: ['Muscle Building'],
      primaryMuscles: ['Upper Chest'],
      secondaryMuscles: ['Shoulders', 'Triceps', 'Core'],
      thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Place your feet on an elevated surface like a bench or step, and hands on the floor in front of you.',
        'Maintain a straight body plank, elbows extended.',
        'Lower your chest slowly toward the floor.',
        'Push back up to the starting position.'
      ],
      alternatives: ['push_ups', 'dips'],
      isCompound: true,
    ),
    Exercise(
      exerciseId: 'ring_push_ups',
      name: 'Ring Push Ups',
      muscleGroup: 'Chest',
      equipmentType: 'Bodyweight',
      difficulty: 'Advanced',
      categories: ['Calisthenics', 'CrossFit'],
      goalTags: ['Strength', 'Stability'],
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Core', 'Shoulder Stabilizers', 'Triceps'],
      thumbnail: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Grip gymnastic rings suspended slightly above the floor and extend your feet back into a plank.',
        'Keep your body rigid and slowly lower your chest between the rings.',
        'Turn your hands slightly outward at the bottom for chest stretch.',
        'Push back up, bringing the rings close together at the top.'
      ],
      alternatives: ['push_ups', 'dips'],
      isCompound: true,
    ),
    Exercise(
      exerciseId: 'dips',
      name: 'Dips',
      muscleGroup: 'Chest',
      equipmentType: 'Bodyweight',
      difficulty: 'Intermediate',
      categories: ['Calisthenics', 'Bodybuilding', 'CrossFit'],
      goalTags: ['Strength', 'Muscle Building'],
      primaryMuscles: ['Lower Chest', 'Triceps'],
      secondaryMuscles: ['Front Delts'],
      thumbnail: 'https://images.unsplash.com/photo-1530822847156-5df684ec5ee1?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Hoist yourself up on parallel bars, arms fully locked out.',
        'Lean your torso slightly forward to target the chest (keep upright for triceps).',
        'Lower your body by bending your elbows until your shoulders are below your elbows.',
        'Push back up to the starting locked position.'
      ],
      alternatives: ['bench_press', 'push_ups', 'close_grip_bench_press'],
      isCompound: true,
    ),
    Exercise(
      exerciseId: 'chest_press_machine',
      name: 'Chest Press Machine',
      muscleGroup: 'Chest',
      equipmentType: 'Machine',
      difficulty: 'Beginner',
      categories: ['Bodybuilding', 'General Fitness'],
      goalTags: ['Muscle Building'],
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Shoulders'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Adjust the seat height so the handles align with your mid-chest level.',
        'Sit back flat against the pad, feet firmly on the ground.',
        'Push the handles away from you, fully extending your arms without locking the elbows.',
        'Slowly bring the handles back toward your chest.'
      ],
      alternatives: ['bench_press', 'pec_deck'],
      isCompound: true,
    ),
    Exercise(
      exerciseId: 'pec_deck',
      name: 'Pec Deck',
      muscleGroup: 'Chest',
      equipmentType: 'Machine',
      difficulty: 'Beginner',
      categories: ['Bodybuilding', 'General Fitness'],
      goalTags: ['Muscle Isolation'],
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Front Delts'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Sit on the machine with your back flat against the backrest.',
        'Grip the handles, placing your forearms against the padded rollers (if applicable).',
        'Squeeze the pads/handles together in front of your chest under control.',
        'Slowly return to the starting stretched position.'
      ],
      alternatives: ['cable_fly', 'dumbbell_fly'],
      isCompound: false,
    ),
    Exercise(
      exerciseId: 'cable_fly',
      name: 'Cable Fly',
      muscleGroup: 'Chest',
      equipmentType: 'Cable',
      difficulty: 'Intermediate',
      categories: ['Bodybuilding', 'General Fitness'],
      goalTags: ['Muscle Building', 'Definition'],
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Front Delts'],
      thumbnail: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Set the pulleys of a cable crossover machine to shoulder height.',
        'Hold the handles, step forward to create tension, and lean slightly forward.',
        'Bring your hands forward in a wide hugging motion, meeting in the center.',
        'Slowly release back, keeping a slight bend in your elbows.'
      ],
      alternatives: ['pec_deck', 'dumbbell_fly'],
      isCompound: false,
    ),
    Exercise(
      exerciseId: 'paused_bench_press',
      name: 'Paused Bench Press',
      muscleGroup: 'Chest',
      equipmentType: 'Barbell',
      difficulty: 'Advanced',
      categories: ['Powerlifting'],
      goalTags: ['Strength', 'Power'],
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Shoulders'],
      thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Setup identically to a standard Bench Press.',
        'Lower the barbell to your chest under strict control.',
        'Pause the bar on your chest for a full 1 to 2 seconds (completely motionless).',
        'Press upward explosively to lockout.'
      ],
      alternatives: ['bench_press', 'spoto_press'],
      isCompound: true,
    ),
    Exercise(
      exerciseId: 'close_grip_bench_press',
      name: 'Close Grip Bench Press',
      muscleGroup: 'Chest',
      equipmentType: 'Barbell',
      difficulty: 'Intermediate',
      categories: ['Powerlifting', 'Bodybuilding'],
      goalTags: ['Strength', 'Muscle Building'],
      primaryMuscles: ['Triceps', 'Inner Chest'],
      secondaryMuscles: ['Chest', 'Shoulders'],
      thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Lie on a flat bench and grip the bar with a narrow grip (shoulder-width or narrower).',
        'Lower the bar slowly to your lower chest, keeping your elbows tucked close to your torso.',
        'Press the bar straight back up, focusing on pushing with your triceps.'
      ],
      alternatives: ['bench_press', 'tricep_pushdowns'],
      isCompound: true,
    ),
    Exercise(
      exerciseId: 'spoto_press',
      name: 'Spoto Press',
      muscleGroup: 'Chest',
      equipmentType: 'Barbell',
      difficulty: 'Advanced',
      categories: ['Powerlifting'],
      goalTags: ['Strength', 'Power'],
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Triceps', 'Shoulders'],
      thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Setup like a normal bench press.',
        'Lower the bar to about 1 to 2 inches off your chest and pause.',
        'Hold the bar motionless in the air for 1 to 2 seconds, maintaining maximum tightness.',
        'Press the bar explosively back to the starting locked position.'
      ],
      alternatives: ['bench_press', 'paused_bench_press'],
      isCompound: true,
    ),
    Exercise(
      exerciseId: 'dumbbell_fly',
      name: 'Dumbbell Fly',
      muscleGroup: 'Chest',
      equipmentType: 'Dumbbell',
      difficulty: 'Intermediate',
      categories: ['Bodybuilding', 'General Fitness'],
      goalTags: ['Muscle Building'],
      primaryMuscles: ['Chest'],
      secondaryMuscles: ['Front Delts'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Lie on a flat bench with a dumbbell in each hand, arms extended above your chest.',
        'Lower the weights out to the sides in a wide arc, keeping a slight bend in your elbows.',
        'Squeeze your chest muscles to bring the dumbbells back to the starting position.'
      ],
      alternatives: ['pec_deck', 'cable_fly'],
      isCompound: false,
    ),

    // ───────── BACK ─────────
    Exercise(
      exerciseId: 'pullups',
      name: 'Pullups',
      muscleGroup: 'Back',
      equipmentType: 'Bodyweight',
      difficulty: 'Intermediate',
      categories: ['Calisthenics', 'CrossFit', 'Bodybuilding', 'General Fitness'],
      goalTags: ['Strength', 'Muscle Building'],
      primaryMuscles: ['Lats', 'Upper Back'],
      secondaryMuscles: ['Biceps', 'Forearms', 'Core'],
      thumbnail: 'https://images.unsplash.com/photo-1603287611837-f214690781d6?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Grip a pullup bar with palms facing away from you, slightly wider than shoulder-width.',
        'Hang with arms fully extended.',
        'Pull yourself up by driving your elbows down towards your ribs until your chin clears the bar.',
        'Lower yourself slowly back to a dead hang.'
      ],
      alternatives: ['lat_pulldowns', 'bent_over_rows'],
      isCompound: true,
    ),
    Exercise(
      exerciseId: 'deadlifts',
      name: 'Deadlifts',
      muscleGroup: 'Back',
      equipmentType: 'Barbell',
      difficulty: 'Advanced',
      categories: ['Powerlifting', 'Weightlifting', 'Bodybuilding'],
      goalTags: ['Strength', 'Power'],
      primaryMuscles: ['Lower Back', 'Hamstrings', 'Glutes'],
      secondaryMuscles: ['Lats', 'Traps', 'Forearms', 'Core'],
      thumbnail: 'https://images.unsplash.com/photo-1603287611837-f214690781d6?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Stand with feet hip-width apart, shins close to the bar. Grip the bar just outside your knees.',
        'Lower your hips, flatten your back, and engage your core.',
        'Pull the bar upward in a straight path by pushing through your legs and standing tall.',
        'Hinge at your hips and lower the bar under control back to the floor.'
      ],
      alternatives: ['squats', 'bent_over_rows'],
      isCompound: true,
    ),
    Exercise(
      exerciseId: 'bent_over_rows',
      name: 'Bent Over Rows',
      muscleGroup: 'Back',
      equipmentType: 'Barbell',
      difficulty: 'Intermediate',
      categories: ['Bodybuilding', 'Powerlifting', 'General Fitness'],
      goalTags: ['Muscle Building', 'Strength'],
      primaryMuscles: ['Upper Back', 'Lats'],
      secondaryMuscles: ['Biceps', 'Rear Delts', 'Lower Back'],
      thumbnail: 'https://images.unsplash.com/photo-1603287611837-f214690781d6?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Hold a barbell with a shoulder-width grip, hinge at hips until torso is almost parallel to floor.',
        'Keep back flat and knees slightly bent.',
        'Pull the bar up toward your lower chest/belly button, driving your elbows back.',
        'Slowly lower the bar back to the starting stretched position.'
      ],
      alternatives: ['lat_pulldowns', 'deadlifts'],
      isCompound: true,
    ),
    Exercise(
      exerciseId: 'lat_pulldowns',
      name: 'Lat Pulldowns',
      muscleGroup: 'Back',
      equipmentType: 'Machine',
      difficulty: 'Beginner',
      categories: ['Bodybuilding', 'General Fitness'],
      goalTags: ['Muscle Building'],
      primaryMuscles: ['Lats'],
      secondaryMuscles: ['Upper Back', 'Biceps'],
      thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Sit at a lat pulldown machine, adjusting knee pads for security.',
        'Grip the bar slightly wider than shoulder-width with palms facing forward.',
        'Pull the bar down toward your upper chest, squeezing your shoulder blades.',
        'Slowly release the bar back to full extension.'
      ],
      alternatives: ['pullups', 'bent_over_rows'],
      isCompound: true,
    ),

    // ───────── LEGS ─────────
    Exercise(
      exerciseId: 'squats',
      name: 'Squats',
      muscleGroup: 'Legs',
      equipmentType: 'Barbell',
      difficulty: 'Intermediate',
      categories: ['Powerlifting', 'Weightlifting', 'Bodybuilding', 'General Fitness'],
      goalTags: ['Strength', 'Muscle Building'],
      primaryMuscles: ['Quads', 'Glutes'],
      secondaryMuscles: ['Hamstrings', 'Lower Back', 'Core'],
      thumbnail: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Position the barbell across your upper back (traps). Stand with feet shoulder-width apart.',
        'Hinge at hips and bend knees, lowering your body as if sitting in a chair.',
        'Keep chest up, back flat, and push knees outward.',
        'Descend until thighs are below parallel, then push through your heels to return to standing.'
      ],
      alternatives: ['leg_press', 'deadlifts'],
      isCompound: true,
    ),
    Exercise(
      exerciseId: 'leg_press',
      name: 'Leg Press',
      muscleGroup: 'Legs',
      equipmentType: 'Machine',
      difficulty: 'Beginner',
      categories: ['Bodybuilding', 'General Fitness'],
      goalTags: ['Muscle Building'],
      primaryMuscles: ['Quads'],
      secondaryMuscles: ['Hamstrings', 'Glutes'],
      thumbnail: 'https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Sit on the machine, placing feet shoulder-width apart on the platform.',
        'Lower safety locks and bend knees to lower the platform slowly toward your chest.',
        'Push the platform away by extending your legs, without locking your knees at the top.',
        'Slowly return to the start.'
      ],
      alternatives: ['squats'],
      isCompound: true,
    ),

    // ───────── SHOULDERS ─────────
    Exercise(
      exerciseId: 'overhead_press',
      name: 'Overhead Press',
      muscleGroup: 'Shoulders',
      equipmentType: 'Barbell',
      difficulty: 'Intermediate',
      categories: ['Powerlifting', 'Weightlifting', 'CrossFit', 'General Fitness'],
      goalTags: ['Strength', 'Power'],
      primaryMuscles: ['Shoulders', 'Triceps'],
      secondaryMuscles: ['Upper Chest', 'Core', 'Traps'],
      thumbnail: 'https://images.unsplash.com/photo-1532029837206-abbe2b7620e3?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Stand with feet shoulder-width apart, barbell resting on your upper chest.',
        'Grip the bar slightly wider than shoulders, squeeze core and glutes.',
        'Press the bar straight up over your head, moving your face back to let the bar pass.',
        'Lock elbows at the top, pushing your head forward slightly for lockout stability.'
      ],
      alternatives: ['lateral_raises'],
      isCompound: true,
    ),
    Exercise(
      exerciseId: 'lateral_raises',
      name: 'Lateral Raises',
      muscleGroup: 'Shoulders',
      equipmentType: 'Dumbbell',
      difficulty: 'Beginner',
      categories: ['Bodybuilding', 'General Fitness'],
      goalTags: ['Muscle Isolation'],
      primaryMuscles: ['Lateral Delts'],
      secondaryMuscles: ['Traps'],
      thumbnail: 'https://images.unsplash.com/photo-1532029837206-abbe2b7620e3?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Stand tall with dumbbells at your sides, palms facing inward.',
        'Keep a slight bend in your elbows and lift the weights out to your sides.',
        'Raise arms until they are parallel to the floor (pinky fingers slightly rotated up).',
        'Slowly lower the dumbbells back to starting position.'
      ],
      alternatives: ['overhead_press'],
      isCompound: false,
    ),

    // ───────── BICEPS ─────────
    Exercise(
      exerciseId: 'barbell_curls',
      name: 'Barbell Curls',
      muscleGroup: 'Biceps',
      equipmentType: 'Barbell',
      difficulty: 'Beginner',
      categories: ['Bodybuilding', 'General Fitness'],
      goalTags: ['Muscle Building'],
      primaryMuscles: ['Biceps'],
      secondaryMuscles: ['Forearms'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Stand tall holding a barbell with underhand grip, shoulder-width apart.',
        'Keep elbows tucked close to your ribs.',
        'Curl the bar up toward your shoulders, squeezing the biceps at the top.',
        'Lower the bar slowly back to full extension.'
      ],
      alternatives: ['hammer_curls'],
      isCompound: false,
    ),
    Exercise(
      exerciseId: 'hammer_curls',
      name: 'Hammer Curls',
      muscleGroup: 'Biceps',
      equipmentType: 'Dumbbell',
      difficulty: 'Beginner',
      categories: ['Bodybuilding', 'General Fitness'],
      goalTags: ['Muscle Building'],
      primaryMuscles: ['Biceps', 'Brachialis'],
      secondaryMuscles: ['Forearms'],
      thumbnail: 'https://images.unsplash.com/photo-1581009146145-b5ef03a726ec?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Stand holding dumbbells with palms facing each other (neutral grip).',
        'Keep elbows fixed at sides.',
        'Curl the weights upward while maintaining the neutral hand position.',
        'Squeeze at the top and lower under control.'
      ],
      alternatives: ['barbell_curls'],
      isCompound: false,
    ),

    // ───────── TRICEPS ─────────
    Exercise(
      exerciseId: 'tricep_pushdowns',
      name: 'Tricep Pushdowns',
      muscleGroup: 'Triceps',
      equipmentType: 'Cable',
      difficulty: 'Beginner',
      categories: ['Bodybuilding', 'General Fitness'],
      goalTags: ['Tricep Isolation'],
      primaryMuscles: ['Triceps'],
      secondaryMuscles: [],
      thumbnail: 'https://images.unsplash.com/photo-1530822847156-5df684ec5ee1?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Attach a rope or bar to a high pulley cable station.',
        'Grip the attachment and tuck your elbows firmly against your ribs.',
        'Push the rope/bar straight down by extending your elbows, separating the rope ends at the bottom.',
        'Slowly return the hands back up to elbow level.'
      ],
      alternatives: ['close_grip_bench_press', 'dips'],
      isCompound: false,
    ),

    // ───────── ABS ─────────
    Exercise(
      exerciseId: 'plank',
      name: 'Plank',
      muscleGroup: 'Abs',
      equipmentType: 'Bodyweight',
      difficulty: 'Beginner',
      categories: ['General Fitness', 'Calisthenics', 'Fat Loss'],
      goalTags: ['Core Strength', 'Endurance'],
      primaryMuscles: ['Core', 'Transverse Abdominis'],
      secondaryMuscles: ['Shoulders', 'Glutes'],
      thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Place forearms on the floor, elbows aligned under shoulders.',
        'Extend legs straight back, balancing on toes.',
        'Keep body in a straight line, contract abs and glutes, hold position without dropping hips.'
      ],
      alternatives: ['push_ups'],
      isCompound: false,
    ),

    // ───────── CARDIO ─────────
    Exercise(
      exerciseId: 'burpees',
      name: 'Burpees',
      muscleGroup: 'Cardio',
      equipmentType: 'Bodyweight',
      difficulty: 'Intermediate',
      categories: ['CrossFit', 'Fat Loss', 'General Fitness'],
      goalTags: ['Conditioning', 'Fat Loss'],
      primaryMuscles: ['Full Body'],
      secondaryMuscles: ['Cardio', 'Quads', 'Chest'],
      thumbnail: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=500&auto=format&fit=crop&q=80',
      gifUrl: '',
      steps: [
        'Stand tall, drop into a squat and place hands on the floor.',
        'Kick feet back into a pushup plank, drop chest to floor.',
        'Push chest up, jump feet forward back to squat position.',
        'Jump up dynamically into the air, reaching hands overhead.'
      ],
      alternatives: ['push_ups', 'plank'],
      isCompound: true,
    ),
  ];
}
